mumble-voip/mumble

src/mumble/MainWindow.cpp
src/mumble/mumble_en.ts

Fixed the typo reported in #1552 at the place where the warning is specified and in the `<source>`-field of all translations.

Fixed typo sever->server reported in #1552

---

src/mumble/WASAPI.cpp

This PR should resolve #1589 as well as fix some other unreported issues. It also adds PCM16 support for audio devices using WASAPI.
As the WASAPI backend is probably the most used one we should review and test this carefully.
See the commits for more information.

Fix handling of WAVEFORMATEX in WASAPI backend

---

3rdparty/speex-build/speex-build.pro
compiler.pri
src/mumble/mumble_pch.hpp
src/murmur/murmur_pch.h

We do not plan on using ICC to build mumble now or in the
foreseeable future. Hence this PR drops it.
Also adjusted compiler custom compiler configuration to
only set flags that weren't set by default anyway.
Further updated compiler.pri to make use of the new /Zo
option to improve our debugging capabilities on optimized
builds.
With this PR we also loose support for Visual Studio 2010.
From now on only VS 2013 Update 3 or later will be supported.

Remove ICC and vc10 support and simplify/update vc flags.

---

installer/Files.wxs
installer/Product.wxs
overlay/overlay_exe/overlay_exe-shared.pro
overlay/overlay_exe/overlay_exe.cpp
overlay/overlay_exe/overlay_exe.h
overlay/overlay_exe/overlay_exe.rc
overlay_winx64/overlay_exe_winx64/overlay_exe.rc
overlay_winx64/overlay_exe_winx64/overlay_exe_winx64.pro
src/mumble/Overlay_win.cpp

Right now, we do not get PDB files for our overlay DLLs because
the overlay DLL PDB files share their name with the overlay helper
PDB files.
To avoid this madness, we rename the overlay helpers as follows:
mumble_ol.exe -> mumble_ol_helper.exe
mumble_ol_x64.exe -> mumble_ol_helper_x64.exe

Rename overlay helpers to avoid PDB name clashes with DLLs.

---

src/mumble/ConfigDialog.cpp
src/mumble/Global.h
src/mumble/LookConfig.cpp
src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/main.cpp

This PR enables Mumble to restart itself when certain configuration options are changed. This enables us to offer the user to restart the client when one of the options we cannot change while the client is running was modified.
I tested the functionality on Windows and Linux and it seemed to work as expected. This leaves OSX. Also we will have to test with a realistic Mumble installation to make sure the versioned directories do not interfere.
For more specific information on the changes see the commit messages and contents.

Add self-restart capability to Mumble and enable its use in ConfigWidgets

---

src/Connection.cpp
src/Connection.h
src/Net.h
src/SSL.cpp
src/SignalCurry.h
src/bonjour/BonjourServiceBrowser.cpp
src/bonjour/BonjourServiceBrowser.h
src/bonjour/BonjourServiceRegister.cpp
src/bonjour/BonjourServiceRegister.h
src/bonjour/BonjourServiceResolver.cpp
src/bonjour/BonjourServiceResolver.h
src/mumble.pri

This PR fixes the warnings produced in code we share between mumble and murmur.
On windows the ```static_cast<int> ``` casts for the socket in Connection.cpp are not 100% cosher on Win64. However I'm pretty sure while in theory windows could return bigger handles according to the type there it's safe the assume they never will. On Linux the fd is defined to be int.

Fix warnings in code shared between mumble and murmur

---

src/mumble/Settings.cpp
src/mumble/XboxInput.h

The XboxInputState structure we used was only compatible
to the XInputGetState function. The undocumented
XboxInputStateEx function we prefer requires additional
padding at the end of the structure.
Fixes #2018
Fixes #2016
This PR also reverts disabling xboxinput by default.

Fix xboxinput calls crashing on x86

---

src/mumble/GlobalShortcut_win.cpp
src/mumble/mumble.pro

This also lets us remove MinHook from the Mumble client itself.
This code is part of the client-in-overlay feature that we had
for Windows and OS X. However, that feature is broken for Qt 5
and never had good performance.

GlobalShortcut_win, mumble.pro: remove use of HardHook in GlobalShortcut_win.

---

src/mumble/ClientUser.cpp
src/mumble/ClientUser.h

As far as I can tell, this is left over from the already-removed jitter reporting feature. This is the last of the code that matches a grep for "jitter" in the tree that isn't related to the jitter buffer. It was originally added in d042b70.
Passed a smoke-test build on Arch Linux with `CONFIG+="bundled-celt no-g15 no-ice packaged release"`.

Remove unused jitter reporting code

---

overlay/overlay_blacklist.h

The interplay between Mumble/Steam/Uplay overlays seems
to have been fixed by one of the parties (not us!).
Far Cry 4 now runs with the Mumble overlay.
Fixes mumble-voip/mumble#1514

overlay: remove Far Cry 4 from the default blacklist.

---

python.pri
src/mumble/PulseAudio.cpp
src/mumble/mumble.pro
src/mumble/mumble_pch.hpp

This allows Mumble to build on OpenBSD OOTB, with dependencies from the OpenBSD ports tree.

Various OpenBSD fixes

---

.mailmap
AUTHORS

In PR #2248, I promised to change the commit's
author before landing. I didn't.
This adds an entry to the .mailmap to make up
for that.

Add Joeliam to .mailmap and sync AUTHORS.

---

plugins/bf4/bf4.cpp

- The pointers were not working on some servers, or pointing to random memory addresses. The new ones seem to work fine.
- Updated the license header.

[Positional Audio] Battlefield 4: Fixed Squad/Squad Leader pointers

---

plugins/bf4/bf4.cpp

The previous code accidently used the
C-string "host" and "serverID" variables
in the JSON output for the context and
identity.
To avoid too many changes, this commit
changes the JSON escape function to
work on C strings instead, and uses
that to escape the "host" and "serverID"
strings from the game before emitting
them into the JSON documents.
This commit also adds some extra code
to ensure that the game strings we
include in the JSON document are
within the printable ASCII range.

plugins/bf4: fix JSON encoding.

---

src/Net.cpp

Fixes the build. We have QT_NO_CAST_FROM_ASCII set.

Net: use QLatin1String instead of implicit char * -> QString conversion Ban::toString().

---

src/mumble/Plugins.cpp
src/mumble/VersionCheck.cpp

Our binaries are timestamped, and we expect them to be deemed
valid by Windows even after the certificate expires. And they
are.
However, our own code explicitly passes WTD_LIFETIME_SIGNING
to the WinTrust APIs, overriding Windows's default of treating
timestamped binaries as valid even after certificate expiry.
(As long as the certificate doesn't have the lifetime signing bit
set!)
Now, this of course begs the question: What if our binaries
*did* have the lifetime signing bit set? Would *not* passing
this flag to the WinTrust APIs override that -- and trick
Mumble into thinking that a code signature that Windows
deems invalid is actually still valid?
I don't know yet. But I would assume that *not* including
the flag makes Windows use the lifetime signing bit of
the certificate to …

Plugins, VersionCheck: don't pass WTD_LIFETIME_SIGNING_FLAG to WinTrust APIs.

---

src/SSL.cpp
src/SSL.h
src/mumble/mumble.pro
src/murmur/murmur.pro

MumbleSSL: add a sanity check for QSsl loading a different version of OpenSSL than we're linked against.

---

man/murmurd.1

I added documentation for `-disablesu` to the murmur manpage.
This also includes a couple other nitpicky fixes to the manpage as separate commits.

Document -disablesu on murmur manpage

---

plugins/rl/rl.cpp

Rocket League uses a right handed coordinate system.

[Rocket League] Fixed inverted Z (left/right) value

---

scripts/mkini.sh

As-is, the murmur.ini.system used by our PPA builds
(and Debian-based distros) are broken because the
script doesn't set the "logfile" and "pidfile"
options.

scripts/mkini.sh: consider semicolons as comments to fix .ini generation.

---

src/Timer.cpp

Once we require C++11, we can drop this, and use std::chrono instead.
Fixes mumble-voip/mumble#1065

Timer: use boost::chrono::steady_clock as the underlying monotonic timer.

---

overlay_gl/overlay.c

World of Warcraft masks all colors via glColorMaskIndexedEXT(0, 0, 0, 0, 0)
before we draw our overlay.
This broke overlay rendering on OS X when shadow quality was set
to anything greater than low.
This commit ensures that we allow drawing of colors to the main
framebuffer -- so we can draw the overlay properly.
Fixes mumble-voip/mumble#1010
Fixes mumble-voip/mumble#1561

overlay_gl: unmask framebuffer color components in drawContext().

---

overlay_gl/overlay.c

GL_QUADS is deprecated in modern GL.

overlay_gl: call glDrawArrays with GL_TRIANGLES instead of GL_QUADS.

---

src/mumble/MainWindow.cpp
src/mumble/ViewCert.cpp
src/mumble/ViewCert.h

It's pretty awkward to find this information easily which is a problem
when self-signed certificates are used. So, let's show the digest of
the certificate immediately on the "SSL Verification failed"
prompt. Furthermore, if we already have a digest recorded for the
address (from a previous run) and it has changed, we *also* show the
old (expected) digest.

Show the SSL cert's SHA1 digest in the "SSL Verification failed" prompt.

---

src/mumble/ViewCert.cpp

Qt 5 doesn't have QChar::fromAscii.

ViewCert: use QChar::fromLatin1 instead of QChar::fromAscii.

---

plugins/rl/rl.cpp

Game version: 1.20
http://www.rocketleaguegame.com/news/2016/06/rocket-league-patch-notes-v1-20

plugins/rl: Plugin update for game's latest version

---

src/mumble/ViewCert.cpp

The previous code assumed that each subject info
item only happens once. That was true for Qt 4, but
in Qt 5, QSslCertificate::subjectInfo() and
QSslCertificate::issuerInfo() return a QStringList.
This commit updates ViewCert to be able to show
multiple occurrences of each item.

ViewCert: clean up Qt 4/Qt 5 compatibility code.

---

src/Timer.cpp

These commits fix https://github.com/mumble-voip/mumble/issues/2366
We:
1. Revert the Boost patch.
2. Commit my earlier PR to use clock_gettime with CLOCK_MONOTONIC so we have a proper fallback  for POSIX systems that use old-ish Boost versions.
3. Re-introduce the Boost patch, guarded by BOOST_VERSION >= 1.56.0
Not pretty, but at least once we can go C++11 only, we can drop the whole mess and just use std::chrono.

Fix Timer class's system-header Boost problems

---

src/mumble/OverlayClient.cpp

Setting an empty QPixmap, at least in Qt 5, causes a great deal of
redraws. The QGraphicsScene triggers a changed() call, and
OverlayClient sends a blit request to the overlay library.
Before, any update to the invisible FPS counter or time view
would cause a full screen blit.
Now, when the overlay is truly empty (no FPS, time or users), no
messages are sent over the wire to the overlay library.

OverlayClient: hide QGraphicsPixmapItems when FPS and time are disabled instead of setting an empty QPixmap.

---

compiler.pri

compiler.pri: enable warnings-as-errors by default if inside Mumble buildenv.

---

overlay_gl/init_unix.c

This ensures we use the Elf_Sym type instead of Elf64_Sym.
This makes the FreeBSD-specific code work on both 32-bit
and 64-bit targets.
Fixes mumble-voip/mumble#2122

overlay_gl: use Elf_Sym instead of Elf64_Sym in FreeBSD specific-code.

---

src/murmur/DBus.cpp

This method was broken by commit f260bd19133086b993a4a0cd027293153b4a15f0.
In particular, the line:
Channel *nc = server->addChannel(cChannel, name);
was removed by a locked block:
{
QWriteLocker wl(&server->qrwlVoiceThread);
server->addChannel(cChannel, name);
}
Note that nc is never assigned in the locked block.
See
https://github.com/mumble-voip/mumble/commit/f260bd19133086b993a4a0cd027293153b4a15f0#diff-a6537e937b1df62a77d014d7a8c3008bL377
for the full diff.
Fixes mumble-voip/mumble#2392

Murmur: fix MurmurDBus::addChannel that was broken by Murmur's new locking.

---

overlay/overlay_blacklist.h

We might as well...
This is short-term fix until we figure out where to go with
the overlay launcher filter, path filter, etc.
Fixes mumble-voip/mumble#1117

overlay: ensure the whole Microsoft Office suite is blacklisted.

---

src/mumble/ViewCert.cpp

When building the tree with Qt 5, the processQSslCertificateInfo overload
that takes a QString is unused.
This commit ensures that this overload is only available in Qt 4 builds.
Fixes mumble-voip/mumble#2394

ViewCert: only include 'QStringList processQSslCertificateInfo(QString in)' when built against Qt 4.

---

overlay/d3d9.cpp

overlay: in D3D9's doPresent(), use swapchain's backbuffer and dimensions if drawn via IDirect3DSwapChain9::present().

---

3rdparty/speex-build/AGC.pro
3rdparty/speex-build/ResampMark.pro
3rdparty/speex-build/SpeexMark.pro
plugins/manual/manual.pro
src/tests/Resample.pro

LIBPATH is deprecated in favor of QMAKE_LIBDIR.

Convert all remaining uses of LIBPATH in qmake files to use QMAKE_LIBDIR instead.

---

src/mumble/WASAPI.cpp

WASAPI: remove unnecessary Timer.h and User.h includes in WASAPI.cpp.

---

src/mumble/AudioInput.h
src/mumble/AudioOutput.h
src/mumble/GlobalShortcut.h
src/mumble/UserListModel.h
src/mumble/UserModel.h

Clang on macOS warns about the lack of the override keyword
for these method declarations.
Add Q_DECL_OVERRIDE to them, to fix the -Werror build on macOS.

mumble: add various Q_DECL_OVERRIDE declarations to fix the macOS build.

---

src/mumble/AudioInput.cpp

Disable use of the register keyword on GCC/Clang in C++11 mode.
Using the register keyword in C++11 mode causes a warning, which
turns into an error via -Werror.
Keep using REGISTER in the code to keep the code intact and
allow older targets to use the register hint and/or other
semantics.

AudioInput: remove use of the register keyword.

---

src/mumble/RichTextEditor.cpp
src/mumble/RichTextEditor.h
src/mumble/TextMessage.cpp
src/mumble/TextMessage.h

A new signal, accept(), is added on RichTextEditor.
This signal is emitted when Ctrl-Enter is pressed in a RichTextEditor.
This commit rips out an old non-working event filter TextMessage
that was supposed to accept the dialog when the user pressed
Enter. However, this code didn't work anymore because the
QTextEditor widgets of RichTextEditor swallowed all the KeyPress
events.
Finally, in the TextMessage class, the accept() signal from RichTextEditor
is connected to the accept() of TextMessage's QDialog, allowing
users to accept the dialog with Ctrl-Enter.
Fixes mumble-voip/mumble#2294

TextMessage, RichTextEditor: accept TextMessage dialog when Ctrl-Enter is pressed.

---

pkgconfig.pri
src/mumble.pri
src/mumble/mumble.pro
src/murmur/murmur.pro
src/murmur_grpcwrapper_protoc_plugin/murmur_grpcwrapper_protoc_plugin.pro

This commit adds a new helper function, must_pkgconfig.
It is intended as a replacement for:
PKGCONFIG *= openssl
The must_pkgconfig function performs error checking,
and fails if the package is not available.
This is to avoid situations mumble-voip/mumble#2309
where the build environment is not set up correctly
in some way.
When using must_pkgconfig, we fail early with a
clear error message, instead of failing with
a cryptic build-time error later on.

build: add pkgconfig.pri and must_pkgconfig qmake function.

---

pkgconfig.pri
src/mumble/mumble.pro

A fix to https://github.com/mumble-voip/mumble/commit/4dc497e6f2693b943b57045ad163f72b8a87c03e («build: add pkgconfig.pri and must_pkgconfig qmake function.») because there are some mistakes in the function names and PKGCONFIG will be empty after the use of the must_pkgconfig function.

Fix must_pkgconfig and misspelling in mumble.pro

---

plugins/gtav/gtav.cpp

Thanks to **Hiradur** on IRC for the retail version of GTA V.
Game version: 1.35
https://support.rockstargames.com/hc/en-us/articles/222662548-GTAV-Title-Update-1-35-Notes-PS4-Xbox-One-PC

plugins/gtav: update plugin to work with version 1.35

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

This new feature improves keyboard navigation in Mumble's main window
and is a great help to users of screen readers.
It was requested in mumble-voip/mumble#2291.
The behavior emulates Windows's (File) Explorer, where pressing F6
allows you to swtich focus between the application's main panes/panels.
In Mumble, pressing F6 switches between
Log view -> Chat input bar -> User tree view -> Log view [...]
Fixes part of mumble-voip/mumble#2291

MainWindow: allow using F6 to switch between MainWindow's main widgets.

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

This seemingly already works on macOS and Linux, but not on Windows.
Implements part of mumble-voip/mumble#2291

MainWindow, CustomElements: implement proper Backtab/Shift-Tab behavior for MainWindow::qteChat.

---

src/mumble/LCD.cpp

This is a temporary workaround until we can get the issue fixed
upstream.
See mumble-voip/mumble#2429 for more information.

LCD: add workarounds for LCD drawing on Qt 5.6.

---

src/mumble/VersionCheck.cpp
src/mumble/VersionCheck.h

Entirely drop the separate autoupdate logic, and no longer use the `auto` parameter of the update check service. Always log success/failure on any update check.
Fixes unintended backwards logic of when to log result (by always logging as mentioned).
Three commits you may want to check individually. They also contain further info about the individual changes.

Fix updatecheck result logging

---

plugins/mumble_plugin_win32_ptr_type.h

Include TH32CS_SNAPMODULE32 in call to CreateToolhelp32Snapshot.
This fixes module enumeration in getModuleAddr().
Without this flag, if called from a WoW64 process, we'll only see the
64-bit DLLs of the process (i.e., WoW64 specific DLLs) such as:
ntdll.dll
wow64.dll
wow64win.dll
wow64cpu.dll
and nothing else.
With this flag, we get everything.
Fixes mumble-voip/mumble#2437

plugins: allow getModuleAddr() to enumerate 32-bit modules in WoW64 mode.

---

plugins/l4d2/l4d2.cpp

Probably it has been changed by this update: http://www.l4d.com/blog/post.php?id=22630
It mentions only fixes for the MacOS version, but also the Windows one got a small update.
Also:
Removed wrong comma in identity at line 103.
Moved "std:endl" in the identity item's line.
Removed extra zero in memory addresses.
Removed empty line at the end of the file.

plugins/l4d2: Updated server ID memory address

---

src/mumble/AudioWizard.ui

This is a sensible default, because it looks good using all themes.
Previously, we used Qt's default style, which is platform-specific.
On Windows, we got an Aero-like style.
This change also fixes our issue with some parts of the wizard not
being styled correctly.
Fixes mumble-voip/mumble#2436

AudioWizard: always use ClassicStyle.

---

src/mumble/GlobalShortcut_win.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h

This PR adds
- A verbose logging mode in which all objects (buttons, axes, etc.) of a DirectInput device are logged.
- Logging of dwDevType when adding or rejecting a device. This is to help troubleshooting in the future. For example, it might turn out that devices that misbehave for us share a device type, or similar.

GlobalShortcut_win: add additional diagnostic logging to the DirectInput backend

---

src/OSInfo.cpp

OSInfo: add Windows 10 displayable version string.

---

src/mumble/BanEditor.ui

This commit removes the `Qt::RightToLeft` property from `qleReason`. This fixes issue #2474.

Fix for ban reason context menu overlap.

---

src/mumble/Log.cpp

A fix to #2477 because it is possible to create an element with width and height that is to long for [qreal](http://doc.qt.io/qt-5/qtglobal.html#qreal-typedef).

Log: check for QSizeF::isValid() in Log::validHtml()

---

3rdparty/xinputcheck-src/xinputcheck.cpp

Querying the device list and checking whether IG_ is in the name does
not work on Windows 10 Anniversary Update (1607).
To work around that, we add the GUIDs for all Xbox One controllers.
This should fix the problem for the most common XInput devices for now.
Presumably, Microsoft will fix this later on. But for now, this will do.
The good thing about doing it this way is that it isn't a workaround per
se -- it's an optimization that already exists in the code.
Fixes mumble-voip/mumble#2483

3rdparty/xinputcheck-src: add Xbox One controller GUIDs to avoid device list querying for Xbox One controllers.

---

3rdparty/xinputcheck-src/xinputcheck.cpp

In my initial testing, I apparently missed that the Xbox One S wireless
controller has a different GUID than a regular Xbox One wireless
controller when used with the Xbox wireless dongle for Windows.
Also, add the GUID for the Xbox One Elite wireless controller, which
also has a different GUID than the regular Xbox One wireless when
used in wireless mode.

3rdparty/xinputcheck-src: add Xbox One S wireless (non-Bluetooth) and Xbox One Elite wireless.

---

src/mumble/GlobalShortcut_win.cpp

The controller ID is shifted 24 bits, so the correct mask is
0x00ffffff.
Also, 0x00ffffffff (40 bits) should have been a red flag, since
we're working with uint32_t types here.
This fixes button names for Xbox controllers that are at indexes > 0.

GlobalShortcut_win: fix XboxInput button mask in buttonName().

---

src/mumble/GlobalShortcut_win.cpp

3rdparty/xinputcheck-src uses the product GUID in its list of well-known
devices.
For debugging purposes, it makes sense for us to log this here.

GlobalShortcut_win: log product GUID when excluding an XInput device from DirectInput processing.

---

src/mumble/GlobalShortcut_win.cpp

Previously, we only logged the instance GUID, not the product GUID.
With this change, the log line when adding a new device contains both.

GlobalShortcut_win: log product guid when adding a new DirectInput device.

---

plugins/link/link-posix.cpp
plugins/link/link.cpp
plugins/mumble_plugin.h
src/mumble/ManualPlugin.cpp
src/mumble/ManualPlugin.h

This PR contains commits to fix the following:
- Replace hard-coded __cdecl with MUMBLE_PLUGIN_CALLING_CONVENTION
- Replace HWND with unsigned long
- Fix typo in MUMBLE_PLUGIN_MAGIC_QT for _MSC_VER == 1600, _M_IX86.
- Remove __cdecl/HWND preamble from ManualPlugin.

Various mumble_plugin.h and ManualPlugin fixes

---

3rdparty/xinputcheck-src/xinputcheck.cpp

Apparently, this one has a different GUID as well.

3rdparty/xinputcheck-src: add Xbox One controller (w/ 3.5 mm jack).

---

src/OSInfo.cpp

These strings from the registry are NUL terminated, but in practice, this
isn't guaranteed.
This means that the displayable version string for Windows 10 currently
contains NUL values.
The Mumble client doesn't care, but it isn't very nice. It breaks things
like CVP providers that don't sanitize Murmur's output.
To fix the problem, this change introduces a regString function that
converts a wchar_t string to QString. Any NUL value in the input
string will terminate the string.
Fixes mumble-voip/mumble#2469

OSInfo: fix new Windows 10 OSInfo to not include NUL values in the displayable version string.

---

src/mumble/ACLEditor.ui
src/mumble/ASIOInput.ui
src/mumble/AudioInput.ui
src/mumble/AudioOutput.ui
src/mumble/AudioWizard.ui
src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.h
src/mumble/GlobalShortcutTarget.ui
src/mumble/LookConfig.ui
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/NetworkConfig.ui
src/mumble/UserEdit.ui
src/mumble/VoiceRecorderDialog.ui
src/mumble/mumble.pro
src/mumble/widgets/MUComboBox.cpp
src/mumble/widgets/MUComboBox.h

This PR introduces MUComboBox and uses it throughout the tree.
Per the commit introducing MUComboBox:
> Add MUComboBox.
>
> This adds a new QComboBox subclass called MUComboBox
> to widgets/MUComboBox.{cpp,h}.
>
> This QComboBox subclass explicitly uses a QListView
> as the backing view for the QComboBox.
>
> This fixes various styling issues for QComboBox
> on macOS.
>
> By default on macOS, QComboBoxes are backed by
> something that tries to emulate a native macOS
> menu. However, that QAbstractItemView behaves
> inconsistently when styled. For example, it does
> not seem possible to set the size of individual
> items, because they're restricted to the height
> of a normal macOS menu item.
> Also, in some cases (such as the QComboBox used
> for the transmission picker in MainWindow's
> …

Introduce MUComboBox subclass and use it throughout the tree.

---

plugins/link/link-posix.cpp

plugins/link: Initialize wsPluginName to fix the empty shortname problem

---

plugins/mumble_plugin_linux.h

Use non-C++11 open() function for std::ifstream.
Convert C-style casts to C++-style casts.

Fix warnings in mumble_plugin_linux.h

---

plugins/l4d2/l4d2_linux.cpp
plugins/mumble_plugin.h
plugins/mumble_plugin_linux.h
plugins/mumble_plugin_win32_32bit.h
plugins/mumble_plugin_win32_64bit.h
plugins/rl/rl.cpp
plugins/rl/rl.pro
src/mumble/Plugins.cpp

This PR implements support for running Windows PA plugins on Linux with Wine.
The existing plugins should, in most cases, be usable without many source changes.
The PR also ports the Rocket League PA plugin for Windows to run on Linux/Wine, as a proof of concept.

Plugins: lay the groundwork for using Windows PA plugins on Linux with Wine

---

src/mumble/UserLocalVolumeDialog.cpp

When pressing the Reset button in Local Volume Adjustment, it now resets to 0 instead of the modified value.
Feature #2461

Reset to 0 dB on Local Volume Adjustment reset button

---

compiler.pri
plugins/mumble_plugin.h
src/mumble/os_win.cpp
toolchain/win32-msvc2015/x64.toolchain
toolchain/win32-msvc2015/x86-xp.toolchain
toolchain/win32-msvc2015/x86.toolchain

This PR adds a toolchain file, and includes various small fixups that are needed to make Mumble build on MSVC2015.
This PR, by itself, allows both Mumble and Murmur to build, but the x64 overlay and some plugins do not build without extra PRs. These are:
https://github.com/mumble-voip/mumble/pull/2522
https://github.com/mumble-voip/mumble/pull/2523
MSVC2015 also shows a few new warnings. These are fixed in the following PRs:
https://github.com/mumble-voip/mumble/pull/2525
https://github.com/mumble-voip/mumble/pull/2524
And, to finish off, PR https://github.com/mumble-voip/mumble/pull/2526 enables warnings by default on Windows when in a buildenv. I used this when fixing the tree.

Allow Mumble to be built with MSVC2015

---

plugins/mumble_plugin_win32_ptr_type.h
plugins/null_plugin.cpp
plugins/wow/wow.cpp

Convert WoW plugin to use procptr32_t and the new 32-bit header.
In mumble_plugin_win32_ptr_type.h, use an intermediate uintptr_t value to fix warnings about casting a pointer to a smaller integer type.
Remove use of mumble_plugin_win32.h in the null plugin. That header results in various warnings in MSVC2015, and it is in fact unnecessary.

Fix various plugin problems that popped up with MSVC2015

---

overlay/lib.cpp
overlay/lib.h
overlay/overlay_exe/overlay_exe.cpp

Add LONG cast when creating RECT.
Before re-defining _WIN32_WINNT, undef it first, if it's already set.
Use unsigned long long in HANDLE conversion code in overlay_exe to avoid casting from a pointer to a smaller-than-pointer-sized integer.

Fix various warnings in the Windows overlay found by upgrading to MSVC2015

---

compiler.pri

Apparently, I missed this the first time around.

compiler.pri: enable warnings-as-errors by default on Windows.

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

Paste and Send from Clipboard Shortcut #2501
Users can now set a shortcut to send the content in their clipboard to the channel they are in. Works when mumble is not in the foreground.
Feature #2501

Send clipboard content to chat

---

src/mumble/Log.cpp

A rework to #2049 and it fixes the validation of image URLs.

Remove the message size restriction and fix the validation of images

---

src/mumble/Messages.cpp

Users can only detect private messages
if there is no prefix like “Channel” or “Tree”
in the messages.
This commit adds a prefix “Private” to the sender.
Fixes mumble-voip/mumble#2362

Messages: add the prefix “Private” in MainWindow::msgTextMessage().

---

src/mumble/AudioInput.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h

This commit adds the ability to use the AUDIO encoder
instead of the VOIP encoder, that can be used for
bots or broadcaster, who wants to stream in a higher quality.
To enable this feature add this to the Mumble config:
[codec]
opus/encoder/music=true
Fixes mumble-voip/mumble#1630

Enable the Opus music encoder

---

src/murmur/ServerDB.cpp
src/murmur/ServerDB.h

This is the new and improved version of https://github.com/mumble-voip/mumble/pull/2383 and addresses issue https://github.com/mumble-voip/mumble/issues/2187
This pull request uses the UPSERT functionality of PostgreSQL. If QPSQL is chosen as the database engine in mumble-server.ini then the **version of PostgreSQL used needs to be 9.5 or higher**.
Key changes this pull request makes:
- It adds the patch from https://sourceforge.net/p/mumble/patches/368/
- It updates the create user table function to include salt and kdfiterations since they weren't used when the patch was made.
- It fixes the dblog function so it works for both PostgreSQL and other database types.
- The patch used the same method to insert or update rows for all database engines. This has been changed so that PostgreSQL …

Murmur postgresql support

---

installer/Files.wxs
installer/Product.wxs
installer/Settings.wxi

There's a conflict with MSVC2015 and LTCG with Mumble's codebase.
Revert to MSVC2013 so we can keep snapshots rolling for now.

Revert PR #2531: installer: use MSVC2015 runtime.

---

src/mumble/MainWindow.cpp

The old behavior causes the MainWindow to not appear on Linux when
using certain Qt 5 versions.
Removing the call to setupView(false) fixes the problem for all
Linux users who have tried it.
I've also tested removing the code path on Windows, and everything
still works as expected.
We'll keep the code path for Qt 4 builds, though!
Fixes mumble-voip/mumble#2192

MainWindow: avoid initial setupView(false) call in setupGui() on Qt 5.

---

src/mumble/DBus.cpp
src/mumble/DBus.h

This is useful, for example, when bridging mumble to a two-way radio. A script can query mumble over DBus for when to push the radio's push-to-talk button.

Added a DBus method for getting a list of currently talking users.

---

scripts/mumble.appdata.xml
scripts/scripts.pro

https://people.freedesktop.org/~hughsient/appdata/ has some more details. The screenshot is pretty poor but https://wiki.mumble.info/wiki/Category:Screenshots_of_Mumble_client had none for Linux.

Added an appdata.xml file for Linux software gallery integration

---

src/mumble/MainWindow.cpp

Since 4009ea353944fc9cbefcbf95979f0d6d0c0ec3b2 on Windows the quickchat
bar was invisible on startup due to height 0. We keep the new logic
introduced for other OSes, but for Windows, we keep the setupView(false)
call.
@mkrautz You wrote the change was tested on Windows. Did you not notice this problem?
PTAL

Fix #2572: Fix invisible Quickchat bar on startup

---

src/mumble/MainWindow.cpp

For lack of better presentation, I implemented it as a simple log information. A dialog would be more prominent/visible, but equally more annoying. On connectivity issues with (some kind of) dynamic channels this could be pretty annoying as well (server reconnects). A log message is the less intrusive way to inform.
Fixes #2577 E.g. when connecting via Mumble URL and the target channel does not exist

Log information about missing target channel

---

compiler.pri

This is an offshoot of Debian bug #831184.
(See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831184)
Basically, G++6 now defaults to C++11 (or greater) mode.
We haven't explicitly passed a C++ standard C(XX)FLAG, so
until now, we've built against the g++/clang's default, which
until now was C++98 or C++03.
Now, Mumble itself doesn't really care what C++ mode it's built in.
We build fine in C++11 mode.
However, on Debian/Ubuntu, libraries such as ZeroC Ice
provide separate C++11 and C++03 .so's with different ABIs.
The default version in system's lib dir is the C++03 version,
but the ABI that is targeted when building with "g++ -lIce [...]"
(that is, without explicitly specifying a default C++ mode)
is the C++11 variant -- because G++6 defaults to C++11 mode.
This puts us in a …

compiler.pri: explicitly default to C++03 on Unix-like systems.

---

compiler.pri

GCC 4.1, used in our CentOS 5 buildenv doesn't know
the c++03 alias. Use c++98 instead.

compiler.pri: use -std=c++98 instead of -std=c++03.

---

plugins/bf1/bf1.cpp

The last update did not have a working pointer for the squad and squad leader values. This one works.

plugins/bf1: better squad pointer

---

installer/Plugins.wxs
plugins/plugins.pro

x64 plugins only work if Mumble is x64 too, this means that we should avoid building them with Mumble x86.

plugins: Build x64 ones only when the target is x86_64

---

plugins/l4d/l4d.cpp

- Correct avatar position (the one used before was the camera one)
- Camera position
- State value
- Context based on server ID
- Host address in identity (it was in context)
- Map name in identity
- Player SteamID in identity
Game version: 1.0.3.1
http://www.l4d.com/blog/post.php?id=20984

plugins/l4d: total revamp and identity support

---

plugins/mumble_plugin_linux.h

This fixes #2615, introduced by #2611.

plugins: fix compile error on Linux

---

src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h
src/mumble/Settings.cpp
src/mumble/Settings.h

This is implemened via a 'max in-flight TCP pings' counter, and
a rule for how many in-flight TCP pings there can be at one
point in time. (The default being 2, which means a client will
disconnect from a server if it takes the server more than 10
seconds to reply to a single ping message, given that Mumble
sends ping messages every 5 seconds.)
The idea is simple: ServerHandler keeps a counter of the number
of TCP pings it has sent, but has not yet received a response for.
When ServerHandler sends a ping, it increments the counter.
Once a pong or response for the ping has been received, it
decrements the counter.
But most importantly, ServerHandler now checks the amount
of in-flight TCP pings before it sends a new ping message.
If the counter exceeds the maximum number of allowed …

ServerHandler: reconnect to the server if it is not responding to TCP pings

---

compiler.pri
cplusplus.pri

This PR adds a cplusplus.pri file (which gets included by compiler.pri).
Its purpose is to handle selection of C++ standards at build time via qmake's CONFIG variable.
Builders can now specify, say, `qmake -recursive -Wall main.pro CONFIG+="release c++11"` to select C++ mode.
Besides the ability to explicitly select a C++ standard, cplusplus.pri will auto-detect an appropriate C++ standard for the current system.
Supercedes PRs #2608 and #2628

compiler.pri: improve modern C++ detection

---

overlay/overlay-shared.pro

This allows the overlay to build with the Windows SDK version
of fxc.exe.
This removes the need for people developing locally to install
the legacy DirectX SDK.

overlay: fall back to fxc.exe on PATH if DXSDK is not set.

---

src/Connection.cpp
src/Connection.h
src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h
src/mumble/Settings.cpp
src/mumble/Settings.h

This PR changes ServerHandler to bind our UDP socket to the same address that our TCP socket is bound to locally.
Murmur actually requires this for UDP to work, due to the way checkDecrypt in Murmur works.
See: https://github.com/mumble-voip/mumble/blob/2e6625b191874b3dd8af5bed15bd78f559e2005a/src/murmur/Server.cpp#L816-L846
It only tries to look up potential users by the address they're mapped to in qhUsers, which is the TCP address that user is connected with.
This PR also adds a config option. This is to allow users to switch back to the old behavior, if necessary.
This fixes some of the problems raised in mumble-voip/mumble#1377. Before this change, Murmur would immediately switch to using a new temporary address as the source address for UDP packets, once a new preferred temporary …

Use same source address for UDP packets that is used for TCP packets

---

compiler.pri

Seems like I forgot to remove this when I added
the new method.
Let's remove it.

compiler.pri: drop old modern C++ detection logic that is now handled by cplusplus.pri.

---

src/murmur/ServerDB.cpp

This commit fixes a potentially uninitialized variable ('id') in
Server::removeChannelDB().
GCC warning was:
ServerDB.cpp: In member function void Server::updateChannel(const Channel*):
ServerDB.cpp:1655: warning: id may be used uninitialized in this function

ServerDB: ensure 'id' is never uninitialized in Server::removeChannelDB().

---

buildenv.pri
compiler.pri
cplusplus.pri
main.pro
src/mumble.pri
src/mumble/mumble.pro
src/murmur/murmur.pro

Some non-pristine systems (in this context, systems that have some of Mumble's dependencies already installed outside the Mumble buildenv) had problems building Murmur inside the Linux buildenv.
The two cases were:
1. Adding the Linux buildenv's $MUMBLE_PREFIX/include to CXXFLAGS via -isystem caused the compiler to prefer /usr/include to $MUMBLE_PREFIX/include. This caused the compiler to use the system headers instead of the buildenv headers, causing build problems.
2. Because cplusplus.pri put the  C++11 Debian libdir (/usr/lib/$MULTILIB_ARCH/c++1) into QMAKE_LIBDIR as one of the first entries, any libraries in that directory were preferred to libraries in $MUMBLE_PREFIX/lib. The fix for this is to simply not use the C++11-specific libdir when inside a buildenv.
The commits in this PR …

Fix Murmur build inside the Linux buildenv

---

src/mumble/Themes.cpp
src/mumble/Themes.h

Mumble will now read and use a user.qss
file from the base path.
The content of the user.qss will
be added after the actual theme's stylesheet.
This allows users to make small tweaks to
the themes we ship.
It also allows developers to test small tweaks
without rebuilding Mumble.
Locations where Mumble will look for user.qss:
Windows:    %APPDATA%\Mumble\user.qss
macOS:      $HOME/Library/Application Support/Mumble/Mumble/user.qss
Unix-like:  $HOME/.local/share/Mumble/Mumble/user.qss

Themes: add support for user styles.

---

cplusplus.pri

This commit also fixes the problem when passing a C++ standard
to CONFIG in general.
Fixes mumble-voip/mumble#2639

cplusplus.pri: refactor 'prior modern C++ standards' logic to work for Qt 4.

---

src/murmur/Messages.cpp

The server has a regular expression setting for channel names.
The additional restriction of having a word character is probably
reasonable for most users.
However, it is an arbitrary limitation that users may want to circumvent.
For example: A channel could not be named with hyphens only "---".
As this is an arbitrary and invisible limitation, whichs use case is covered
by the channelname setting (with a default and adjustable by the user)
remove it.

Remove additional word character channel name restriction

---

.gitignore

Qt generates this file when I build on Windows
with the latest win64-static-no-ltcg buildenv.
Let's add it to gitignore.

.gitignore: add mocinclude.opt.

---

cplusplus.pri

This avoid a lot of logspam on OS X's clang, where
-print-multiarch doesn't exist.

cplusplus.pri: pipe gcc -print-multiarch output to stderr.

---

macx/compat/compat.m

The Sierra SDK seems to require an id<NSApplicationDelegate>
for its setDelegate: call.
To accomplish this, split off the existing adoption of
NSFileManagerDelegate into a seperate class extension.
Then, add another class extension for conforming to the
NSApplicationDelegate protocol.
Both of them are gated with MAC_OS_X_VERSION_MAX_ALLOWED
to allow building with older SDKs.

macx/compat: fix build of compat.m shim with Sierra SDK.

---

3rdparty/qqbonjour-src/BonjourServiceResolver.cpp

This fixes mumble-voip/mumble#2223
Before this commit, BonjourServiceResolver would not consistently
tear down the ResolveRecord when an error occurred.
The 100% CPU usage problem from issue 2223 happens in
BonjourServiceResolver::bonjourResolveReply, where previously,
the ResolveRecord was removed from qmResolvers for both error
and success -- but was never deleted on error. To fix this issue,
we delete the ResolveRecord for bonjourResolveReply's error case.
For constency, we also introduce similar code in the
BonjourServiceResolver::bonjourSocketReadyRead method.
Now, if DNSServiceProcessResult returns an error, we tear down
the ResolveRecord and remove it from qmResolvers.

3rdparty/qqbonjour-src: in BonjourServiceResolver, always tear down ResolveRecord on error.

---

src/mumble/ConnectDialog.cpp
src/mumble/ConnectDialog.h
src/mumble/UserView.cpp

This restores the green background color we've had in the ConnectDialog and on the root channel when connected to a server.
It doesn't fully fix mumble-voip/mumble#1543, since it doesn't make the color fully configurable in the theme. However, it makes it possible to once again discern whether a given server uses a "strong" (in Mumble-speak) certificate.

Restore green background for strong certificate in UserView (root channel) and ServerView (ConnectDialog)

---

3rdparty/speex-build/speex-build.pro

If we don't do it ourselves, qmake will add it automatically, and
warn to stdout.
The reason we need it here is because we use two VPATHs that include
files with the same names. That confuses nmake's inference rules, so
we have to disable them with no_batch.

3rdparty/speex-build: add CONFIG += no_batch to speex-build.pro.

---

3rdparty/speex-build/AGC.pro
3rdparty/speex-build/ResampMark.pro
3rdparty/speex-build/SpeexMark.pro
overlay/overlay-shared.pro
overlay_gl/overlay_gl.pro
src/mumble.pri
src/tests/Resample.pro

This commit changes various pri and pro files to always prepend
the global build output directory (which can be either 'release'
or 'debug', depending on the current build configuration).
Otherwise, if a library that we build ourselves, such as -lspeex in
CONFIG+=bundled-speex, is also available in one of the other lib dirs,
we can't be sure that the one in our build output directory will be used.
This is a problem on FreeBSD, where we add /usr/local/lib
to the QMAKE_LIBDIR in compiler.pri. That directory might contain
its own -lspeex.
With this change, we now prefer libraries in our build output directory
to system libraries.

Always prepend 'release' or 'debug' dirs when adding to QMAKE_LIBDIR.

---

src/mumble/ServerHandler.cpp

Qt 5 has a QUdpSocket::bind(QHostAddress), which is what we used to use
here.
Qt 4 does not. Fix this by using port 0, like we do for the
non-UdpForceTcpAddr cases.

ServerHandler: use QUdpSocket::bind(QHostAddress, int) overload to fix Qt 4 build.

---

plugins/link/link.pro
src/mumble/mumble.pro

In this case, the linux mkspec should really be a
check for glibc. But there isn't an easily available
way to check that in qmake -- so gate it behind linux
instead.
If/when we need to support other libcs on Linux, we'll
find a suitable solution.

Only link against -lrt when using a linux mkspec.

---

compiler.pri
main.pro

This PR contains two separate commits.
1. Handle OpenBSD like FreeBSD in compiler.pri. (/usr/local/include includepath an /usr/local/lib lib dir)
2. Disable building the overlay on OpenBSD for now.

Add OpenBSD to compiler.pri and, in main.pro disable the overlay on OpenBSD.

---

plugins/ffxiv/ffxiv.cpp
plugins/ffxiv/ffxiv.pro
plugins/plugins.pro

This is the first draft of a positional audio plugin for Final Fantasy XIV.  It probably requires more work before being merge ready.  I used the l4d2 plugin as a base, with a few patterns found in the wow plugin.
I'd appreciate some feedback, especially since I'm pretty sure I've messed up the coordinate system.  I couldn't find any documentation on how to debug this thing aside from littering the code with `cout` statements.
The plugin does compile on Linux, though it's not set to in this pull request.  I'm in the process of setting up a Windows build environment, so I haven't had a chance to do any testing.
What do you all like about this code?  What do you dislike, and what should I change?

Add plugin for Final Fantasy XIV

---

src/mumble/Audio.cpp
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioOutput.h
src/mumble/AudioStats.cpp
src/mumble/Global.h
src/mumble/GlobalShortcut.cpp
src/mumble/PulseAudio.cpp

QSharedPointer is thread-safe and atomic, while boost::shared_ptr isn't.
For some audio systems, this is necessary for proper implementation (for
example, an audio system where AudioOutput runs the show, and AudioInput
is simply 'fed' data from AudioOutput -- like my upcoming 'sndio' backend).
Most of this commit is straight-forward. Most of the change is simply
renaming the types and fixing up uses of boost::shared_ptr::get() to
use QSharedPointer::data() instead. Some places also use operator bool()
now.
In Audio.cpp, in stop(), stopInput() and stopOutput(), the
boost::shared_ptr-based code used the unique() method on
boost::shared_ptr. That doesn't exist for QSharedPointer,
so we emulate the old behavior by keeping a QWeakPointer to
the object around. Once the weak pointer is no longer …

Mumble: convert AudioInputPtr and AudioOutputPtr to use QSharedPointer instead of boost::shared_ptr.

---

installer/Plugins.wxs
plugins/ffxiv/ffxiv.cpp
plugins/ffxiv_x64/ffxiv_x64.pro
plugins/plugins.pro

This is almost identical to the DirectX 9 plugin, just using 64 bit pointers and new addresses.
I'd love to combine both plugins, and could do it with something like `#ifdef IS_DX11`, but am not familiar enough with qmake to set the `#define` and have both versions build.
Note:  The plugin short name is the same, since that seems to be part of the context.

ffxiv_x64 Plugin: Add a plugin for Final Fantasy XIV DX11/x64

---

src/mumble/MainWindow.cpp

MainWindow: disable MainWindow::changeEvent on macOS; it causes Mumble to be non-interactive after restoring from being minimized.

---

qt.pri

This introduces a new variable, QT_VERSION_INT, which allows
qmake files to more easily do Qt version checks.
Previosly, code would chain greaterThan/equals/lessThan with
logical ands for QT_MAJOR_VERSION and QT_MINOR_VERSION.
That worked OK, but was a little verbose, and is inconvenient
if you want to use a QT_VERSION check alongside other conditions
in a conditional.
The QT_VERSION_INT is a string variable is of the form:
Qt 5.0.0:   50000
Qt 5.6.1:   50601
it is base 10, and can be used with qmake's comparison operators
like so:
greaterThan(QT_VERSION_INT, 50600) {
// Do stuff for Qt > 5.6
}
This commit also removes our own copies of QT_MAJOR_VERSION
and QT_MINOR_VERSION. These are provided by mkspecs/qconfig.pri,
and have been since (at least) Qt 4. So they're already available.
We …

qt.pri: introduce QT_VERSION_INT for easier version comparisons in qmake files.

---

src/mumble/mumble.pro

Qt 5.3 introduced a feature where it'll automatically fill out QTPLUGIN
with appropriate auto-detected plugins for TEMPLATE=app.
This commit avoids adding entries to QTPLUGIN if we detect we're on a
Qt version that automatically fills out QTPLUGIN.
For Windows static builds, we don't use TEMPLATE=app, so for that
platform, we have to fill out QTPLUGIN in any case.

mumble.pro: don't add to QTPLUGIN if we're on a Qt with auto-plugin support.

---

src/mumble/ASIOInput.cpp
src/mumble/DirectSound.cpp
src/mumble/GlobalShortcut_win.cpp
src/mumble/main.cpp
src/mumble/mumble.pro
src/mumble/os_win.cpp

This commit removes MumbleHWNDForQWidget -- the only user of
private Qt API in Mumble on Windows.
It is replaced with a variable, mumble_hw_hwnd, which gets
filled out in main.cpp just after creating MainWindow.
Most MumbleHWNDForQWidget() uses were for g.mw, so the change
makes sense. The ones that weren't have been changed to use it,
or removed. Most of the removed instances are g.ocIntercept-related,
which is already broken beyond repair in Qt 5.

os_win: remove MumbleHWNDForQWidget, add mumble_mw_hwnd.

---

src/LogEmitter.cpp
src/LogEmitter.h
src/mumble.pri
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/Tray.cpp
src/murmur/main.cpp

It's a natural refactoring and it'd be nice to be able to
use LogEmitter in Mumble as well.

Refactor LogEmitter from Murmur into its own file in src/.

---

src/CryptState.cpp
src/CryptState.h
src/mumble/Messages.cpp
src/murmur/Messages.cpp

This change modifies CryptState to use AES_KEY_SIZE_BYTES and
AES_KEY_SIZE_BITS constants instead of using AES_BLOCK_SIZE.
This cleans up the code, making it easier to read and understand.
The key size is a distinct concept from the block size, even though
Mumble only offiiclaly supports OCB-AES128.
This also allows users of custom builds to bump their key size to
256-bit, if they desire. Of course, such builds will not be compatible
with any existing Mumble server, because neither Mumble nor Murmur
currently supports negotiating the crypto mode used for voice packets.

CryptState: introduce AES_KEY_SIZE_* constants.

---

python.pri

Previously, the python.pri helper would try to query which python
binary on the system to use via the 'which' command.
Some systems do not have which (some Docker-based CI systems,
for example).
We now detect the presence of 'which'. If it is not available,
we try to use 'python' as the Python command. We also print a
warning about 'which' not being available -- as well as a message
pointing users to the MUMBLE_PYTHON environment variable.
Fixes mumble-voip/mumble#2748

python.pri: detect missing 'which' command and try to recover.

---

plugins/aoc/aoc.cpp
plugins/arma2/arma2.cpp
plugins/bf1942/bf1942.cpp
plugins/bf2/bf2.cpp
plugins/bf2142/bf2142.cpp
plugins/bf3/bf3.cpp
plugins/bfheroes/bfheroes.cpp
plugins/blacklight/blacklight.cpp
plugins/borderlands/borderlands.cpp
plugins/breach/breach.cpp
plugins/dys/dys.cpp
plugins/etqw/etqw.cpp
plugins/gmod/gmod.cpp
plugins/gw/gw.cpp
plugins/insurgency/insurgency.cpp
plugins/lol/lol.cpp
plugins/mumble_plugin.h
plugins/mumble_plugin_win32_ptr_type.h
plugins/ql/ql.cpp
plugins/sto/sto.cpp
plugins/ut2004/ut2004.cpp
plugins/ut3/ut3.cpp

```
warning: converting to non-pointer type 'procptr32_t {aka long unsigned int}' from NULL [-Wconversion-null]`
```
```
ql\ql.cpp:87: warning: comparison is always true due to limited range of data type [-Wtype-limits]
if (team >= 0 && team <= 3) {
```
```
sto\sto.cpp:11: error: 'numeric_limits' is not a member of 'std'
if (src.length() > static_cast<size_t>(std::numeric_limits<int>::max())) {
```
Not fixed:
```
sto\sto.cpp:55: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
if (* reinterpret_cast<DWORD *>(& posblock[52]) == 1) {
```

plugins: Fix visibility, warnings and errors when compiled with MinGW

---

main.pro

The option currently works only on Linux, since there was no need in Windows, until now.
During a MinGW build test we noticed that minhook can be compiled only with MSVC, for various macros and probably other things.

main.pro: fix-ups for "no-overlay" CONFIG option on Windows

---

main.pro

We use minhook only for the overlay. Therefore, If the option "no-overlay" is present, we shouldn't build it.

main.pro: don't build minhook if "no-overlay" option specified

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/MainWindow.ui

Add a new entry to the menu, allowing users to hide Mumble without minimizing it.
This is especially useful for users with a window manager that does not support minimizing windows, as these users were previously unable to hide Mumble. Mumble can (as always) be restored by clicking on the tray icon (if present) or starting Mumble again (without the --multiple switch). Fixes #2737.
A possible further change would be to change the "Minimize" option in the closing dialogue to "Hide", which I feel would be more appropriate in most cases. Also, a shortcut could be added to hide Mumble directly.

Allow hiding Muble from the menu without minimizing

---

src/mumble/MainWindow.cpp

It is unnecessary (the system has window-hiding built-in) and
can get us in a state where the window can't be shown again.
Easier just to leave it out.

MainWindow: don't include 'Hide Mumble' menu item on macOS.

---

g15helper/g15helper.rc
src/mumble/mumble.rc
src/murmur/murmur.rc

This fixes a problem with MinGW on Linux where it can't find the icon file, because of the backslashes.
Windows handles the path correctly with both methods.

Use forward slash for paths in .rc files

---

src/mumble/mumble.pro

This fixes a problem with MinGW on Linux where the "win32" block is triggered and the two backslashes are used, resulting in a path without slashes.
Python on Windows handles the path correctly with both methods.

mumble.pro: use forward slash for GENQRC also on Windows

---

src/mumble/Audio.cpp
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioOutput.h
src/mumble/AudioStats.cpp
src/mumble/Global.h
src/mumble/GlobalShortcut.cpp
src/mumble/PulseAudio.cpp

Two commits:
- Revert PR 2674.
- Add docs about the expected behavior of `AudioInput`/`AudioOutput` constructors/destructors and `Audio::start*()` and `Audio::stop*()` methods.
This fixes mumble-voip/mumble#2745

Revert PR 2674 and document audio backend initialization and teardown

---

src/murmur/main.cpp

Without this, we delay the log messages from -limits
until we exit with a qFatal.
This isn't good, because -limits *can* fail in ways that
cause it to get stuck. One example of this is when Murmur
runs out of memory. This typically happens on 32-bit systems
during the test that counts the number of threads Murmur can
spawn, given the system's resource limits.
One such instance is if we reach the virtual memory limit on
i386. Then, QThread::start() will try to call pthread_create(),
which fails with EACCESS. (Insufficient resources, system-imposed
or otherwise). Qt doesn't handle this error situation, but
instead calls qWarning to make the user aware.
Without this change, we would never present this warning to
the user, because Murmur would be stuck.
With this change, the user can at least …

Murmur: set detach=false for -limits (implies -fg).

---

src/mumble/mumble_pch.hpp

This fixes a problem with MinGW on Linux where it can't find "Softpub.h" and "Dbt.h".

mumble_pch.hpp: Change header name capitalization for MinGW on Linux

---

src/mumble/WASAPI.h

This fixes a problem with MinGW on Linux where it can't find "Audiopolicy.h".

WASAPI.h: Change header name capitalization for MinGW on Linux

---

rcc.pri

This fixes a problem with MinGW on Linux where it can't find the script file, because of the backslashes.
Windows handles the path correctly with both methods.

rcc.pri: Fix script path for MinGW on Linux

---

src/mumble/WASAPI.h

This fixes an error when compiling with MinGW on Linux.
```
error: 'PKEY_Device_FriendlyName' was not declared in this scope
```

WASAPI.h: Include missing header for MinGW on Linux

---

src/murmur/Cert.cpp
src/murmur/Meta.cpp
src/murmur/murmur.pro

This consists of two changes:
- First, ensure we use the final API throughout Murmur.
- Second, allow QSslDiffieHellmanParameters usage without being in a Mumble buildenv
This allows Murmur to use QSslDiffieHellmanParameters on stock Qt installations.

Update QSslDiffieHellmanParameters API calls to final Qt 5.8 API

---

installer/Files.wxs

I accidently neglected to rename this to the new name in MSVC2015.
The "msvcr" file is now "vcruntime".

installer: use "vcruntime140.dll" instead of "msvcr140.dll" for vcruntime140.dll's component ID.

---

src/mumble/Cert.cpp
src/mumble/Cert.ui

When a (p12) certificate file is specified, it is being imported. If this
is not successful it is either because of a missing or wrong password, or
because the file is in fact otherwise not valid.
Instead of simply disabling and enabling the wizard Next button we now
display a text notice to the user to make this clear (especially for the
common use-case of having to provide a correct password).
Fixes #1025
---

CertWizard: Password requirement notice on import

---

plugins/mumble_plugin_win32_ptr_type.h

Define "NOMINMAX" only if it isn't already.
MinGW defines it by default, which results in the following warning:
```
warning: "NOMINMAX" redefined
```

mumble_plugin_win32_ptr_type.h: Prevent redefinition of "NOMINMAX"

---

src/murmur/Server.cpp

The current implementation tries too hard to avoid duplication
of very few lines of code.
Instead, use two separate code paths, one for Windows, one for
Unix-like sytems.
This makes it more readable, and allows us to handle system-specific
quirks much easier. For example, SOCKET is unsigned on Windows, and
comparing it to -1 technically works (at least for two's complement
machines), but causes a compiler warning for a signed vs. unsigned
comparison.

Refactor Server::supportsDualStack().

---

src/mumble/os_win.cpp

The macro should be undefined and then defined again to change its value.
This fixes the following warning when compiling with MinGW:
```
warning: "PATH_MAX" redefined
```

os_win.cpp: Fix PATH_MAX redefinition warning

---

src/mumble/VoiceRecorder.cpp

This fixes the following warning when compiling with MinGW:
```
warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
```

VoiceRecorder.cpp: Use braces to avoid ambiguous "else"

---

src/OSInfo.cpp

```
../OSInfo.cpp:74:113: warning: passing NULL to non-pointer argument 3 of 'LONG RegOpenKeyExW(HKEY, LPCWSTR, DWORD, REGSAM, PHKEY)' [-Wconversion-null]
err = RegOpenKeyEx(HKEY_LOCAL_MACHINE, L"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion", NULL, KEY_READ, &key);
^
../OSInfo.cpp: In static member function 'static QString OSInfo::getOSVersion()':
../OSInfo.cpp:197:135: warning: format '%d' expects argument of type 'int', but argument 3 has type 'DWORD {aka long unsigned int}' [-Wformat=]
os.sprintf("%d.%d.%d.%d", ovi.dwMajorVersion, ovi.dwMinorVersion, ovi.dwBuildNumber, (ovi.wProductType == VER_NT_WORKSTATION) ? 1 : 0);
^
../OSInfo.cpp:197:135: warning: format '%d' expects argument of type 'int', but argument 4 has type 'DWORD {aka long unsigned int}' [-Wformat=] …
```

OSInfo.cpp: Fix MinGW compilation warnings

---

src/mumble/ConnectDialog.cpp

If a country flag icon does not exist, we now display a placeholder (`__.svg`)
It looks like this, with the Aland Islands missing its flag.
---
* Is the placeholder ok? Maybe make it less dark, and increase the question mark size?
* I’m not too fond of adding the `__.svg` to the `icons/flags` folder, which is otherwise only SVGs from emojione, plus our own README and LICENSE files. But I don’t know where else I would put it, it fits best in there after all.

Show fallback icon on missing country flag icon

---

src/mumble/ConnectDialog.cpp

This should fix our PPA build.
See log https://launchpadlibrarian.net/305049230/buildlog_ubuntu-precise-i386.mumble_1.3.0~1902~gd871f34~snapshot-1~ppa1~precise1_BUILDING.txt.gz

Fix usage of QFileInfo for Qt4

---

src/mumble/Overlay_win.cpp

Overlay_win.cpp:184:9: warning: enumeration value 'UnknownError' not handled in switch [-Wswitch]
switch (processError) {
^

Overlay_win.cpp: Fix MinGW compilation warning

---

src/mumble/LCD.cpp

This drops the workaround we added in c04aa4e8 (see also
mumble-voip/mumble#2429). There was a Qt regression in
early 5.6 versions that caused our previously working
monochrome bitmap drawing code to break.
To be fair, our original code was not exactly correct
per the Qt docs, but it did produce correct results before
Qt 5.6.
Qt accepted the bug as a regression, and restored the old
behavior, so we can now keep using the old behavior.
We should re-visit this soon, because the drawing code
isn't actually correct according to the Qt docs.
But it works. At least until Qt 6.
Fixes mumble-voip/mumble#2815

LCD: drop workaround for Qt >= 5.6.2.

---

src/mumble/GKey.cpp

```
GKey.cpp:89:95: warning: passing NULL to non-pointer argument 3 of 'LONG RegOpenKeyExW(HKEY, LPCWSTR, DWORD, REGSAM, PHKEY)' [-Wconversion-null]
if (RegOpenKeyEx(GKEY_LOGITECH_DLL_REG_HKEY, GKEY_LOGITECH_DLL_REG_PATH, NULL, KEY_READ, &key) == ERROR_SUCCESS) {
^
GKey.cpp:93:111: warning: format '%d' expects argument of type 'int', but argument 4 has type 'DWORD {aka long unsigned int}' [-Wformat=]
qWarning("GKeyLibrary: Found ServerBinary with libLocation = \"%s\", len = %d", qPrintable(qsLocation), len);
^
GKey.cpp:96:108: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'LONG {aka long int}' [-Wformat=]
qWarning("GKeyLibrary: Error looking up ServerBinary (Error: 0x%x, Type: 0x%x, len: %d)", err, type, len);
^
GKey.cpp:96:108: warning: format '%x' …
```

GKey.cpp: Fix MinGW compilation warnings

---

src/mumble/DirectSound.cpp

```
DirectSound.cpp:548:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (static_cast<int>(dwReadyBytes) < sizeof(short) * iFrameSize) {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
DirectSound.cpp:563:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
} while (static_cast<int>(dwReadyBytes) < sizeof(short) * iFrameSize);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
DirectSound.cpp:571:120: warning: format '%d' expects argument of type 'int', but argument 4 has type 'long long unsigned int' [-Wformat=]
qWarning("DXAudioInput: Lock from %ld (%d bytes) failed: hr=0x%08lx",dwLastReadPos, sizeof(short) * iFrameSize, hr);
^
```

DirectSound.cpp: Fix MinGW compilation warnings

---

installer/Files.wxs
installer/MumbleUCRTComponentRefs.wxi
installer/MumbleUCRTComponents.wxi
installer/MurmurUCRTComponentRefs.wxi
installer/MurmurUCRTComponents.wxi
installer/Product.wxs
installer/Settings.wxi
installer/gen-ucrt.py

MSVC2015 uses a new CRT called the Universal CRT.
This CRT is distributed in different ways, depending on your
OS.
For Windows XP, the official distribution is a VCRedist installer.
(Or, for Windows XP only -- merge modules).
For Vista through 8.1, UCRT is distributed via Windows Update.
For Windows 10, it's shipped as part of Windows.
This commit amends our installer to install an app-local copy of
the Universal CRT. This is the sanest way for us to distribute the
Universal CRT across all supported targets.
Even if we could drop Windows XP support, the fact that earlier
Windows versions deploy the Universal CRT through Windows Update
makes it a hard pill to swallow. People's hacked up machines might
not be able to get the update from Windows Update for whatever reason.
(Maybe they …

installer: ship app-local copies of UCRT DLLs.

---

src/mumble/GlobalShortcut_win.cpp

```
GlobalShortcut_win.h: In constructor 'GlobalShortcutWin::GlobalShortcutWin()':
GlobalShortcut_win.h:77:7: warning: 'GlobalShortcutWin::nxboxinput' will be initialized after [-Wreorder]
int nxboxinput;
^~~~~~~~~~
GlobalShortcut_win.h:61:16: warning:   'unsigned int GlobalShortcutWin::uiHardwareDevices' [-Wreorder]
unsigned int uiHardwareDevices;
^~~~~~~~~~~~~~~~~
GlobalShortcut_win.cpp:44:1: warning:   when initialized here [-Wreorder]
GlobalShortcutWin::GlobalShortcutWin()
^~~~~~~~~~~~~~~~~
GlobalShortcut_win.cpp: In member function 'virtual void GlobalShortcutWin::run()':
GlobalShortcut_win.cpp:85:85: warning: passing NULL to non-pointer argument 3 of 'LONG RegOpenKeyExA(HKEY, LPCSTR, DWORD, REGSAM, PHKEY)' [-Wconversion-null]
if (RegOpenKeyExA(HKEY_CURRENT_USER, "Control …
```

GlobalShortcut_win.cpp: Fix MinGW compilation warnings

---

src/murmur/Server.cpp

This comit (full SHA-1 is 91dc3d39f0a20644e10143d30048be64a28b6d75) is
obviously flawed.
So revert it.

Revert 91dc3d39f0 ('Move counter variable in processMsg into Opus condition.').

---

src/murmur/DBus.cpp
src/murmur/DBus.h
src/murmur/main.cpp

Qt 5.6 changed QDBus to use a thread, QDBusConnectionManager for
DBus connections.
This caused a bad interaction with Murmur. It turns out that, prior
to this commit, the QDBusConnectionManager in Murmur was launched at
program start, because of a global static QDBusConnection in DBus.cpp.
This meant that there would be a QDBusConnectionManager thread around,
waiting to manage DBus connections. ...Until Murmur calls fork().
After fork()ing, the QDBusConnectionManager thread is gone -- fork only
keeps a 'main' thread, and isn't generally compatible with multi-threaded
programs.
Ouch!
Fortunately, the static global QDBusConnection (MurmurDBus::qdbc) was
only initialized this way because it worked in the past. Also, because
QDBusConnection has no default constructor, the 'qdbc' …

Murmur: fix bad interaction with QDBus and fork().

---

3rdparty/minhook-build/minhook-build.pro

- Rename "HDE" folder to "hde", the name was changed in https://github.com/TsudaKageyu/minhook/commit/28338f33fac2a5a3162a461dd032b92189b1525f
- Use "$$SOURCEDIR" instead of manually specifying the folder name

minhook-build.pro: Fix paths

---

src/mumble_proto/mumble_proto.pro

This fixes the error:
```
File does not reside within any path specified using --proto_path (or -I). You must specify a --proto_path which encompasses this file. Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
```

mumble_proto.pro: fix protoc invocation for out-of-tree builds

---

installer/MumbleInstall.wixproj

Previously, we required people to install WiX globally.
That's yet another tedious dependency required in order to build Mumble.
We'll now be distributing WiX in our buildenvs, so tell our .wixproj
to use that version.

installer: use WiX from buildenv.

---

installer/Files.wxs
installer/Product.wxs
installer/Settings.wxi

Only older versions of dbghelp.dll are redistributable by themselves.
Newer versions only allow redistribution via MSI files, which are
useless for us.
To sidestep this problem, we'll simply go back to relying on the OSes
version of dbghelp.dll. Shipping an outdated version of dbghelp.dll
isn't sensible. We're better off allowing Windows 10 to use a modern
(its own) version of dbghelp.dll than using a year-old version.
To give some context on how we use dbghelp.dll:
In Mumble, we use dbghelp.dll for writing our Minidumps.
In Murmur, Ice uses it for symbolicating stack traces in
Ice exceptions.

installer: don't ship dbghelp.dll anymore.

---

src/mumble_exe/mumble_exe.cpp

Previously, we always used the directory holding mumble.exe
as the working directory.
This commit changes that to use the versioned root directory
as the working directory -- if we're using one.
When not using a versioned root directory, the old behavior
is kept intact.
This is primarily done to work around mumble-voip/mumble#2837,
where, when loading mumble_app.dll, the search order for ucrtbase.dll
seems to be using the "Standard Search Order for Desktop Applications"
instead of the "Alternate Search ORder for Desktop Applications", as it
should when we specify LOAD_WITH_ALTERED_SEARCH_PATH to LoadLibraryEx.
For context, see the following MSDN page:
https://msdn.microsoft.com/en-us/library/ms682586.aspx
Changing the working directory to the versioned root path allows
the Universal CRT …

mumble_exe: when using a versioned root, set the CWD to it.

---

appveyor.yml
scripts/appveyor/appveyor-build.ps1
scripts/appveyor/appveyor-install-environment.ps1

The current configuration uses a hacked up
win64-static-no-ltcg build environment until we
build our next set of real ones. As we do not want
to distribute our build env at this point the source
is obfuscated for now.
We utilize the appveyor cache to cache the compressed
build environment we downloaded. We do not cache the
uncompressed variant to save the time it takes to package
it up in case of cache invalidation. Cache invalidation
is keyed on changes to the appveyor.yml .

Add appveyor configuration for windows proof builds

---

.travis.yml

Travis builds with Ubuntu 12.04 so this is more of a
legacy compilation test with qt4. Should still be
helpful.

Add travis configuration for linux proof builds

---

protoc.pri
src/mumble_proto/mumble_proto.pro
src/murmur/murmur.pro
src/murmur/murmur_grpc/murmur_grpc.pro

On Linux the protobuf compiler binary's name is usually _protoc_, except when using a MinGW one to cross-compile for Windows.
The binary in the MXE Debian package is called _x86_64-w64-mingw32.static-protoc_, _x86_64-w64-mingw32.shared-protoc_, _i686-w64-mingw32.static-protoc_ or _i686-w64-mingw32.shared-protoc_, depending on the chosen target.

Add support for custom "protoc" path and scan using "which" on Linux

---

icons/muted_pushtomute.svg
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/mumble.qrc
themes/MumbleTheme.qrc

This changes the tray icon when the push-to-mute hotkey is pressed. Fixes #2736.
This still needs icons, as I am not experienced with graphic design and was not sure how they should look. I would be grateful if someone could provide some.

WIP: Indicate push-to-mute in tray

---

python.pri

MinGW triggers the "win32" block, which sets the Python command to "python" without searching for its path.
Now it isn't needed anymore since the script checks if the "which" command is available. If it doesn't the command is set to "python".

python.pri: Fix path search for MinGW on Linux

---

src/mumble/mumble.pro

Qt for MinGW on Linux doesn't import it automatically, which results in Mumble being unable to create or open the SQLite database.

mumble.pro: handle case where QSQLite a plugin in static builds.

---

lrelease.pri
src/mumble/mumble.pro

In MXE's Qt 5 package the binary is called lrelease, unlike QMake's one, which has a prefix.
This resulted in the script using the wrong name.

Always use lrelease binary from QT_INSTALL_BINS.

---

src/mumble/OverlayConfig.cpp

This commit fixes the OverlayConfig code to build on Qt 5.8,
where qWinAppInst() was removed.
It was removed via
https://github.com/qt/qtbase/commit/64507c7165e42c2a5029353d8f97a0d841fa6b01
Thankfully, qWinAppInst() was very simple: it just called through
to GetModuleHandle(0) -- in both Qt 4, and Qt 5.
To sidestep the removal of qWinAppInst(), we fix our code by calling
GetModuleHandle() directly. (With 0 changed to NULL, which is what
we usually do in our coding style.)

OverlayConfig: handle removal of qWinAppInst() in Qt 5.8.

---

src/murmur/Cert.cpp
src/murmur/Meta.cpp
src/murmur/MurmurIce.cpp
src/murmur/Server.h

This PR introduces support for loading EC certificates by @tycho.
It also introduces a new method, Server::privateKeyForPEM(). This method
moves the chain of of QSslKey constructor calls into a single method, so we
can remove a bit of code duplication across the source tree.
Finally, it also introduces a series of commits to make use of this new method.

Murmur: refactor private key loading sequence.

---

lrelease.pri

NMake doesn't like Unix-style paths, whereas jom doesn't care.
This lead to a situation where AppVeyor builds (that use jom)
succeeded, but Jenkins builds (that use nmake) failed.
This commit fixes that by adding a Windows-specific codepath to
lrelease.pri that finds a Windows-style path for lrelease.exe.

lrelease.pri: add Windows-specific code path, to fix nmake build.

---

qmake/openssl.pri
src/mumble.pri

This is needed to be able to add tests that depend on OpenSSL.

mumble.pri: split out OpenSSL depenency lookup into qmake/openssl.pri for easier use in tests.

---

src/CryptographicHash.cpp
src/CryptographicHash.h
src/mumble.pri
src/tests/TestCryptographicHash.cpp
src/tests/TestCryptographicHash.pro

We used to use QCryptographicHash, but Qt 4 doesn't support Sha256.
To remedy that, we've implemented this class on top of OpenSSL's EVP
system.
Besides being able to work on Qt 4, this class also means we can add
additional hash functions in the future, which are not necessarily
supported by Qt, such as BLAKE2.

CryptographicHash: new class for computing cryptographic hashes.

---

.gitignore

The _plugin_import.cpp files are auto-generated by the Qt build
process for importing plugins.
To avoid listing every present plugin_import.cpp file, and to avoid
having to update .gitignore every time we add a new target, we
change the existings to a glob, *_plugin_import.cpp.

.gitignore: make xxx_plugin_import.cpp a glob entry.

---

qmake/openssl.pri

This fixes a problem I encountered where including openssl.pri
in TestCryptographicHash.pro on Qt 4 wouldn't link OpenSSL.
This commit fixes that problem by ensuring link_pkgconfig is
always included in CONFIG when openssl.pri uses pkgconfig.

qmake/openssl.pri: when using OpenSSL via pkgconfig, ensure link_pkgconfig is in CONFIG.

---

src/tests/TestCryptographicHash/TestCryptographicHash.pro

Explicitly set QT = core in order to force Qt's QTEST_MAIN
to use a QCoreApplicaiton instead of a QApplication.
Also, while we're here, move from the deprecated
CONFIG += qtestlib
to
QT += testlib

TestCryptographicHash: make test GUI-less.

---

src/Message.h
src/mumble/AudioInput.cpp
src/mumble/AudioOutput.cpp
src/mumble/AudioOutputSpeech.cpp

This patch series fixes mumble-voip/mumble#2863 (Mumble segfaults during recording.)
During a VoiceRecorder session, when pressing a voice target shortcut, it was possible to set iPrevTarget to -1. That, combined with the fact that flushCheck() in AudioInput didn't properly check whether the values for iTarget and iPrevTarget were valid. This caused a voice packet with the an invalid flag byte to generated. This caused a crash in AudioOutputSpeech's needSamples(), because it would treat the bad packet as a Speex packet. Basically -- the logic was that anything that isn't CELT or Opus must be Speex -- which obviously isn't true: invalid packets would be treated as Speex.
The first commit in this series fixes the problem with missing validation for iTarget/iPrevTarget.
The second commit …

Fix crash when using the VoiceRecorder with voice target shortcuts

---

src/murmur/MurmurIce.cpp

The ad-hoc RSA checks in updateCertificate are unnecessary: we already have a
function that can check whether a given certificate belongs to a given private
key: Server::isKeyForCert().
Rip out the old RSA-specific code (which limited updateCertificate() to only
work with RSA keys), with the more general Server::isKeyForCert().

MurmurIce: remove ad-hoc RSA checks in updateCertificate with Server::isKeyForCert().

---

src/murmur/Cert.cpp
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/Register.cpp
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/UnixMurmur.cpp
src/murmur/UnixMurmur.h
src/murmur/main.cpp

- Commit 1: Change MetaParams::typeCheckedFromSettings to take an optional QSettings parameter.
- Commit 2: Add USR1 signal handler implementation.
- Commit 3: Move callsite of qmConfig.clear() in MetaParams::read() to allow MetaParams::read() to be split out into separate functions.
- Commit 4: Add Server::bUsingMetaCert flag, such that hot cert reload knows which servers to reload.
- Commit 5: Add qAbsSettingsFn, such that hot cert reload knows where to read murmur.ini.
- Commit 6: Move SSL check and OpenSSL version advertisement from MetaParams::read() to main.cpp.
- Commit 7: Avoid use of global QSslSocket::defaultCiphers() list; prefer applying the default list to each QSslSocket/QSslConfiguration individually.

Various minor fixes in preparation for hot-cert reload

---

src/mumble/ManualPlugin.cpp

Unhinging works OK now, after we've migrated the plugin
to live inside Mumble.

ManualPlugin: re-enable unhinge button for Qt 5.

---

qmake/openssl.pri
src/tests/TestCrypt/TestCrypt.cpp
src/tests/TestCrypt/TestCrypt.pro
src/tests/TestCryptographicHash/TestCryptographicHash.pro
src/tests/TestTimer/TestTimer.pro

This makes 'jom check' pass on our win32-static buildenv with MSVC 2015.

src/tests: fix various MSVC build issues.

---

src/murmur/Cert.cpp

It was not implemented until Qt 5.5:
https://github.com/qt/qtbase/commit/962ea5690cb9351822c30da534ecae7aeeba667d
No trace in the Qt docs.

Cert: require Qt 5.5 for QSsl::Ec.

---

.gitignore

This adds Qt's auto-generated test-runner-wrapper target_wrapper.bat
to gitignore.

.gitignore: add target_wrapper.bat.

---

src/PasswordGenerator.cpp
src/PasswordGenerator.h
src/mumble.pri
src/tests/TestPasswordGenerator/TestPasswordGenerator.cpp
src/tests/TestPasswordGenerator/TestPasswordGenerator.pro
src/tests/tests.pro

This depends on https://github.com/mumble-voip/mumble/pull/2882 and includes the commits of that PR as well. Will need to be removed before landing.

PasswordGenerator: add new class for generating human-friendly passwords via CryptographicRandom.

---

src/murmur/ServerDB.cpp

This replaces our ad-hoc password generator in ServerDB for generating
the initial SuperUser password.
The original implementation had several problems, including use of a
non-cryptographically secure random number generator, as well as problems
with modulo bias.

ServerDB: use PasswordGenerator class for generating initial SuperUser password.

---

src/tests/TestCrypt/TestCrypt.pro
src/tests/TestCryptographicHash/TestCryptographicHash.pro
src/tests/TestCryptographicRandom/TestCryptographicRandom.pro
src/tests/TestPacketDataStream/TestPacketDataStream.pro
src/tests/TestPasswordGenerator/TestPasswordGenerator.pro
src/tests/TestTimer/TestTimer.pro
src/tests/test.pri

This refactors a lot of the common code from each test file into
a test.pri file, which is then included by all of our tests.

src/tests: make all test .pro files 'inherit' from common test.pri file.

---

appveyor.yml

This updates the buildenv we use on AppVeyor to use
win64-static-no-ltcg-1.3.x-2017-03-04-1ddd966-811.
It also drops the use of secrets in appveyor.yml to
mask the URL for the build environment. That doesn't
work for public repos.

appveyor.yml: use win64-static-no-ltcg-1.3.x-2017-03-04-1ddd966-811.

---

src/murmur/Meta.cpp

On systems using systemd, Murmur is often started early, even before
Murmur can query the network interfaces.
This commit adds a fallback, where Murmur will expect such a system to
support both IPv4 and IPv6.
Fixes mumble-voip/mumble#1629
Fixes mumble-voip/mumble#1904

Meta: enable both IPv4 and IPv6 if we're unable to query network interfaces.

---

scripts/murmur.ini
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/ServerDB.cpp

Using SQLite's WAL (write-ahead log) can create less disk I/O while
still providing good consistency and durability.
This change uses SQLite's WAL with synchronous=NORMAL which can
can cause loss of transactions on power failure. Only the transactions
which haven't been synced to the disk by the OS are lost. The database
itself will still be in a consistent state, but it might not have all
recent changes.

ServerDB, Meta: add support for SQLite WAL. 

---

overlay/overlay_blacklist.h

XBMC is now Kodi. Add `kodi.exe` to the overlay blacklist.

overlay_blacklist.h: add "kodi.exe"

---

src/murmur/Murmur.ice
src/murmur/MurmurIce.cpp

Ice messages, parameters and return values are not allowed by
the Ice spec to contain NUL bytes. Some Ice implementations
(such as C#) fail if they encounter them.

MurmurIce: avoid NUL bytes in Ice messages

---

src/mumble/Overlay_win.cpp

We neglected to properly initialize these variables in OverlayPrivateWin,
causing the overlay helpers to sometimes not be launched.

Overlay_win: properly initialize m_helper_enabled, m_helper64_enabled and m_mumble_handle.

---

src/mumble/About.cpp
src/murmur/About.cpp

This changes the string "3rd party licenses" to be "Third-Party Licenses" instead.
It also fixes all occurrences to be Title Case, which what we use all across our UI already.

Use 'Third-Party Licenses' in About dialog instead of "3rd party licenses"

---

main.pro

Apparenty, a lot of our builders didn't catch this, apparently because
they don't clean the Git repo on every build.

main.pro: use qmake/compiler.pri -- the compiler.pri in the root does not exist.

---

src/mumble/ASIOInput.cpp

Fixes:
```
ASIOInput.cpp:446:85: error: format '%d' expects argument of type 'int', but argument 3 has type 'long int' [-Werror=format=]
qWarning("ASIOInput: Buffer mismatch mode. Wanted %d, got %d", wantBuf, lBufSize);
^
ASIOInput.cpp:446:85: error: format '%d' expects argument of type 'int', but argument 4 has type 'long int' [-Werror=format=]
```

ASIOInput.cpp: Fix print format warning

---

src/mumble/os_win.cpp

Fixes:
```
os_win.cpp:71:13: error: 'void mumbleMessageOutput(QtMsgType, const char*)' defined but not used [-Werror=unused-function]
static void mumbleMessageOutput(QtMsgType type, const char *msg) {
^
```

os_win.cpp: Fix unused "mumbleMessageOutput()" function with Qt 5

---

src/mumble/LookConfig.cpp
src/mumble/LookConfig.ui
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/MainWindow.ui
src/mumble/Settings.cpp
src/mumble/Settings.h

Prior to this PR, the Developer menu was always enabled.
That was OK for snapshots, but for release, we're going to want it disabled by default.
This PR....
- Adds a new setting, 'ui/developerconsole' for enabling the Developer menu.
- Adds a checkbox in LookConfig and hooks it up to the 'ui/developerconsole' setting.
- Hooks up MainWindow to dynamically show/hide the Developer menu depending on the state of 'ui/developerconsole'.

Add setting for enabling the Developer menu

---

src/mumble/Global.cpp

Also added comments near "#endif" to better understand the function
logic.
Fixes:
```
Global.cpp:12:13: error: 'void migrateDataDir()' defined but not used [-Werror=unused-function]
static void migrateDataDir() {
^
```

Global.cpp: Fix unused "migrateDataDir()" function on Windows

---

src/mumble/XboxInput.cpp
src/mumble/XboxInput.h

Fixes:
```
XboxInput.cpp:48:46: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
*(reinterpret_cast<void **>(&m_getStateFunc)) = reinterpret_cast<void *>(GetPr
^
XboxInput.cpp:52:48: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
*(reinterpret_cast<void **>(&m_getStateExFunc)) = reinterpret_cast<void *>(Get
^
```

XboxInput: Fix type-punned pointer dereference warning

---

src/mumble/WASAPI.cpp

Fixes:
```
WASAPI.cpp: In member function 'virtual void WASAPIOutput::run()':
WASAPI.cpp:929:0: error: format '%d' expects argument of type 'int', but argument 4 has type 'DWORD {aka long unsigned int}' [-Werror=format=]
qWarning("WASAPIOutput: Driver says no to 2 channel output. Closest format: %d channels @ %d kHz", closestFormat->nChannels, closestFormat->nSamplesPerSec);
^
In file included from /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtCore/qglobal.h:1125:0,
from /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/include/QtCore/QtCore:4,
from mumble_pch.hpp:39:
WASAPI.cpp: In instantiation of 'bool getAndCheckMixFormat(const char*, const char*, IAudioClient*, WAVEFORMATEX**, WAVEFORMATEXTENSIBLE**, SAMPLEFORMAT*) [with SAMPLEFORMAT = AudioInput::SampleFormat; IAudioClient = …
```

WASAPI.cpp: Fix print format warnings

---

src/mumble/UserView.cpp

```
UserView.cpp:39:25: error: 'QStyleOptionViewItemV4' is deprecated [-Werror=deprecated-declarations]
QStyleOptionViewItemV4 o = option;
^
```
Fixes #2381.

UserView.cpp: Fix deprecated Qt class

---

src/murmur/MurmurIce.cpp

```
MurmurIce.cpp:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int i = 0; i < s.size(); i++) {
~~^~~~~~~~~~
```

MurmurIce.cpp: Fix comparison between signed and unsigned integer

---

src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.ui
src/mumble/GlobalShortcut_win.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h

This PR contains commits that allow users to configure the use of our additional Windows shortcut sources (WinHooks, XboxInput and GKey).
It also contains a few bugfixes necessary for this feature to work as intended.
Fixes mumble-voip/mumble#2739

GlobalShortcut: allow users to enable/disable our additional shortcut engines on Windows.

---

plugins/ql/ql.cpp

The previous offset was pointing at a value of "32" when in-game, which resulted in the plugin being disabled even when not spectating.

plugins/ql: Fix spectator state offset

---

src/mumble/Overlay_win.cpp

Fixes:
```
Overlay_win.h:51:8: error: 'OverlayPrivateWin::m_active' will be initialized after [-Werror=reorder]
bool m_active;
^
Overlay_win.h:41:8: error:   'bool OverlayPrivateWin::m_helper_enabled' [-Werror=reorder]
bool m_helper_enabled;
^
Overlay_win.cpp:49:1: error:   when initialized here [-Werror=reorder]
OverlayPrivateWin::OverlayPrivateWin(QObject *p)
^
```

Overlay_win: Fix "m_active" variable order

---

src/murmur/Register.cpp

The 1.2.x branch already does this.

Murmur: update registration URL to use mumble.info instead of mumble.hive.no.

---

src/mumble/WASAPI.cpp

Fixes:
```
WASAPI.cpp:358:9: warning: variable 'numFramesLeft' set but not used [-Wunused-but-set-variable]
UINT32 numFramesLeft;
^
```

WASAPI.cpp: Remove unused "numFramesLeft" variable

---

src/mumble/Settings.cpp

The setting is still available in the audio wizard, which should point
users to the possibility of enabling it, should they choose to want it
enabled.
See discussion in #2711

By default do not use attenuation

---

src/OSInfo.cpp

Solaris returns "non-negative" result for uname() upon success.
See: http://www.unix.com/man-page/sunos/2/uname/

Fixed uname() query on Solaris.

---

INSTALL
src/mumble/TextToSpeech.cpp
src/mumble/mumble.pro

Qt 5.8 introduced Qt Speech, a module that contains a TTS system which works on every OS.
This commit provides a new file called "TextToSpeech.cpp", without any suffix, indicating that it is OS-independent.
If the "qtspeech" CONFIG option is present and the "texttospeech" Qt module is available, the new file is included instead of the OS-specific one.

Implement QtSpeech-based text-to-speech backend

---

src/mumble/ASIOInput.cpp
src/mumble/ASIOInput.h
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioConfigDialog.h
src/mumble/ConfigDialog.cpp
src/mumble/ConfigDialog.h
src/mumble/ConfigDialog.ui
src/mumble/ConfigWidget.h
src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.h
src/mumble/LCD.cpp
src/mumble/LCD.h
src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/LookConfig.cpp
src/mumble/LookConfig.h
src/mumble/MainWindow.cpp
src/mumble/NetworkConfig.cpp
src/mumble/NetworkConfig.h
src/mumble/OverlayConfig.cpp
src/mumble/OverlayConfig.h
src/mumble/Plugins.cpp
src/mumble/Plugins.h
src/mumble/Settings.h

This commmit removes the concept of expert mode configuration
from the Mumble client.

Mumble: remove expert mode.

---

src/mumble/TextToSpeech.cpp

This commit removes the parent of the QTextToSpeech object and deletes it in TextToSpeechPrivate's destructor.
We do this in order to avoid generating and including a Moc file, since we don't actually need QObject functions for QTextToSpeech.

TextToSpeech.cpp: Fix build problem

---

plugins/gtav/gtav.cpp

Game version: 1.38 (Steam)
https://support.rockstargames.com/hc/en-us/articles/115004482908

plugins/gtav: update plugin to work with version 1.38 (Steam)

---

scripts/travis-ci/script.bash

travis-ci: Remove unneeded "winpaths_custom" CONFIG option

---

qmake/compiler.pri

The MinGW PR changed MUMBLE_ARCH to use QT_ARCH on Qt 5.
However, QT_ARCH uses 'i386' for 32-bit x86, we're currently
using 'x86' throughout our .pro files.
To fix this problem, we map 'i386' back to 'x86'.
This is currently breaking the win32-static (x86) build.

qmake/compiler.pri: fix value of MUMBLE_ARCH on Qt 5.

---

src/murmur/MurmurIce.cpp

std::numeric_limit's max() method return a T, so when comparing it against
a container size, we have to cast it to size_t.
This is currently breaking the win32-static (32-bit) build.

MurmurIce: fix signed/unsigned comparison between string size and std::numeric_limits.

---

scripts/rcc-depends.py

On Windows, it is not always possible to create a relative path from an
absolute path. For example, if Qt lives on C:, and Mumble is being built
on Z:.
Things will fall apart then, because we include some of Qt's
translations in our .qrc files.
This commit works around that issue by falling back to absolute paths
when finding a relative path fails.

scripts/rcc-depends.py: fall back to using the absolute path when os.path.relpath() fails on Windows.

---

.travis.yml
scripts/travis-ci/script.bash
src/murmur/Meta.h

This PR fixes a recently introduced no-pch error in Meta.h.
It also adds a no-pch configuration to Travis CI so we can catch these beforehand in the future.

Fix no-pch build and add a no-pch configuration to Travis CI

---

3rdparty/opus-build/opus-build.pro

This removes a section of opus-build.pro that sets the proper install name on the Opus shared library.
This commit removes it because it is not needed anymore -- we only ever build Opus as a static library on Unix-like systems.

3rdparty/opus-build: remove unnecessary shared library handling for macOS

---

src/mumble/Log_macx.mm

While the Growl path is unlikely to see much use in general, let's
keep it there for Qt versions < 5.8 for Mumble 1.3.0.
We'll drop it after that.

Log_macx: disable Growl fallback on Qt >= 5.8.

---

src/mumble/MainWindow.cpp

Document workaround to identify image in text under position
It was originally implemented without an explanation in b0c9521e4b5f743325380a67e6c68aa057cd635a
I was able to verify the issue and that this change solves the issue (the noticeable part of left half of the image; it also introduces half of the previous character identified as image). When using PreviousCharacter the following element is used/identified and the left half of the image stays unidentified.

Document workaround in LogTextBrowser

---

.mailmap

dark_skeleton contacted us, asking us to use this
variant of their author line for our mailmap.

.mailmap: add dark_skeleton's preferred author line.

---

overlay/overlay_whitelist.h

The original launcher filter PR only added the 32-bit Guild Wars 2 client.
This adds the 64-bit client.

overlay: add gw2-64.exe to the default launcher-filter program whitelist.

---

qmake/protobuf.pri
src/mumble.pri
src/mumble_proto/mumble_proto.pro

This PR adds a new helper for depending on protobuf called protobuf.pri.
Then, it modifies src/mumble.pri and src/mumble_proto/mumble_proto.pro to use the new helper include.

Introduce protobuf.pri helper for depending on protobuf

---

plugins/gtav/gtav.cpp

Game version: 1.38 (Retail)
https://support.rockstargames.com/hc/en-us/articles/115004482908

plugins/gtav: update plugin to work with version 1.38 (Retail)

---

src/tests/TestPacketDataStream/TestPacketDataStream.cpp

The string test for PacketDataStream uses the string
Bærtur -- but encoded as Latin1.
Keep the string -- it's as good as any -- but use UTF-8 instead,
to make clang happy.
Fixes mumble-voip/mumble#2978

TestPacketDataStream: use UTF-8 instead of Latin1.

---

src/tests/TestCrypt/TestCrypt.pro
src/tests/TestCryptographicHash/TestCryptographicHash.pro
src/tests/TestCryptographicRandom/TestCryptographicRandom.pro
src/tests/TestPasswordGenerator/TestPasswordGenerator.pro
src/tests/test.pri

The murmur_pch.h file which most tests use -- either directly,
or indrectly -- depends on being able to include OpenSSL headers.
Some of our tests did not include(qmake/openssl.pri), which meant that
those tests would fail to build in CONFIG(no-pch), such as on macOS.
This commit works around that issue by depending on OpenSSL for all tests.

tests: depend on OpenSSL in test.pri instead of each individual test.

---

src/mumble/Overlay_macx.mm

This a quick band-aid until we implement proper support for
launcher-detection in Overlay_macx.

Overlay_macx: fix code to work with removal of OverlaySettings::bUseWhitelist.

---

src/tests/TestTimer/TestTimer.cpp

For standard libraries that only provide float overloads for abs/std::abs,
this is necessary.
Also, IMHO, doing this instead of playing with fire using float casts and
whatnot seems to be the more sane approach.

Simplify delta calculation in TestTimer.cpp

---

src/murmur/murmur_ice/murmur_ice.pro

- Add support for specifying MUMBLE_ICE_PREFIX on macOS, allowing us to use a Homebrew-installed Ice.
- Add Homebrew's default slice path variant to the default include path in murmur_ice.pro.

murmur_ice: various fixes in preparation of macOS Travis-CI PR

---

.travis.yml
scripts/travis-ci/before_install.bash
scripts/travis-ci/script.bash

This commit adds a Homebrew-based macOS build to our Travis CI build
matrix.
It also cleans up the exising build matrix such such that Linux builds
are built only on Linux hosts, and macOS builds are only built on macOS
hosts.

travis-ci: add macOS target.

---

src/mumble/ACLEditor.ui

The tooltip for the channel sort order was previously the very obscure
"Channel positioning facility value".
This commit makes it more understandable: "This is the sort order for the channel."

ACLEditor: fix tooltip for channel sort order.

---

overlay/excludecheck.cpp

This is useful for cases like GTA V.
Its launcher is available via Steam, or via Rockstar Social Club/Retail.
Before this change (if it wasn't already in the blacklist), the GTA V
Launcer, when launched through Steam, would show the overlay.
Now, since we treat it as a launcher, it'll be implicitly blacklisted.

overlay: treat launchers as implicitly blacklisted programs.

---

src/mumble/MainWindow.cpp

Previously, the code tried to use floorf (in VolumeUp) and ceilf (in
VolumeDown) in order to ensure that VolumeUp and VolumeDown rounded to
the nearest 10%.
However, with /fp:fast on MSVC, that didn't work in all cases. For
example, in VolumeDown, the volume was previously always calculated via
ceilf(). On some occasions, a previous invocation of VolumeDown will have
set g.s.fVolume to a value close to 1.3 (130%). This value, when passed to
ceilf() would become 1.4 (140%) and subtracting 10% from that would still
be 130%. Not as we would expect.
This commit fixes the logic to not expect on exactness of floats via
floorf/ceilf. Instead of rounding to the nearest 10%, we just subtract
or add 10% to the current volume. It doesn't matter that it isn't a
multiple of 10.

MainWindow: avoid floor/ceil in VolumeUp/VolumeDown global shortcut handlers.

---

src/mumble/OverlayConfig.cpp

The three file lists already discard duplicate entries. Do the same for
paths in the path exceptions list.

Discard duplicate path exceptions

---

INSTALL

Paths are no longer specified in mumble.pro (directly).
---
I guess there’s no single place to configure for *nix and OSX, like there is for Windows? Anyway, this change should be an improvement over people looking in the mumble.pro file and expecting (configurable) paths in there.

Update description of configuring lib paths

---

src/mumble/UserLocalVolumeDialog.ui

The default geometry was too small on macOS (#2993).
Remove default geometry and instead specify a minimum width. The dialog
will auto-adjust its height for content.
Fixes #2993
---
As I don't have a macOS, untested.

Fix local volume dialog default size

---

src/mumble/MainWindow.cpp

This makes sure that MainWindow is active when showing tooltips. Previously any mumble window (including user information) could be in the foreground and tooltips would still show for the MainWindow, foregrounding the MainWindow.

MainWindow: Don't open tooltips when not active

---

src/mumble/DirectSound.cpp
src/mumble/DirectSound.h
src/mumble/WinGUIDs.cpp

This fixes CONFIG(no-pch) on MSVC.
In DirectSound, move includes to headers to fix moc invocation.
In WinGUIDS, add missing wtypes.h header to get PROPERTYKEY type.

Fix CONFIG(no-pch) build on MSVC.

---

scripts/appveyor/appveyor-build.ps1

The comment was not correct: We pass CONFIG(no-elevation) because we need
to disable elevation because we don't sign the builds.

scripts/appveyor: fix comment about signing/UIAccess in appveyor-build.ps1.

---

appveyor.yml
scripts/appveyor/appveyor-build.ps1

If we don't track this, we'll just break the build.
It helps with correctness of header includes, etc. -- so I think it is
worth tracking.

AppVeyor: add no-pch build for x86_64 MSVC.

---

src/mumble/NetworkConfig.cpp
src/mumble/NetworkConfig.ui
src/mumble/ServerHandler.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h

This patch adds an option to not send information about the user's OS and OS version to the server. It implements the request from #2899.
The Mumble version and release is still sent, since the server seems to use it for certain decisions. This information alone should not reveal much information about the user.
The option is currently placed in the "Misc" section of the "Network" tab.

Add option to hide OS information from server ("privacy mode")

---

src/mumble/NetworkConfig.cpp
src/mumble/NetworkConfig.ui

This is a followup to #3009 (and #2899). Currently, information about the user's operating system is sent regardless of the privacy setting
* by the crash reporter and
* in the HTTP User-Agent header field.
IMO, crash reports should contain this information. They are also not sent without the user's approval.
This patch changes the HTTP user agent to not include the user's OS if the privacy setting is enabled and changes the setting's description.
RFC 7231 does not mandate the OS to be included in the user agent, see [section 5.5.3](https://tools.ietf.org/html/rfc7231#section-5.5.3).

Do not include OS in HTTP user agent depending on privacy setting

---

src/mumble/Cert.ui

This fixes a styling issue, where the button container at
the botom of the wizard is styled in white in the Dark theme.
Fixes mummble-voip/mumble#3019

Cert: use classic wizard style for the Certificate Wizard.

---

src/mumble/MainWindow.cpp

Previously, this would hide Mumble when switching workspaces in XMonad, and possibly other WMs
without a default notification area/system tray.
See mumble-voip/mumble#1679

MainWindow: only perform changeEvent's hide-in-tray logic if there is a system tray available.

---

INSTALL
qmake/compiler.pri

Shelling out to dpkg-buildflags to get the preferred build flags
is now the way to on Debian.
Previously, our PPA packages used hardening-wrapper to pass the
proper hardening flags to the package. That package is no longer
available in Debian unstable or Ubuntu zesty.
This commit implements a new CONFIG flag, CONFIG(dpkg-buildflags)
which will query dpkg-buildflags and append the retrieved CFLAGS,
CXXFLAGS, CPPFLAGS and LDFLAGS to QMAKE_CFLAGS, QMAKE_CXXFLAGS,
QMAKE_CPPFLAGS, QMAKE_LDFLAGS to ensure they are used in the Mumble
build.

qmake/compiler.pri: add CONFIG(dpkg-buildflags).

---

INSTALL
compiler.pri

Shelling out to dpkg-buildflags to get the preferred build flags
is now the way to go on Debian.
Previously, our PPA packages used hardening-wrapper to pass the
proper hardening flags to the package. That package is no longer
available in Debian unstable or Ubuntu zesty. To remedy that situation,
we have to add flags ourselves via dpkg-buildflags.
This commit implements a new CONFIG flag, CONFIG(dpkg-buildflags)
which will query dpkg-buildflags and append the retrieved CFLAGS,
CXXFLAGS, CPPFLAGS and LDFLAGS to QMAKE_CFLAGS, QMAKE_CXXFLAGS,
QMAKE_CPPFLAGS, QMAKE_LDFLAGS to ensure they are used in the Mumble
build.

Backport PR #3033 to 1.2.x: compiler.pri: add CONFIG(dpkg-buildflags).

---

plugins/bf2142/bf2142.cpp

The avatar orientation is copied from the camera orientation for lack of something better.
In addition to the BF2 identity fields, it includes
- `ipport` to avoid having to parse the context on the server
- `name` for the in-game player name
- `on_voip` and `on_voip_com` to e.g. mimick the ingame voip behaviour or address different groups of players
- `target_squad_id`  to e.g. address a single squad as commander

Update BF2142 plugin, adding identity support

---

src/murmur/ServerDB.cpp

As a fix to issue #1269 
https://github.com/mumble-voip/mumble/issues/1269
Updated ServerDB::ServerDB() with a check for MySQL, SQLite, and Postgres

Updating ServerDB.cpp to check for MySQL, SQLite, and Postgres

---

overlay/lib.cpp

This was originally implemented in
2f07778a0eaf349b6a80489007ac31b7e54064f2.
This change was a mistake. We use the WH_CBT hook to inject our DLL into
potential targets. That means that every mouse/keyboard event will trigger
an attempt to load our overlay DLL, if it isn't already loaded.
That, combined with the new ability for the overlay to decline being
injected caused problems for processes that are blacklisted by Mumble:
Every mouse/keyboard event would attempt to load the DLL, go through the
exclusion checks (query the process tree, query the registry, find out
that the process is blacklisted, unload the DLL...).
We can't have that, so let's just revert this.

overlay: remove ability for overlay to decline being attached to a process.

---

overlay/overlay_launchers.h

See #3043, fix if the itch user does not use the sandboxing feature of
the itch launcher.

Add itch.exe as known overlay launcher

---

src/mumble/Overlay.cpp
src/mumble/Overlay.h
src/mumble/Overlay.ui
src/mumble/OverlayConfig.cpp
src/mumble/OverlayConfig.h
src/mumble/PathListWidget.cpp
src/mumble/PathListWidget.h
src/mumble/mumble.pro

Implements #2998
~~Implemented in two commits. (The first commit prior to these is a fix, used in PR #3000.)~~
As described in the second commit, there's an open issue:
> Issue: With an "Add" dialog open, dragging and dropping a file or folder
to where the dialog does not accept them will make the underlying widget
accept it.
The dialogs are modal `QFileDialog`s, so that is not the behaviour I would except. Dropping into a droppable area of the dialog (the file list area) captures the event as expected, with no bleeding into the window and widget below. With the dialog in front, and the mouse/drag events over non-droppable areas apparently propagates the mouse drag events to the window and widget below rather than discarding/blocking them.
I could make all four list widgets not accept …

Accept File And Folder Drops In Overlay Exceptions

---

overlay/overlay_launchers.h

As provided by Remadan in mumble-voip/mumble#3029.
LaunchPad is Daybreak Games's own launcher, used for games such as
PlanetSide 2 (Standalone) and others.

overlay: add LaunchPad.exe (Daybreak Games's launcher) to the launcher list.

---

man/murmurd.1

This commit documents SIGHUP (log rotation) and SIGUSR1 (graceful TLS
settings reload).
Fixes mumble-voip/mumble#3031

man: update murmurd.1 to mention SIGHUP and SIGUSR1.

---

overlay/d3d11.cpp
src/mumble/EnvUtils.cpp
src/mumble/ServerHandler.cpp
src/mumble/VoiceRecorder.cpp
src/mumble/WASAPI.cpp
src/mumble/main.cpp
src/murmur/main.cpp

Fixing some stuff I found with PVS-Studio.
I also noticed: In `src/mumble` we have EnvUtils to handle getting environment variables. This should be moved to `src`, so the code in `src/murmur` can also make use of it (there’s another place I didn't touch as well).
CryptState also still has two fields which I don’t know how to correctly initialize (openssh types), so for now I didn’t (I believe these missing init. were pointed to by cppcheck as well).

Fix Some Issues, Improve Code quality

---

src/mumble/AudioOutput.cpp
src/mumble/Database.cpp
src/mumble/MainWindow.cpp
src/mumble/RichTextEditor.cpp

We have found and fixed a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/
We suggests having a look at the emails, sent from @pvs-studio.com.
Analyzer warnings:
- V519 The 'uri' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 96, 97. RichTextEditor.cpp 97
- V519 The 'needclose' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 542, 544. RichTextEditor.cpp 544
- V547 Expression 'aos' is always true. AudioOutput.cpp 506
- V547 Expression '!dlg' is always true. MainWindow.cpp 2380
- V612 An unconditional 'return' within a loop. Database.cpp 224
- V612 An unconditional 'return' within a loop. Database.cpp 247
- V612 An unconditional 'return' …

Checking with PVS-Studio static analyser.

---

src/mumble/SocketRPC.cpp

Cross-compiled the latest mumble to run on the Raspberry Pi 3 specifically to use the RPC calls and discovered that none of them worked. Tracked the problem down to the creation of the the pipepath in the client send method. The pipepath didn't match the pipepath created for the server SocketRPC::SocketRPC.

SocketRPC: ensure pipe paths match up.

---

plugins/bf2/bf2.cpp

(and updated peekProc call signatures)
(and changed whitespace in the comment block so it's aligned regardless of tab size)
Like #3040 did for BF2142, this adds the following fields to the BF2 identity:
- `ipport` to avoid having to parse the context on the server
- `on_voip` (in-game voip to squad) and `on_voip_com` (in-game voip to commander or as commander to squad leaders) to e.g. mimick the ingame voip behaviour or address different groups of players
- `target_squad_id` (selected squad as commander) to e.g. address a single squad as commander
The existing fields are left untouched, since changing them would break the mumo plugin.
(I just noticed the last peekProc line has a tab instead of 4 spaces; if that's annoying and you can easily edit it, go ahead)

plugins/bf2: extend identity with in-game VoiP state and selected squad

---

src/mumble/TextToSpeech_unix.cpp

This PR includes two commits:
- The first commit, to make TextToSpeech_unix lazily initialize speech-dispatcher.
- Second commit, which fixes the behavior of setVolume(). Previously, our lazy-init wouldn't be effective, because TextToSpeech would call setVolume() on us very early on in Mumble's initialization.

TextToSpeech_unix: lazy initialize speech-dispatcher.

---

src/mumble/Cert.ui

Implemented (2 people) consensus of #3021 plus some more improvements.
* Drop strong recommendation of issued email certificates
* Mention friends list independent of servers
* Mention user certificate automatic creation vs third party email
certificates

Fix #3021: Update cert wizard introductory text

---

src/tests/TestTimer/TestTimer.cpp

This commit drops the tests in TestTimer that depend on comparisons
to QTime to work.
In some environments, such as CI VMs/containers, we don't seem to get
the resolution we desire from QTime.
It's also worth noting that these tests were dormant in the repository
for a long time, until we hooked up 'make check'. So, they were quite
old, and assumptions made when the code was written might not hold up
any longer.
Fixes mumble-voip/mumble#3060

src/tests: remove fragile TestTimer tests.

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioInput.ui
src/mumble/GlobalShortcut.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h

Added a new "Undo Idle action upon activity" checkbox underneath the idle action area in the Audio Input settings.
When this checkbox is enabled, the idle action will be reversed as soon as the user returns from idle. (i.e. If the idle action mutes you, when you're active again, it unmutes. If the idle action deafened you, when you're active again, it undeafens you). I tried to keep this as simple as possible to increase the chances of it being merged.
I know there are other, more ambitious efforts around this such as https://github.com/mumble-voip/mumble/pull/1724, but it appears to be trying to do a lot of things and has been stalled for nearly a couple of years now. I'd very much like to get this merged, so feedback is welcome.

Added a "Undo Idle action upon activity" setting.

---

src/murmur/murmur_pch.h

This PR contains two commits that fix some OpenSSL include problems in Murmur.
First, we explicitly include <openssl/bn.h>. We make use of BN_GENCB, but we never explicitly included the header -- instead, we relied on the fact that current versions of OpenSSL seem to include bn.h via the other headers we include. Future versions might not. So let's be explicit here.
Second, we now include opensslv.h to get access to OPENSSL_VERSION. We added OPENSSL_VERSION preprocessor checks to src/murmur/Cert.cpp recently -- but they did not work, because this header was not included. Oops.

OpenSSL include fixes

---

src/murmur/Cert.cpp

I mistakenly checked OPENSSL_VERSION (which doesn't exist), instead of
OPENSSL_VERSION_NUMBER, making the check fail.

murmur/Cert: OPENSSL_VERSION -> OPENSSL_VERSION_NUMBER.

---

src/mumble/RichTextEditor.cpp
src/mumble/XMLTools.cpp
src/mumble/XMLTools.h
src/mumble/mumble.pro
src/tests/TestXMLTools/TestXMLTools.cpp
src/tests/TestXMLTools/TestXMLTools.pro
src/tests/test.pri

Implements #3055
Makes some potential implementation issues visible that should be discussed further/later with potential changes to the implementation.
I had to add the mumble and murmur source folders to the VPATH. It seems existing tests only used files from the src folder (parent of the two).
---
Time spent: > 4 hours

Move RichTextEditor XML tool methods into separate class

---

src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/Settings.cpp
src/mumble/Settings.h

This adds a hidden option to allow users to select which microphone
channels will be downmixed to mono.
Examples of using the setting:
audio/inputchannelmask = 0x0  # Use no channels. Nothing is recorded.
audio/inputchannelmask = 0x1  # Only use left channel (channel index 0)
audio/inputchannelmask = 0x2  # Only use right channel (channel	index 1)
audio/inputchannelmask = 0x3  # Use both left and right channel.
The value of inputchannelmask is used as a bit mask. If a given bit is
set, the channel with the same index as the bit will be included in the
final downmix.
Fixes mumble-voip/mumble#3064

AudioInput, Settings: add 'audio/inputchannelmask' setting for selecting which mic channels should be mixed.

---

src/tests/TestTimer/TestTimer.cpp

We're still getting test failures on the build farm:
FAIL!  : TestTimer::resolution() Insufficient timer resolution.
Got >= 5 usec, expected < 5 usec resolution...
Loosen our requirements a bit to require a change at least
every 100 microseconds, instead of every 5 microseconds.

src/tests: make TestTimer's resolution test more VM friendly.

---

icons/talking_off.svg

This replaces a grayed out mouth icon with a grayed out but *closed* mouth icon.

Replacing grayed out with closed mouth icon

---

src/SSL.cpp
src/SSL.h

This PR removes the sanity check for multiple copies of OpenSSL.
It also ensures Mumble always initializes its own copy of OpenSSL, even when Mumble and Qt are using distinct versions of OpenSSL.
See commit messages for more information.

SSL: remove multi-OpenSSL sanity check.

---

src/mumble/mumble.pro
src/murmur/murmur.pro

This library has been added in commit 4aa902ded33072c97cb91052e66da9eab41750f7 and it should have been removed in commit f544524d4c3289bf3341d685277de0e6a6895469.

Remove unnecessary "-ldl" library from Mumble and Murmur project files

---

src/mumble_exe/mumble_exe.cpp

This adds our bug report from Microsoft Connect inline mumble_exe.cpp
to ensure it's preserved.
It is not obvious why we use the versioned path as the CWD otherwise.

mumble_exe: document LoadLibraryEx workaround for mumble-voip/mumble#2837.

---

src/mumble_exe/mumble_exe.cpp

Thanks to @klemun on GitHub for reporting the typo.

mumble_exe: fix typo and simplify comment about LoadLibraryEx bug.

---

src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/WASAPI.cpp

By default, Mumble will open WASAPI devices with the eCommunications role,
since we're a voice chat applicaiton.
Some users have requested this to be configurable.
This commit adds a setting, 'wasapi/role', which is a string that maps
directly to the ERole enum from WASAPI:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd370842
Users can now set 'wasapi/role' to one of 'console', 'multimedia' or
'communications'.
The default is still 'communications'.

WASAPI, Settings: expose 'wasapi/role' setting to allow users to set WASAPI role.

---

src/mumble/AudioOutputSample.cpp

siInfo.format was used uninitialized when siInfo was passed to libsndfile
so better initialize it to 0.
==11511== Conditional jump or move depends on uninitialised value(s)
==11511==    at 0x667CB97: psf_open_file (sndfile.c:2935)
==11511==    by 0x1B4527: SoundFile::SoundFile(QString const&) (AudioOutputSample.cpp:52)
==11511==    by 0x1B4BA6: AudioOutputSample::loadSndfile(QString const&) (AudioOutputSample.cpp:188)
==11511==    by 0x1B388E: AudioOutput::playSample(QString const&, bool) (AudioOutput.cpp:222)
==11511==    by 0x190EFB: Log::log(Log::MsgType, QString const&, QString const&, bool) (Log.cpp:486)
==11511==    by 0x1C7627: MainWindow::serverConnected() (MainWindow.cpp:2330)

Initialize siInfo.format

---

src/ServerAddress.cpp
src/ServerAddress.h
src/ServerResolver.h
src/ServerResolverRecord.cpp
src/ServerResolverRecord.h
src/ServerResolver_nosrv.cpp
src/ServerResolver_qt5.cpp
src/UnresolvedServerAddress.cpp
src/UnresolvedServerAddress.h
src/mumble.pri
src/mumble/ConnectDialog.cpp
src/mumble/ConnectDialog.h
src/mumble/Database.cpp
src/mumble/Database.h
src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h
src/tests/TestServerAddress/TestServerAddress.cpp
src/tests/TestServerAddress/TestServerAddress.pro
src/tests/TestServerResolver/TestServerResolver.cpp
src/tests/TestServerResolver/TestServerResolver.pro
src/tests/TestUnresolvedServerAddress/TestUnresolvedServerAddress.cpp
src/tests/TestUnresolvedServerAddress/TestUnresolvedServerAddress.pro
src/tests/tests.pro

This PR implements the new hostname resolving infrastructure in Mumble. This includes support for SRV records in Mumble.
The new resolver lives in the ServerResolver class. It now allows Mumble to also resolve SRV records.
The class isn't meant to be used exclusively for SRV records. We could add an alternative later on. For example, something I've toyed with is using a ".well-known" HTTPS URL, like https://gaming.example.com/.well-known/mumble as a "server pointer". The file at /.well-known/mumble would then link to a Mumble server (maybe something as simple as mumble://my-host:64800/). However, users would be able to connect to the server via mumble://gaming.example.com/ because of the pointer file. ...Just something I've toyed around with. Not related to this PR.
The PR changes …

Implement new hostname resolving infrastructure

---

src/mumble/ConnectDialog.cpp

Usernames in Murmur aren't case-sensitive, but we only showed the password
field when it was entered as SuperUser, which resulted in some confusion for
users.
Hard-coded the string as lowercase, rather than leaving it and doing an
extra toLower() on it.

Make comparison case-insensitive in ConnectDialog.cpp

---

src/mumble/ServerHandler.cpp

The call to QSslSocket::setPeerVerifyName() was accidently removed
in edd95a87a979c20cedb6872f21a8c1c354df3fd6.
Re-add it.

ServerHandler: fix broken hostname validation.

---

src/mumble/ServerHandler.cpp

In mumble-voip/mumble#3153, it was reported that the new SRV code can
disconnect you from a server after a short while.
It turns out that we weren't being careful enough about our connection
timeout timer. A new timer was created for each connection attempt to
a server in the SRV list. In practice, this meant that 30 seconds after
each connection attempt, ServerHandler would try to tear down the
connection.
We now ensure we destroy the timer after we disconnect from a server.
This should ensure there is only one such timer active at any point in
time.
Fixes mumble-voip/mumble#3153

ServerHandler: ensure only a single connection timeout timer is active at one time.

---

src/mumble/Log.cpp
src/mumble/Log.h

Previously, the invalid state for a LogDocument that contained images
that Mumble deemed invalid.
For example, if Mumble was configured to not download external iamges,
a LogDocument that contained references to external images would be
marked as invalid, and would not show up in the user's log. Instead,
the whole message would be shown as "[[ No valid image ]]".
With this change, Mumble will instead show the message, but replace
the images with a 'broken image' marker (currently, Qt shows a 1x1
black image.)
This makes the 'Disable image download' option in Mumble more usable.
Before, messages that contained external (i.e, HTTP/HTTPS) images would
not be shown at all. This was not desirable, since such messages could
potentially contain messages alongside the images.

Log: remove the notion of an invalid LogDocument.

---

overlay/d3d10.cpp
overlay/d3d11.cpp
overlay/d3d9.cpp
overlay/dxgi.cpp
overlay/lib.cpp
overlay/opengl.cpp
src/mumble/GlobalShortcut_win.cpp

It is better to be explicit and API correct, even if the resulting
types ended up to be the same through typedefs or the implementation
reinterpret-casting to a memory address pointer.

Cast to correct API types

---

src/mumble/ServerHandler.cpp

This changes the ServerResolver used in the ServerHandler thread to be
properly cleaned up after we've performed name resolution.

ServerHandler: avoid leaking ServerResolver in ::run().

---

overlay/d3d10.cpp
overlay/d3d11.cpp
overlay/d3d9.cpp
overlay/dxgi.cpp
overlay/lib.cpp
overlay/lib.h

Use correct types for handling pointer size/memory addresses.
Make use of boost optional as GetFnOffsetInModules return type. The
unsigned return type does not allow for negative error values anymore,
which we did not make use of anyway, and optional is more explicit.
Replaces workaround/error detection from the commits
114495e59f002531ac9bb02070a1bcbd6652669e
a3e7958f1605339560679cbbd3a27de4fd12066c
Fixes #1924
---
Time spent: ~1h10

overlay: Use SIZE_T as correct type for memory addresses

---

src/tests/TestServerResolver/TestServerResolver.cpp

Unfortunately QHostInfo::lookupHost is a static method, so we can’t
mock it. As a result, the test TestServerResolver is dependent on the
network. Travis builds could fail with network timeouts. Hence, we
increase the 5s timeout to 10s.

Fix #3162: Travis builds could fail with timeout

---

src/mumble/Log.cpp
src/mumble/Log.h

The rest of the code was removed in mumble-voip/mumble#3157
(ab783c74330f0f630635be585bd7941d761fbfbd)
Remove the rest, since it is unused.

Log: remove dead m_valid code from LogDocument.

---

src/mumble/Settings.cpp

This commit adds a new macro to Settings. It's called DEPRECATED, and it
is meant to be used to mark removed settings as deprecated.
It is primarily meant as documentation for developers, to ensure we don't
re-use a name in the future.
For loading, it's a no-op.
For saving, it removes the key from the user's settings store.

Settings: add DEPRECATED macro for keeping old, reserved names around.

---

src/ServerResolver_qt5.cpp

This seems like a very sensible change. If no SRV records are retrieved,
treat the situation as an error, and fall back to a regular A/AAAA/CNAME
lookup.
Fixes mumble-voip/mumble#3163

ServerResolver: treat SRV lookups that return NOERROR but no records as errors.

---

scripts/mkini-win32.bat

This ensures that murmur.ini on Windows installations has
Windows-style line endings, allowing admins to use Notepad
to edit the file.
Fixes mumble-voip/mumble#3101

scripts/mkini-win32.bat: perform LF -> CRLF conversion.

---

.gitmodules

The driving factor for this is that the CentOS builder is so
old that its copy of curl/OpenSSL doesn't support SNI properly,
so trying to clone from xiph.org fails (since the default certificate
for the site specifies opus-codec.org, not xiph.org).
It's also a bit nicer not to leech on Xiph.org's bandwidth. Plus,
we now have the possibility to do fixups (that aren't upstreamable for
some reason) to these repos without too much hassle.

.gitmodules: always use our own submodule repos on GitHub.

---

src/SSL.cpp
src/SSL.h
src/SSLLocks.cpp
src/SSLLocks.h
src/mumble.pri
src/mumble/main.cpp
src/tests/TestCrypt/TestCrypt.cpp
src/tests/TestCrypt/TestCrypt.pro
src/tests/TestCryptographicHash/TestCryptographicHash.cpp
src/tests/TestCryptographicHash/TestCryptographicHash.pro
src/tests/TestCryptographicRandom/TestCryptographicRandom.cpp
src/tests/TestCryptographicRandom/TestCryptographicRandom.pro
src/tests/TestPasswordGenerator/TestPasswordGenerator.cpp
src/tests/TestPasswordGenerator/TestPasswordGenerator.pro
src/tests/TestSSLLocks/TestSSLLocks.cpp
src/tests/TestSSLLocks/TestSSLLocks.pro
src/tests/TestSelfSignedCertificate/TestSelfSignedCertificate.cpp
src/tests/TestSelfSignedCertificate/TestSelfSignedCertificate.pro
src/tests/tests.pro

We neglected to register our own callbacks for locking and thread IDs
when we removed the restriction that we only allow one copy of OpenSSL
in the address space. (f544524)
This commit remedies that by providing our own set of callbacks for
locking and getting thread IDs to OpenSSL.
Previously, we just expected that Qt would properly initialize OpenSSL.
However, when Qt and us use separate copies of OpenSSL -- we have to do
it ourselves.

SSL: register OpenSSL threading callbacks when we can't access Qt's OpenSSL.

---

installer/Product.wxs

This reverts commit 3d4663465ea1e528a299f1939237c31a4188775c.
That commit was done because of reports that stale files from
old versions of Mumble were left behind. In particular, in
the "Versions" subdirectory.
I just tested this locally, and I can't reproduce that problem.
Reverting this commit should hopefully resolve a lot issues
such as:
mumble-voip/mumble#2901
mumble-voip/mumble#1917
mumble-voip/mumble#1845
mumble-voip/mumble#1700
Perhaps more.

installer: revert "installer: force uninstall before install."

---

src/mumble/Overlay_win.cpp

This gets rid of the errors in the Mumble log about destroying
QProcess instances while they're still running.

Overlay_win: properly terminate our overlay helper processes.

---

src/mumble/GlobalShortcut_win.cpp

Prior to this change, using Mumble on Windows would produce a warning
from Qt in the log:
<W>2017-07-20 12:11:33.842 QObject::killTimer: Timers cannot be stopped from another thread
<W>2017-07-20 12:11:33.842 QObject::~QObject: Timers cannot be stopped from another thread
This was because the QTimer in GlobalShortcutWin, used for polling
the various global shortcut engines, was being destroyed by the wrong
thread.
The QTimer in GlobalShortcutWin is constructed within the
GlobalShortuctWin thread. So, the QObject belongs to that thread.
However, the destructor of GlobalShortcutWin is not called in the
scope of the thread. It is called on the main thread by
GlobalShortcutEngine::remove (in GlobalShortcut.cpp) when the last
GlobalShortcut object is removed.
This change works around the …

GlobalShortcut_win: delete poll timer inside the GlobalShortcut thread.

---

src/murmur/MurmurGRPCImpl.h

This existing syntax doesn't build on my Ubuntu 14.04 LTS test machine, and
it seems odd to me.
Change the syntax to something more conventional.

MurmurGRPCImpl.h: declare variable for QMutexLocker in RPCSingleStreamCall class.

---

src/mumble/ConnectDialog.cpp

This ensures that we apply all globally visible state from the lookedUp()
method before we attempt to auto-connect.
The previous block of code would, when auto-connect is enabled, call
accept() to perform the auto-connect. In case the selected ServerItem
has no username set, accept() will trigger a dialog box to appear asking
the user to input their desired username. Unfortunately, showing this
dialog causes Mumble to enter the event loop before the lookedUp()
method anticipated it to be entered. The point at which the auto-connect
happens, is before the lookedUp() method has had time to update the
global state of the ConnectDialog to reflect the successful host lookup.
In practice, this meant that the auto-connect would be triggered many,
many times in a row. In this scenario, Mumble …

ConnectDialog: re-arrange lookedUp() code to avoid recursive runloop problem.

---

src/murmur/murmur.pro
src/murmur/murmur_ice/murmur_ice.pro

CONFIG(ermine) was used before we had CONFIG(buildenv).
All CONFIG(ermine) does is to try and use Ice from our build
environment.

src/murmur: remove CONFIG(ermine), use CONFIG(buildenv) instead.

---

src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.h
src/mumble/GlobalShortcut_win.cpp
src/mumble/GlobalShortcut_win.h
src/mumble/MumbleApplication.cpp

We don't support the in-overlay Mumble client in 1.3.x because it doesn't
work correctly on Qt 5.
It's a big hack. Let's wave goodbye.

GlobalShortcutWin: remove code related to the in-overlay Mumble client.

---

src/murmur/murmur.pro
src/murmur/murmur_ice/murmur_ice.pro

Fixes #3210 
Ice 3.7 seems to have changed some folder's capital case around (Ice -> ice), added an include path to fix that.
Besides that IceUtil merged into Ice, added some logic to select the correct linking params.
Didn't test actual running with ice enabled in settings, it compiles and murmur runs without problems. Also I couldn't test it with 3.6, since I don't have 3.6 installed on any of my machines anymore.
Please be free to suggest improvements, I didn't wrote any qmake stuff before.
More Ice 3.7 stuff: https://doc.zeroc.com/display/Ice37/Upgrading+your+Application+from+Ice+3.6

[BUILD] ZeroC Ice 3.7 compatibility

---

src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.ui
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/main.cpp
src/mumble/mumble.pro
src/mumble/os_early_win.cpp

This is a continuation of PR mumble-voip/mumble#2008. This PR implements the mechanism to disable UIAccess in mumble_app.dll instead of mumble.exe -- a much cleaner architecture that keeps our mumble.exe minimal.

Allow users to disable UIAccess via Additional Shortcut Engines setting.

---

src/mumble/GlobalShortcut_win.cpp
src/mumble/GlobalShortcut_win.h
src/mumble/MumbleApplication.cpp

This should fix the problem where some keys could not be observed in
Mumble when Mumble was the program in focus. People have reported this
problem with keys F13-F24.
The reason these keys could not be observed in Mumble is that:
Our keyboard and mouse hook callbacks do not receive keypresses and
mouse clicks when Mumble is on focus. We only recieve events when
other programs are focused.
DirectInput does not know of F13-F24.
To remedy this situation, this commit implements a system where we feed
the native Windows keyboard and mouse events from Qt's nativeEventFilter
into GlobalShortcutWin.
Technically, we provide methods in GlobalShortcutWin that allows the
nativeEventFilter to inject keyboard and mouse evnets into it. The events
from nativeEventFilter are received on the main thread. …

GlobalShortcutWin, MumbleApplication: inject native WM_* keyboard and mouse messages into GlobalShortcutWin. 

---

src/mumble/GlobalShortcut.ui

Basically: relesed -> released.

GlobalShortcut: fix typo in What's This for 'Enable shortcuts in privileged applications'

---

3rdparty/celt-0.11.0-build/celt-0.11.0-build.pro
3rdparty/celt-0.7.0-build/celt-0.7.0-build.pro
3rdparty/opus-build/opus-build.pro
3rdparty/speex-build/speex-build.pro
g15helper/g15helper.pro
macx/osax/osax.pro
macx/scripts/scripts.pro
main.pro
overlay/overlay-shared.pro
plugins/plugins.pro
scripts/scripts.pro
src/mumble/mumble.pro
src/murmur/murmur.pro

We used to use DIST for referencing extra files that should be included
in our tarballs created by 'make dist'.
However, we've since migrated away relying on 'make dist' in release.pl.
Instead, we include everything, and have a list of items to exclude, such
as IETF RFC drafts distributed in 3rdparty/speex-src that do not adhere to
the Debian Free Software Guidelines.

Remove DIST directive from all .pro files.

---

src/mumble/GlobalShortcut_win.cpp
src/mumble/GlobalShortcut_win.h
src/mumble/MumbleApplication.cpp

This adds the ability to suppress global shortcuts injected from the main
thread. In practice, this means that Mumble will now honor suppressed keys
*inside* Mumble itself.
This is implemented by using a std::promise<bool>. The
injectKeyboardMessage and injectMouseMessage methods now
create a std::promise<bool> and a future associated with
the promise. The promise is then passed onto the GlobalShortcut
engine thread via InjectKeyboardMessageEvent and InjectMouseMessageEvent.
Once the injection events have been posted, injectKeyboardMessage
and injectMouseMessage will wait on the future, blocking the main thread
until the GlobalShortcut engine's thread sets the promise's value to
whether or not the injected event is supposed to be suppressed.
The injectKeyboardMessage and …

GlobalShortcutWin, MumbleApplication: add suppression support for injected Windows keyboard/mouse message events.

---

scripts/murmur.ini
src/FFDHE.cpp
src/FFDHE.h
src/murmur/Meta.cpp
src/tests/TestFFDHE/TestFFDHE.cpp

This PR uses the newly introduced FFDHE class to allow users to specify RFC 7919 Diffie-Hellman parameters for the sslDHParams option in murmur.ini.
Also, this PR changes the default value for the sslDHParams option. Instead of being blank by default (which would previously cause Murmur to auto-generate Diffie-Hellman parameters for all virtual servers), we now use @ffdhe2048.
This PR depends on
mumble-voip/mumble#3183
Fixes mumble-voip/mumble#2204

Allow users to specify RFC 7919 Diffie-Hellman parameters for the sslDHParams murmur.ini option

---

src/murmur/Cert.cpp

Remove automatic generation of Diffie-Hellman parameters for vservers.
There were various problems with this approach.
- It was somewhat slow.
- To avoid blocking the main thread while generating the DH parameters,
the code would enter an event loop. However, this meant that other code
could still execute (for example, clients could connect to the server
before the DH params were generated).
As a replacement, we're going to be shipping the Diffie-Hellman parameters
from RFC 7919 bundled into Murmur, and we'll default to one of them.

murmur/Cert: remove auto-generation of Diffie-Hellman parameters.

---

src/mumble/GlobalShortcut_win.cpp

When a lookup in qhNames fails, it returns a default-constructed (null and
empty) string.
Do not update the name variable if the result of the lookup is empty.
This ensures we fall back to 'Unknown' when we encounter an unknown
button.
For now, this means that "F13-F24" are shown as K:Unknown instead of just
"K:".

GlobalShortcutWin: fall back to 'Unknown' for unknown DirectInput buttons.

---

src/murmur/MurmurIce.cpp
src/murmur/murmur_ice/murmur_ice.pro

Our OSX build uses brew to install dependencies, amongst which is Ice.
The brew keg (package) `ice` was updated from 3.6 to 3.7.
With the update, the slice file path changed to `/usr/local/opt/ice/share/ice/slice`
(where `/usr/local/opt/<keg-name>` is the symlinked path to the currently installed keg (=package) files.
* Use `share/ice/slice` as a possible subpath for slice file inclusion when running slice2cpp to compile Ice cpp files.
* Replace method calls that were marked obsolete in Ice 3.7.

Fix Travis OSX build, Support Ice 3.7

---

scripts/travis-ci/before_install.bash

Using brew to install now fails because of an incompatible ruby version.
Update brew before installing a package to work around this.
https://github.com/travis-ci/travis-ci/issues/8552

Fix travis OSX build

---

src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h

ServerHandler::sendPing must be invoked in the ServerHandler's thread since it contains networking code.
Also there is a direct call to sendPing routine from
```c++
void MainWindow::msgServerSync(const MumbleProto::ServerSync &msg) {
g.sh->sendPing(); // Send initial ping to establish UDP connection
```

Fixed crashing on disconnect

---

src/mumble/Database.cpp

In a userbase of primarily gamers system instabilities aren't
that uncommon. Without synchronization of the user-db this can
lead to corruption of our client database storing the
user-certificate. We have had various reports of such issues
over time.
The current mode was set in 2010 in commit 9fee66e8 to speed
up the client-db "even more" though it is unclear whether we
actually had performance problems that required this step.
This patch switches the client synchronization mode from OFF
to NORMAL which according to the sqlite documentation will
leave a "very small" chance for database corruption but is
than the default FULL sync mode.
This commit should partially address issue #3254 by making
database corruption much more unlikely but detecting
corruption and/or handling DB backups are …

Switch client DB to sqlite synchronization mode NORMAL

---

src/mumble/ServerHandler.cpp

It causes Mumble's UDP system to not work properly on Linux, probably because udpRead() is never called.
Fixes issue #3256.

ServerHandler.cpp: Remove "Qt::QueuedConnection" attribute for connection between "readyRead()" and "udpReady()"

---

src/mumble/ConnectDialog.cpp
src/mumble/ConnectDialog.h
src/mumble/ConnectDialogEdit.ui
src/mumble/Themes.cpp

The commits in this PR restructure the ConnectDialogEdit code and implement suggesting to the user to fill the dialog form from the clipboard (if clipboard data is available). Implements #3143 
---
Outdated
TODO:
@mkrautz @davidebeatrici @hacst what do you think about this new UI element (as per screenshot)?
Also makes sense for prefilling with the current connected to server instead of autofilling like we currently do, right? (Even though we can not have invalid/wrong data there like for HTTP URLs.)

Allow Prefilling Add Server Dialog With HTTP URLs

---

src/ServerResolver_qt5.cpp
src/mumble/ConnectDialog.cpp
src/tests/TestServerResolver/TestServerResolver.cpp

This PR includes two fixes for SRV port issues.
The first fix is for ServerResolver.  The Qt 5 (SRV) version had a bug where resolved ServerResolverRecords would be created with `m_origPort`. In practice, this meant that Mumble would *always* use the port specified in the ConnectDialog record for the server. Typically, this would be 64738, the default port.
The second fix is somewhat related to the first. The ConnectDialog had a bug where it would use `ServerResolver::port()` instead of `ServerResolverRecord::port()` when constructing the list of resolved addresses for a ConnectDialog entry. Unfortunately, `ServerResolver::port()` is the "original port". That is, the port specified in the ConnectDialog entry. Once again, this meant that Mumble would display the wrong port to user: the one …

Fix SRV port bugs in ServerResolver and ConnectDialog 

---

overlay_gl/init_unix.c

This fixes a crash in libmumble's library constructor when built against
the musl libc.
The code that locates libc's `dlsym(3)` relied on addresses in dynamic
entries in the link map returned by `dlopen(3)` to always be absolute.
This seems to be specific to glibc though, so add a glibc feature test.

overlay_gl: linux: only assume absolute dynamic entries on glibc.

---

src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/NetworkConfig.cpp
src/mumble/NetworkConfig.ui
src/mumble/Settings.cpp
src/mumble/Settings.h

This change remove support for loading external images.
That is, this change ensures Mumble doesn't load images from <img> tags in text messages,
comments and channel descriptions via HTTP or HTTPS.
With this change in place, Mumble only supports images that are embedded
in the message via data URLs.

Log: remove support for external images.

---

src/mumble/GlobalShortcut_win.cpp

The comment block that justifies the use of Boost in GlobalShortcut_win
accidently stated that MinGW "does not support
boost:future/boost::promise", which is incorrect.
Fix the comment to say what was intended: that MinGW doesn't
support std::future/std::promise.

GlobalShortcut_win: fix std::/boost:: confusion in comment.

---

qmake/compiler.pri
src/OSInfo.cpp

Qt 5.10 uses features available only on macOS 10.8, such as
std::future<void>.
See the referenced issue for more information.
Fixes mumble-voip/mumble#3288

qmake/compiler.pri: target macOS 10.8 when building against Qt 5.10 or above.

---

src/mumble/AudioOutput.cpp
src/mumble/mumble_pch.hpp
src/tests/TestStdAbs/TestStdAbs.cpp
src/tests/TestStdAbs/TestStdAbs.pro
src/tests/tests.pro

This change Fixes AudioOutput to use the float overload of std::abs:
float std::abs(float);
instead of a non-existant template version.
Fixes mumble-voip/mumble#3281
Needs-Backport: 1.2.x

AudioOutput: do not use non-existant template version of std::abs.

---

src/PlatformCheck.cpp
src/PlatformCheck.h
src/tests/TestCrypt/TestCrypt.pro
src/tests/TestCryptographicHash/TestCryptographicHash.pro
src/tests/TestCryptographicRandom/TestCryptographicRandom.pro
src/tests/TestFFDHE/TestFFDHE.pro
src/tests/TestPacketDataStream/TestPacketDataStream.pro
src/tests/TestPasswordGenerator/TestPasswordGenerator.pro
src/tests/TestSSLLocks/TestSSLLocks.pro
src/tests/TestSelfSignedCertificate/TestSelfSignedCertificate.pro
src/tests/TestServerAddress/TestServerAddress.pro
src/tests/TestServerResolver/TestServerResolver.cpp
src/tests/TestServerResolver/TestServerResolver.pro
src/tests/TestStdAbs/TestStdAbs.pro
src/tests/TestTimer/TestTimer.pro
src/tests/TestUnresolvedServerAddress/TestUnresolvedServerAddress.pro
src/tests/TestXMLTools/TestXMLTools.pro
src/tests/test.pri

Originally via https://github.com/mumble-voip/mumble/pull/3277.
It turns out SRV resolving is broken in Wine. So, for now, skip the tests when running on Wine.

Disable SRV tests  when running on Wine

---

.travis.yml

Our MinGW build was left stale due to mumble-voip/mumble#3208.
Although our current MinGW builders use Wine as their test runner
-- and were added to allow_failures exactly for that reason --
it makes more sense to get blocked from merging on build failures.
The alternative is that we actively *check* that the MinGW is not
broken, which doesn't happen in practice.
We obviously can't expect Wine to mirror the exact behavior on any
particular Windows version, but let's just look at the MinGW targets
in .travis.yml as a check for whether a) the MinGW build works on Linux,
and b) whether our tests pass using Wine.

.travis.yml: remove mingw builds from allow_failures.

---

src/murmur/MurmurGRPCImpl.cpp
src/murmur/MurmurGRPCImpl.h
src/murmur_grpcwrapper_protoc_plugin/main.cpp

When gRPC support initially has been added to Murmur there was no way to get notified when a stream to a client has been cancelled (e.g. by the client or simply network failure). So back then a timer has been used to periodically check all active streams via `ServerContext::IsCancelled()`.
By now there's `ServerContext::AsyncNotifyWhenDone(void*)` which one can use to get notified of closed/cancelled streams.
In fact, `ServerContext::IsCancelled()` has been declared unsafe to call unless said method is used (and it does indeed cause Segfaults).
This PR changes Murmur's gRPC server to use AsyncNotifyWhenDone instead of the no longer functional cleanup timer.

Update gRPC server to work with recent gRPC versions

---

src/murmur/MurmurGRPCImpl.cpp

`Server::removeChannel` already acquires the voice thread lock where necessary, doing so before calling it will result in a dead lock.

GRPC: fix deadlock in removeChannel

---

src/mumble/ServerHandler.cpp

sss123next in mumble-voip/mumble#3294 reports that the current ping
timer logic causes problems with slow TLS handshakes, such as when
connecting to servers with large DH parameters.
This commit ensures pings are not sent before the TLS handshake has
completed.

ServerHandler: do not send pings unless the TLS handshake has completed.

---

scripts/travis-ci/before_install.bash

Our Tavis CI builds ended up taking a long time to complete.
This PR was made to try out whether mirroring pkg.mxe.cc ourselves would improve that situation.
It did.   Build times dropped from ~50 minutes to ~15 minutes.

scripts/travis-ci: use our own (Fastly-fronted) mirror of pkg.mxe.info.

---

src/mumble/ServerHandler.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h

This PR contains two commits:
1. `Settings: implement settings for ping interval and connection timeout duration.`, which adds the necessary plumbing to the Settings class.
2. `ServerHandler: use ping interval and connection timeout duration from Settings instead of magic numbers.`, which hooks up ServerHandler to use the new values from the Settings class.

ServerHandler, Settings: add ping interval and connection timeout duration settings.

---

overlay_gl/overlay_gl.pro

Linking the overlay library with '-z now' requires all target
processes to have libGL symbols in them at load time.
If it doesn't, the program will not start at all.
Instead, explicitly use '-z lazy' to defer libGL symbol resolution
until first use, which is never for non-libGL users.
[This is a backport of 859da4dabec070959b5c06f8d32512990d7ec9c2
from the master branch.]

Do not link the Linux overlay with '-z now'.

---

src/mumble/AudioOutput.cpp

This cherry-picks commit ea861fe86743c8402bbad77d8d1dd9de8dce447e into 1.2.x to fix the std::abs issue reported in mumble-voip/mumble#3281.
In short, the commit fixes a problem where we used a (non-existant) template version of std::abs that older compilers were OK with, but newer compilers are not.

Backport AudioOutput std::abs fix to 1.2.x.

---

scripts/travis-ci/script.bash

Change our checks for MUMBLE_NO_PCH to use string comparisons
instead of numerical comparisons.
When MUMBLE_NO_PCH is not set, the numerical equivalent check
fails because nothing is on the left-hand side of the -eq operator.
Fixes mumble-voip/mumble#3314

scripts/travis-ci: fix MUMBLE_NO_PCH checks in script.bash.

---

scripts/travis-ci/before_install.bash

After switching to using a mirror of MXE on dl.mumble.info we've begun
running into timeouts from apt on Travis CI. For example:
E: Failed to fetch https://dl.mumble.info/mirror/pkg.mxe.cc/repos/apt/debian/pool/main/m/mxe-x86-64-unknown-linux-gnu-cmake/mxe-x86-64-unknown-linux-gnu-cmake_3.5.2-20170208_amd64.deb  Operation too slow. Less than 10 bytes/sec transferred the last 10 seconds
The error is from cURL, and it means that the options CURLOPT_LOW_SPEED_LIMIT
and CURLOPT_LOW_SPEED_TIME are set quite low.
(See https://github.com/curl/curl/blob/bb0ffcc36fd46298e02f943b255ee5d6553c06dc/lib/speedcheck.c)
To fix this, we set the Acquire::http::Timeout option to 120 seconds.
This causes apt's https transport to set CURLOPT_LOW_SPEED_TIME to 120.
(See …

scripts/travis-ci: bump apt timeout in before_install.bash.

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h

This commit adds a signal to ServerResolver and a slot to MainWindow to handle ServerHandler errors, in order to start the reconnection timer after the first connection attempt.
Fixes #3220.

Correctly handle ServerResolver errors, with dedicated signal and slot

---

src/Group.cpp
src/mumble/Cert.cpp
src/mumble/PulseAudio.cpp
src/murmur/Server.cpp

Fix and refactor problems found via GCC 7's -Wimplicit-fallthrough.
This commit fixes various problems discovered by building on Debian buster
which uses GCC 7. Building on buster gave various -Wimplicit-fallthrough warnings.
In Group.cpp and Server.cpp, we now use if statements instead of a switch with fallthrough.
This improves readability of the code, and fixes the implicit fallthroughs.
In PulseAudio.cpp, we had unintended fallthroughs in a switch statement, which have been
fixed.
In Cert.cpp, we had a potential fallthrough which was impossible to trigger at runtime,
fixed by adding an error return, like the surrounding code.
Fixes #3306.

Fix and refactor problems found via GCC 7's -Wimplicit-fallthrough.

---

src/SelfSignedCertificate.cpp
src/SelfSignedCertificate.h
src/tests/TestSelfSignedCertificate/TestSelfSignedCertificate.cpp

Previously, the generator was choosing the certificate type (server or client) basing on the presence of the name and email, which broke it.
This PR also includes various other small fixes.
Fixes mumble-voip/mumble#3284.

SelfSignedCertificate: fix automatic certificate generator

---

src/murmur/Server.cpp

0b5579c erroneously replaced the
variable (letter) l with the integer 1.
Revert this change and use a more descriptive variable name `len`.
Fixes #3325

Fix error when handling TCP tunneled UDP voice packets

---

src/murmur/MurmurGRPCImpl.cpp

ignore connecting users in qhUsers hash in gRPC implementation

---

src/mumble/XMLTools.h
src/tests/TestXMLTools/TestXMLTools.cpp

This fixes the build on our OS X Universal builder.
Our legacy OS X Universal builder's gcc 4.2 seems to
misparse this.
There are no users of this default argument, and it's an
internal API. We can change it as we wish.
Fixes mumble-voip/mumble#3336

XMLTools: remove unused default argument 'opstyle' in recurseParse().

---

3rdparty/celt-0.11.0-build/celt-0.11.0-build.pro
3rdparty/celt-0.7.0-build/celt-0.7.0-build.pro
3rdparty/mach-override-build/mach-override-build.pro
3rdparty/minhook-build/minhook-build.pro
3rdparty/opus-build/opus-build.pro
3rdparty/sbcelt-helper-build/sbcelt-helper-build.pro
3rdparty/sbcelt-lib-build/sbcelt-lib-build.pro
3rdparty/speex-build/speex-build.pro
3rdparty/xinputcheck-build/xinputcheck-build.pro
g15helper/g15helper.pro
macx/compat/compat.pro
macx/osax/osax.pro
overlay/overlay-shared.pro
overlay/overlay.pro
overlay/overlay_exe/overlay_exe-shared.pro
overlay/overlay_exe/overlay_exe.pro
overlay_gl/overlay_gl.pro
overlay_winx64/overlay_exe_winx64/overlay_exe_winx64.pro
overlay_winx64/overlay_winx64.pro
plugins/plugins.pri
qmake/builddir.pri
qmake/compiler.pri
qmake/symbols.pri
src/mumble.pri
src/mumble_exe/mumble_exe.pro
src/mumble_proto/mumble_proto.pro
src/murmur/murmur_grpc/murmur_grpc.pro
src/murmur/murmur_ice/murmur_ice.pro
src/tests/test.pri

This pull request sets all build artifacts to be stored in a single build directory in the root of the source tree (either "release" or "debug").
Previously, that build folder was set in in every component's project file, rather than in one of the global project files (such as "compiler.pri").
Every build file (aside from the binary) was created in the component's project directory rather than in the build one.
Also, the tests binaries were being created inside their project folder, meaning that Git showed these files as "added" rather than "untracked".
In addition to that, there was a problem with the shadow builds: binaries being in our build directory and other artifacts in the shadowed one.
This pull request sets custom folders in "compiler.pri" for as many types of build file as …

Set custom build folders globally, with support for shadow builds

---

src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/Log.ui
src/mumble/Settings.h
src/mumble/mumble_en.ts

Add per-notification setting to toggle window highlight (if not active)

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/UserModel.cpp
src/mumble/UserModel.h

Change icon when muted/deafened

---

installer/MumbleInstall.wixproj

This should allow building the installer with Visual Studio.
Thanks to @sregister for the bugreport.

installer: only use WiX toolset from MUMBLE_PREFIX if the MUMBLE_PREFIX env var is set.

---

overlay_gl/overlay.c

I have Mac OS installed on a case-sensitive filesystem and compilation fails without this change.

Correct case of AGL/agl.h to allow compilation on case-sensitive filesystem

---

src/mumble/MainWindow.cpp
src/mumble/SvgIcon.cpp
src/mumble/SvgIcon.h
src/mumble/mumble.pro

This commit adds new class SvgIcon which allows you to create a QPixmap-backed QIcon
from an SVG.
We need this to fix mumble-voip/mumble#3124.
Basically, SVG-backed QIcons returns an empty list for QIcon::availableSizes().
There is some confusion as to whether this is the expected behavior or not.
(Tracked in mumble-voip/mumble#3374).
However: Plasma/KStatusNotifierItem currently expects QIcon::availableSizes()
to return a valid list of available sizes. For our SVG icons, that is not the case.
This commit works around this by constructing a QIcon backed by pixmaps, such that
QIcon::availableSizes() returns something sensible.
This is implemented via the static method, SvgIcon::addSvgPixmapsToIcon(), which renders
SVG icon in various common sizes (including 22x22 and 44x44, the Plasma …

SvgIcon: add new class to work around issues with SVG QIcons in Plasma/KStatusNotifierItem

---

src/mumble/XMLTools.h

Our macOS Universal build has been dead for a while. This is due to an
interaction between XMLTools.cpp, XMLTools.h and Qt 4.
In Qt 4, the QXmlStream* classes once lived in the QXml module. In Qt 4.4,
they were moved to QtCore. However, to keep binary compatibility, the symbols
from QtCore are called QCoreXmlStreamReader/QCoreXmlStreamWriter.
The qxmlstream.h header then has preprocessor defines to map
QXmlStream* to QCoreXmlStream*. For more information, see:
https://github.com/qt/qt/blob/0a2f2382541424726168804be2c90b91381608c6/src/corelib/xml/qxmlstream.h#L100-L114
This means that the pre-declared classes used in XMLTools.h:
class QXmlStreamReader;
class QXmlStreamWriter;
won't work with Qt 4, >= 4.4, since QXmlStreamReader and QXmlStreamWriter
don't exist in QtCore in those verions of …

XMLTools: include QXmlStream headers to get proper symbols names on Qt 4.

---

src/mumble/main.cpp

This fixes a link-time issue for the macOS Universal build.
It only happens there because it's the only Qt 4 static build
we have a build machine for.
The problem is that commit 7a450721f2a76048a57f1ebf9d7d9e89d4bd3db0
changed mumble.pro to only include qico for Windows.
That commit did not update main.cpp to not invoke Q_IMPORT_PLUGIN(qico)
for non-Windows platforms.
This commit fixes that, and hopefully allows the macOS Universal build
to link properly.

Only invoke Q_IMPORT_PLUGIN(qico) on Windows.

---

src/mumble/mumble.pro

PR mumble-voip/mumble#2688 refactored the .pro file to
avoid special-casing newer versions of Qt.
However, in doing that, it also left out the qtaccessiblewidgets
from PLUGINS for Qt 4 builds.
This commit remedies that, by rewriting the comparison logic to
use integer-based Qt versions instead of complicated logic where
each part of the version (major/minor) is compared separately.
This makes the code easier to read, and fixes a link-time issue
for the macOS Universal build. Since qtaccessiblewidgets is not
on PLUGINS on Qt 4, the build doesn't link against -lqtaccessiblewidgets,
causing linking to fail.

Add qtaccessiblewidgets to PLUGINS for Qt 4 builds.

---

src/mumble/PulseAudio.cpp

On non-English locale systems, PulseAudio localises the sink/source names, resulting in invalid characters being rendered in the mumble audio settings widget.
Switching QStrings from Latin1 to Utf8 in PulseAudio.cpp fixes this issue.

Use Utf8 QStrings for PulseAudio

---

scripts/murmur.ini
src/Mumble.proto
src/mumble.pri
src/mumble/Messages.cpp
src/murmur/Messages.cpp
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/Server.cpp
src/murmur/Server.h

Having to many channels on a server can impact performance to the point
of making the instance unusably slow. This can be a problem for hosters
that allow their users unlimited channel creation.
This patch introduces a new per-server configuration parameter
channelcountlimit which can be used to configure a maximum number of
channels that may be created on each of the virtual servers. Once the
limit is reached channel creation will be rejected with permission
denied.
To allow a translated error message we have to bump the client version
to 1.3.1 to be able to use a fallback message for older clients.
As usual dbus, ice and grpc can ignore this limit. It is only enforced
against clients.
Note that I have not done extensive testing of this patch. The setting seems to work as expected when …

Introduce channelcountlimit to limit max channels per server

---

scripts/travis-ci/before_install.bash

Python's installation folder has been changed in a recent update, causing Brew to fail because there are symlinks pointing to files which were in the old one.

travis-ci: unlink Python 2 files on MacOS

---

src/mumble/ACLEditor.cpp
src/mumble/ConnectDialog.cpp
src/mumble/Database.cpp
src/mumble/Database.h
src/mumble/Global.h
src/mumble/GlobalShortcut.cpp
src/mumble/MainWindow.cpp
src/mumble/Messages.cpp
src/mumble/Overlay.cpp
src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h
src/mumble/Tokens.cpp
src/mumble/UserLocalVolumeDialog.cpp
src/mumble/UserModel.cpp
src/mumble/main.cpp

Qt5 documents that QSqlDatabase must not be called from varying threads.
An instance must be limited to its thread.
In Mumble the Database class handles database access.
Up to now it contained static methods and always used the global default
database instance.
We instantiate the default database connection into the Global context.
It is mostly used from the main event loop, but also from a thread in
ServerHandler.
This is broken as per specification, and Qt 5.11 seems to finally enforce
that.
To resolve this issue, we promote Database to an instantiable class,
use the created Global context class instance from the event loop,
and a distinct Database instance (and connection) from the ServerHandler
instance (and thread).
---
This replaces PR #3419.
@davidebeatrici Please not the elaborate …

Fix #3411: Threaded access to Database

---

scripts/travis-ci/before_install.bash
src/mumble/JackAudio.cpp
src/mumble/JackAudio.h
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/mumble.pro

Hello,
I took the jack patch from https://github.com/mumble-voip/mumble/pull/137 and tried to fix/advance it.
Main Changes:
- Added stereo output support
- Configurable output devices (Mono/Stereo). We can talk about the names, as strictly speaking "Mono" or "Stereo" is not an output device.
- **EDIT**: Jack port auto connect is disabled by default and can be enabled in ~/.config/Mumble/Mumble.conf 
`[jack]
autoconnect=true`
- **EDIT**: the jack server starts by default on mumble start (if not already running). This can be disabled in ~/.config/Mumble/Mumble.conf 
`[jack]
startserver=false`
Bugfixes:
- Jack input/output was always running (even if not selected) and causing crashes when interacting with a different input/output source. This fixes the crash when changing the output/input …

Add JACK Audio support

---

src/mumble/JackAudio.cpp
src/mumble/JackAudio.h

This pull request improves JACK support by:
- starting the server only if JACK is set as audio backend;
- creating only the ports which are used by Mumble. Previously, both input and output ports were created even if only one of the two directions was being used.
@buscher Feel free to review.

JACK: don't start the server if using another backend, create only required ports

---

src/mumble/Settings.cpp

JACK should be ready to be used with little to no interaction required by the user, especially because the setting has to be changed by manually editing the configuration file.

Settings: enable JACK auto-connect option by default

---

src/mumble/Messages.cpp
src/mumble/mumble_en.ts

- A new message "User connected and entered channel." has been added, in order to distinguish when a user joins the server and when it moves to the channel
- The "User joined channel" sound is reproduced when a user joins the server and enters the same channel as the client
- When moving a user, there are no longer duplicate messages, such as: "You moved User into Channel." and "User moved to Channel by You."
- The message "User moved to Channel by the server." no longer appears, when the user connects to the server and is moved to the last channel he was in.

Messages: revamp channel join/leave logic and add "User connected and entered channel." message

---

3rdparty/opus-build/opus-build.pro
src/mumble/Audio.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioOutputSpeech.cpp
src/mumble/AudioOutputSpeech.h
src/mumble/Global.h
src/mumble/MainWindow.cpp
src/mumble/OpusCodec.cpp
src/mumble/OpusCodec.h
src/mumble/mumble.pro

In the past we already encountered a problem where we couldn't link statically to both Opus and CELT at the same time, because there are multiple symbols (functions) shared across the two libraries, as Opus is the successor of CELT.
Initially this was solved by building Opus in C++ mode. which provides name mangling for the symbols, but since version 1.1 this isn't possible anymore:
https://github.com/mumble-voip/mumble/blob/c19ac8c0b0f934d2ff206858d7cb66352d6eb418/3rdparty/opus-build/opus-build.pro#L50-L57
We currently build Opus as static library and CELT as shared, loading it through the `CELTCodec` class.
#3427 adds support for RNNoise, an advanced noise suppression library, which has some functions shared with Opus, resulting in a linker error.
This pull request adds a new class …

Create OpusCodec class, similar to CeltCodec, in order to load Opus' functions from a shared library

---

src/mumble/OpusCodec.cpp

The library is called `libopus.so.0` on Ubuntu and `opus.dll` on Windows.

OpusCodec: add "libopus.so.0" (Linux) and "opus.dll" (Windows) to the library names

---

src/mumble/mumble.pro

The name of the library is `boost_thread-mt.a`.

Fix Boost library link for MSYS2

---

src/mumble/Log.cpp

Log: fix notification being triggered for own messages when TTS readback is enabled

---

installer/Files.wxs
installer/Product.wxs
installer/Settings.wxi

Fixes #3477.
The file copy can be disabled with the MumbleNoRNNoise environment variable.

installer: copy rnnoise.dll

---

src/mumble/JackAudio.cpp

`jack_get_ports()` returns all the ports registered on the JACK server, unless a name pattern is specified, which means that Mumble disconnected ports registered by other clients.
This commit changes `disconnect_ports()` so that it disconnects the ports which are stored in our internal variables, making it faster.
Fixes #3489.

JackAudio: change disconnect_ports() so that it uses stored ports instead of retrieving them using jack_get_ports()

---

src/murmur/Messages.cpp
src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

This patch adds a rate limiting to selected patches. The underlying rate limiter
used is the Leaky-Bucket algorithm. It allows for a burst of messages, but
limits them after a specified amount of messages within a time frame.
If the ratelimit hits the messages are simply ignored.
For now its set to a burst of 30 allowed messages and a subsequent limit of 4 messages per second, which seems to do the trick without inconveniencing normal users.
It should to some extend prevent the recent issues with bots decribed in #3505.
What was tested with the patch:
- Joining (works)
- Talking with UDP and TCP mode (works)
- Switching channels (works)
- Bringing down the server with a bot, tested with two different bots (does not work)
I'm thanking the Zom.bi community for testing and @Natenom for some …

Prevent instability and crash due to message flood

---

src/murmur/ServerUser.cpp

I guess I was too generous with the bucket parameters. My bad.
After some more testing this evening a "1 message per second, 5 messages burst" limit is still sufficient enough to not _annoy_ people under normal circumstances.

Lower bucket params

---

scripts/murmur.ini
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

This makes the previously added rate limiter configurable. The change adds messagelimit and messageburst to the configuration file murmur.ini, the ServerDB as well as the ability to set these live. Because setting either of these to a value of 0 would render the Server unusable, both have a minimum of 1. The defaults are kept as before with a messagelimit of 1 and a messageburst of 5.
Though adjusting these live is entirely possible on the serverside, they currently only take effect for new connections. If they should take effect immediately for all present connections, I could add some more changes that allow that if you want.
I tested this change by printing either value on a new connection, as well as rapidly muting and unmuting myself with a messagelimit of 100 and a burstlimit of …

Make Rate limiter configurable

---

src/mumble/MainWindow.cpp
src/mumble/Settings.cpp

In environments where the system tray is not present (in my case, a tiling window manager on GNU/Linux) the application can still be hidden which causes it to become totally invisible and inaccessible while still running. This patch fixes that, by hiding the "Hide Mumble" menu item as well as making the application exit on window close when the system tray is not available.

Disable hiding when system tray not present

---

src/mumble/ALSAAudio.cpp

`snd_pcm_drain()` waits for all pending frames to be played.
`snd_pcm_drop()` is better in our case, because we want the PCM stream to be stopped immediately.
This fixes a problem where Mumble would hang when closing the ALSA stream:
```cpp
#0  0x00007ffff32484ec in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555556d32c10) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555556d32bc0, cond=0x555556d32be8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555556d32be8, mutex=mutex@entry=0x555556d32bc0) at pthread_cond_wait.c:655
#3  0x00007ffff3509fbb in QWaitConditionPrivate::wait (time=18446744073709551615, this=0x555556d32bc0) at thread/qwaitcondition_unix.cpp:143
#4 …
```

ALSAAudioInput: use snd_pcm_drop() instead of snd_pcm_drain() in class destructor

---

src/murmur/ServerDB.cpp

This is a bad idea since it tries to delete primary key indices, which fails on modern MySQL/MariaDB versions thus breaking the upgrade process in the middle. The only way to recover is to rename all tables back to their original names, pull out this code and let it upgrade again. Also it seems pointless to me since all tables and thus their indices are getting destroyed afterwards anyways.

Don't drop indices on MySQL

---

.gitignore
src/SSL.cpp

../SSL.cpp:32:17: error: reinterpret_cast from 'nullptr_t' to 'void *' is not allowed\
when compiled with clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
While here, update gitignore with vim swp files.

Fix build on FreeBSD

---

.azure-pipelines.yml
README.md
scripts/azure-pipelines/build.ps1
scripts/azure-pipelines/install-environment.ps1

Azure Pipelines offers many advantages over AppVeyor, with the biggest one being a maximum of 10 parallel builds for open-source projects, drastically reducing the builds completion time.
A pipeline takes about the same time to build on the two CI infrastructures, however the caching feature is currently only available on AppVeyor, meaning that on Azure Pipelines the compressed environment is downloaded for each build consuming about 10 minutes.
This means that we'll save at least 10 minutes per pipeline compared to AppVeyor once the feature is added to Azure Pipelines: https://github.com/Microsoft/azure-pipelines-tasks/issues/9190

Add Azure Pipelines for continuous integration (Windows)

---

src/mumble/ConnectDialog.cpp
src/mumble/mumble_en.ts

1. There are currently two servers appearing in a non-existent continent and country because their public IP addresses are part of two blocks assigned recently which are not in our GeoIP database.
This commit adds a new continent called "Unknown" without countries, which replaces the "ghost" continent and category.
2. If the user's public IP address was not in our GeoIP database, the "Unknown" continent and country categories were expanded because the strings resulted empty.
This commit adds a check to make sure that those categories are never expanded automatically.
---
Before:
After:

ConnectDialog: create "Unknown" continent, never expand it automatically

---

src/murmur/Messages.cpp

Fixes #3585.
---
The vulnerability was kindly reported by the [zom.bi](https://zom.bi) community, who also provided a patch, which is applied in this commit.
Thank you very much for your support!

Murmur: fix Denial of Service vulnerability in msgChannelState()

---

src/mumble/Global.cpp

Fixes #1702.
---
`rename()` was failing because it doesn't expect the new directory to exist.
From Qt's documentation (http://doc.qt.io/qt-5/qdir.html#rename):
> On most file systems, rename() fails only if _oldName_ does not exist, or if a file with the new name already exists.

Global: fix migrateDataDir() not migrating the data directory

---

src/mumble/ViewCert.cpp

This PR prevents duplicate certificates from appearing in the certificate chain viewer. The fix uses a rather cautious approach (some may call it hacky) to address this issue as to avoid fiddling with the necessary "certificate chain shuffling" workaround cited in #2141

Fix Duplicate Certificates In Chain Viewer

---

main.pro
qmake/compiler.pri
qmake/pkgconfig.pri
src/mumble.pri
src/mumble/mumble.pro

This is a pull request for a set of 5 commits to allow making Mumble cross buildable, from a patch made by Helmut Grohne <helmut@subdivi.de> in Debian bug #919453.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919453

Crossbuild fix

---

src/mumble/Themes.cpp
src/mumble/Themes.h

Fixes https://github.com/mumble-voip/mumble/issues/2646, by creating a single function to load a stylesheet and user.qss

Refactor themes.cpp and themes.h

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/MainWindow.ui
src/mumble/mumble_en.ts

Fixes #3509 which involved the user being unable to show the window after hiding it with Mumble on LXDE environment

Add tray menu action to show the main window

---

src/mumble/AudioWizard.cpp

The sample is not part of the "skin" namespace since #3475.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921268

AudioWizard: fix speech sample path

---

src/mumble/ASIOInput.ui
src/mumble/AudioInput.ui
src/mumble/AudioOutput.ui
src/mumble/LCD.ui
src/mumble/Plugins.ui

Those windows are "integrated" into the Settings window and thus their title is not shown, but the strings appear in the translation files because they are marked as translatable.
Thanks to @deluxghost for reporting the issue.

mumble: change title of windows which have the default one ("Form")

---

src/mumble/Settings.cpp

We see a lot of crashes due to our GKey integration. Until we can
diagnose the underlying issue leaving GKey enabled by default is
not acceptable for the upcoming release.

Default disable GKey

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/mumble_en.ts

The CycleTransmitMode shortcut often leaves me in the wrong mode, so I want to add shortcuts for switching to specific modes.

Add global shortcuts for setting specific transmit modes

---

.travis.yml
scripts/travis-ci/before_install.bash
scripts/travis-ci/script.bash

Ubuntu Xenial is available on Travis CI since November: https://blog.travis-ci.com/2018-11-08-xenial-release
Regarding MXE's APT repository: mxe/mxe/issues/2253

travis-ci: switch to Xenial for Qt 5 builds, improve matrix, update MXE mirror

---

src/mumble/Messages.cpp

Since #3426 if you are, for example, in channel C and you move a user from channel A to B, no messages are shown.
This pull request changes this behavior so that the "You moved user to channel" message is always shown (#1133).

Messages: show "You moved user to channel" message also when the user is not in/moved to own channel

---

src/murmur/ServerDB.cpp
src/murmur/ServerDB.h

The Qt logging functions already insert spaces between each item when using the stream insertion operator, so no need to insert them manually.
I also fixed the name of the method (PKBDF2 should be PBKDF2).

Fix log spacing and typos when setting up the PBKDF2 iteration count

---

src/mumble/Settings.cpp

Fixed a small client bug which prevented `UserLeftChannel.ogg` from playing when a user disconnected from the current channel and server.
Introduced in fc4368ad53dd1f974453e53a3c0935baa2469595.

Fixed a bug/typo which prevented audio from playing on user disconnect

---

.azure-pipelines.yml
scripts/azure-pipelines/build_macos.bash
scripts/azure-pipelines/install-environment_macos.bash

This should lower the overall CI completion time, because the macOS build seems to always take a while to start on Travis CI.
The macOS build will be removed from Travis CI in a dedicated pull request.

Azure Pipelines: add macOS build

---

src/murmur/ServerDB.cpp

Before this commit, the `TransactionHolder` is not destructed until the end of `registerUser`, causing `setInfo` to try to open a transaction on top of the one created by `registerUser`.

Fix transaction handling in Server::registerUser

---

3rdparty/opus-build/opus-build.pro
macx/scripts/osxdist.py
scripts/travis-ci/script.bash

Fixes #3642.
We load Opus at runtime since #3431.

Build Opus as shared library in static build, copy it into App Bundle

---

src/SSL.cpp

When connecting to a server using TLS 1.3, the server information windows displays "The connection uses UnknownProtocol".
This pull request fixes that by adding a case for `QSsl::TlsV1_3` in `MumbleSSL::protocolToString(QSsl::SslProtocol protocol)`.
See https://doc.qt.io/qt-5/qssl.html#SslProtocol-enum
Before:
After:

Add support for TLS 1.3 in the server information window

---

src/murmur/murmur.pro

`win10DisplayableVersion` in `OSInfo.cpp` makes use of the registry to
determine a user displayable windows version string.
This was introduced in 88e664710dd375dc0be42a30dc266efa5833bb4c.
The registry functions used are in the Windows API `advapi32` library.
This file was not declared for linkage yet, which leads to a linker
error.
---
Why was this not a problem yet? Will it just work when running qmake for both client and server (not using `CONFIG+=no-client`?)

Add missing advapi32 library reference in server project

---

qmake/openssl.pri

MumbleSSL (defined in SSL.h/.cpp) uses OpenSSL functions - starting with
SSL_library_init. These functions are defined in the ssleay32 library.
This library was missing, which resulted/could result in linker errors
(in specific kinds of build environments).
---
Why was this not an issue before? Does our mumble-releng buildenv do some magic/have some side effects?
It was an issue for me when building from my new vcpkg environment.

Add missing ssleay32 library reference in openssl qmake configuration

---

src/mumble/JackAudio.cpp
src/mumble/JackAudio.h

Fixes #3682.
The crash happens when an invalid client is passed to `jack_port_register()`.
This pull request changes `JackAudioInit::initialize()` so that it aborts the initialization process in case the client cannot be opened (e.g. when the server cannot be started due to permission issues).
`bJackIsGood` was set to true by `init_jack()`, which was called by `initializeInput()` and `initializeOutput()`. In order to be able to check whether the client is correctly initialized (`bJackIsGood == true`) before making the backend available to the rest of the program (e.g. settings window), this pull request merged `init_jack()` with `JackAudioSystem()` and `destroy_jack()` with `~JackAudioSystem()`.
The downside to moving the client initialization into the constructor is that it stays open …

JackAudio: fix segmentation fault, revamp initialization logic

---

src/mumble/MainWindow.cpp

Closes #3680.
This pull request changes `MainWindow::on_Icon_activated()` so that it minimizes Mumble's window if it's not already.
Previously, no action occurred when clicking on the tray icon while the window was shown.

Minimize window on tray icon click

---

src/mumble/GlobalShortcut_macx.mm

Fixes #3471.
Since macOS Mojave, passing `NULL` to `CGEventTapEnable()` causes a segmentation fault.
This pull request also:
- Initializes pointers to `NULL` in the constructor.
- Adds a check in the destructor so that `NULL` is not passed to `CFRunLoopStop()`.
- Adds a check to `enabled()`, so that `NULL` is not passed to `CGEventTapIsEnabled()`.

GlobalShortcutMac: fix segmentation fault in setEnabled()

---

src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

Fixes #3662.
The legacy implementation (with `ctime`), used when `std::chrono` is not available (C++ < 11), caused the client's messages to be permanently blocked until it reconnected.
More specifically, `millisecondsBetween()` always returned 0.
This commit replaces both implementations with a simpler one which makes use of `QTime`.
@tu-maurice

ServerUser: use QTime instead of std::chrono and ctime

---

src/murmur/MurmurGRPCImpl.cpp

when updating username of GRPC DatabaseUserUpdate() it sets the comment (if no comment is set) using setUserInfo instead of setting the name

fixed setting comment to username instead of updating username

---

scripts/travis-ci/before_install.bash
scripts/travis-ci/script.bash

This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with …

Generate and upload AppImage

---

.travis.yml

Currently each build triggers an extraneous build. This fixes it.

Do not build tags that we create when we upload to GitHub Releases

---

.lgtm.yml

This file specifies two dependencies that weren't automatically identified by LGTM.com. With this file in place, the C/C++ analysis should start working.
Using the standard configure and build commands (LGTM detected that `qmake` followed by `make` should do the trick), only 1.8k of the ~250k LOC is built, so I guess the build needs a bit more tweaking. Feel free to amend this PR to add additional configuration/build hints for LGTM. Here's an example of what's possible: https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#example-lgtm.yml-file
Full disclosure: I'm part of the team that built LGTM. Happy to help!

Create lgtm.yml to configure C/C++ analysis for LGTM.com

---

.cirrus.yml

Cirrus CI released support for FreeBSD on their CI service in December: https://www.freebsd.org/news/newsflash.html#event20181211:01

Add Cirrus CI for continuous integration (FreeBSD)

---

src/SSL.cpp

qt/qtbase@92cda9474245c79b635c21cd140c5d0a3a6d2e5b

SSL.cpp: replace deprecated QSslSocket::systemCaCertificates() with QSslConfiguration::systemCaCertificates()

---

.azure-pipelines.yml
scripts/azure-pipelines/build_linux.bash
scripts/azure-pipelines/install-environment_linux.bash

This is the first step towards our new build infrastructure.

Azure Pipelines: add Linux build to create and store AppImage as artifact

---

scripts/travis-ci/script.bash

It's now handled by Azure Pipelines (#3734).

Travis CI: remove AppImage creation and upload

---

src/murmur/Server.cpp

Server.cpp: replace deprecated QSslSocket::setCiphers() with QSslConfiguration::setCiphers()

---

src/murmur/Register.cpp

Register.cpp: replace deprecated QSslSocket::defaultCaCertificates()

---

src/murmur/MurmurIce.cpp

qt/qtbase@5957f245c6c77c98d7e90d614c9fe2cdbfe7e8e6

MurmurIce.cpp: replace deprecated qSort() with std::sort()

---

scripts/azure-pipelines/build.ps1
scripts/azure-pipelines/install-environment.ps1

Recent builds have failed because there is not enough space in `C:\` after installing the build environment, which we used to extract in `C:\MumbleBuild`.
This commit changes the PowerShell scripts so that our environment directory (e.g. `MumbleBuild`) is created in the proper directory (**Agent.ToolsDirectory**'s value, e.g. `D:\a\_tool\`) instead of `C:\`.
`C:\MumbleBuild` is still required because our build environment's qmake expects its configuration files to be there (hardcoded). The environment installation script creates a symbolic link to solve the problem.

Azure Pipelines: store build environment in the proper directory

---

src/SSL.cpp

Fixes regression caused by 3cd2984e8a, as mentioned in the IRC room.

Use QSslSocket for Ca Certs on Qt5 < 5.5

---

src/mumble/Settings.cpp

This partially implements #3502 by setting bUseOpusMusicEncoding to default on, thus using CELT alone by default, the simplest step suggested by the issue.
As explained in the Opus docs, by restricting oneself to CELT and getting rid of the SILK layer, latency is lowered and higher quality is achieved.
As made clear by the issue description and further comments by other users, it seems pointless to keep this setting off by default. While I initially thought, based on theory, there might be a quality decrease for cases with very low bandwidth, this was unable to be reproduced in testing by me and another user with very low bandwidth and thus there seems to be virtually no drawback to turning this on in practice.
This is why at first I was going to implement this by keeping it off by …

CELT on by default.

---

plugins/gtav/gtav.cpp

This updates the GTA V Positional Audio Plugin to work with the most recent Steam version.
I was able to remove the pointer indirection for the avatar front and top vectors and replaced them with static addresses. I tested this multiple times (with multiple restarts) in several different Story and Online sessions and the address that I found, does indeed seem to be static.
Here is a screenshot of it working:
I was in a car driving towards the east while looking north (only with the camera).

Update GTA V (Steam) Plugin

---

src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/Log.ui
src/mumble/Messages.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h

When a user sends a message to the log, the TTS engine
will play "Channel <username> <message>". When omit scope
box is selected, the phrase "Channel" is omitted from the TTS
engine which allows for the users message to quickly be spoken
for all clients. There is also an option not say the username.
Addresses: https://github.com/mumble-voip/mumble/issues/3676

Add option to omit scope in TTS messages

---

src/mumble/MainWindow.cpp

check if Screen::screenAt(p) is not nullptr in MainWindow.cpp,
MainWindow::trayAboutToShow(). If screen == nullptr, do nothing more.
This is a work around / fix for #3755, on my machine everything works after adding this check (the tray works too as always).
I'm not an C++/QT expert so maybe that is not a good solution - in that case just tell me and close the PR.
Thanks!

Fix for #3755, check if Screen::screenAt(p) is nullptr

---

plugins/gtasa/gtasa.cpp
plugins/gtasa/gtasa.pro
plugins/mumble_plugin_main.h
plugins/plugins.pro

Supports the 1.0 version of Grand Theft Auto: San Andreas, the only one supported by multiplayer modifications.
The camera's vectors are synced with the avatar's ones; in future we should locate the camera's CMatrix in the game's memory and retrieve the proper values.
No context/identity support; in future we should at least add the context (e.g. server IP address + port) for Multi Theft Auto and San Andreas: MultiPlayer.
@Whitetigerswt

plugins: add positional audio plugin for GTA: San Andreas

---

qmake/compiler.pri

This commit disables warnings for deprecated stuff, which we are not going to replace due to 1.3.x being frozen.
We also want to keep compatibility with Qt 4, meaning that we would have to adapt each fix from the `master` branch.
We don't disable the warnings for MSVC because we use our build environment for that.

compiler.pri: disable warnings for deprecated stuff

---

scripts/azure-pipelines/build.ps1
scripts/azure-pipelines/install-environment.ps1

This is a cherry-pick of c7c4fba6 which landed in master.
Recent builds have failed because there is not enough space in `C:\` after installing the build environment, which we used to extract in `C:\MumbleBuild`.
This commit changes the PowerShell scripts so that our environment directory (e.g. `MumbleBuild`) is created in the proper directory (Agent.ToolsDirectory's value, e.g. `D:\a\_tool\`) instead of `C:\`.
`C:\MumbleBuild` is still required because our build environment's qmake expects its configuration files to be there (hardcoded). The environment installation script creates a symbolic link to solve the problem.

CI: Fix Azure Pipelines build failing

---

CHANGES

Update the changelog
Generated with scripts/generate-CHANGES.py
~This changes also previously existing entries from a 7-character to an
8-character short hash code.
This could be considered unexpected.
Unfortunately this additional character also leads to a line break in
some lines that then reaches the maximum.~
~We do not specify the number of characters explicitly.
Git determines the length it uses dynamically from the number of objects
to determine a reasonable hash length for the repository.
It seems our repository’s commit and hence object count now exceeds the
7-character use.~
~We could force 7 characters to remain consistent, with an increasing
risk of ambiguity.
We could force 7 for the old entries, and use 8 for the new entries,
which limits the higher risk of ambiguity to the …

Docs: Update CHANGES file

---

src/mumble/AudioOutput.ui

Original:
Attenuate other users while talking as Priority Speaker.
Update:
Attenuate other users while talking as Priority Speaker
This was a minor fix to an issue: https://github.com/mumble-voip/mumble/issues/3665

Updated UI String to be consistent with others

---

Doxyfile

Currently the tab-size is set to 8 which isn't what one would expect in most cases. Thus I changed it to be 4 which from my experience is what people would expect a tab to look like.

Change tab-size to 4 in Doxygen

---

src/murmur/ServerUser.cpp

This variable has been unused since 0fc5d55, which is the very same
commit where it was introduced.

Get rid of unused variable "records"

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioInput.ui
src/mumble/Settings.cpp
src/mumble/Settings.h

This pull request implements Opus' low delay mode selection, which should result in a big decrease in latency.
The `bUseOpusMusicEncoding` option has been removed, because now the Opus mode is selected depending on the bitrate. The automatic selection aims to decrease the latency while maintaining acceptable quality.
The exact values may have to be tuned further for a smarter auto-selection because the low delay mode, while causing a strong decrease in latency, requires an higher bitrate to maintain the same quality; in order to compensate, the maximum bitrate in the UI has been increased to **192 kbit/s**.
The automatic selection sets:
- Low-delay mode when the bitrate is **>= 64 kbit/s**.
- Music mode when the bitrate is **>= 32 kbit/s**.
- VOIP mode when the bitrate is **< 32 kbit/s**.

Implement & auto-select Opus' low delay mode

---

plugins/mumble_plugin.h

The doc says that the function is named `mumbleGetPlugin` whereas in the implementation it searches for a function called `getMumblePlugin`:
https://github.com/mumble-voip/mumble/blob/cb7244a6d3d9370fb47392645368cb60f409430b/src/mumble/Plugins.cpp#L312

Corrected error in doc

---

src/mumble/AudioOutput.cpp
src/mumble/AudioOutputSample.cpp
src/mumble/AudioOutputSample.h
src/mumble/AudioOutputSpeech.cpp
src/mumble/AudioOutputSpeech.h
src/mumble/AudioOutputUser.h

Fixes #3786
I went for `prepareSampleBuffer` as my name of choice.
Before the rename:
```
find -type f \( -iname "*.h" -o -iname "*.cpp" -o -name "*.pro" \) -exec fgrep -n needSamples {} /dev/null \;
./src/mumble/AudioOutputSpeech.h:69:            virtual bool needSamples(unsigned int snum) Q_DECL_OVERRIDE;
./src/mumble/AudioOutput.cpp:379:               if (! aop->needSamples(nsamp)) {
./src/mumble/AudioOutputSample.cpp:200:bool AudioOutputSample::needSamples(unsigned int snum) {
./src/mumble/AudioOutputUser.h:25:              virtual bool needSamples(unsigned int snum) = 0;
./src/mumble/AudioOutputSample.h:62:            virtual bool needSamples(unsigned int snum) Q_DECL_OVERRIDE;
./src/mumble/AudioOutputSpeech.cpp:169:bool AudioOutputSpeech::needSamples(unsigned int snum) { …
```

Renamed AudioOutputUser::needSamples

---

installer/Translations/SimpChinese.wxl

Modify the following entry:
<String Id="MUMBLE_CREATE_SHORTCUT">创建桌面快捷方式</String>
<String Id="MUMBLE_CREATE_SHORTCUT">Create Desktop Shortcut</String>
<String Id="DESC_SectionBonjour">Bonjour现在可以在您的网络上报告和发现Murmur服务器。是否下载并运行Bonjour安装程序。</String>
<String Id="DESC_SectionBonjour">Bonjour enables announcement and discovery of Murmur servers on your LAN. This will download and run the Bonjour installer.</String>
<String Id="MUMBLE_SEC_DesktopShortcut">桌面快捷方式</String>
<String Id="MUMBLE_SEC_DesktopShortcut">Desktop shortcut</String>
<String Id="DESC_DesktopShortcut">创建桌面快捷方式</String>
<String Id="DESC_DesktopShortcut">Creates a shortcut on the desktop</String>
thanks

Update Simplified Chinese Translations installer

---

g15helper/g15helper.plist
g15helper/g15helper.rc
installer/Settings.wxi
macx/common.pri
macx/osax/osax.plist
overlay/mumble_ol.rc
overlay/overlay-shared.pro
overlay/overlay_exe/overlay_exe.rc
overlay_gl/overlay_gl.pro
overlay_winx64/mumble_ol.rc
overlay_winx64/overlay_exe_winx64/overlay_exe.rc
src/mumble.pri
src/mumble/mumble.plist
src/mumble/mumble.rc
src/mumble/mumble_dll.rc
src/murmur/murmur.plist
src/murmur/murmur.rc

1.3.0 has been released. master now represents the current state of
development towards the next feature release 1.4.0.
Bugfixes for 1.3 will happen in the 1.3.x branch.
Compared to earlier version bumps we bump a lot more files because of
we produce more artifacts; overlay process, dll and exe split, etc.
This should have happened right after the 1.3.x branch was split off.
Fixes #3761
Waiting on response from xPoke in that ticket concerning theme version. That will have to be landed first, and then this PR updated with the landed commit in mumble-theme.
Feel free to already review independent of xPoke response.
As the mumble-theme commit did not land yet checking out this PR will not work (for others than me who has the commit locally).

Bump version to 1.4.0

---

src/mumble/JackAudio.cpp
src/murmur/MurmurGRPCImpl.cpp
src/murmur/Server.cpp

`delete` handles null pointers: https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null
Fixes #3649.

Remove unneeded null pointer checks

---

src/mumble/PulseAudio.cpp

When compiling Mumble on Linux (g++) I get some warnings about implicit fallthrough in `PulseAudio.cpp`. According to [this question](https://stackoverflow.com/questions/45129741/gcc-7-wimplicit-fallthrough-warnings-and-portable-way-to-clear-them) on SO this can be fixed by placing a comment about it right before the following `case`-statement so I went to do that. It turns out there have already been comments about this, just in the wrong places. Thus this PR will merely move those comments in order to silence the warnings.

fixed (g++) warning about implicit fallthrough

---

src/mumble/PulseAudio.cpp

https://maemo.org/api_refs/5.0/5.0-final/pulseaudio/paplay_8c-example.html
In the example the stream writer callback does nothing and returns in case there is no data to send. 
Our code, instead, creates a buffer, fills it with zeroes and writes it to the stream if audio output is not enabled.
This pull request changes the callback function's code so that it returns immediately in such case.
The change has been tested by setting an underflow callback function (using `pa_stream_set_underflow_callback()`) and checking whether underflows occurred.
---
Fixes #1246.

PulseAudio: don't send empty data into the stream if audio output is not enabled

---

src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h

This is basically the same thing as in #3267, but for the UDP/voice connection.
Currently if you have murmur running on port 2 (and your SRV `_mumble._tcp.` record matches that), but the connect dialog says port 1, Mumble will do server pings and the TCP/control channel over port 2, but the voice channel sends data over port 1, causing it to fallback to TCP tunneling.

ServerHandler: Use the SRV resolved port for UDP connections

---

src/mumble/Log_unix.cpp

This commit adds include guards around a QDBusInterface include added in
commit 15831dbca without the appropriate guards.

Add include guards for builds without dbus

---

scripts/azure-pipelines/build_linux.bash
scripts/mumble-version.py

This pull request changes the Linux build script so that it retrieves the full Mumble version using `mumble-version.py`, which determines the full Mumble version based on multiple variables, such as the current commit hash and the latest tag.
Previously we were using the first 7 characters of the commit hash as version, which is not very descriptive.
`mumble-version.py` is copied from our current build environment and the header is changed to match the one in the other scripts.
There's no reason to keep the script in the build environment repository (`mumble-releng`), because it's supposed to be run inside the Mumble repository and doesn't depend on anything from the build environment.
---
Fixes #3706.

Azure Pipelines: get Mumble version with mumble-version.py

---

src/mumble/ConnectDialog.cpp

This commit fixes a warning encountered today on FreeBSD, probably because Clang was updated and now `-Wdangling-else` is enabled by default.
```cpp
ConnectDialog.cpp:1178:3: error: add explicit braces to avoid dangling else [-Werror,-Wdangling-else]
foreach(ServerItem *si, qlItems)
^
```

Fix dangling else warning in ConnectDialog::OnSortChanged()

---

src/mumble/AudioStats.cpp

I just had a [build](https://cirrus-ci.com/task/5107295804981248?command=build#L598) failing because `AudioStats.cpp` is using `QPalette::Background` which apparently has been declared deprecated. The Qt docs advise to use `QPalette::Window` instead (see https://doc.qt.io/qt-5/qpalette.html) so I went ahead and changed the code accordingly.

Fix QPalette::Background is deprecated

---

src/mumble/ALSAAudio.cpp
src/mumble/GlobalShortcut_win.cpp
src/mumble/JackAudio.cpp
src/mumble/OSS.cpp
src/mumble/PulseAudio.cpp
src/mumble/WASAPI.cpp
src/murmur/MurmurGRPCImpl.cpp

qt/qtbase@5957f245c6c77c98d7e90d614c9fe2cdbfe7e8e6
I accidentally forgot to search for "qSort" in files when I created 3132f993d83820d72124ffbb6fc4fd3810d36b8e.
This pull request replaces the `qSort()` instances I missed.

Replace deprecated qSort() with std::sort()

---

src/murmur/Messages.cpp

This pull request fixes a warning encountered today on FreeBSD, probably because Clang was updated and now `-Wdangling-else` is enabled by default.
```cpp
Messages.cpp:1330:5: error: add explicit braces to avoid dangling else [-Werror,-Wdangling-else]
foreach(int id, pg->members()) {
^
```

Fix dangling else warning in Server::msgACL()

---

src/murmur/Murmur.ice

Mumble.com kindly reported that the `getRegistration()` Ice method fails with an `enumerator out of range` error, due to a missing value in the `UserInfo` enum.
The value was added to Murmur in 813aceb854949a863e095930423d8d49793e4be8 and then renamed and moved in 5131d9e3036bb7de94967dd026f2c7f4ec91645d.

Murmur.ice: add missing value to UserInfo

---

src/murmur/MurmurGRPCImpl.cpp

I accidentally left it in 062fe2661d2457b2ae200c11709175f9d9f2b2a3 (#3602).

MurmurGRPCImpl.cpp: remove QAtomicInt compatibility layer

---

src/mumble/JackAudio.cpp
src/mumble/JackAudio.h

Some users were encountering issues such as the client taking ~8 seconds to start when `jackd` could not be run, due to the library attempting many times to connect to the JACK server (#3822).
While working on a fix I corrected the many warnings emitted by Clang-Tidy and I realized that there were many things that could be improved.
This commit almost entirely rewrites the implementation, but here are some of the changes:
- Mutexes are used everywhere, race conditions should not be possible anymore.
- The JACK client is not opened until it's required (i.e. `JackAudioInput` and/or `JackAudioOutput` start running). The initialization code has been moved to a dedicated function, the constructor doesn't execute it anymore. This is what fixes #3822.
- The JACK client is deactivated and closed …

Revamp JackAudio implementation

---

src/mumble/Log.cpp
src/mumble/Log.ui
src/mumble/Settings.cpp
src/mumble/Settings.h

By default `QTime` uses the 24-hour time format when converting to a string.
This commit adds a setting (a checkbox) which allows users to toggle the format.
The setting only applies for new messages, the already shown ones will retain the previous time format.
---
Fixes #3823.

Add setting to toggle 24-hour time format for the chat

---

plugins/bf1/bf1.cpp
plugins/mumble_plugin_utils.h

Appeared after #3511, description in each commit.

plugins: fix escape() warnings

---

src/mumble/main.cpp

removed redundant workaround for https://bugreports.qt.io/browse/QTBUG-6504 in debug-mode
Fixes #3840

Fix deprecated QSslSocket::setDefaultCaCertificates

---

.travis.yml
scripts/travis-ci/before_install.bash
scripts/travis-ci/script.bash

The macOS build on Azure Pipelines was restored in #3837.

Travis CI: remove macOS build, it's on Azure Pipelines

---

.travis.yml
scripts/travis-ci/before_install.bash
scripts/travis-ci/script.bash

Travis CI announced support for ARM64 builds a few days ago: https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support
We already have a Linux x86_64 build on Azure Pipelines, which also generates an AppImage.
This commit changes the architecture for the build we have on Travis CI, so that it's not redundant anymore (and becomes useful).
The "no-pch" build is not changed because the only differences consist in the PCH header not being used and the SonarQube Scanner being executed.
Also, we don't want to use an ARM64 builder unnecessarily.
We don't use `make check` because of #3845.

Travis CI: transform Linux x86_64 build into ARM64

---

src/mumble/TaskList.cpp

Fixes the following error:
```cpp
TaskList.cpp:77:20: error: 'SHARD_LINK' was not declared in this scope
SHAddToRecentDocs(SHARD_LINK, link);
^
```
`SHARD_LINK` is only defined when `NTDDI_VERSION` is at least `NTDDI_WIN7` (`0x06010000`).
We handle the logic for MinGW in "win.h", this commit fixes the error by including it.

TaskList.cpp: fix compilation error with MinGW when PCH is disabled

---

.travis.yml
scripts/travis-ci/script.bash

Unfortunately `sonar-scanner` fails with the following error:
```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: The "build-wrapper-dump.json" file was found empty. Please make sure that:
* you are using the latest version of the build-wrapper and the SonarCFamily analyzer
* your compiler is supported
* you are wrapping your build correctly
* you are wrapping a full/clean build
at com.sonar.cpp.plugin.CFamilySensor.execute(CFamilySensor.java:239)
at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:62)
at …
```

Travis CI: disable SonarCloud scanner, incompatible with Ubuntu Bionic (18.04)

---

.lgtm.yml

We'll soon upgrade the lgtm.com build environment to Ubuntu 19.10, where  `libg15daemon-client-dev` is no longer available, which makes the build fail because it can't find `g15daemon_client.h`. Adding `no-g15` makes  the build succeed.

.lgtm.yml: Prepare for Ubuntu 19.10

---

src/mumble/MainWindow.cpp

Fixed unexpected behavior.
Old behavior: Pressing a global shortcut for pasting clipboard content to channel while user's clipboard is empty resulted in empty messages being posted to channel.
New behavior: pressing the global shortcut for pasting clipboard content to channel while user's clipboard is empty does not post a message to channel

Fixed posting of empty clipboards to channel on Global Shortcut input

---

src/mumble/Messages.cpp
src/mumble/UserModel.cpp
src/mumble/UserModel.h

While this should not occur the client did not properly
consider what would happen if a server send a ChannelRemove
without first moving all users out. Allowing this operation
to happen will bring our UserModel into an undefined state
where users (even ourselves) might have been dropped while
the server still considers them.
With this patch we now detect that case and disconnect ourselves
from the broken server instead of breaking our state.

Make client robust against server dropping occupied channel

---

src/mumble/Messages.cpp

If during message handling we somehow end up in a situation
where no ClientUser is registered or g.uiSession is not set
we end up with pSelf as a null pointer. Dereferncing that
crashes the application.
Similar to other objects we retrieve for message processing
this patch modified the macro to log and bail if we encounter
this situation instead of crashing.
One drawback of this patch is that it might make state
corruption caused by client bugs less visible to us because
we no longer receive crash reports on them while the client
functionality could still be degraded severly.

Make client more robust against inconsistent state

---

src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

Use `QDateTime` instead of `QTime` when tracking the last update for rate limiting purposes. This avoids the time underflow around midnight.
Further avoided backwards time updates due to DST by using UTC time instead of the local time.
And finally, if the time _does_ go backwards (due to user changing the date for example), reset the last update time to ensure it doesn't need to wait for the time to catch up to the previous update.
Fixes #3724 hopefully.

Use QDateTime to avoid time underflow

---

src/murmur/Server.cpp

Try to remove the ability to join a full channel by
creating a sub channel, then joining it
and removing it (discovered by @Natenom).
Check `isChannelFull` in addition to existing
`hasPermissions` `ChanACL::Enter` check.

Try to fix channel limit override by subchan delete

---

3rdparty/jack-src/jack/types.h
scripts/azure-pipelines/install-environment_linux.bash
scripts/travis-ci/before_install.bash
src/mumble/JackAudio.cpp
src/mumble/JackAudio.h
src/mumble/mumble.pro

JackAudio: load symbols at runtime

---

src/mumble/GlobalShortcut_win.cpp

The code accessed a variable (`nxboxinput`) even when not existent, resulting in compiler errors.
This commit fixes the issue by adding the missing checks.

GlobalShortcutWin: fix build without XboxInput

---

src/mumble/JackAudio.cpp
src/mumble/JackAudio.h

According to the JACK specification the process callback cannot have
anything that could block. JACK can also kill the process thread while
it is holding the lock which can cause a deadlock. Removing the locks prevents
both deadlocks in Mumble and xruns in the JACK processes.
There have also been some changes to the order in which the JACK clients
get activated. This is to make sure that they are fully set up before
the activate function is called. This prevents graph errors from showing
up in the JACK logs.
This way it's set up is to use JACK's lock-free ringbuffers. The callback threads just read and write from the buffers, and the run() does the actual processing of the audio. Because there should be at most, one frame of latency between audio being ready and audio sent to JACK this …

JackAudio: remove locks from realtime callbacks, various improvements

---

src/mumble/Audio.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioOutputSpeech.cpp
src/mumble/MainWindow.cpp
src/mumble/mumble.pro

Adds few missing checks where Opus is included even if not building with it and also modifies the qmake project file to not always build OpusCodec.
Build tested with Linux and MXE, latter runtime tested on Windows.

fix build without Opus

---

3rdparty/portaudio-src/portaudio.h
src/mumble/PAAudio.cpp
src/mumble/PAAudio.h
src/mumble/mumble.pro

While working on the code to load the library at runtime, I corrected the many warnings emitted by Clang-Tidy and I realized that there were many things that could be improved.
This commit almost entirely rewrites the implementation, but here are some of the changes:
- Symbols are loaded at runtime, the library is not a dependency anymore.
- A callback is used to read/write from/to the stream.
- `PortAudioSystem` is not a static class anymore, the object is managed by `PortAudioInit`.
- All instances of `delete` have been removed, raw pointers have been replaced with `std::unique_ptr<>()`.
- All instances of `NULL` have been replaced with `nullptr`.

Revamp PortAudio implementation

---

src/mumble/ConnectDialog.cpp
src/mumble/ConnectDialog.h

Many parts of the code used Bonjour stuff even when not available, resulting in compiler errors.
This commit fixes the issue by adding the missing checks.

ConnectDialog: fix build without Bonjour

---

src/murmur/MurmurGRPCImpl.cpp
src/murmur/MurmurGRPCImpl.h

This prevents a segmentation fault in next() when it tries to call back
to a deleted object when murmur is shut down.

Shutdown and drain gRPC completion queue on exit

---

scripts/murmur.ini
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/MurmurGRPCImpl.cpp
src/murmur/MurmurGRPCImpl.h

This adds client authentication using TLS certificates when it is
enabled in gRPC. This just the basic feature right now. You either have
access or you do not.
Access is granted by putting the certificate digests of the authorized
users into the murmur.ini file. It's a simple configuration for the moment, but the authentication class would be easily able to be extended to have more fine-grained control.
This should solve also feature request #3496. It allows the gRPC port to be safely opened up to the internet as anybody without a valid certificate won't get much past the handshake. It also doesn't interfere with people who are using the unsecured connection types over a loopback device or a UNIX domain socket.
If anybody wants to test this, since I don't think there are many gRPC enabled …

Client authentication for gRPC

---

src/mumble/Log.cpp
src/mumble/Log.h

Some parts of the code used TTS stuff even when not available, resulting in compiler errors.
This commit fixes the issue by adding the missing checks.

Log: fix build without TTS

---

src/mumble/GlobalShortcut_unix.cpp
src/mumble/GlobalShortcut_unix.h

Xi causes a conflict in the compiled MOC files when they are generated by CMake, because it defines a type called `Bool`:
```
In file included from mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/../../../../../src/mumble/GlobalShortcut_unix.h:14,
from mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_GlobalShortcut_unix.cpp:9,
from mumble/build/src/mumble/mumble_autogen/mocs_compilation.cpp:26:
mumble/build/src/mumble/mumble_autogen/EWIEGA46WW/moc_Log.cpp:191:89: error: expected unqualified-id before ‘int’
191 |     QMetaType::Void, 0x80000000 | 3, QMetaType::QString, QMetaType::QString, QMetaType::Bool, QMetaType::QString,    4,    5,    6,    7,    8,
|                                                                                         ^~~~ …
```

Fix Xi conflict that appears when MOC files are generated and included by CMake

---

src/mumble/ManualPlugin.cpp
src/mumble/ManualPlugin.ui
src/mumble/mumble_en.ts

I think the current UI of the manual placement plugin is a bit cumbersome and confusing. Thus I tweaked it to what I would consider a better UI.
The improvements I think I made are:  
1. The linked and activated status can now actually be seen (for some reason Qt ignored the checked-state of PushButtons at least on my PC making it impossible to see in the UI, whether the plugin is currently set to link or not)  
2. The unhinge-button is moved out of the state-category. As this button does not describe a state, it shouldn't be in there
3. The position view now has antialiasing enabled
4. The position indicator is bigger (now it doesn't look like some defect pixels on my screen)
5. The position indicator now also reflects the set azimuth
Here's how it is currently looking:
And this is with …

Manual plugin UI improvement

---

src/murmur/MurmurGRPCImpl.cpp
src/murmur/MurmurGRPCImpl.h

This fixes a segfault when stopping Murmur with gRPC enabled, probably worth having on the stable branch

Backport gRPC fixes

---

src/murmur/Server.cpp

As the commit message in #2336 contained some typos, it hasn't been merged. However mkrautz doesn't seem to have the time to fix them. Thus I did just that.
Note however that I really only fixed typos in the commit message. The actual coding work has been done by @mkrautz

Murmur: allow certificates without full chain, but do not deem such certificates 'strong'.

---

src/mumble/Audio.cpp
src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/main.cpp
src/mumble/mumble_en.ts

As of now, log messages (that is the ones that are shown in the UI) can only be created, after g.l (the global `Log` instance) has been created.
This makes it impossible to create log-messages during Mumble's startup.
This PR introduces the possibility of deferring such log-messages until the point that the `Log` instance is available, by using a static vector of deferred messages that can be processed later by the respective instance.
This framework has then been used, to fix #3672 (https://github.com/mumble-voip/mumble/issues/3672#issuecomment-524669026).
Usage-note: For deferring log messages two functions are provided. `Log::deferLog` should be used, if you know for sure, that the code is running before `g.l` is initialized. If you aren't quite sure about that, use `Log::logOrDefer` …

Add possibility to log, before g.l is available

---

scripts/generate-mumble_qt-qrc.py
src/mumble/main.cpp
src/mumble/mumble.pro
src/mumble/qttranslations/translations.conf

- I adapted the python script generating the qrc-file for bundled qt-translations so that it'll respect a config-file stating whether some translations shall overwrite the official qt-translations
- I adapted the actual cpp code loading the translations so that it'll always prefer packaged translations for the ones that have been marked to overwrite Qt's translations

Allow bundled translations to overwrite Qt's

---

scripts/azure-pipelines/build_linux.bash
scripts/azure-pipelines/build_macos.bash
scripts/azure-pipelines/install-environment_macos.bash
scripts/travis-ci/script.bash

As encountered by @deluxghost, the macOS CI reports success even though the actual buikld fails.
Our build-scripts use bash's `-e` flag that terminate the script on the first encountered error. However this is only true for error that are encountered outside if-like structures.
Unfortunately compilation happens via
https://github.com/mumble-voip/mumble/blob/ce40787cc576eef4771a707c3e2738c8cfdd6839/scripts/azure-pipelines/build_macos.bash#L18
And the use of `&&` turns this statement into such an if-like structure.
This can be easily verified by running the following script:
```
#!/usr/bin/env bash
set -e
echo "Now failing"
false && echo "This won't even be executed"
echo "This is printed even though above statement failed"
```
The conclusion of this is: When using `-e` don't use the `&&` …

Ensure CI reflects the actual build status

---

scripts/azure-pipelines/install-environment.ps1

This PR will improve the script downloading the windows build-env by
- Wrapping `Invoke-WebRequest` in a `try/catch`-block to print the enountered error on failure
- Disabling the 'progressbar` for the `Invoke-WebRequest` command which speeds it up a lot (see https://github.com/PowerShell/PowerShell/issues/2138 for reference)

Improve Azure-Pipelines Windows build

---

src/Connection.cpp
src/HostAddress.cpp
src/OSInfo.cpp
src/mumble/Audio.cpp
src/mumble/Audio.h
src/mumble/AudioStats.cpp
src/mumble/ConnectDialog.cpp
src/mumble/GlobalShortcut.cpp
src/mumble/MainWindow.cpp
src/mumble/Messages.cpp
src/mumble/Overlay.ui
src/mumble/SvgIcon.cpp
src/murmur/DBus.cpp
src/murmur/Messages.cpp
src/murmur/MurmurIce.cpp
src/murmur/Server.cpp
src/tests/TestSSLLocks/TestSSLLocks.cpp

Our failing macOS CI indicates that there are a few constructs in our code-base that are considered deprecated. This PR attempts to fix that.

Replace deprecated constructs

---

src/ACL.cpp
src/ACL.h
src/Channel.cpp
src/Channel.h
src/Mumble.proto
src/mumble/ACLEditor.cpp
src/mumble/Messages.cpp
src/mumble/UserModel.cpp
src/mumble/UserModel.h
src/murmur/Messages.cpp
themes/Classic/lock_locked.svg
themes/Classic/lock_unlocked.svg
themes/ClassicTheme.qrc
themes/MumbleTheme.qrc

This is aimed to fix #3857 and to fix #3856
Changes of this PR:
- Add 2 fields to the `MumbleProto::channelState` msg indicating whether a channel is protected by ACLs denying ENTER privilege and whether the user the message is being sent to has the permissions to enter the channel
- Implement the backend to process the abovementioned fields (Mumble + Murmur)
- Added the equivalents of those message-fields as fields in the channel class inside the Mumble-client
- UI: Show lock-icon if channel is access-restricted (locked lock for the case in which the local user can't enter the respective channel and unlocked lock for the case in which the local user has the necessary privileges to enter the channel noetheless)
- UI (kinda): Changed permission denied message for ENTER or MOVE requests, if …

Improve channel password handling

---

src/mumble/AudioWizard.cpp
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h
src/mumble/main.cpp

As noted in https://sourceforge.net/p/mumble/bugs/868/ , mumble consumes a great deal of CPU when it is idle. The vast majority of this usage can be traced to the audio input DSP. When mumble is self-muted, these operations are largely unnecessary and unhelpful. To save CPU, the audio input stream can be "corked" (muted) when it is not needed. This blocks the audio input DSP when it isn't needed.
This update automatically corks the PulseAudio input when the user is self-muted. In order to do this, `MainWindow` emits a new signal, `corkStream(bool)`, whenever the audio input is or is not required. This signal is slotted by the PulseAudio source, which passes it to the underlying PulseAudio server. This implementation will enable the fix to be ported to other sound servers and systems …

PulseAudio: Cork audio input when it isn't needed

---

.azure-pipelines.yml
scripts/azure-pipelines/build.ps1

Currently we are publishing the build artifacts on Azure-pipelines for Linux (AppImage) and for macOS (installer) but we don't do it for windows.
This PR aims at changing that.

Publish Windows installer as build artifact

---

src/mumble/Overlay.cpp

As noted in #3970 we are currently relying on system defaults for the access permissions of the pipe created for communication to the overlay.
In this PR I changed the code to explicitly set these permissions in order to not be dependent on whatever the system considers the default.
(Hopefully) fixes #3970 - we'll see about that once it has been tested :point_up: 
(The first commit is from #3980 which is required to get an installer out of the CI in order to test that this actually fixes the issue)

Explicitly set permissions for overlay-pipe

---

.cirrus.yml

We are currently using FreeBSD 12.0 for our CI which [has reached EOL](https://www.mail-archive.com/freebsd-security@freebsd.org/msg07438.html) on February 29, 2020.
This appears to result in errors during CI and thus this PR here will update CirrusCI to use FreeBSD 12.1 instead.

CirrusCI: Update to FreeBSD 12.1

---

src/mumble/Settings.cpp

Setting bJackStartServer to false, so mumble will not unconditionally start a JACK server on start (#3989).

Don't start JACK by default on mumble start

---

README
README.md

This PR does 2 removes the bandwidth note from the README(.md) as according to #2184 the note is outdated anyways. As this information is apparently also covered in our wiki, I opted for removing the note instead of updating it (as I agree with the author of the linked issue that bandwidth is not that big of an issue anymore).
Fixes #2184

Remove bandwidth note from README

---

src/mumble/NetworkConfig.cpp
src/mumble/main.cpp

bdbd4808fe9a45f945856db76d5266b7e662f09c intentionally forced the auto-update feature on all snapshot-users.
While I see the benefits of having snapshot-users to always be on the newest version, I highly disagree with forcing it upon them. Thus in this PR I revert the changes made in that commit (10 years ago).

Allow disabling autoUpdates for snapshot-builds

---

src/murmur/main.cpp

For some reason qFatal has been used to log information such as the
version requested by the --version argument.
abdb5004bb92b28271673e33df9cc3e314f5711a made qFatal exit with an
exit status of one leading to successful operations that happened
to contain some print-out to leave an exit status of 1.
Fixes #3911

Use qInfo instead of qFatal for normal logging

---

src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

The most important change is to use a timer that is based on a monotonic
clock in order to avoid time jumps and this inconsistent measurements
of time intervals (see
https://github.com/mumble-voip/mumble/issues/3985#issuecomment-601754212).
Furthermore the code-style has been adapted (m_ prefix instead of usage
of this->) and documentation has been added / extended.
This should fix #3985 and fix #3831

Improve implementation of the leaky bucket algorithm

---

src/mumble/AudioInput.cpp

Previously uninitialized value was returned.

AudioInput::encodeOpusFrame: return 0 if Opus is disabled

---

src/ACL.cpp
src/ACL.h
src/murmur/Messages.cpp
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/main.cpp

Fixes #2481 
See commit messages for detailed description of what this PR doe in detail.
This PR adds 2 new murmur config options:
| *Name* | *Description* |
| --- | --- |
| `loggroupchanges` | Enables logging of group changes |
| `logaclchanges` | Enables logging of ACL changes |
This PR also adds 2 new command-line options that allow enabling these features regardless of what is set in the config file. The options are named `loggroups` and `logacls` respectively. 
The PR itself is inspired by @sss123next's code patches given in #2481

Add option to log ACL & group changes

---

src/mumble/UserModel.cpp

Right now Mumble can come in a state where the local client is muted but
its talking state is still frozen to Talking.
This is also reflected in the UI (#4006) so this commit provides a
workaround that at least fixes the UI symptoms of the bug as I haven't
been able to track down the actual origin of it.

src/mumble/UserModel.cpp: Fix talking indicator

---

src/mumble/WebFetch.cpp

If we don't have a "servicePrefix" set, prefixedServiceHost() and
serviceHost() return the same host. The code however expected them to
implicitly be different.
This only ever made a difference if the main service host wasn't
reachable but in that case the endless-loop kicks in and the CPU usage
goes up.
Fixes #3760

src/mumble/WebFetch.cpp: Fix endless loop if there is no prefix

---

src/mumble/Settings.cpp
src/mumble/Settings.h

src/mumble/Settings: Removed implementation of deprecated expert-setting

---

src/murmur/Server.cpp

Fixes #3679.
---
A severe bug was introduced in qt/qtbase@93a803a6de27d9eb57931c431b5f3d074914f693: `q_SSL_shutdown()` causes Qt to emit `error()` from unrelated `QSslSocket`(s), in addition to the correct one.
The issue causes `Server::connectionClosed()` to disconnect random authenticated clients.
The workaround consists in ignoring a specific OpenSSL error:
> Error while reading: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [20]
Definitely not ideal, but it fixes a critical vulnerability. Details on how to trigger it are deliberately omitted.

src/murmur/Server.cpp: implement workaround for critical QSslSocket issue

---

scripts/murmur.ini

There are also a TODO here, with some things I couldn't document without spending much more time on understanding code logic...

Document settings missing in example murmur.ini

---

src/murmur/murmur_grpc/murmur_grpc.pro

b380274e3d85b8de1370a2dad43ec501bb43ca08 (#3476) changed the way we look
for the GRPC_CPP_PLUGIN but forgot to include an assignment for that
variable on non-Windows systems, which caused the build to fail for
them.

src/murmur/murmur_grpc/murmur_grpc.pro: Fix GRPC build

---

src/HostAddress.cpp
src/OSInfo.cpp
src/mumble/AudioStats.cpp

In b263b91340fb8b359e34626de880f606cfd9c116 I exchanged QString::sprintf
with QString::asprintf as the former was declared deprecated from Qt 5.5
onwards. I forgot to check the docs though. If I had, I would have
noticed that in contrast to sprintf, asprintf is a static function which
returns the assembled String (sprintf wrote it to the object it was
being called on). Thus I also have to assign the return value of
asprintf to a variable in order to have it have an effect.
Fixes #4021

src: Fix for b263b91

---

src/mumble/Log.cpp
src/mumble/Log.ui
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/mumble_en.ts

See individual commit messages for what has been done. In here I only want to provide some screenshots.
Before this PR:
After this PR:
Fixes #1590 by only drawing borders around messages that end with one or more empty lines. If a message contains line-breaks in between or at the beginning, we no longer draw a border around the message as its start and end are clearly visible to the user.

Improve log message style

---

.cirrus.yml
src/mumble/VersionCheck.cpp
src/mumble/VersionCheck.h
src/mumble/mumble.pro

As it stands, the VersionCheck always causes small mini-freezes. The
part that is responsible for them is reading the application binary
and computing its hash-value which has to be attached to the
request-URL.
Thus this whole process is outsourced to another thread so to not
delay Mumble's startup time.
Thanks to Qt's singal/slot mechanism, the processing of the incoming
answer to the request is handled in the main-thread (just as before).

Make VersionCheck prepare asynchronously

---

src/mumble/AudioInput.cpp
src/mumble/AudioInput.h

g.iTarget is not protected by a lock or a Mutex. This means that it can
change its value while AudioInput::encodeAudioFrame is running. However
the value is accessed at multiple stages (including
AudioInput::flushCheck that is called from encodeAudioFrame) meaning
that there could be inconsistencies of what g.iTarget was meaning for
this audio frame.
This commit makes sure that g.iTarget is only accessed once at the
beginnign of AudioInput::encodeAudioFrame and then copied to a local
variable which is then used for all the places in which g.iTarget
previously was access directly.
One scenario this race condition could be observed was pressing and
immediately releasing a whisper shortcut. This could sometimes cause one
of the whisper frames (the second last to be more precise) to be sent …

Fix racecondition for g.iTarget

---

src/Connection.cpp

Having the server perform 2 syscalls per TCP audio packet is extreme - turning this
off led to 30% lower CPU utilization in a test with 200 music-playing bots.
Switching to TCP_NODELAY for all packets is probably a win as well - TCP is only
typically used for control packets like users joining and leaving channels, of
which there are few. (As alluded to above, TCP is also sometimes used for audio,
in which case it should be in TCP_NODELAY mode anyway).

Use TCP_NODELAY by default and remove attempts to flush.

---

themes/ClassicTheme.qrc
themes/MumbleTheme.qrc

This icon is referenced/needed from ConnectDialog and before this
commit, an error would be printed that this icon can't be found (#4057).
Fixes #4057

Add alias for places/network-workgroup.svg

---

src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.h
src/mumble/GlobalShortcutTarget.ui
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/Messages.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/UserModel.cpp
src/mumble/UserModel.h
src/mumble/mumble_en.ts

Implements #1548 
It works by adding a shortcut for the normal `Whisper/Shout` functionality but then in the changed UI of selecting the target for that action you'll have to select `Current selection`

Whisper to selection

---

plugins/gtav/gtav.cpp

Update all memory addresses to the latest build of GTA V (Steam).
Minor other changes:
- Add the exact build version id to the version description, as Rockstar sometimes updates the GTA binary without even bumping the minor version
- Remove `in_game` variable, as `state == 2` (being in an online session) already implies `in_game == 1`

Update GTA V Plugin

---

Dockerfile

Building a docker image with the current Dockerfile seems to run into
issues caused by not finding files on the Ubuntu disco repositories
anymore. So, this patch updates the Ubuntu version in the Dockerfile
from disco to eoan.
Signed-off-by: hwipl <33433250+hwipl@users.noreply.github.com>

Dockerfile: update ubuntu version to latest

---

scripts/travis-ci/before_install.bash
scripts/travis-ci/script.bash
src/murmur/MurmurGRPCImpl.cpp
src/murmur/MurmurGRPCImpl.h

This PR fixes a compilation error that occurs when building murmur with GRPC enabled with an older version of the GRPC lib (probably a version less than 1.28 but I'm not sure of the exact version).
Furthermore it fixes a Qt warning about a deprecated function (Qt >= 5.14) in the GRPC code.
Finally it adds GRPC to be built on our CI in order to catch errors in the GRPC code in the CI as well.

Fix grpc build

---

scripts/murmur.ini
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/Server.cpp

The idea here is that sometimes you really do have a lot of folks connecting from a single IP,
and if those connections are successful you don't want to ban any of them.
However, in cases where the server needs to guard against malicious users attempting a DDOS
by reconnecting their valid user account over and over, we need to be able to configure the
server to still ban those successful attempts.
How does this idea sound, and how does this code look for solving it? Thanks!

Add autobanSuccessfulConnections flag.

---

src/mumble/MainWindow.cpp
src/mumble/Markdown.cpp
src/mumble/Markdown.h
src/mumble/TextMessage.cpp
src/mumble/TextMessage.h
src/mumble/mumble.pro

Supported are sections, inline code and code-blocks, bold, italic and
strikethrough text, links and quotes.
It is also possible to use the backslash character to escape other
characters (to prevent them from triggering Markdown interpretation).
The changes made in this commit do not apply to direct messages though
(which are assembled via a RichTextEditor and I haven't found a clever
way to hack into that one yet).
This implements #2945 and fixes #4075
-----
An example:
```
We can have `inline` code and
```code
blocks```
**bold**  and *italic*  text is also supported. ~~Scratch that~~
We can have [links](google.de) and www.google.de
> I am a quote
Although these are not pretty, they do work and are supported.
We can escaoe markdown using the \\ character: \*not italic\* and \*\*not …
```

Markdown support

---

src/murmur/Messages.cpp

ChannelListener will be introduced with Mumble 1.4.0 but older clients
will not know what these are. Thus they won't show them in their UI
which could lead to users being listened to without noticing.
In order to solve this issue, this commit implements a logic on the
Server that'll inform older clients about this possibility by sending
them a TextMessage right after they have authenticated (and after they
have received the server's welcome text).
Thanks to @streaps for pointing this problem out in #4011

Warn older clients about ChannelListeners

---

plugins/mumble_plugin_linux.h

free "path" only after we're done with "filename"

---

src/mumble/AudioWizard.cpp
src/mumble/AudioWizard.ui
src/mumble/mumble_en.ts

This PR improves the appearance of the AudioWizard by performing the following steps:
* Include a commit of @mkrautz that fixes #2735 (use colors in which the text is actually readable)
* Make the showcase for the positional audio render properly (not this pixelated mess it was before)
* Add some additional explanations and clarifications
* Make explanatory texts selectable. Fixes #4002 
-----
This is how the positional audio showcase renders after this PR:
Changelog
```
| Improved: Appearance & Accessibility of AudioWizard
```

Revamp audio wizard

---

src/murmur/Messages.cpp

Before this commit it was possible to pass more or less arbitrary sized
strings as part of the Version message. This could lead to malicious
clients sending huge strings as part of this message.
The problem arises once these Strings are displayed in the UI (e.g. once
a user selects Information from the context menu of such a malicious
client). Qt will then be so busy to render this String that it
completely freezes the UI (#4067).
This commit prevents this attack by restricting the size of the Version
strings on the server side. If a client sends strings that exceed this
size, the server will drop the original content and replace it with a
generic "[[Invalid]]".
Fixes #4067

Restrict string sizes for Version information

---

src/mumble/VersionCheck.cpp

The include for QtConcurrent produces an error in 1.4.0 build using the cmake project with MSVC 142 (Visual Studio 2019). This fixes the path not found error

Fix qtconcurrent include path

---

src/murmur/Messages.cpp

Before this commit it was possible to pass more or less arbitrary sized
strings as part of the Version message. This could lead to malicious
clients sending huge strings as part of this message.
The problem arises once these Strings are displayed in the UI (e.g. once
a user selects Information from the context menu of such a malicious
client). Qt will then be so busy to render this String that it
completely freezes the UI (#4067).
This commit prevents this attack by restricting the size of the Version
strings on the server side. If a client sends strings that exceed this
size, the server will drop the original content and replace it with a
generic "[[Invalid]]".
(Backported from #4101)

Backport "Restrict string sizes for Version information"

---

src/mumble/AudioOutputSpeech.cpp
src/mumble/Global.cpp
src/mumble/Global.h
src/mumble/LookConfig.cpp
src/mumble/LookConfig.ui
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/MainWindow.ui
src/mumble/Messages.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h
src/mumble/UserModel.cpp
src/mumble/UserModel.h
src/mumble/main.cpp
src/mumble/mumble.pro
src/mumble/mumble_en.ts

The TalkingUI is meant as some sort of a light version of the Overlay
primarily intended for use when using the computer normally (e.g. with
many different programs instead of one that is FullScreen).
It consists of a small window that can be toggled and it will show the
names of the person currently talking as well as the channel that person
is in.
If a person has stopped talking for some time (5s in the current
implementation), it will be removed from the UI again.
By default the UI will stay on top of all other windows so that you'll
always be able to see it.
Note that the selection in the TalkingUI and the MainWindow is synchronised in terms of selected users (if a channel is selected, the TalkingUI will not show a selection).
This means that this feature plays nicely with the …

Talking UI

---

src/mumble/ASIOInput.cpp
src/mumble/ASIOInput.h
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioConfigDialog.h
src/mumble/AudioInput.ui
src/mumble/ConfigDialog.cpp
src/mumble/ConfigDialog.h
src/mumble/ConfigWidget.h
src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.h
src/mumble/LCD.cpp
src/mumble/LCD.h
src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/LookConfig.cpp
src/mumble/LookConfig.h
src/mumble/NetworkConfig.cpp
src/mumble/NetworkConfig.h
src/mumble/OverlayConfig.cpp
src/mumble/OverlayConfig.h
src/mumble/Plugins.cpp
src/mumble/Plugins.h

This PR makes sure that the enablement of the echo cancellation ComboBox in the setting is done correctly (and on-the-fly: No need to press `Apply` for this to work) and if it is disabled, a tooltip will explain why.
Fixes #4110 
Changelog
```
| Improved: Echo cancellation setting in the UI is now much more intuitive in regards to when and why it is disabled
```

Improve echo cancellation settings ui

---

qmake/compiler.pri

The flag is added by our latest update to Qt's mkspec in our build environment: mumble-voip/mumble-releng@ad9fd58f47541feb4ec7a93d756d898789f24d40.

qmake/compiler.pri: remove "/Z7" flag from compiler options

---

qmake/compiler.pri

Backport "qmake/compiler.pri: remove "/Z7" flag from compiler options"

---

src/murmur/Messages.cpp
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/ServerUser.h

If you placed a listener proxy into an empty channel and someone was
shouting to that channel, you'd still not hear any of that. This is
because the old processing logic was injected into the code for the
normal shouting feature. However if there is no user in the channel, the
shouting feature won't do anything.
This commit added the listener targets as a separate entry in the
WhisperTargetCache in order for it to be processed independently of
normal shouts. It also had to tweak the logic for how and when to clean
the WhisperTargetCache in order for this to work nicely with
ChannelListeners as well.

Fix ChannelListener not hearing shout if no real user is in shouted channel

---

src/mumble/MainWindow.cpp
src/mumble/UserModel.cpp
src/murmur/Messages.cpp
src/murmur/Server.cpp

Before you weren't able to place a listener proxy (ChannelListener) into
the same channel that you're currently in and if you joined a channel
that you were listening to before, your listener proxy would be removed
from that channel.
It was brought to my attention though that there are cases in which a
person wants to hear what's going on in several channels and thus places
listener proxies into them. However if that same person needs to
constantly hop between these listened channels (e.g. to talk to the
folks in there), it gets very annoying as that person constantly has to
think about re-adding the listener proxy into the channel it just left.

Allow ChannelListener in same channel

---

src/mumble/DBus.cpp
src/mumble/DBus.h
src/mumble/MainWindow.h

This lets users control their transmit mode through DBus.
Changelog
```
| Added: DBus interface for setting/querying current transmission mode
```

Added DBus methods for setting/querying the current transmit mode

---

src/mumble/LookConfig.cpp
src/mumble/LookConfig.ui
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/Messages.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h
src/mumble/main.cpp
src/mumble/mumble_en.ts

With this setting enabled, the local user is always visible in the
TalkingUI as long as the user is connected to a server.
Furthermore the local user will always be listed first in its channel
and the channel of the local user will also be at the top of the
TalkingUI. This is independent from the new setting.
In order to make sure that the state displayed in the TalkingUI is
actually correct, some EventHandlers are added to the TalkingUI as well.

Added setting for TalkingUI to keep local user visible

---

src/mumble/UserModel.cpp
src/mumble/UserModel.h

The ModelIndex::rowOf functions did not take into account that checking
whether ModelIndex::pUser is not sufficient anymore as listener proxies
share the same associated user. Thus to uniquely identify the index for
the actual user, it also has to be taken into account whether the index
at hand corresponds to a listener proxy.
This mis-behavior was responsible for a segfault triggered by being in a
channel you also have a listener proxy in and then being dragged out of
that channel (the dragging part is important). During this process it
would delete the wrong item which it later wanted to select again
(causing access to deleted memory) resulting in the segfault.

Fixed UserIndex::rowOf() function for listener proxies

---

.azure-pipelines.yml
scripts/azure-pipelines/assertNoTranslationChanges.sh
scripts/azure-pipelines/install-environment_linux_translations.bash
src/mumble/mumble_en.ts

As it happens rather frequently for someone (e.g. me) to forget to
update the translations after having messed with translated strings,
this commit introduces a check to the CI that verifies that the
translations are always up-to-date.

Added check for unprocessed translations

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/MainWindow.ui
src/mumble/mumble_en.ts

This might be useful for situations in which a channel is pretty full
and thus one doesn't see the channel entry in the UI but instead sees
some users that are in that channel. Now if you want to join these
users, you don't really care about which channel they are in anyway, so
with this you can just right click on any user in a different channel
and join their channel via the context menu.
Changelog
```
| Added: Context action to join a user's channel
```

Join user's channel context action

---

src/murmur/ServerDB.cpp

Fixes the version-check for when to use Write-Ahead-Logging (https://www.sqlite.org/wal.html) with SQLite.
Fixes #4162

Fix sqlite version requirement

---

src/mumble/ConfigDialog.cpp
src/mumble/ConfigDialog.h
src/mumble/LookConfig.cpp
src/mumble/LookConfig.h
src/mumble/LookConfig.ui
src/mumble/MainWindow.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h

…
Instead of only showing the name of the channel the respective user is
currently in, this commit adds the possibility to also include (parts
of) the channel hierarchy to remove ambiguities.
Alongside comes a system to potentially abbreviate the (hierarchy) names
in order to not use too much screen space.
Thiis is how it can look:

Implemented options to display channel hierarchy in TalkingUI

---

src/murmur/ServerDB.cpp

Fixes the version-check for when to use Write-Ahead-Logging (https://www.sqlite.org/wal.html) with SQLite.
Backport of #4163

Backport "fix sqlite version requirement"

---

src/mumble/LookConfig.cpp
src/mumble/LookConfig.ui
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h
src/mumble/mumble_en.ts

With this new settings the user can scale the font size for the
TalkingUI to make it bigger or smaller (relative to the default font
size). This way every user can set it to his/her preferred size.

Made font size for TalkingUI entries configurable

---

src/mumble/MainWindow.cpp
src/mumble/NetworkConfig.cpp
src/mumble/Settings.cpp

With commit 847ed7ad0eef3c4e1a4a7dd230e05b70f17ec412 it was introduced
that when using the no-update config flag, not only the default values
for checking or not checking for updates were affected but actually the
whole setting would be hidden from the UI.
This commit reverts that as a user should always be able to decide for
him- or herself whether or not they want to see update notifications or
not.
It does make sense for package maintainers to disable these checks by
default (as updates are received via package manager anyways) but if the
user wants to have that check enabled nonetheless, they should be able to
do so.
Context: Discussion in #4128
/cc @toby63

Don't hide the setting if no-update config was used

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioInput.ui
src/mumble/mumble_en.ts

This tooltip explains the difference between mixed and multichannel echo cancellation.
Most of the wording and the info comes from @fedetft
Fixes #4125

Added tooltip for echo cancellation

---

src/mumble/Global.h
src/mumble/MainWindow.cpp
src/mumble/main.cpp
src/mumble/mumble_en.ts

In #4153 it was requested to have an option that allows to customize the
window title in order to better differentiate between the windows of
multiple Mumble instances.
This commit allows just that by letting the user specify a postfix
that'll be appended to the window title.
Fixes #4153
Changelog
```
| Added --window-title-ext to set a custom window title extension
```

Added option to add custom window title extension 

---

src/mumble/TalkingUI.cpp

This commit uses a "hack" to trick the MainWindow to display the context
menu for a given user in the TalkingUI. That's very convenient for
people that have only the TalkingUI open and want to take quick actions
(e.g. adjust volume of a user, mute a user, etc.) without having to open
the MainWindow again.

Allow user-context menu to be triggered from the TalkingUI

---

src/mumble/ServerHandler.cpp
src/mumble/Settings.cpp

The `iInFlightTCPPings >= g.s.iMaxInFlightTCPPings` check would mean
that if 1 is in flight and another is started, it immediately
disconnects, so as OP said in
https://github.com/mumble-voip/mumble/issues/3448 we want to have >
here.
Maybe that already fixes most of the spurious disconnects in practice,
or maybe we want to increase the default to 3 (right now it’s
effectively 2−1, so 1).
Fixes: https://github.com/mumble-voip/mumble/issues/3448

Fix iInFlightTCPPings check

---

src/mumble/TalkingUI.cpp

The problem that can arise is the following: A user changes channel.
Inside Messages.cpp UserModel::moveUser gets called that directly
updates the channel of the user. In order to propagate this change to
the TalkingUI, QMetaObject::invokeMethod is used leading to an
asynchronous processing of this event. If however in the same iteration
of the event loop the audio system sent a change in TalkingState, that
will be processed first in the next iteration of the event loop (before
the channel change is processed). This violates the assumption of
TalkingUI::ensureVisible that the channel of the local user is always
present in the TalkingUI. Due to how HashMaps work for non-existent keys
when using the [] operator, a nullptr gets inserted in the HashMap. If
that gets dereferenced at a …

TalkingUI: Fix race leading to crash

---

scripts/murmur.ini

(Backport of 7fde61f681653a9636a8afe1feb785d575776ad7 and changed to fit
the 1.3.x branch)
This should lead to an updated ini file being shipped in e.g. the static server binary for the 1.3.x series
reference: #4184

Backport "Document settings missing in example murmur.ini"

---

3rdparty/jack-src/jack/systemdeps.h

The file is included by the `types.h` header.
Our CI builds with JACK never threw any errors because we install the development package.
jackaudio/jack2#522 applied, for MSVC compatibility (in future we will release Windows builds with JACK support).

3rdparty/jack-src: add systemdeps.h

---

src/mumble/JackAudio.cpp

We build AppImage releases with Ubuntu 16.04, which has a compiler that doesn't support C++17.

src/Mumble/JackAudio.cpp: remove C++17 usage in JackAudioOutput::run()

---

src/mumble/NetworkConfig.cpp
src/mumble/NetworkConfig.h
src/mumble/mumble_en.ts

If Mumble has been compiled with the no-update config flag, then the
auto-updates are deactivated by default. If a user wants to enable it in
the settings, a pop-up will be shown to the user explaining that the
update notifications are probably not meaningful (as the user is most
likely getting their Mumble updates from a package repository). This is
to prevent confusion of the user.
The popup looks like this:
This is a followup addressing concerns voiced in #4138
@toby63 is this what you had in mind?

Show warning message for enabling update checks with no-update config

---

installer/Files.wxs

Adds mumble icon file to fix icon representation in Windows 10 Menu tile and desktop icon.

Add mumble icon file

---

src/mumble/AudioOutput.cpp

If front and top are not perpendicular by a small margin, it is better
to find a perpendicular vector that differs the least from top.
Only for large errors, i.e. if front and top are not perpendicular at
all, it makes sense to create a totally new top vector by assuming Y is
up.
This fixes distorted audio if the positional audio plugin would
sometimes (but only rarely) deliver errors larger than 0.01, in which
case Mumble would rapidly switch between Y up and the real up vector.
Fixes #4169
See the attached screenshot for old behaviour vs new behaviour (old corrected top is a totally new perpendicular vector, while new corrected top is the closest perpendicular vector (closest to top, perpendicular to front):

Positional Audio: Do not assume Y up for small errors

---

installer/Files.wxs

Adds mumble icon file to fix icon representation in Windows 10 Menu tile and desktop icon.
(Backported from #4204)

Backport "Add mumble icon file"

---

src/mumble/TalkingUI.cpp

Instead of setting the colors (the highlight color in particular)
explicitly in the code, adapt the code so that it is possible to style
it via the Theme.
The related PullRequest for the theme is https://github.com/mumble-voip/mumble-theme/pull/25

Make TalkingUI use theme for styling

---

src/mumble/GlobalShortcut_win.cpp
src/mumble/GlobalShortcut_win.h

This PR adds a detection mechanism that, while primitive, prevents windows hooking when a screen reader is found to be running when Mumble is executed. This is accomplished by enumerating the process list and checking for a (currently hardcoded) set of (only two right now) screen reader binaries. I know that NVDA (denoted by image name nvda.exe) is affected when Mumble loads winhooks, but I don't know if JAWS (denoted with image name jfw.exe) is. Rather than add every screen reader I know of to this list, I feel it might be better to just add them when we come across them.
Note: I have not built this code yet. I am working on automating the build process since I am unable to do it on my local machine at this time, so expect errors. (I tried not to make any, but you know...) Also, I did my …

Disable winhooks if screen reader is active

---

src/mumble/Settings.cpp

Now that the echo canceller has been fixed, it is time to default-enable
echo cancelling. As multi-channel cancelling is more CPU intensive, we
default to mixed channel cancellation.
Don't enable it on MacOS though as right now we don't support echo
cancellation for that platform.
Closes: #4178
Changelog:
```
| Improved: Echo cancellation now enabled by default
```

Enable echo cancellation by default

---

src/murmur/ServerDB.cpp
src/murmur/ServerDB.h

In #4213 it was reported that connecting to a server with a unicode
character (Emoji) in the name can crash the server (provided the user
name passes validation which is only possible if the server uses a
special rule for the username config) when using MySQL as the backend.
This is because we have been using "utf8" for MySQL which - as it turns
out - isn't actual utf8 (https://mathiasbynens.be/notes/mysql-utf8mb4).
Therefore this commit changes this behavior by setting the proper utf8
encoding for MySQL databases. For SQLite and PostgreSQL the encoding is
checked and if it is not utf8 (or utf16), the server will refuse to
start. This is because there is no way to set the encoding for existing
databases for these backends.
Fixes #4213 
Changelog
```
| Fixed: Character encoding issues with …
```

Fix database encoding

---

src/mumble/ACLEditor.cpp
src/mumble/ASIOInput.cpp
src/mumble/About.cpp
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioStats.cpp
src/mumble/AudioWizard.cpp
src/mumble/BanEditor.cpp
src/mumble/Cert.cpp
src/mumble/ConfigDialog.cpp
src/mumble/ConnectDialog.cpp
src/mumble/GlobalShortcut.cpp
src/mumble/LCD.cpp
src/mumble/Log.cpp
src/mumble/LookConfig.cpp
src/mumble/MainWindow.cpp
src/mumble/NetworkConfig.cpp
src/mumble/OverlayEditor.cpp
src/mumble/Plugins.cpp
src/mumble/TextMessage.cpp
src/mumble/Tokens.cpp
src/mumble/UserEdit.cpp
src/mumble/UserLocalVolumeDialog.cpp
src/mumble/VoiceRecorderDialog.cpp
src/mumble/mumble_en.ts

The QT5 framework has attributes for accessibility clients (screen readers or other programs used to analyze the accessibility of an application). These attributes are:
* Accessible name: the name for the control, e.g.: the label.
* Accessible description: a description presented to accessibility clients used to elaborate on the controls function/purpose.
* Accessible role: the role (type) of a control, e.g.: button, pain, combo box, etc.
These three attributes are not uncommon and are available in most GUI frameworks. This PR sets the accessible name attribute for controls that do not automatically get this attribute set. (This only applies to Windows.) This PR sets these in code, not in QT UI files. These changes could be merged into the UI files themselves with a bit of time and …

More accessibility enhancements for accessibility clients

---

src/mumble/OverlayText.h

src/mumble/OverlayText.h: add missing <QtGui/QPainterPath> include for Qt 5.15

---

src/mumble/OverlayText.h

Backport "src/mumble/OverlayText.h: add missing <QtGui/QPainterPath> include for Qt 5.15"

---

src/mumble/Log.cpp
src/mumble/LookConfig.cpp
src/mumble/mumble_en.ts

These typos have been introduced in #4211

Fixed typos in accessibility names

---

src/murmur/ServerDB.cpp

In a scenario in which a database with an older structure version
already exists this would lead to the server re-generating all tables on
every start due to the version number not being updated in the process.
Backport of #4234

Backport "Fix DB structure version not getting updated on table update"

---

src/murmur/ServerDB.cpp

In a scenario in which a database with an older structure version
already exists this would lead to the server re-generating all tables on
every start due to the version number not being updated in the process.
This is a follow-up on #4220

Fix DB structure version not getting updated on table update

---

src/ACL.cpp
src/ACL.h
src/mumble/ACLEditor.cpp
src/mumble/MainWindow.cpp
src/mumble/mumble_en.ts
src/murmur/Messages.cpp
src/murmur/Murmur.ice

Currently if a user has a "move" permission, they can also reset the comment or avatar of another user as describe in issue #1016. I stumbled into this by accident when I gave a user the move permission to help get new users into the right channels with their friends.
After reviewing the content found in PR #1223 which introduced the reset avatar feature, I found the code that allowed a user to do these resets and changed the required permission from Move to RegisterUser as suggested by @bontibon in the issue thread. As they state, this permission makes more sense than the move permission.
After compiling I found no issues and the changes worked as expected. The one caveat is that if the server has these changes implemented and not the client, (seems daft but this is preferable for me so …

Add permission for Reset Comment/Avatar

---

src/mumble/AudioOutput.cpp
src/mumble/AudioOutput.h
src/mumble/AudioOutputSample.cpp
src/mumble/AudioOutputSample.h
src/mumble/AudioOutputSpeech.cpp
src/mumble/AudioOutputSpeech.h
src/mumble/AudioOutputUser.cpp
src/mumble/AudioOutputUser.h
src/mumble/OpusCodec.cpp
src/mumble/OpusCodec.h

Just executed the idea in #4193. Merging this PR will close #2829, ending a three-year-long pursuit for the stereo audio, realizing the dream of dozens of forks :D.
Thank @Krzmbrzl, @streaps for their help, and @felix91gr for supporting me!
In this commit, I initialize opus decoder in stereo mode. For incoming mono stream, the opus decoder will automatically convert it into a stereo stream so we don't have to make any changes to the protocol, thus this improvement is backward compatible. I carefully tweaked the jitter buffer and the resampler and the fade in/out, and I guess that's all I should take care of.
Actually, opus decoder can also automatically convert a stereo stream into a mono stream, so even if we transmit a stereo stream to an older version of mumble, it would still work. …

Stereo stream decoding and playing support

---

src/mumble/TalkingUI.cpp

The bug appeared occasionally when changing channel into another one in
which there was someone talking. In that case it could happen that in
the TalkingUI the old channel the local user has just moved out from,
would still show up and remain in the TalkingUI (until another action -
change of talking state or change of channel) even though that channel
was empty now.
This was due to a race condition between the channelChanged and the
talkingStateChanged event. If the talkingStateChanged event arrived
first, the code that is responsible for inserting the local user at the
top of the channel it is in, would then blindly "remove" the local user
from that channel in order to add it again at the top. In this situation
however, the local user wasn't even in that channel yet (in the
TalkingUI …

Fix "empty entry bug"

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioConfigDialog.h
src/mumble/AudioOutput.ui
src/mumble/mumble_en.ts

We do have a separate section in the AudioOutput settings for positional
audio but the option to enable/disable it is not in that section. This
doesn't make a whole lot of sense.
This commit simply moves the setting into the positional audio section
and also renames it from "positional audio" to "enable" as due to its
location in the settings, it's clear what it'll be about.
----

Move positional audio option to proper section

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioConfigDialog.h
src/mumble/AudioOutput.ui
src/mumble/mumble_en.ts

Before this commit we had 3 places in the AudioOutput settings page that
dealt with stuff related to attenuation (1 in the "Audio Output"
section, the "Advanced Attenuation Options" and the "Priority Speaker"
section).
This commit merges all of them into a single "Attenuation" section.
-----
-----
/cc @streaps :)

Group all attenuation settings together

---

src/murmur/ServerDB.cpp

In #3803 it is reported that the server regularly crashes because the
MySQL/SQLite part of the database code for group changes doesn't handle
conflicts in primary keys (as the PostgreSQL part does).
This commit makes the SQL statement use REPLACE INTO instead of INSERT
INTO which according to the docs "REPLACE works exactly like INSERT,
except that if an old row in the table has the same value as a new row
for a PRIMARY KEY or a UNIQUE index, the old row is deleted before the
new row is inserted."
It's actually a MySQL extension but according to Wikipedia SQLite
supports it as well.
(Edited by @Krzmbrzl)

Use REPLACE instead of INSERT

---

src/murmur/ServerDB.cpp

In #3803 it is reported that the server regularly crashes because the
MySQL/SQLite part of the database code for group changes doesn't handle
conflicts in primary keys (as the PostgreSQL part does).
This commit makes the SQL statement use REPLACE INTO instead of INSERT
INTO which according to the docs "REPLACE works exactly like INSERT,
except that if an old row in the table has the same value as a new row
for a PRIMARY KEY or a UNIQUE index, the old row is deleted before the
new row is inserted."
It's actually a MySQL extension but according to Wikipedia SQLite
supports it as well.
Backported from #4105

Backport "Use REPLACE instead of INSERT"

---

src/mumble/Markdown.cpp

Special characters inside of markdown code in the chat were escaped twice.
The message `**<test>**` was previously escaped to `**&lt;test&gt;**`.
The markdown code changed the `**` to `<b>` tags,
but also escaped the `&` character again, resulting
in `<b>&amp;lt;test&amp;gt;</b>`.
Due to the double escaping, special characters like `<` were not
displayed correctly.
Fixes: #4179

src/mumble/Markdown.cpp remove double html escaping from markdown.

---

src/CryptState.cpp
src/CryptState.h
src/mumble/ServerHandler.cpp
src/murmur/Server.cpp
src/tests/TestCrypt/TestCrypt.cpp

As explained in https://github.com/mumble-voip/mumble/issues/4219#issuecomment-636218461:
> In simple terms:
>
> Never encrypt any message where the second to last block starts (or ends? don't recall how len was actually implemented in OCB2. be sure not to mess this one up! if unsure, just do both) with 120 bits of zeros.
> Ignore any decrypted message which we would not have encrypted according to 1.
>
> Given we mostly send compressed audio over UDP, it seems unlikely that there would ever legitimately be 120 bits of zeros, so impact should be minimal. Ping packets are probably only a single block in size, so they're not affected either.
Removing either encryption or decryption oracle will make the attacks impossible. And because a Mumble client never decrypts its own packets, if we …

Safeguard from potential attacks against OCB2

---

src/CryptState.cpp
src/CryptState.h
src/mumble/ServerHandler.cpp
src/murmur/Server.cpp
src/tests/TestCrypt/TestCrypt.cpp

OCB2 is known to be broken under certain conditions:
https://eprint.iacr.org/2019/311
To execute the universal attacks described in the paper, an attacker needs
access to an encryption oracle that allows it to perform encryption queries with
attacker-chosen nonce. Luckily in Mumble the encryption nonce is a fixed counter
which is far too restrictive for the universal attacks to be feasible against
Mumble.
The basic attacks do not require an attacker-chosen nonce and as such are more
applicable to Mumble. They are however of limited use and do require an en- and
a decryption oracle which Mumble seemingly does not provide at the same time.
To be on the safe side, this commit implements the counter-cryptanalysis
measure described in the paper in section 9 for the sender and receiver side. …

Backport "Safeguard from potential attacks against OCB2"

---

src/mumble/Messages.cpp
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h

When a client disconnected from the server that was still talking and
therefore showing up in the TalkingUI, it could happen that this user
was not removed from it even though it was no longer on the server. This
is due to a race-condition in the event chain: It could happen that the
respective user object got deleted before the on_talkingStateChanged
function in the TalkingUI got called. This then led to this function not
getting a reference to the user object which causes it to return.
This commit explicitly wires up the UserRemove event with the TalkingUI
to make sure a user gets removed from it once it is removed from the
server.

TalkingUI: Fix ghost users

---

src/mumble/CoreAudio.cpp
src/mumble/CoreAudio.h

src/CoreAudio: update CoreAudio API, remove deprecated API calls.

---

src/mumble/ALSAAudio.cpp
src/mumble/OSS.cpp
src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h

The check was originally implemented to avoid initializing multiple channels when it was guaranteed only one would be available (i.e. positional audio disabled).
Now that we support stereo audio decoding (#4209), the check has to be removed in order to make the feature available when positional audio is disabled.

src/mumble: remove positional audio check in audio backends

---

src/mumble/AudioOutput.cpp
src/mumble/AudioOutput.h
src/mumble/AudioOutputSample.cpp
src/mumble/AudioOutputSample.h
src/mumble/AudioOutputSpeech.cpp
src/mumble/AudioOutputSpeech.h
src/mumble/AudioOutputUser.cpp
src/mumble/AudioOutputUser.h
src/mumble/CoreAudio.cpp
src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h

Thank @Reikion for bringing this up :).
After the stereo support is added, mumble would crash when trying to play stereo samples (customized message alert sound, etc) on some Linux distribution using PulseAudio.
According to the backtrace, I learn that this crash is caused by resizing a buffer inside prepareSampleBuffer, which is invoked by our output audio callback function mix().
```
#0  0x00007f1a10782355 in raise () from /usr/lib/libc.so.6
#1  0x00007f1a1076b853 in abort () from /usr/lib/libc.so.6
#2  0x00007f1a107c5878 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f1a107ccd3a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f1a107d0417 in _int_malloc () from /usr/lib/libc.so.6
#5  0x00007f1a107d15a9 in malloc () from /usr/lib/libc.so.6
#6  0x00007f1a10b1152a in …
```

Fix: Resizing buffer in audio callback causes mumble to crash

---

src/mumble/AudioOutput.ui

Some labels were stacked on top of each other in the Positional Audio
section of the settings page. This probably happened in a wrongly
resolved merge-conflict and is corrected by this commit.
----
##After

src/mumble/AudioOutput.ui: Fix stacked elements

---

scripts/azure-pipelines/build_linux.bash

Previously AppImages built on the CI got their updates from https://dl.mumble.info/snapshots/
but now we have a separate directors `nightly` that'll contain CI build artifacts and this should be used instead.

CI: change update target for AppImages

---

src/mumble/Overlay.cpp
src/mumble/Overlay.h

This PR makes the overlay work again (got broken in https://github.com/mumble-voip/mumble/commit/aac3214d4be2ba31c852619bc8d3666391dcd02a) and furthermore makes sure that it really only is initialized if needed.
----
I have not tested the changes to actually work yet. Would be great if someone could do so :)

Fix overlay

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/mumble_en.ts

I always want to send an image by copy and paste it into the chat bar of mumble.
This is a commonly expected behavior of any chat app. Can't see why mumble should not have one.

Send image pasted into the chat bar

---

src/SSL.cpp

This fixes a regression introduced in
b691108d3820695d51e2f4d76d1ee080e9bfaa91. In there it was thought that
there is no need to explicitly add the system CaCertificates to the SSL
configuration. This turned out to be wrong.
It was brought up that by removing this line, properly signed
certificates would also be shown as self-signed.
Fixes #4289

FIX(certificate): Properly process signed certificates

---

src/mumble/ClientUser.cpp
src/mumble/ClientUser.h
src/mumble/Database.cpp
src/mumble/Database.h
src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/MainWindow.ui
src/mumble/Messages.cpp
src/mumble/mumble_en.ts

These changes make it possible to disable Text-To-Speech for specific
users while still receiving the messages as normal text.
A use case for this would be muting text to speech for a music bot.

Allow disabling of TTS for specific users

---

src/mumble/UserLocalVolumeDialog.cpp

Before this commit, if the MainWindow was set to be always on top of
other windows, it could happen that the UserLocalVolumeDialog got hidden
behind the MainWindow (it wanted to open on top of it but since the
MainWindow is set to be on top of all other windows, it couldn't). This
could be especially annoying on Windows where you can't move the
MainWindow away as long as the UserLocalVolumeDialog is open (luckily
you can close it via Esc though).
In order to avoid this kind of situation, this commit make the
UserLocalVolumeDialog "inherit" the AlwaysOnTop flag from the
MainWindow. This way it can open on top of it again and won't be hidden.

UserLocalVolumeDialog: "Inherit" AlwaysOnTop behavior

---

src/mumble/Messages.cpp

1a4d134a35b656113684b8070a74bfd2474304a1 (part of #4287) introduced the ability to
disable TTS for specific users. The change however didn't account for
messages that are sent from the server. In these cases pSrc is nullptr
but that commit introduced code that access it without checking for
null. This lead to a SegFault as soon as a text message from the server
is received.
This commit fixes this by simply adding a null-check before accessing
the variable.

FIX(text-chat): Fix crash on TextMessage from server

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/UserLocalVolumeDialog.cpp
src/mumble/mumble_en.ts

Log a message if a change like local muting of a user could not be saved because this user does not have a certificate.
The displayed message is:
> This change could not be saved permanently and is lost on restart because Username does not have a certificate.

FEAT(client): Log a message if some change could not be saved due to missing certificate

---

src/mumble/Messages.cpp
src/mumble/mumble_en.ts

The new features "Omit Message Scope" and "Omit Message Author" where
somewhat broken.
The problems are adressed by transforming the message from HTML to
plaintext and creating a new TTS string that either contains no prefix
or just the scope or the author.
Fixes #4309

 FIX(tts): OmitScope/OmitAuthor no longer reads HTML-formatted message

---

src/mumble/TalkingUI.cpp

Until now the TalkingUI assumed that session IDs of users are unique
throughout the server's lifetime. This turned out to be wrong as the
server reuses session IDs of disconnected users.
This could lead to a new user being shown with the name of an old user
in the TalkingUI as that new user was reusing the old's session ID.
With this commit a user gets deleted from the TalkingUI if it
disconnects from the server.

FIX(talking-ui): Fix glitch on session reuse

---

src/mumble/ConnectDialog.cpp
src/mumble/ConnectDialog.h
src/mumble/ConnectDialog.ui
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/mumble_en.ts

This PR revamps the ServerBrowserUI to facilitate its usage. Additionally it also adds a search-functionality to it.
Fixes #3532
----
Screenshot:

Revamp ServerBrowser UI

---

src/Mumble.proto

This PR corrects a few typos I stumbled on in the Mumble.proto file.

Fix typos in Mumble.proto

---

src/mumble/TalkingUI.cpp

With tiling window managers (e.g. i3) the TalkingUI was seen as any
other regular window and thus it was assigned its own screen space.
This is however unfitting for the TalkingUI as it is meant to take the
least amount of possible screen space.
The solution is thus to mark the TalkingUI as floatable in order to
bypass the WM's tiling logic. In order to do so, the TalkingUI is now
marked as a dialog. Dialogs however also show the "?" button in the
title bar by default, which had to explicitly be disabled as it is
absolutely useless for the TalkingUI anyways.
Fixes #4324

FIX(talking-ui): Make TalkingUI float wit tiling WMs

---

src/mumble/AudioOutputSpeech.cpp
src/mumble/MainWindow.cpp
src/mumble/OpusCodec.cpp
src/mumble/OpusCodec.h
src/mumble/OverlayEditorScene.cpp
src/mumble/OverlayUser.cpp
src/mumble/OverlayUserGroup.cpp
src/mumble/ServerHandler.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h
src/mumble/UserModel.cpp
src/mumble/UserModel.h
src/mumble/mumble_en.ts
themes/Classic/talking_muted.svg
themes/ClassicTheme.qrc
themes/MumbleTheme.qrc

Before this commit it is impossible to tell whether a client is talking
or not once that client is locally muted.
This commit changes this by introducing a new talking state
"MutedTalking" for these special cases. In order for this talking state
to come in existence, the audio code was altered so that audio packets
are no longer dropped if the associated user is locally muted. Instead
the audio frame will pass the normal processing chain until it comes to
actually decoding it.
For Opus packets only the sample count is read out without actually
doing the work of decoding. For all other codecs the packet is decoded
as usual. In a final step the sample buffer is filled/overwritten with
zeros in order to mute the stream.
With this commit in place, the UI will indicate a user that is talking …

FEAT(client): Indicate talking users when locally muted

---

src/mumble/Messages.cpp
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h

The icons for (local/self) muting and (self) deafening of a user are now
also displayed in the TalkingUI. The used icons are the same as in the
MainWindow.
---
Screenshot:

FEAT(talking-ui): Show selected status icons in TalkingUI

---

scripts/azure-pipelines/install-environment_macos.bash

If brew is asked to install a package that is already installed, it will
set a non-zero exit status that causes the CI to abort and fail.
The fix for that is to explicitly check every package for whether it is
already installed and only if they are not, ask brew to install them.
This fix is the same that has been applied in
3e0c5065d21dfbd1e56b91f81c28fccdbadad794

CI(azure): Fix brew-error for installed packages

---

src/murmur/Server.cpp

Backport: FIX(cert, mac): Avoid adding key pairs into system's keychain of MacOS.

---

src/murmur/Server.cpp

One unexpected behavior of Qt's SSL backend is: it will add the key pair
it uses in a connection into the default keychain, and when access the private
key afterward, a pop up will show up asking for the user's permission.
In some case (OS X 10.15.5), this pop up will be suppressed somehow and no private
key is returned.
This env variable will avoid Qt directly adding the key pair into the default keychain,
using a temporary keychain instead.
See #4298 and https://codereview.qt-project.org/c/qt/qtbase/+/184243
After this patch, the key pair won't be automatically added to the default keychain, therefore no annoying popup will show up. Also, #4298 is solved.
Fixes #4298

FIX(cert, mac): Avoid adding key pairs into system's keychain of MacOS.

---

scripts/murmur.ini
src/murmur/Messages.cpp
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/ServerDB.cpp
src/murmur/ServerDB.h
src/murmur/main.cpp
src/murmur/murmur.pro

This option allows to set a threshold on how long a user's channel
should be remembered. This is useful for scenarios where users usually
don't want their channel to be remembered by the server unless they had
a disconnect (aka have ot re-connect after a short period of time).
Implements #4143

FEAT(server): Add rememberduration option

---

src/mumble/ConnectDialog.cpp
src/mumble/NetworkConfig.cpp
src/mumble/NetworkConfig.ui
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/mumble_en.ts

This implements #4070 and makes it possible to hide the public-server-list from the connect dialog.
The save location was left under ui for backwards compatibility.
This is a follow-up on #4305

Allow disabling the public-server-list

---

src/mumble/ConnectDialogEdit.ui
src/mumble/mumble_en.ts

For some reason the "Ignore" String in the ConnectDialogEdit was not
marked as translatable. This is fixed by this commit.
Fixes #4359

FIX(translation): Make "Ignore"-string translatable

---

src/mumble/AudioOutput.cpp
src/mumble/AudioOutput.h
src/mumble/ManualPlugin.cpp
src/mumble/ManualPlugin.h
src/mumble/ManualPlugin.ui
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/mumble_en.ts

With this change the positions of other speakers are also displayed in
the UI of the ManualPlugin (next to your own position) as red dots. This
allows for better understanding of the positional audio feature.
It is also possible to specify a time for these dots to persist even if
the corresponding speaker has stopped talking. In this time the
respective dot will start to fade out until it gets removed completely.
This does not show the names of the associated speakers in order to not
clutter the UI too much. If this information is needed, the TalkingUI
can be opened alongside the ManualPlugin to get an overview of who's
currently talking.
----
Screenshot:

FEAT(manual-plugin): Show speaker's position

---

src/mumble/GlobalShortcut.cpp

Right now after having removed a shortcut from the UI, the next shortcut
in the list is selected automatically. This could cause the user to
accidentally delete this next shortcut by accident as the mouse is
hovering over the remove button anyways.
This change makes mass-removing of shortcuts a bit tedious but I don't
think that this is a common thing to do. Given that you can't undo the
deletion of a shortcut, we should better be safe than sorry with this.

FIX(shortcuts-ui): Clear selection after remove

---

scripts/murmur.ini
src/murmur/Meta.cpp
src/murmur/Meta.h
src/murmur/Server.cpp
src/murmur/Server.h

This allows specifying welcometextfile in murmur.ini. If no welcometext
is set in the ini-file, the welcome text is loaded from the file.
Fixes #3723

FEAT(server): Allow loading welcome text from file

---

src/mumble/MainWindow.cpp
src/mumble/main.cpp

MainWindow::serverDisconnected did not always get called when
terminating Mumble normally (not by pressing Ctrl+C). The reason for
that was that 2-fold:
a) There was a race between the main thread and the ServerHandler
thread. If the ServerHandler did not exit fast enough, the disconnect
event it emitted wouldn't reach the main thread in time to be processed
before the application exits
b) The main thread didn't make sure that all events have been processed
before actually shutting down and starting deleting objects.
This is solved now by first waiting for the ServerHandler thread to exit
before proceeding the shutdown process. In order to never run in the
situation in which the main thread won't exit because the ServerHandler
got stuck somehow, a hard limit of 2 seconds was set.
After …

FIX(client): Always run Disconnected-EH on exit

---

.azure-pipelines.yml
scripts/azure-pipelines/build_linux.bash
scripts/azure-pipelines/build_macos.bash
scripts/azure-pipelines/build_windows.bat

`Agent.BuildDirectory` refers to the path on the agent where all folders for the pipeline are created.
`Build.BinariesDirectory` is the correct variable to use: it refers to the path that can be used as an output folder for compiled binaries.
Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables

CI(azure-pipelines): use correct path for build output

---

overlay/CMakeLists.txt
overlay/HardHook_x86.h

FIX(overlay): only use minhook for 64 bit overlay library, add missing <unknwn.h>

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml
.ci/azure-pipelines/steps_macos.yml

[MacStadium](https://www.macstadium.com) kindly provided us an hosted 2012 Mac mini for free last year.
Until now we only used it for testing and to build the vcpkg environment, waiting for the CMake project to be merged.
Now that everything is in place, we can use it for CI and to release builds.

CI(azure-pipelines): use our own macOS builder for releases

---

src/mumble/CMakeLists.txt
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h
src/mumble/TalkingUISelection.cpp
src/mumble/TalkingUISelection.h
src/mumble/mumble.pro

Before this commit it was only possible to select users in the TalkingUI
(and thereby it was also only possible to trigger the context menu for
users via the TalkingUI).
This commit extends the functionality that currently exists for users to
channels as well. This includes selection as well as the context menu.

FEAT(talking-ui): Make channels selectable

---

.ci/azure-pipelines/install-environment_windows.ps1

As experienced before, disabling the progress monitor for web-requests
in PowerShell can drastically increase the download speed. The newer
script however only used to trick for the main build environment but not
for downloading the other stuff (like ASIO SDK).
This commit sets the respective preference in the beginning of the
script and doesn't reset it anymore so that now all web-requests should
benefit from it.

CI(windows): Potential download speedup

---

src/mumble/CustomElements.cpp

I can consistently reproduce the linked issue on my machine.
Let me know if you want me to test some other approach.
Fixes https://github.com/mumble-voip/mumble/issues/3701.

FIX(ui): Make chatwidget max height >= than its minimum height

---

scripts/Create-Win32InstallerMUI.ps1

This should save some time during building the installer which hopefully
helps preventing the Windows CI from exceeding the maximum time.

CI(installer): Only build a few cultures by default

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat
.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml
.ci/travis-ci/script.bash

As with the 64 bit build, it uses a build environment we provide on our website.

CI(azure-pipelines): add 32 bit Windows build

---

src/murmur/Server.cpp

This PR fixes 2 issues in the server's code that have something to do with packet sizes:
1. Make sure `poslen <= len` in order for `len - poslen` to never get negative (which can cause trouble down the line)
2. Enforce the maximum package size for packets received via UDPTunnel as well

FIX(server): Packet size issues

---

src/mumble/ServerHandler.cpp

If a received UDP is greater than what our allocated buffers can hold,
they are discarded as of now. Previously they have been trimmed down but
the untrimmed size was used in following code which could lead to stack
corruption.

 FIX(client): Discard oversized UDP packets 

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml
.ci/azure-pipelines/steps_windows.yml

As of now the built x86 files overwrite the x64 ones since the x64
build is usually done first but they both produce files of the same
name.
With this commit the build artifacts for x86 and x64 are separated.

CI(azure): Don't overwrite build artifacts

---

.ci/azure-pipelines/steps_windows.yml

Instead of publishing each and every PDB file separately, we now zip
them together into an archive and publish that. That'll reduce the
amount of published files which should make it easier to find what
you're looking for.

CI(windows): Zip all PDB files

---

src/mumble/Database.cpp
src/mumble/Database.h
src/mumble/Global.cpp
src/mumble/Global.h
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/main.cpp
src/mumble/mumble_en.ts

This adds the switch -c/--config to the mumble client. If -c is followed by a filename, this file will be read instead of the standard config.
A new config option `database=` has been added to the 'General' section of the ini file. This can be used to specify a different database which is necessary to run multiple completely separate Mumble instances at the same time.
Additionaly the (undocumented) function to merge another ini file by providing it as a parameter has been removed as it was conflicting with the added functionality.
FIXES #3953

 FEAT(client): Allow specifying config file via commandline switch 

---

CMakeLists.txt
cmake/project-utils.cmake
src/mumble/CMakeLists.txt

In order to not be spammed with warnings from 3rdparty projects that we
make use of in Mumble, this commit modifies the respective cmake files
in a way that disables warnings for the respective projects.

MAINT: Disable warnings for 3rdparty projects

---

cmake/project-utils.cmake

Without this change it could happen that get_targets returned
non-compilable targets (e.g. install or uninstall targets) and this
could lead to errors when e.g. trying to set compile options on those
targets.

MAINT(cmake): Only return compilable targets

---

src/mumble/CMakeLists.txt

The dbus config option has been respected in the server's CMakeLists.txt
but the client ignored the option. This is corrected by this commit.
Fixes #4409

MAINT(cmake): Enable DBus for the client

---

src/CMakeLists.txt

This fixes the version appearing as `0.0.0` in builds produced by CI.
We should probably choose a better name for the two defines. Perhaps `MUMBLE_VERSION_SHORT` and `MUMBLE_VERSION_EXTENDED`.

FIX(cmake): define "MUMBLE_VERSION_STRING" to short version (e.g. "1.4.0")

---

src/murmur/Server.cpp

Commit bdb12c6 added a regression for servers built with QT older than version
5.15. After this commit these servers do not server intermediate certificates
anymore.  This happens because the QSslConfiguration is retrieved before adding
the CA certificates to the socket and is reinserted into the socket again after
adding the CA certificates, thereby overwriting the CA certificates added in
between.
This commit fixes that by retrieving the QSslConfiguration just after setting
the CA certificates in case an older QT version than 5.15 is used.

FIX(certificate): Retrieve QSslConfiguration after setting CA

---

src/mumble/ServerHandler.cpp

This should help us investigate why a crash happens immediately after the function fails on Windows 10 Insider Build 20185.

FEAT(client): print extended error when QOSRemoveSocketFromFlow() fails

---

src/mumble/AudioOutput.cpp
src/mumble/AudioOutput.h
src/mumble/Plugins.cpp

Whe using CONFIG+=no-manual-plugin with the old qmake buildsystem or
-Dmanual-plugin=OFF with the new cmake one, there were compile errors
due to the ManualPlugin being referenced in other files without include
guards.
This commit makes sure that in case the manual plugin is not included,
other code won't reference it either.
Fixes #4422

FIX(client): Compile error without manual plugin

---

.ci/azure-pipelines/steps_macos.yml
.ci/azure-pipelines/steps_windows.yml

This feature of AzurePipelines has only been introduced recently.
However it turned out that on average the caching of the environment
takes significantly more time than simply downloading it on every run.
Thus this commit disables environment caching again.

CI(azure): Disable environment caching

---

macx/scripts/osxdist.py

Before this PR the MacOS packaging script failed on copying Codecs
if the respective directory already existed (e.g. because the packaging
script has been run before).
Furthermore the script called a function to delete a directory (tree)
on a file. This error never surfaced before because usually when this
script is run, the respective file doesn't exist yet.
Both issues are fixed by this PR. It is now possible to run the
packaging script multiple times consecutively without it erroring on
already existing files.

FIX(packaging): Enable mac-script to run multiple times

---

src/mumble/CMakeLists.txt
src/mumble/main.cpp

This fixes the loader not being able to load the DLL due to the missing symbol (mumble-voip/mumble-releng-vcpkg#8).
Previously, the function was defined and exported only when `QT_NO_DEBUG` was not defined (i.e. release builds).
This was probably the case due to:
- Our old environment not providing debug libraries.
- The DLL + loader idea only making sense when Mumble is installed. See PR #1684 for further info.

FIX(client): define and export "MumbleMain" also in debug builds

---

man/mumble.1
man/murmurd.1

Missing options from the help messages of mumble and murmur have
been added to the respective man pages.

DOCS(man): Add missing options from help messages to man pages

---

src/mumble/MainWindow.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/main.cpp

In order for the UI to not pop-up in the middle of the MainWindow (or
any other default location) after you have placed it carefully the last
time, this commit makes the UI's position to be saved and restored.
For cases in which there is no position set yet, it will be positioned
to the right of the initial position of the MainWindow.
Note that the UI's position is only saved if it is visible at the time
Mumble is closed which is used as an indication that the user is
actually using it (and has thus placed it explicitly).

FEAT(talking-ui): Save last position

---

.ci/azure-pipelines/install-environment_macos.bash

Axel is a CLI download utility that'll open multiple concurrent streams
and thereby increasing the overall download speed.
Ref.: https://www.linuxjournal.com/content/speed-your-downloads-axel
Using axel to download the environment seems to be up to 5x faster than
using wget.

CI(macOS): Use axel instead of wget

---

.ci/azure-pipelines/extractWithProgress.bash
.ci/azure-pipelines/install-environment_macos.bash

As tar doesn't support a proper progress bar this commit adds a helper
script that'll print a rough progress.

CI: Show progress for decompressing

---

src/mumble/AudioOutput.cpp
src/mumble/ClientUser.cpp
src/mumble/ClientUser.h
src/mumble/LookConfig.cpp
src/mumble/LookConfig.ui
src/mumble/Messages.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h
src/mumble/UserLocalVolumeDialog.cpp
src/mumble/UserModel.cpp
src/mumble/UserModel.h
src/mumble/mumble_en.ts

This feature optionally allows users to display the set volume
adjustments next to the user's/listener's name.
It will only be shown if it is not equal to 0 dB (aka: it is actually
having an effect).
By default this option is enabled since it is only visible if volume
adjustments are set up anyways.
Screenshot:

FEAT(client, mainwindow): Show volume adjustments

---

src/CMakeLists.txt
src/mumble/CMakeLists.txt
src/murmur/CMakeLists.txt
src/murmur/Messages.cpp
src/murmur/Meta.cpp
src/murmur/PBKDF2.cpp
src/murmur/Server.cpp
src/murmur/UnixMurmur.cpp

With the old qmake buildsystem we used to set QT_NO_CAST_FROM_ASCII (for
the Mumble client) in order to avoid problems with character encodings
in our Strings. This was not done in the new cmake system yet.
Instead of the aforementioned macro, this commit sets
QT_RESTRICTED_CAST_FROM_ASCII instead in order to be able to
automatically convert direct String literals to QString as these usually
don't contain any problematic characters (non-ASCII) in the first place.
And this allows to e.g. compare a QString against a String literal or do
something like
QString myString = "This is a test";
which we know to be unproblematic.
Note however that (quote from Qt's docs)
"Using this macro together with source strings outside the 7-bit range,
non-literals, or literals with embedded NUL characters is …

FIX(cmake): Set QT_RESTRICTED_CAST_FROM_ASCII

---

src/mumble/ALSAAudio.cpp

'ALSA_ERRCHECK' is an unsafe function-like macro that should be replaced with a function. 'avail' is used uninitialized whenever 'bOk' is false which is undefined behavior.

FIX(client): Initialize variable before use

---

src/mumble/PulseAudio.cpp

A prominent feature of PulseAudio is automatic sample rate management. Mumble always wants 48000 Hz sample rate yet will often tell PulseAudio to sample at a different rate, such as 44100 Hz, and then resample internally reducing audio quality and wasting CPU time.

FIX(client): Make PulseAudio always sample at 48000 Hz

---

src/murmur/Server.cpp

Format specifies type 'void *' but the argument has type 'QObject *'. Using an argument of an unexpected type is undefined behavior.

FIX(server): Use valid format string type

---

src/mumble/About.cpp

Fix the regression introduced with commit 3575a4c
by using the proper Qt text interaction flag.

FIX(client): Make link in about dialog clickable again

---

src/mumble/ACLEditor.ui

The ACLEditor's Groups tab has 3 separate columns for dealing with
members. These columns wouldn't grow equally though: The 2 leftmost
columns basically didn't grow at all while the rightmost grew to fill
the available space.
This is a problem though since the 2 leftmost columns have a ComboBox in
them and if the user wants to make those bigger, then (s)he expects this
to be possible by increasing the window's size. This was not the case
though and the ComboBoxes stayed at their initial size.
This commit makes sure that all columns now grow equally and thus
allowing the user to increase the ComboBoxe's size by increasing the
window's size.
Fixes #4453

FIX(client, ui): ACLEditor not growing evenly

---

src/mumble/ALSAAudio.cpp

Backport "FIX(client): Initialize variable before use"

---

src/mumble/PulseAudio.cpp

Backport "FIX(client): Make PulseAudio always sample at 48000 Hz"
