src/murmur/Cert.cpp, src/murmur/Messages.cpp, src/murmur/Server.cpp, src/murmur/ServerUser.h
This PR should fix the remaining warnings during a murmur build (on Linux using gcc).
=> Fix remaining warnings in murmur

src/Mumble.proto
=> document undocumented fields in Mumble.proto

plugins/bf4/bf4.cpp
- Added Squad State value (Public or Private).
- Added/Changed comments.
=> plugins/bf4: Added Squad State value

plugins/ql/ql.cpp
Added:
Context/Identity escape function
Map name in identity
Improved:
Horizontal and vertical view memory addresses changed, the new ones are updated in real-time
Team names
Fixed:
Avatar/Camera front and top vectors calculation
Wrong comment at line 140
Game version: 1069
http://steamcommunity.com/games/282440/announcements/detail/876328108049672536
=> plugins/ql: Plugin update for game's latest version

src/murmur/Server.cpp
Due to a regression in Qt 5, we can't use disconnectSocket(true)
to abort a handshake.
Use non-forceful disconnect to work around the Qt 5 bug.
See inline comment for more details.
Fixes mumble-voip/mumble#2334
=> Murmur: use non-forceful disconnect when encountering SSL handshake errors on Qt 5.

plugins/gtav/gtav.cpp
Fixed:
X/Z axes: http://www.gtamodding.com/wiki/Map_system
Wrong comma at line 106
Wrong comment at line 150
Game version: 1.34
https://support.rockstargames.com/hc/en-us/articles/220249028-GTAV-Title-Update-1-34-Notes-PS4-Xbox-One-PC
=> plugins/gtav: Plugin update for game's latest version

plugins/rl/rl.cpp
Fixed X/Z axes: Rocket League uses a left-handed Y-up coordinate system (like Mumble), even if Unreal Engine uses a Z-up one. http://www.aclockworkberry.com/world-coordinate-systems-in-3ds-max-unity-and-unreal-engine/
Game version: 1.19
http://www.rocketleaguegame.com/news/2016/06/patch-notes-v1-19-title-update-7
=> plugins/rl: Plugin update for game's latest version

plugins/gtav/gtav.cpp
Added support for retail version.
Fixed avatar position Y being 0 when the game is paused.
Many thanks to **hiradur** on [IRC](http://wiki.mumble.info/wiki/IRC) for his testing and support, this wouldn't have been possible without him.
Version detector adapted from [Borderlands 2 plugin](https://github.com/mumble-voip/mumble/blob/master/plugins/borderlands2/borderlands2.cpp).
=> plugins/gtav: Support for retail version

src/mumble/GlobalShortcut_win.cpp
This removes any observable mouse lag from the winhook initialization
process.
Fixes mumble-voip/mumble#2273
=> GlobalShortcutWin: delay winhook initialization until after our first timeTicked() slot.

src/mumble/About.cpp
=> About: HTML-escape third party license text.

installer/Plugins.wxs, plugins/plugins.pro, plugins/wow_x64/wow_x64.cpp, plugins/wow_x64/wow_x64.pro
Context based on Realm's name.
Identity: Player's name.
Game version: 7.0.3.22566
Thanks to [OwnedCore](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/578228-wow-7-0-3-22522-release-info-dump-thread-post3584506.html#post3584506) for most of the memory addresses.
=> plugins/wow: Total revamp and support for the x64 version of the executable

plugins/wow/wow.cpp, plugins/wow_x64/wow_x64.cpp
Game version: 7.0.3.22624
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/585582-wow-7-0-3-22624-release-info-dump-thread.html#post3615091
=> plugins/wow: update plugin to work with build 22624

installer/Plugins.wxs, plugins/bf1/bf1.cpp, plugins/bf1/bf1.pro, plugins/plugins.pro
Context based on server name.
Identity: Team, squad and squad leader.
=> Positional audio support for Battlefield 1

src/mumble/GlobalShortcut_win.cpp
When handling low-level Windows key events, we emit them to the
GlobalShortcut engine using the same key ID that we use for
the DirectInput backend.
Unfortunately, the existing code for generating a DirectInput
compatible key ID didn't produce correct results for NumLock
and Pause.
This commit fixes that by special-casing the translation of the
"extended key" flag when translating a scancode into a DirectInput
key ID.
Now, we ensure that the extended flag bit is ALWAYS set for the Pause
key (even though it isn't in the low-level key event). We also ensure
that the extended flag bit is NEVER set for the NumLock key (even though
it is in the low-level key event).
This yields correct DirectInput key IDs for NumLock and Pause keys.
Fixes mumble-voip/mumble#1353
=> GlobalShortcutWin: ensure winhook NumLock and Pause keys are translated into their correct DirectInput key IDs.

src/mumble/Settings.cpp
Qt expects to be able to write NUL bytes in strings
serialized via QSettings. macOS Sierra broke this.
We've since backported a fix from Qt master into
our buildenv, and the bug is fixed.
This commit adds a workaround for users whose clients
have already written 'bad' config files on macOS.
If a bad config value is detected, it is skipped and
the default is used instead.
=> Settings: add workaround for macOS "@Variant(" bug.

installer/Files.wxs, installer/Product.wxs, installer/Settings.wxi
Our builders are now running MSVC2015. Update the installer to work
with MSVC2015's CRT.
=> installer: use VC140 CRT.

plugins/aoc/aoc.cpp, plugins/arma2/arma2.cpp, plugins/bf2/bf2.cpp, plugins/bf3/bf3.cpp, plugins/bf4/bf4.cpp, plugins/bf4_x86/bf4_x86.cpp, plugins/blacklight/blacklight.cpp, plugins/borderlands2/borderlands2.cpp, plugins/dys/dys.cpp, plugins/gmod/gmod.cpp, plugins/gw/gw.cpp, plugins/insurgency/insurgency.cpp, plugins/lol/lol.cpp, plugins/sr/sr.cpp, plugins/sto/sto.cpp, plugins/ut99/ut99.cpp, plugins/wolfet/wolfet.cpp
This replaces PR #2756. I removed unwanted changes and made some other small adjustments for consistency.
=> plugins: Use tabs for indentation, remove trailing whitespace

plugins/rl/rl_linux.cpp, plugins/rl/rl_win32.cpp
Game version: 1.29
https://rocketleaguegame.com/news/patch-notes-v1-29
=> plugins/rl: update plugin to work with version 1.29

src/mumble/mumble_en.ts
Updating 'mumble_en.ts'...
Found 1672 source text(s) (52 new and 1620 already existing)
Removed 11 obsolete entries
=> Translation update

qmake/rcc.pri
The path has changed with PR #2905.
=> rcc.pri: Fix wrong script path

.mailmap, AUTHORS
- Update hacst's email, to avoid a duplicate in AUTHORS.
- Re-run scripts/generate-AUTHORS.py.
=> Update AUTHORS file (2017-03-25)

src/tests/TestTimer/TestTimer.cpp
Previously, this test depended on the fact that QTime is/was a low
resolution timer, which is/may not always be the case.
This changes the test to only use the Timer class.
=> TestTimer: make resolution test independent of QTime.

README, README.md
=> Drop Speex from README

plugins/bf1/bf1.cpp
https://www.battlefield.com/news/update-notes/bf1-they-shall-not-pass-update
=> plugins/bf1: update plugin to work with version 1.0.49.28890

src/CryptState.cpp, src/mumble/ConnectDialog.cpp, src/mumble/Global.cpp
* Initialize variables in constructor
* Drop redundant if condition in else case
Found via CPPCheck
=> Resolve code issues

src/tests/TestTimer/TestTimer.cpp
- Refactory accuracy test, and add logging
- Add logging to atomicity test
- Add delta64 function and use it throughout TestTimer to do delta calculations
=> TestTimer: refactor some tests to provide more useful log output

src/murmur/Cert.cpp
This commit gets rid of manually allocated BN_GENCB structs
in favour of objects returned from BN_GENCB_new().
Why do this? OpenSSL structs are now considered opaque. Therefore, it is
not wise for us to allocate them based on their size in the current
OpenSSL header, since its size can change in the future.
Instead, we let OpenSSL allocate the object for us using the
BN_GENCB_new() method (and corresponding BN_GENCB_free() method for
freeing the allocated object).
These functions are only available in OpenSSL 1.1. To remedy this, this
commit implements mumble_BN_GENCB_new() and mumble_BN_GENCB_free().
On OpenSSL >= 1.1, these functions use OpenSSL's own new and free
functions. On prior versions, we allocate using malloc/free.
=> Use BN_GENCB_new() and BN_GENCB_free() where applicable.

src/murmur/Cert.cpp
These functions are only used when the QSslDiffieHellmanParameters
class is available.
This commit moves the functions into an #if
defined(USE_QSSLDIFFIEHELLMANPARAMETERS) block.
=> Murmur: fix warning about unused mumble_BN_GENCB_new/mumble_BN_GENCB_free.

plugins/bf1/bf1.cpp
https://www.battlefield.com/news/update-notes/spring-update
=> plugins/bf1: update plugin to work with version 1.0.49.52296

src/mumble/MainWindow.ui
this makes it more obvious whether an action has an immediate effect
fixes #3069
=> add trailing ellipses to each main window action text that open a window or dialog

scripts/murmur.ini
Removed useless whitespaces...
=> murmur.ini: Remove extra whitespaces

src/mumble/LookConfig.cpp, src/mumble/LookConfig.ui, src/mumble/MainWindow.cpp, src/mumble/Settings.cpp, src/mumble/Settings.h
Adds option to disable the "Drag Here" zone when in custom layout mode.
=> Add toggle to lock layout when in custom layout mode

src/tests/TestServerResolver/TestServerResolver.cpp
In mumble-voip/mumble#3163 it was reported that a server that was
accessible via a CNAME was no longer being resolved correctly by
Mumble's connect dialog.
This commit adds CNAME to the ServerResolver test suite, so we're
sure that it is working.
=> TestServerResolver: add CNAME test.

scripts/murmur.ini
=> scripts/murmur.ini: fix minor typo in gRPC comment.

src/murmur/MurmurGRPCImpl.cpp
=> MurmurGRPCImpl.cpp: fix typo

g15helper/g15helper.plist, g15helper/g15helper.rc, installer/Settings.wxi, macx/common.pri, macx/osax/osax.plist, overlay/overlay.pro, overlay_gl/overlay_gl.pro, src/mumble.pri, src/mumble/mumble.plist, src/mumble/mumble.rc, src/murmur/murmur.plist, src/murmur/murmur.rc
This PR bumps 1.2.x to version 1.2.20.
=> Bump version to 1.2.20.

src/mumble/PulseAudio.cpp, src/murmur/Server.cpp
=> Fix changes made in #3311

src/mumble/Log.cpp, src/mumble/Log.h, src/mumble/Messages.cpp, src/mumble/mumble_en.ts
=> Add configurable "You joined channel" and "You have been moved to channel by..." messages

src/mumble/About.cpp
=> About: allow text in "About" tab to be selected

plugins/rl/rl.cpp
Requested in #3360.
Game version: 1.42
https://www.rocketleague.com/news/patch-notes-v1-42
=> plugins/rl: update plugin and add avatar top vector support

src/mumble/UserModel.cpp
=> UserModel: show muted/deafened state icon only in the right hand column

src/mumble/Messages.cpp
=> use user leave message when user disconnects and is in the same channel

src/mumble/Log.cpp, src/mumble/Log.h, src/mumble/Messages.cpp, src/mumble/Settings.cpp, src/mumble/mumble_en.ts
=> Add configurable "User connected and entered channel" and "User left channel and disconnected" messages

src/mumble/Log.cpp, src/mumble/Log.h, src/mumble/Messages.cpp, src/mumble/Settings.cpp, src/mumble/mumble_en.ts
=> Add configurable private text message notification

src/mumble/AudioInput.cpp
=> AudioInput: calculate audio statistics after RNNoise processing

src/mumble/Messages.cpp
This fixes a problem with the user's context menu being inaccessible in the join message due to the user's unique link being generated from the Session ID, rather than the hash, as `addUser()` doesn't set it.
Thanks to @Natenom for reporting the issue.
=> Messages: set user hash and ID on join

src/mumble/Messages.cpp
=> Messages: fix user registration status not being updated

src/mumble/AudioInput.cpp, src/mumble/AudioOutputSpeech.cpp, src/mumble/Messages.cpp, src/mumble/mumble_en.ts
=> Fix crash when Opus is not available and add critical error message

src/murmur/Register.cpp
=> Murmur: use dedicated domain for public list registration

src/murmur/murmur.pro
Followup to https://github.com/mumble-voip/mumble/pull/3589 for murmur.
=> murmur: cross pkg-config build fix

src/mumble/OverlayEditorScene.cpp
=> OverlayEditorScene: fix object opacity calculation

src/mumble/main.cpp
When Mumble is statically built, an executable and a shared library are generated.
The executable loads the Mumble library and calls its main entry point.
In order to do that we define the `MumbleMain` function in Mumble, which mimics Qt's `WinMain` function.
The Qt `qWinMain` function was used to parse command line arguments into a vector. However, this was no longer the case for normal Windows since Qt 5.4, and the function was removed in Qt 5.9.
Since Qt 5.4 the Windows API function `CommandLineToArgvW`[1] is used for parsing the command line arguments. Consequently, we now use the same to do the same (this is the effective change of this commit).
The change history and use of `qWinMain` in Qt is as follows:
* Before Qt 5.4 the `qWinMain` function was used for all Windows platforms.
* …
=> mumble/main.cpp: fix compilation with Qt >= 5.9

.travis.yml, scripts/travis-ci/script.bash, sonar-project.properties
https://sonarcloud.io/dashboard?id=mumble-voip_mumble
=> Travis CI: add SonarCloud integration for static code analysis

scripts/travis-ci/script.bash
Should fix https://github.com/TheAssassin/AppImageLauncher/issues/209
=> Correct path to icon

plugins/mumble_plugin_linux.h, plugins/mumble_plugin_main.h, plugins/mumble_plugin_win32.h, plugins/mumble_plugin_win32_internals.h
Each commit's message describes in detail what is changed and why.
=> plugins: process type detection improvements

AUTHORS
Generated with scripts/generate-AUTHORS.py
=> Docs: Update AUTHORS file

src/mumble/UserLocalVolumeDialog.ui
=> Fix vertical resizing of user local volume dialog

src/mumble/BonjourClient.cpp, src/mumble/BonjourClient.h, src/mumble/ConnectDialog.cpp, src/mumble/OverlayClient.cpp, src/mumble/OverlayClient.h
=> BonjourClient, OverlayClient: convert raw pointers to QScopedPointer(s)

3rdparty/opus-build/opus-build.pro
https://people.xiph.org/~jm/opus/opus-1.3
Fixes #3547.
=> Update Opus to version 1.3.1

src/mumble/GlobalShortcut.cpp
Resolves https://github.com/mumble-voip/mumble/issues/3774.
Based on https://www.qtcentre.org/threads/3741-How-to-sort-a-QComboBox-in-Qt4
=> Enabled sorting of shortcuts function list

src/murmur/Murmur.ice
=> Backport "Murmur.ice: add missing value to UserInfo"

.travis.yml, scripts/travis-ci/before_install.bash, scripts/travis-ci/script.bash
https://docs.travis-ci.com/user/reference/bionic
Detailed explanation of the changes in commits' messages.
=> Travis CI: switch to Ubuntu Bionic (18.04)

src/mumble/Messages.cpp
The protocol requires that a server sends all client information
before sending the sync message that indicates state is matching.
Before this patch violating this condition could bring the client
into a bad state where a connection was established but the client's
user object not existing. Now the client disconnects itself if
such an issue occurs.
=> Disconnect if server does not send clients user before sync

README.md
This pull request also updates the website link.
=> README.md: add Shield.io badges

Doxyfile, src/mumble/AudioOutput.cpp, src/mumble/Global.h, src/mumble/Messages.cpp, src/mumble/Usage.h
See commit messages for what this PR does
=> Add class documentation and general doxygen completeness

src/Group.cpp, src/Group.h
Fixes #3926 (https://github.com/mumble-voip/mumble/issues/3926#issuecomment-569408933 to be more precise)
=> Introduce static field for case-sensitivity of AccessTokens

src/Group.h, src/Mumble.proto, src/mumble/ServerHandler.cpp, src/murmur/Messages.cpp
This PR addresses most of the review comments of davidebeatrici made in #3927 after it had been merged.
=> Fixups for #3927

src/mumble/DBus.cpp
=> Set non-empty path correctly

src/mumble/ClientUser.cpp
In ClientUser::remove a QWriteLocker is created on
ClientUser::c_qrwlUsers in order to remove the respective user from
ClientUser::c_qmUsers.
However the lock is not released after that but it is instead held until
the function exits. This causes the lock to be held even when
AudioOutput::removeBuffer is being called. Apart from this being bad
practice, it can also lead to a deadlock (verified for the case in which
a ReadLock on ClientUser::c_qrwlUsers is being requested inside
AudioOutput::mix [after the lock on AudioOutput::qrwlOutputs has been
acquired]. This can happen if one calls e.g. ClientUser::get in that
function. In that case the deadlock can happen if audio is being
received and played while one or more users are disconnecting from the
server).
=> src/mumble/ClientUser.cpp: Narrow down the scope of QWriteLocker

src/mumble/Overlay.cpp, src/mumble/Overlay.h, src/mumble/Overlay_macx.mm, src/mumble/Overlay_unix.cpp, src/mumble/Overlay_win.cpp, src/mumble/Settings.cpp, src/mumble/main.cpp
See commit messages for what is being done.
Fixes #3552 
Fixes #3515
=> Fix overlay start

src/mumble/AudioInput.cpp, src/mumble/Global.h
=> Fix last audio frame target

src/mumble/mumble.pro
In response to a review of @bendem on #3987 after having merged it already.
=> Moved concurrent dependency to other Qt deps

src/mumble/AudioInput.cpp, src/mumble/AudioInput.h, src/mumble/Global.h
This PR aims to backport #4050 and #4051 to be included in the 1.3.1 release
=> Backport some more fixes

themes/ClassicTheme.qrc, themes/MumbleTheme.qrc
=> Backport "Add alias for places/network-workgroup.svg"

installer/Files.wxs
=> Installer: Do not delete murmur.ini

installer/Files.wxs, installer/Product.wxs, installer/Settings.wxi, installer/Translations/Czech.wxl, installer/Translations/Danish.wxl, installer/Translations/Dutch.wxl, installer/Translations/English.wxl, installer/Translations/Finnish.wxl, installer/Translations/French.wxl, installer/Translations/German.wxl, installer/Translations/Greek.wxl, installer/Translations/Italian.wxl, installer/Translations/Japanese.wxl, installer/Translations/Norwegian.wxl, installer/Translations/Polish.wxl, installer/Translations/Portuguese.wxl, installer/Translations/Russian.wxl, installer/Translations/SimpChinese.wxl, installer/Translations/Spanish.wxl, installer/Translations/Swedish.wxl, installer/Translations/TradChinese.wxl, installer/Translations/Turkish.wxl
Fixes #4083. Not checked to be working.
=> Optional start menu shortcut for installer

src/Mumble.proto
=> Documention on ContextActionModify

src/mumble/ServerHandler.cpp, src/mumble/Settings.cpp
=> Backport "Fix iInFlightTCPPings check"

src/mumble/ConfigDialog.cpp, src/mumble/Global.cpp, src/mumble/Global.h, src/mumble/GlobalShortcut_win.cpp, src/mumble/MainWindow.cpp, src/mumble/MainWindow.h, src/mumble/Messages.cpp, src/mumble/UserModel.cpp, src/mumble/main.cpp, src/mumble/mumble.pro
=> Remove overlay related code if no-overlay option is used

src/mumble/AudioConfigDialog.cpp
=> Set the echo combo box to "off" before disabling it

src/mumble/AudioConfigDialog.cpp
Avoid infinite signal loop triggered by checking the value of the combo box -> setting the value of combo box -> checking the value of the combo box -> setting the value of combo box -> checking the value of the combo box -> setting the value of combo box...
=> Fixed infinite loop caused by #4215

src/murmur/ServerDB.cpp, src/murmur/ServerDB.h
=> Backport "Fix database encoding"

src/mumble/NetworkConfig.cpp
=> src/mumble/NetworkConfig.cpp: Added missing include

src/ACL.cpp, src/SSL.cpp, src/mumble/ConnectDialog.cpp, src/mumble/MainWindow.cpp, src/mumble/XMLTools.cpp, src/mumble/main.cpp, src/murmur/Meta.cpp, src/murmur/Register.cpp, src/murmur/Server.cpp, src/murmur/main.cpp, src/tests/Benchmark.cpp
This PR is about replacing stuff that has been deprecated in Qt 5.15
=> Replace deprecated constructs

src/mumble/TalkingUI.cpp
In #4306 a glitch in the TalkingUI was fixed that was associated with
session reuse by the server. As an additional fail-safe the respective
commit (bbfe736b133201c685ecc86dbbec5079aa458c18) also implemented a
quick check for whether the name of the user with a given ID is still
the same as the stored one for that user.
In #4325 however it was pointed out that this leads to the local user
being added to the TalkingUI every time it starts speaking. This is due
to the local user's name being written in bold meaning that it contains
HTML tag in the TalkingUI which are obviously not part of the actual
user name.
This commit fixes this issue by first stripping out any HTML tags from
the stored name before comparing it to the actual username.
Fixes #4325
=> FIX(talking-ui): Fix local user added multiple times

scripts/mumble-version.py
Until now the snapshot versions looked something like
`1.4.0~444~g4afab7c~snapshot`. They include the Mumble version which they
are a snapshot for at the beginning, then the revision number (the
amount of commits since the last tag in git's history), followed by the
latest commit's hash (prefixed by "g") and finally the word "snapshot".
The problem with this approach is that it requires knowledge of the git
history at least until the most recent tag. In addition to that it also
requires someone to think about moving the "tag-for-ci" that marks a
release-state in the master branch to be set on every release.
The history requirement is not an issue for a normal clone of the
repository but if someone (e.g. the CI) performs a shallow clone of the
repository, then the script fails.
In order to …
=> MAINT(snapshot-versions): Change snapshot version format 

scripts/travis-ci/before_install.bash, src/mumble/Overlay.cpp, src/mumble/Overlay.h
Backport of #4282 
Additionally this PR also fixes the MXE URLs used in the TravisCI script
=> Backport "Fix overlay"

.ci/azure-pipelines/main-pr.yml, .ci/azure-pipelines/main.yml
I accidentally forgot to do it in #4374 (no CI to remind me about it because it couldn't run due to the file being moved).
=> CI(azure-pipelines): fix template paths

src/mumble/CustomElements.cpp
=> Backport "FIX(ui): Make chatwidget max height >= than its minimum height"

src/murmur/Server.cpp
=> Backport "FIX(server): Packet size issues"

src/mumble/ServerHandler.cpp
=> Backport "FIX(client): Discard oversized UDP packets"

src/mumble/ACLEditor.ui
=> Backport "FIX(client, ui): ACLEditor not growing evenly"

scripts/updatetranslations.sh
The script now uses relative paths (in order to not include information
about the committer's file tree in the commit message.
Furthermore the pushd/popd was removed as we don't have to restore the
path in a shell script as these run in a sub-shell anyways and therefore
can't change the calling shell's pwd.
=> MAINT: Use rel paths in updatetranslations.sh

.ci/azure-pipelines/install-environment_linux.bash, .ci/travis-ci/before_install.bash, 3rdparty/pulseaudio/pulse/cdecl.h, 3rdparty/pulseaudio/pulse/channelmap.h, 3rdparty/pulseaudio/pulse/context.h, 3rdparty/pulseaudio/pulse/def.h, 3rdparty/pulseaudio/pulse/ext-stream-restore.h, 3rdparty/pulseaudio/pulse/format.h, 3rdparty/pulseaudio/pulse/gccmacro.h, 3rdparty/pulseaudio/pulse/introspect.h, 3rdparty/pulseaudio/pulse/mainloop-api.h, 3rdparty/pulseaudio/pulse/operation.h, 3rdparty/pulseaudio/pulse/proplist.h, 3rdparty/pulseaudio/pulse/sample.h, 3rdparty/pulseaudio/pulse/stream.h, 3rdparty/pulseaudio/pulse/subscribe.h, 3rdparty/pulseaudio/pulse/thread-mainloop.h, 3rdparty/pulseaudio/pulse/volume.h, src/mumble/CMakeLists.txt, src/mumble/PulseAudio.cpp, src/mumble/PulseAudio.h
This effectively removes it as dependency.
Ref: #3794
=> Load PulseAudio at runtime

src/mumble/Messages.cpp
PR #4487 introduced a regression in form of a failing assertion in case
a user has stored volume adjustments for a ChannelListener in its DB. In
that case the client would crash as soon as the server-connection has
synchronized.
The issue was caused by a change-event being emitted before the
ChannelListener officially existed. The fix is to simply not send these
events in the first place.
=> FIX(client): Assertion-error for ChannelListeners

plugins/mumble_plugin_linux.h
Thanks to @ZeroAbility for the idea.
=> REFAC(client): move common stuff from getExportedSymbol() to a template function

Dockerfile
The change fixes this issue: https://github.com/mumble-voip/mumble/issues/4514
=> BUILD(docker): Updated Dockerfile to use CMake

overlay_gl/init_unix.c
Tested on Linux and FreeBSD.
Fixes https://bugs.gentoo.org/527504.
@dscharrer
=> Overlay: improve find_odlsym(), add support for DT_GNU_HASH

plugins/CMakeLists.txt, plugins/HostLinux.cpp, plugins/HostLinux.h, plugins/HostWindows.cpp, plugins/HostWindows.h, plugins/Process.cpp, plugins/Process.h, plugins/ProcessLinux.cpp, plugins/ProcessLinux.h, plugins/ProcessWindows.cpp, plugins/ProcessWindows.h, plugins/mumble_plugin_linux.h, plugins/mumble_plugin_utils.h, plugins/se/CMakeLists.txt, plugins/se/client.h, plugins/se/common.h, plugins/se/engine.h, plugins/se/se.cpp
For now only `se` (Source Engine) is converted to use the new classes.
=> FEAT/REFAC(plugins): Add classes for process-related functions

scripts/vcpkg/get_mumble_dependencies.ps1
=> BUILD: Support working directories other than repository root

Dockerfile
MAINT: Potentially Reduce Docker Container Size
Add "--no-install-recommends" and "rm -rf /var/lib/apt/lists/*"
=> MAINT: Potentially Reduce Docker Container Size

docs/dev/build-instructions/build_linux.md
Implements suggestions in #4598
=> DOCS: Dependencies for Cent OS 8

src/mumble/TalkingUI.cpp
If the font size for the TalkingUI was set to something different than
100%, the TalkingUI's icon sizes would be incorrect.
This is due to the icon size being initialized to the widget's
font-size. This doesn't seem to have been affected by inherited
StyleSheets right after construction and therefore they'd always report
the default font-size.
This commit fixes this by explicitly setting the icon-size after an
entry is created.
In this context the method of calculating the current line height has
been overhauled as well as this would also depend on when the respective
function was called. This is probably due to Qt not having stored the
display's DPI correctly yet and thus the conversion from point size to
pixel size is flawed.
=> FIX(client, talking-ui): Icon size initialized incorrectly

docs/dev/build-instructions/README.md, docs/dev/build-instructions/faq.md
Signed-off-by: Tobias Gerold <tobias@g3ro.eu>
=> DOCS: Added notes how to build specific versions/commits.

installer/ClientInstaller.cs
=> BUILD(installer): Include g15-helper

Dockerfile
MAINT(docker): added missing sql driver
Closes #4755
=> MAINT(docker): added missing sql driver

.github/pull_request_template.md
It seems that nobody read the comment that was inserted into the PR.
Thus this was now changed to a checkbox that will be visible after
having created the PR.
=> MAINT(github): Update PR template

src/mumble/CMakeLists.txt
=> BUILD(cmake): Add sndfile library/target name

.ci/azure-pipelines/install-environment_windows.ps1
See commit descriptions for more details
=> CI: Make windows scripts more robust

CMakeLists.txt, src/licenses.h, src/mumble/About.cpp, src/mumble/CMakeLists.txt, src/mumble/mumble_en.ts
See commits for descriptions
The first commit is unrelated but something that I noticed along the way
=> FIX(client): About dialog improvements

Dockerfile
In doing so the current state of the Dockerfile on the master
branch has been used as a template.
Fixes #4813
=> MAINT(docker): Make Dockerfile working again

src/murmur/main.cpp
On macOS, it is observed that Ctrl-C terminates murmur abruptly
without a graceful shutdown. And the UDP port it used just keeps
occupied even after murmur is terminated.
This fix sets up signal handlers to ensure a graceful shutdown
before quitting.
=> FIX(server): Ctrl-C leaves UDP port open.

docs/dev/ExtendingTheIceInterface.md
In order to help document & maintain tribal knowledge, include a few snippets regarding testing Ice interface changs.
=> DOCS: Extending Ice interface example

plugins/amongus/Game.cpp, plugins/amongus/structs.h
https://store.steampowered.com/news/app/945360/view/3050597789009577255
=> FIX(positional-audio): Update Among Us plugin to work with v2021.3.5s

.gitignore
=> MAINT: Ignore local VS and VSCode file and folders

plugins/amongus/structs.h
https://store.steampowered.com/news/app/945360/view/3021326294554201922
=> FIX(positional-audio): Update Among Us plugin to work with v2021.3.31.3s

scripts/updatetranslations.py
=> MAINT: Fix endless loop in translation update script

CODE_OF_CONDUCT.md
=> MAINT: Add Code of Conduct

.appveyor.yml, .ci/azure-pipelines/main-pr.yml, .ci/azure-pipelines/main.yml, .ci/azure-pipelines/steps_windows.yml, .ci/build_windows.bat, .ci/install-environment_windows.ps1
https://about.signpath.io/open-source
https://about.signpath.io/documentation/build-system-integration#appveyor
=> CI: Add AppVeyor configuration for SignPath (Windows)

src/mumble/CMakeLists.txt, src/mumble/mumble_sq.ts
As was requested on Weblate by a potential contributor two days ago.
=> TRANSLATION: Add new language Albanian (sq)

src/ProcessResolver.cpp, src/ProcessResolver.h, src/mumble/PluginManager.cpp
While I was at it, I refactored the class to use smart pointers afterwards.
Fixes #4975
=> FIX(client): Mismatched delete in ProcessResolver 

docs/dev/build-instructions/build_linux.md, docs/dev/build-instructions/build_macos.md
=> DOCS: Added info about Poco dependency

src/mumble/Markdown.cpp
If one was to send a link like
"http://localhost/?var1=foo&var2=bar&var3=baz" either as-is or as a
markdown-style link ("[name](<url>)"), the "&" character in the link
would get escaped as "&amp;".
For displaying purposes this is fine, as the Mumble client re-interprets
these escape sequences before rendering them to the user. The same
escaping was done in the surrounding <a> HTML element's href
specification. This lead to invalid URLs being used as link targets.
Therefore this commit makes sure that the href content of an <a> HTML
element will be un-escaped before inserting into the HTML structure
(thus preserving the original characters in the href specification).
Fixes #4999
=> FIX(client): Don't escape characters in URL targets

src/mumble/AudioOutput.cpp, src/mumble/Global.cpp, src/mumble/Global.h, src/mumble/ListenerLocalVolumeDialog.cpp, src/mumble/MainWindow.cpp, src/mumble/TalkingUI.cpp, src/mumble/UserModel.cpp, src/mumble/main.cpp, src/murmur/Messages.cpp, src/murmur/Server.cpp
=> FORMAT: Run clang-format 10 on all source files

COMMIT_GUIDELINES.md, macx/scripts/osxdist.py, scripts/commitMessage/CommitMessage.py, scripts/generateChangelog.py
=> Backport "BUILD(macos): Fix package script failing"

.github/workflows/check_commit_style.py, .github/workflows/pr-checks.yml
=> Backport "CI: Fix PR checks for backports"

3rdparty/celt-0.7.0-build/CMakeLists.txt, plugins/PluginComponents_v_1_0_x.h, src/CMakeLists.txt, src/mumble/GlobalShortcut_unix.h
=> Backport "BUILD: Fixes for Ubuntu 20.04 ppa build"

src/mumble/mumble_he.ts, src/mumble/mumble_ko.ts, src/mumble/mumble_pl.ts, src/mumble/mumble_pt_BR.ts
=> Backport "Translations update from Weblate"

docs/DeveloperConsole.md
=> DOCS: Fix typo in developer console description

docs/dev/build-instructions/README.md
=> DOCS: Mention Cpp14 requirement

src/murmur/main.cpp
In short: The lock file(s) for the SQLite DB were being discarded as
soon as fork() was called on Unix systems. Thus the DB connection was a
ghost connection and accessing the DB from somewhere else (e.g. CLI)
would likely cause DB corruption because of missing locks.
Because this only happened when calling fork(), Debug builds are
unaffected since they always run in foreground mode which never calls
fork().
The underlying issue here is that an open SQLite connection should
have a read POSIX lock on the database file. Because we were calling
fork() and then _exit() **after** taking out these locks (which was done
when creating the ServerDB object), the locks were being released.
POSIX locks are super easy to get wrong. This is a nice rant about how
they stink: …
=> FIX(server, unix): DB corruption due to missing locks

src/murmur/main.cpp
=> Backport "FIX(server, unix): DB corruption due to missing locks"

src/mumble/mumble_de.ts, src/mumble/mumble_en_GB.ts, src/mumble/mumble_fr.ts, src/mumble/mumble_hu.ts, src/mumble/mumble_ko.ts, src/mumble/mumble_nl.ts, src/mumble/mumble_pl.ts, src/mumble/mumble_ru.ts, src/mumble/mumble_tr.ts, src/mumble/mumble_zh_CN.ts
=> Backport "Translations update from Weblate" to 1.4.x

src/mumble/Settings.cpp
=> Backport "FIX(pipewire): Do not initialize stream with 0 channels"

README.md, docs/dev/plugins/Bundling.md, docs/dev/plugins/CreatePlugin.md, docs/dev/plugins/Debugging.md, docs/dev/plugins/LanguageBindings.md, docs/dev/plugins/MumbleAPI.md, docs/dev/plugins/PluginAPI.md, docs/dev/plugins/PluginLifecycle.md, docs/dev/plugins/PositionalAudioPlugin.md, docs/dev/plugins/README.md, docs/dev/plugins/ResourceManagement.md, docs/dev/plugins/Versioning.md
=> DOCS: Document new plugin system

docs/dev/plugins/PositionalAudioPlugin.md
=> DOCS(plugins): Fix missing pointer star in example

README.md, docs/dev/plugins/Bundling.md, docs/dev/plugins/CreatePlugin.md, docs/dev/plugins/Debugging.md, docs/dev/plugins/LanguageBindings.md, docs/dev/plugins/MumbleAPI.md, docs/dev/plugins/PluginAPI.md, docs/dev/plugins/PluginLifecycle.md, docs/dev/plugins/PositionalAudioPlugin.md, docs/dev/plugins/README.md, docs/dev/plugins/ResourceManagement.md, docs/dev/plugins/Versioning.md
- DOCS: Document new plugin system (#5096)
=> Backport "DOCS: Document new plugin system (#5096)" to 1.4.x

src/murmur/Messages.cpp
In eabfbab403e6ba10219c262518899db5a60d0c1e the assignment of the
uiSession variable of any given client was delayed into the
Server::msgAuthenticated function in order to prevent non-Mumble
connections to be counted as users.
However the assignment of the session ID was moved so far down that
there is now previous code that already depends on its value and is now
using an uninitialized (or at least wrong) value for the session ID.
This commit fixes this by assigning the session ID very early in the
Server::msgAuthenticated function, making sure that the code before it
does not reference the session ID already.
This bug could have had all kinds of side-effects but one of them was
that users were always presented with the "Unable to find matching CELT
codecs with other clients." message …
=> FIX(server): uiSession being used before assignment

src/murmur/Messages.cpp
- FIX(server): uiSession being used before assignment (#5111)
=> Backport "FIX(server): uiSession being used before assignment (#5111)" to 1.4.x

plugins/amongus/Game.cpp, plugins/amongus/Game.h, plugins/amongus/amongus.cpp
Full functionality is retained.
=> REFAC(positional-audio): Use new plugin API in Among Us plugin

.github/workflows/code-ql.yml
=> CI: Add CodeQL analysis

plugins/ProcessLinux.cpp
Our Source Engine plugin retrieves the interfaces on Linux through `s_pInterfaceRegs`, an exported symbol.
Left 4 Dead 2 just received a big update and the binaries don't have the `DT_HASH` table anymore.
As a result, the plugin was not finding the symbol anymore.
This is basically a follow-up to #4534, which implemented support for `DT_GNU_HASH` in the overlay code.
=> FEAT(positional-audio): Add support for DT_GNU_HASH, to locate exported symbols

plugins/amongus/structs.h
https://steamcommunity.com/games/945360/announcements/detail/3055110270127094252
=> FIX(positional-audio): Update Among Us plugin to work with v2021.6.15s

plugins/se/engine.h
This pull request makes the plugin work again with the Linux version of the game.
The game update didn't break support for the Windows version.
https://steamcommunity.com/games/L4D2/announcements/detail/4625740823862061052
=> FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.1.3

src/murmur/MurmurIce.cpp
The implementation for the Ice setACL function did not take a write lock
even though it writes to objects that are owned by the main thread
(thereby violating the synchronization scheme in the server code).
Due to it deleting Group objects this is strongly suspected to have
caused a Segfault crash of the server when the voice thread would check
whether a user has permission in a channel while the ACL for that is not
cached. The Segfault then occurs in Group::isMember when dereferencing
the Group pointer (which got deleted in the Ice function).
=> FIX(server): Missing lock in Ice-call setACL

src/murmur/MurmurIce.cpp
- FIX(server): Missing lock in Ice-call setACL (#5130)
=> Backport "FIX(server): Missing lock in Ice-call setACL (#5130)" to 1.4.x

src/murmur/ServerDB.cpp
=> Backport "FIX(server): Also INSERT queried value"

src/mumble/Log.cpp
=> FEAT(client): Allow magnet-URIs for links

plugins/gtav/CMakeLists.txt, plugins/gtav/Game.cpp, plugins/gtav/Game.h, plugins/gtav/gtav.cpp
This updates the GTA 5 positional audio plugin to work with the latest Steam version and also ports the whole plugin to the new Plugin API.
=> REFAC(positional-audio): Port GTA5 to new Plugin API

plugins/gtav/CMakeLists.txt, plugins/gtav/Game.cpp, plugins/gtav/Game.h, plugins/gtav/gtav.cpp
=> Backport "FEAT(positional-audio): Update & port GTA5 to new Plugin API"

Dockerfile
=> MAINT(docker): added frequently used sql drivers

plugins/amongus/structs.h
https://steamcommunity.com/games/945360/announcements/detail/2994312940971770701
=> FIX(positional-audio): Update Among Us plugin to work with v2021.6.30s

plugins/se/client.h
https://store.steampowered.com/news/app/550/view/2990935241286354880
https://store.steampowered.com/news/app/550/view/2990936690600094237
=> FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.2.0

src/mumble/mumble_cs.ts, src/mumble/mumble_de.ts, src/mumble/mumble_en_GB.ts, src/mumble/mumble_eo.ts, src/mumble/mumble_fi.ts, src/mumble/mumble_fr.ts, src/mumble/mumble_he.ts, src/mumble/mumble_ko.ts, src/mumble/mumble_lt.ts, src/mumble/mumble_no.ts, src/mumble/mumble_oc.ts, src/mumble/mumble_pl.ts, src/mumble/mumble_pt_BR.ts, src/mumble/mumble_ru.ts, src/mumble/mumble_si.ts, src/mumble/mumble_sv.ts, src/mumble/mumble_zh_CN.ts
=> TRANSLATION: Backport translations

CODING_GUIDELINES.md
=> MAINT: Add coding guidelines

docs/dev/build-instructions/build_linux.md
=> DOCS(build): Add info about RELEASE_ID

README.md
As per [#3688](https://github.com/mumble-voip/mumble/issues/3688#issuecomment-896964297).
=> DOCS(Readme): Add building Docker image from source.

Dockerfile
=> MAINT(Dockerfile): Backport most recent improvements

src/mumble/PluginConfig.cpp, src/mumble/PluginManager.cpp, src/mumble/ServerHandler.cpp
=> Backport "BUILD(client): Fix compile errors without manual plugin"

src/murmur/MurmurIce.cpp
Some of the ICE functions were writing data without holding the
respective lock.
=> FIX(server, ice): Missing locks in ICE functions

src/mumble/PluginManager.cpp
Before when installing Mumble (on Windows) it could happen that when
viewing the plugin settings, every plugin would be listed multiple
times. This was caused by duplicate entries in the plugins search path
used by Mumble. The duplicates arose from using non-canonical paths in
the set for storing the search paths which allowed to add the same
directory twice by describing its path slightly differently.
This commit makes sure that all paths are first canonicalized before
they are added to the set, such that only distinct paths are maintained.
Fixes #5271
=> FIX(client): Duplicate plugin entries

src/mumble/PluginManager.cpp
- FIX(client): Duplicate plugin entries (#5325)
=> Backport "FIX(client): Duplicate plugin entries (#5325)" to 1.4.x

src/murmur/MurmurIce.cpp
- FIX(server, ice): Missing locks in ICE functions (#5308)
=> Backport "FIX(server, ice): Missing locks in ICE functions (#5308)" to 1.4.x

docs/dev/plugins/PluginAPI.md
=> DOCS(api): Fix typo

src/mumble/PluginManager.cpp, src/mumble/PluginManager.h
=> Backport "FIX(client): Fix crash & deadlock on plugin link/unlink"

src/murmur/Messages.cpp
Inside Server::msgUserState there are a couple of places that implement
the functionality of a client making modifications to itself (e.g.
self-mute). In these cases, uSource == pDstServerUser. Therefore
functionality-wise, it doesn't matter which of these variables the
implementation uses. However, there is a semantic differences and as
such this commit refactors these code parts to perform the actions on
pDstServerUser instead of uSource in order to make clear that
pDstServerUser is always the user to whom the action is applied.
=> REFAC(server): Improve semantics in msgUserState

src/murmur/MurmurIce.cpp
This commit attempts to narrow down the lock scopes in the Ice
implementations. It also removed a few locks that were taken before
making a DB connection.
This could potentially take a significant amount of time (when taking
into account that during that time the voice thread is pretty stalled)
and also any DB connection mustn't be performed from outside the main
thread anyway. Therefore, these function calls should be "implicitly
synchronized" (only occur from a single thread).
=> FIX(server): Narrow down lock scopes

plugins/amongus/Game.cpp, plugins/amongus/Game.h, plugins/amongus/amongus.cpp, plugins/amongus/structs.h
https://store.steampowered.com/news/app/945360/view/3097907147121066176
https://store.steampowered.com/news/app/945360/view/3097908416252836584
=> FIX(positional-audio): Update Among Us plugin to work with v2021.11.9.5s

plugins/amongus/Game.cpp, plugins/amongus/Game.h, plugins/amongus/amongus.cpp, plugins/amongus/structs.h
Backports the current state of the `among us` plugin to 1.4.x
=> Backport "FIX(positional-audio): Update Among Us plugin to work with v2021.11.9.5s"

src/murmur/MurmurIce.cpp
- FIX(server): Narrow down lock scopes (#5357)
=> Backport "FIX(server): Narrow down lock scopes (#5357)" to 1.4.x

plugins/amongus/structs.h
https://store.steampowered.com/news/app/945360/view/5918290951261475310
=> FIX(positional-audio): Update Among Us plugin to work with v2021.12.15s (1421)

plugins/ProcessBase.cpp, plugins/ProcessBase.h, plugins/ProcessLinux.cpp, plugins/ProcessLinux.h, plugins/ProcessWindows.cpp, plugins/ProcessWindows.h, plugins/amongus/CMakeLists.txt, plugins/cod2/CMakeLists.txt, plugins/cod2/cod2.cpp, plugins/gtav/CMakeLists.txt, plugins/se/CMakeLists.txt, plugins/se/se.cpp
- BUILD(windows): Fix debug build (#5374)
=> Backport "BUILD(windows): Fix debug build (#5374)" to 1.4.x

src/mumble/mumble_de.ts, src/mumble/mumble_el.ts, src/mumble/mumble_en_GB.ts, src/mumble/mumble_eo.ts, src/mumble/mumble_es.ts, src/mumble/mumble_eu.ts, src/mumble/mumble_fi.ts, src/mumble/mumble_it.ts, src/mumble/mumble_ko.ts, src/mumble/mumble_nl.ts, src/mumble/mumble_oc.ts, src/mumble/mumble_pl.ts, src/mumble/mumble_pt_BR.ts, src/mumble/mumble_ru.ts, src/mumble/mumble_sq.ts, src/mumble/mumble_tr.ts, src/mumble/mumble_zh_CN.ts
=> TRANSLATION: Backport translations from master

src/mumble/mumble.plist.in, src/murmur/murmur.plist.in
=> Backport "MAINT: Change app ID in plist files"

docs/DockerCompose.md
=> Improve Docker Compose documentation

src/ChannelListenerManager.cpp, src/ChannelListenerManager.h, src/mumble/Database.cpp, src/mumble/Database.h, src/mumble/MainWindow.cpp, src/mumble/Messages.cpp
=> Backport "CHANGE(client): Remove channel listener persistence"

.ci/azure-pipelines/build_linux.bash, .ci/azure-pipelines/build_macos.bash, .ci/build_windows.bat, docs/dev/build-instructions/find_build_number.md, scripts/mumble-build-number.py, scripts/mumble-version.py
=> MAINT: Add script to fetch build number

.appveyor.yml
=> MAINT: Change build-number token for AppVeyor

src/ProcessResolver.cpp
The code remains unchanged on other platforms.
=> BUILD(client): Plugin Framework: Fix build on NetBSD and OpenBSD

.ci/azure-pipelines/checkDocs.bash
These are much easier to read and match default behaviour in git.
=> CI(azure): checkDocs: Generate unified diffs

.github/workflows/pr-checks.yml
=> CI: Update clang-format action

docs/DockerCompose.md
=> DOCS(docker): Document Docker Compose '--build' switch.

README.md, docs/dev/TheMumbleSourceCode.md
=> DOCS: General intro to Mumble's source code

docs/dev/build-instructions/cmake_options.md, src/mumble/CMakeLists.txt
=> Backport "BUILD(client): RNNoise: Support linking against the system library"

docs/dev/build-instructions/build_linux.md
=> DOCS: Add missing build dependency

plugins/amongus/structs.h
https://store.steampowered.com/news/app/945360/view/3121564363609006624
=> FIX(positional-audio): Update Among Us plugin to work with v2022.3.29s (1864)

scripts/vcpkg/get_mumble_dependencies.ps1, scripts/vcpkg/get_mumble_dependencies.sh
=> MAINT(vcpkg): Install Qt's MySQL and PostgreSQL plugins

src/murmur/ServerDB.cpp, src/murmur/ServerDB.h, src/murmur/main.cpp
=> FIX(server): Improve rememberchannelduration compare logic

src/mumble/Markdown.cpp, src/mumble/PluginManifest.cpp, src/mumble/QtWidgetUtils.cpp, src/mumble/QtWidgetUtils.h, src/mumble/SearchDialog.cpp
See individual commits for details
Fixes #5606
=> BUILD(client): Fix various issues

plugins/gtav/Game.cpp, plugins/gtav/gtav.cpp
This works with the latest Steam release again.
=> FIX(positional-audio): Update GTAV plugin to version 1.59.2612

docs/dev/build-instructions/build_linux.md
=> DOCS(build_linux): Added dependency install instructions for OpenSUSE Tumbleweed

plugins/HostLinux.h, plugins/HostWindows.h, plugins/ProcessBase.cpp, plugins/ProcessBase.h, plugins/amongus/Game.cpp, plugins/amongus/Game.h, plugins/gtav/Game.cpp, plugins/gtav/Game.h, plugins/gtav/gtav.cpp, plugins/gtav/structs.h, plugins/mumble_legacy_plugin.h
- [Merge PR #5704: FEAT/REFAC(positional-audio): Rewrite GTAV plugin, define "procid_t" to "uint64_t"](https://github.com/mumble-voip/mumble/pull/5704)
=> Backport "FEAT/REFAC(positional-audio): Rewrite GTAV plugin, define "procid_t" to "uint64_t"" to 1.4.x

src/mumble/mumble_sk.ts
=> TRANSLATION: Add Slovak (sk) template

src/murmur/Server.cpp
- [Merge PR #5769: FIX(server): Update suppress state on ACL change](https://github.com/mumble-voip/mumble/pull/5769)
=> Backport "Merge PR #5769: FIX(server): Update suppress state on ACL change" to 1.4.x

src/mumble/MainWindow.cpp
=> DOCS: Fix invalid URL in source comment

src/mumble/Log.cpp
- [Merge PR #5820: FIX(client, ui): resolve log text scaling issues](https://github.com/mumble-voip/mumble/pull/5820)
=> Backport "Merge PR #5820: FIX(client, ui): resolve log text scaling issues" to 1.4.x

.ci/azure-pipelines/main-pr.yml, .ci/azure-pipelines/main.yml
=> CI(azure): Update to Ubuntu 20.04

.github/workflows/release_dispatch.yml
=> CI(github-actions): Fix workflow file syntax

docs/dev/build-instructions/cmake_options.md, src/ProcessResolver.cpp, src/mumble/AudioWizard.cpp, src/mumble/CMakeLists.txt
=> Backport "BUILD: BSD fixes"

.github/workflows/winget.yml
=> CI(github-actions): Use versioned tags for winget-releaser

src/mumble/Log.cpp
This commit removes the additional gaps within the chat. The gaps were introduced by Qt's block-padding between frames. With this commit, the block *after* the last chat message is set to invisible.
The previous approach of a very small `fontPoinzSize()` within the `blockCharFormat()` unfortunately didn't work on Windows. This variant should work on both Windows and Linux; unfortunately, I was only able to test it on Windows.
Fixes #5886.
Before the patch (on 78350de057a75c062e2cc314cf2df675517712e6):
After the patch:
=> FIX(client, ui): remove gaps within chat

src/mumble/MainWindow.cpp
This commit addresses two issues within the 'updateMenuPermissions' method:
First, the target selection introduced in be7ad39fd was suffering from the same problem as described in #3090 where selected tree items were not preferred for determining targets. This issue caused the chat bar to be erroneously disabled in certain situations, for example when connecting to a channel with "Text Message" permission disabled and switching to a different by left-clicking.
The second issue is an oversight in 441d06f6d where the 'Use selected item as the chat bar target' option was introduced. The permission check in 'updateMenuPermissions' was not updated to take the new option into account and therefore always used the selected target for the permission query independent of the state of the option. …
=> FIX(client): Fix target and permission selection in updateMenuPermissions

src/mumble/JSONSerialization.cpp
=> BUILD(cmake): Fix build without RNNoise

src/mumble/mumble_en_GB.ts, src/mumble/mumble_hi.ts
=> TRANSLATION: Added Hindi

src/mumble/mumble_hi.ts
=> TRANSLATION: Update translation files

src/ACL.cpp, src/Group.cpp, src/Group.h, src/murmur/Server.cpp
And while we're at it, give it a different name that better describes what this function is actually doing (spoiler: it is not only checking whether the given user is part of the specified group).
=> REFAC(server): Improve readability of Group::isMember

.backportrc.json, .github/workflows/backport.yml
=> MAINT: Update backport config

.appveyor.yml
=> CI(appveyor): Update to latest image version

docs/dev/build-instructions/cmake_options.md, src/CMakeLists.txt, src/mumble/CMakeLists.txt, src/mumble/Log_unix.cpp, src/murmur/CMakeLists.txt, src/murmur/DBus.h, src/murmur/ServerDB.cpp
=> BUILD(cmake): Always use DBus on Linux(-like) systems

.appveyor.yml
=> CI(appveyor): Fix vcvars path

.github/workflows/build.yml, .github/workflows/code-ql.yml
=> CI(github-actions): Avoid duplicate runs

src/mumble/PulseAudio.cpp
When applying the settings, Mumble will restart the AudioSystems for input and output. During this time, if a PulseAudio write_callback happens, Mumble will write nothing and just return. However, this behavior will cause PulseAudio to never request a callback again, disabling audio output for the user until mumble is restarted. ( See: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1132 )
This commit instead changes the code to return an empty buffer in that case instead, such that PulseAudio will continue to send Mumble write_callbacks and keep audio output intact.
Special thanks to GitHub User @WGH- who found out about this fix and originally posted the patch in the Mumble issue tracker.
Fixes #4883
Co-Authored-By: WGH <wgh@torlan.ru>
=> FIX(client): Send empty buffer in PA write_callback instead of nothing

src/mumble/PulseAudio.cpp
- [Merge PR #6051: FIX(client): Send empty buffer in PA write_callback instead of nothing](https://github.com/mumble-voip/mumble/pull/6051)
=> Backport "Merge PR #6051: FIX(client): Send empty buffer in PA write_callback instead of nothing" to 1.5.x

src/murmur/Messages.cpp
The ACL for group 'auth' depends on the user (db) id. Previously, code paths using checks for 'auth' ACLs in msgAuthenticate would not work correctly, because the ACL cache still contained a state where the id was not set.
This commit adds cache invalidation after the user id is set, allowing to correctly apply the 'auth' ACL in later parts of msgAuthenticate.
Fixes #5907
=> FIX(server): Add ACL cache invalidation after user id is set

src/murmur/Messages.cpp
- [Merge PR #6044: FIX(server): Add ACL cache invalidation after user id is set](https://github.com/mumble-voip/mumble/pull/6044)
=> Backport "Merge PR #6044: FIX(server): Add ACL cache invalidation after user id is set" to 1.5.x

src/mumble/mumble_de.ts, src/mumble/mumble_el.ts, src/mumble/mumble_fi.ts, src/mumble/mumble_fr.ts, src/mumble/mumble_nl.ts, src/mumble/mumble_no.ts, src/mumble/mumble_pl.ts, src/mumble/mumble_pt_BR.ts, src/mumble/mumble_pt_PT.ts, src/mumble/mumble_sv.ts, src/mumble/mumble_tr.ts, src/mumble/mumble_uk.ts, src/mumble/mumble_zh_CN.ts
=> TRANSLATION: Backport translation updates

README.md
=> DOCS(readme): Mention SignPath

src/mumble/AudioConfigDialog.cpp, src/mumble/Settings.h
See individual commits for what has been changed
Fixes #6132
=> FEAT(client): Positional audio improvements

src/mumble/AudioOutputSpeech.cpp
Elements of a vector were failing to be cleared correctly which created performance issues.
A nuance with speex was also causing the library to fail to call a destroy callback.
Fixes #6150
=> FIX(client): Performance degradation around speex

src/mumble/AudioOutputSpeech.cpp
- [Merge pull request #6154 from nJ3ahxac/fix-6150](https://github.com/mumble-voip/mumble/pull/6154)
=> Backport "Merge pull request #6154 from nJ3ahxac/fix-6150" to 1.5.x

.appveyor.yml, .ci/azure-pipelines/main-pr.yml, .ci/azure-pipelines/main.yml
=> MAINT: Update Windows build env to latest version

docs/dev/build-instructions/build_static.md
=> DOCS: Change encoding to UTF-8 & clean up error msg in FAQ

src/murmur/AudioReceiverBuffer.h, src/tests/TestAudioReceiverBuffer/TestAudioReceiverBuffer.cpp
The factor difference cap works for larger volume adjustments, but for low volumes, the difference can easily exceed 5dB (from -24dB and lower, a difference of 0.05 in the factor is a difference of more than 5dB).
=> FIX(server): Cap receiver ranges at a vol. diff of 5dB

scripts/generateIceWrapper.py
=> MAINT: Fix invalid escape sequences in generateIceWrapper.py

src/mumble/CMakeLists.txt
=> BUILD(client): Fix project attempting to call "cscs.exe" on Linux

.cirrus.yml
=> CI(cirrus): Update FreeBSD image

src/murmur/AudioReceiverBuffer.h, src/tests/TestAudioReceiverBuffer/TestAudioReceiverBuffer.cpp
- [Merge PR #6267: FIX(server): Cap receiver ranges at a vol. diff of 5dB](https://github.com/mumble-voip/mumble/pull/6267)
=> Backport "Merge PR #6267: FIX(server): Cap receiver ranges at a vol. diff of 5dB" to 1.5.x

docs/dev/build-instructions/build_linux.md
Fixes https://github.com/mumble-voip/mumble/issues/6204
=> DOCS(build): Update Ubuntu package names 

README.md
=> MAINT: Fixed spelling and grammar in README.md

src/mumble/main.cpp
This commit refactors the code repeated in the main.cpp file. Three connect functions were called with same parameters.
Co-Authored-by: Abdullah Ömer Yamaç aomeryamac@gmail.com
=> REFAC(client): Refactor the code repeated in the main.cpp

scripts/generate_changelog.py
The script had the following issues:
* Typo in the match regex string
* Wrong enumeration of match groups
* No support for commits without merge commit
I also added a hotfix for backport commits which
did not conform to the pattern (sorry)
=> MAINT: Fix generate changelog script

src/mumble/GlobalShortcutButtons.cpp
This commit makes the shortcut configuration dialog a modal window. It also explicitly searches for a parent QDialog, such that the window can be centered over the Mumble application instead of randomly out of bounds of the screen. (This is most likely only necessary because of a bug in Qt, but Qt is a pain to debug)
Fixes #5024
=> FIX(client): Improve handling of the GlobalShortcutButtons dialog

src/mumble/GlobalShortcutButtons.cpp
- [Merge PR #6443: FIX(client): Improve handling of the GlobalShortcutButtons dialog](https://github.com/mumble-voip/mumble/pull/6443)
=> Backport "Merge PR #6443: FIX(client): Improve handling of the GlobalShortcutButtons dialog" to 1.5.x

.ci/azure-pipelines/install-environment_linux.bash, .ci/azure-pipelines/main-pr.yml, .ci/azure-pipelines/main.yml, .github/workflows/backport.yml, .github/workflows/build.yml, .github/workflows/code-ql.yml, .github/workflows/pr-checks.yml, .github/workflows/release_dispatch.yml, .github/workflows/stale_issues.yml
=> MAINT(ci): Various maintenance work related to CI configs

.github/workflows/backport.yml
=> MAINT(ci): Don't run backport action on backport PRs

.github/workflows/winget.yml
=> Update winget-releaser to latest

docs/dev/build-instructions/README.md, docs/dev/build-instructions/build_linux.md
=> DOCS: Simplify build steps on Linux

.github/workflows/backport.yml
=> CI(backport): Fix workflow file

.github/workflows/backport.yml
=> CI(backport): Fix backport action

.github/workflows/backport.yml
=> CI(backport): Make label checker happy

README.md
=> MAINT(readme): Update Docker usage instructions

.github/workflows/backport.yml
=> CI(backport): Add debug output

.github/workflows/backport.yml
=> CI(backport): Refine label checker action

.github/workflows/backport.yml
=> CI(backport): Fix label checker

.github/workflows/backport.yml
=> CI(backoprt): Fix workflow file

.github/workflows/backport.yml
=> CI(backport): Fix label checker version

src/mumble/BanEditor.cpp, src/mumble/PluginUpdater.cpp, src/mumble/PluginUpdater.h, src/mumble/SocketRPC.cpp, src/mumble/UserListModel.cpp, src/murmur/Messages.cpp, src/murmur/ServerDB.cpp
=> FIX(client, server): Fix build with Qt 6.8

.cirrus.yml
=> CI(cirrus): Update to FreeBSD 14.2

src/mumble/LookConfig.cpp
=> FIX(Client): bug with talking UI options

src/mumble/MainWindow.cpp, src/mumble/MainWindow.h, src/mumble/Messages.cpp
=> Backport "Merge PR #6748: FIX(client): Update chat bar if selected channel target state is modified" to 1.5.x

.ci/azure-pipelines/release_windows.bat, CMakeLists.txt, installer/ClientInstaller.cs, installer/MumbleInstall.cs, installer/ServerInstaller.cs, installer/Theme.xml, src/mumble/CMakeLists.txt, src/murmur/CMakeLists.txt
- [Merge PR #6789: FEAT(installer): Bundle C++ redistributables](https://github.com/mumble-voip/mumble/pull/6789)
=> Backport "Merge PR #6789: FEAT(installer): Bundle C++ redistributables" to 1.5.x

src/tests/TestSSLLocks/TestSSLLocks.cpp
=> Backport "FIX(tests): Reduce the amount of rounds in TestSSLLocks"

.appveyor.yml, .ci/azure-pipelines/main-pr.yml, .ci/azure-pipelines/main.yml
=> CI: Update build environment

src/CMakeLists.txt, src/MumbleProtocol.cpp, src/MumbleProtocol.h, src/mumble/GlobalShortcut_win.h
cherry-picked the commits from #6924 and #6918
=> Backport "Merge PR #6924: REFAC(client,server): Remove GSL dependency" to 1.5.x
