src/mumble/About.cpp

Backport "FIX(client): Make link in about dialog clickable again"

---

src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/mumble_en.ts

If someone wants to select or deselect all messages in a given column,
they had to do that manually. With this commit a new header row is
introduced that allows for easily selecting or deselecting all entries in
a column.
Fixes #4464
Screenshot:

FEAT(client,ui): Add "select all" for messages

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioConfigDialog.h
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioInput.ui
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/mumble_en.ts

This PR does the following:
* It disables the Speex noise canceller when RNNoise is enabled as per https://github.com/mumble-voip/mumble/issues/4181
* It moves RNNoise after the echo canceller so that the input DSP chain is always Input -> Resampler -> Echo cancel -> Noise cancel -> Additional filters -> VAD -> Encoder as per https://github.com/mumble-voip/mumble/issues/4181
* It adds provision for disabling the noise canceller altogether, going in the direction of https://github.com/mumble-voip/mumble/issues/3323
Since I did not use RNNoise before, can someone who really likes RNNoise test this branch and see if it works just as well for his/her use case?
-----
The Windows installer containing the changes of this PR: 
[WindowsInstaller.zip](https://github.com/mumble-voip/mumble/files/4808 …

Streamline noise cancel chain

---

overlay_gl/CMakeLists.txt
src/mumble/CMakeLists.txt
src/murmur/CMakeLists.txt

On Unix-systems (Linux & Mac) we now also install our man-files when
the user invokes the generated install target.
Fixes #4472

BUILD(cmake): Also install man files

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat
.ci/travis-ci/script.bash
.cirrus.yml
.gitignore
CMakeLists.txt
cmake/os.cmake
src/CMakeLists.txt
src/mumble/CMakeLists.txt

We used the BUILD_TESTING variable in order to indicate whether or not
tests shall be built. However this variable is used by e.g. CTest
already and there it had a different default value. Therefore we now
deprecate BUILD_TESTING and use the tests option instead.

BUILD(cmake): Don't re-use BUILD_TESTING

---

src/mumble/MumbleApplication.cpp

This could also cause a crash, in case `gswForward()` was called before `GlobalShortcutsWin`'s initialization.
For reference, the bug was introduced in #4317.

FIX(client): typo in gswForward() causing "WM_" messages not to be injected

---

src/mumble/MainWindow.cpp
src/mumble/UserModel.cpp
src/mumble/UserModel.h

This is a followup on #4439 (and #4436) that fixes 2 issues of that implementation:
- Wrong volume adjustments being displayed for ChannelListeners in certain situations
- MainWindow not updating automatically when the adjustments change

FIX: volume adjustment display

---

overlay_gl/CMakeLists.txt
scripts/mumble-overlay

Before the overlay libraries and the related script would not be
installed. Instead the user would have to manually install them on the
system.
Now the overlay libraries are added to the install. The script was fixed
to take into account the correct overlay library names.
Closes: #4471

BUILD(cmake): Install overlay libs and scripts if enabled

---

src/mumble/AudioOutputSample.cpp

If a sound-file failed to load, there is no hint about this in the logs
or anywhere else as it never actually gets ensured that the loading was
successful.
Now and explicit check is performed and if the loading failed, a warning
is printed to the console.
Closes #4492

FIX(client, audio): Loading sample fails silently

---

src/mumble/Settings.cpp

The showVolumeAdjustment setting was saved twice but wasn't loaded
anywhere.

FIX(client): Setting not saved

---

src/mumble/main.cpp

On Linux (KDE Plasma) Qt (or rather the window manager) won't move a
widget off-screen so there was no need to check whether the position
saved for the TalkingUI was actually on-screen or not.
The situation seems to be a different one on Windows though. There it
can happen that the UI is moved off-screen. Once that happens the user
is more or less incapable of bringing it back again (as the saved
position won't get cleared).
In order to mitigate this issue, it is now (thoroughly) checked whether
or not the TalkingUI will end up on-screen or not.

FIX(client, ui): Don't move TalkingUI off-screen

---

src/mumble/TalkingUIContainer.cpp
src/mumble/TalkingUIContainer.h
src/mumble/TalkingUIEntry.h

The way TalkingUIContainer::updatePriority() worked prevented a
container's priority to decrease (even thought the entry because of which
the priority initially increased is no longer contained).
To fix this, the referenced function will now simply reset the cached
priority to the lowest possible value before performing the actual
checking.

FIX(client, ui): Container prio never sinks in TalkingUI

---

src/mumble/TalkingUI.cpp

The setting for keeping the local user always visible in the TalkingUI
was not put into effect immediately if the local user didn't happen to
be displayed in the TalkingUI at the time of applying the settings.
Instead the effect was only visible after a re-connect or after having
changed the local user's TalkingState so that it was added to the UI via
that route.
The fix was simply to add the user if it is currently not present but is
asked to be shown permanently.

FIX(client, ui): Make setting take effect immediately

---

.ci/travis-ci/script.bash
src/CMakeLists.txt
src/mumble/CMakeLists.txt
src/mumble/ConnectDialog.cpp
src/mumble/ConnectDialog.h
src/mumble/Global.cpp
src/mumble/Global.h
src/mumble/Zeroconf.cpp
src/mumble/Zeroconf.h
src/mumble/main.cpp
src/mumble/mumble_pch.hpp
src/murmur/CMakeLists.txt
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/Zeroconf.cpp
src/murmur/Zeroconf.h
src/murmur/murmur_pch.h

This allows:
- The client to find servers advertized via zeroconf without the need for Bonjour to be installed.
- The server to advertize itself via zeroconf without the need for Bonjour to be installed.
The Win32 API was introduced in the version `10.0.18362.0` (1903/19H1) of Windows SDK. Before that, only the UWP interface was available (introduced in Windows 10 1507).
This commit was successfully tested on Windows 10 1809, which probably means that the API can be used on previous versions as well.
Even if that isn't the case, it's not a problem: the code checks whether the functions we need are exported. If they're not, it falls back to Bonjour.
`Q_OS_WIN64` is used instead of `Q_OS_WIN` because of an issue that appears when certain DNS functions are used in an x86 (32 bit) build: …

FEAT(client, server): use native mDNS/DNS-SD API on Windows, if available

---

plugins/CMakeLists.txt
plugins/css/CMakeLists.txt
plugins/dods/CMakeLists.txt
plugins/hl2dm/CMakeLists.txt
plugins/sto/CMakeLists.txt
plugins/tf2/CMakeLists.txt

As these plugins typically don't do anything anymore it doesn't make all
that much sense to include them by default.
If you still want to include retracted plugins, use
-Dretracted-plugins=ON when invoking cmake.

BUILD(cmake): Don't build retracted plugins by default

---

README.md

We don't support Windows XP anymore. A note is added about Vista as well, which may be supported but we don't know for sure.
This commit also adds FreeBSD to the supported platforms list.

MAINT(readme): update supported platforms list

---

src/mumble/Zeroconf.cpp

Closing `ConnectDialog` causes the `ZeroConf` object to be destroyed. The destructor cancels any running operations, as expected.
However, a warning is printed in `Zeroconf::callbackResolveComplete()` because `ERROR_CANCELLED` is not handled:
> Zeroconf: DnsServiceBrowse() reports status code 1223, ignoring results
This commit fixes the issue.

FIX(client): don't print Zeroconf warning if the operation was cancelled

---

src/mumble/CustomElements.cpp

As requested in Issue #4257 this commit implements the ability to paste and send messages whit a single keyboard shortcut.
The keyboard shortcut is Ctrl + Shift + V, as requested.
I tried to add the shortcut into the "paste and send" drop down menu item but the shortcut is not visible to me, maybe it's because my screen resolution.
Implements #4257

FEAT(ui): Add ability to paste and send messages using a keyboard shortcut

---

cmake/compiler.cmake
g15helper/CMakeLists.txt

The changed files used a generator expression in an if-statement, which
is invalid as these generator expressions are not evaluated during the
initial configuration stage (at which point the if-statement is
evaluated).
This commit changes the use of the generator-expression in such a way
that it will actually do what it was meant to.
Note that this commit also enables position independent code for all
platforms and all build-types instead of only for debug builds on unix
systems. This was the preferred choice instead of porting the -fPIE
compiler option to use proper generator expressions as the presence of
these options caused linking errors with Celt/Opus.

BUILD(cmake): Fix use of generator expression

---

CMakeLists.txt

Those using single config generators (Unix Makefiles, etc...) should be supplying needed build types or empty.
Multiconfig generators specify a config type passed during the cmake --build call
Fixes https://github.com/mumble-voip/mumble/issues/4470

FIX(cmake): Revise if condition for Release build type

---

src/murmur/Messages.cpp

The "Channel Listeners" (#4011) feature allows users to hear the audio
from a channel without joining it. This commit also delivers text
messages to all users who are just "listening to" a channel this way.
Implements #4539
The actual code change is just 4 lines but I've added some comments along as I was worked my way through understanding the code. If you want of course, I can submit only the required code changes.

FEAT(server): Send text messages also to users only listening to channels

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat
.ci/azure-pipelines/install-environment_linux.bash
.ci/travis-ci/before_install.bash
.ci/travis-ci/script.bash
.cirrus.yml
cmake/compiler.cmake
src/murmur/CMakeLists.txt
src/murmur/MurmurGRPCImpl.h

We are using a custom FindGRPC.cmake script in order to locate the gRPC
targets as not all distribution variants of gRPC include the respective
cmake support. Those that do however will use "gRPC" (note the lowercase
"g") as the target's name and therefore our current way of searching for
it via find_pkg won't find them.
The solution is to first look for "gRPC" and only if that fails, check
for "GRPC". This way the official target "gRPC" should be found and
preferred if present.
Fixes #4508

BUILD(cmake): Fix gRPC not being found

---

src/mumble/ConfigDialog.cpp
src/mumble/ConfigDialog.ui
src/mumble/mumble_en.ts

Previously the user only had the choice of setting the settings on the
current settings page to their default value. Therefore, if you wanted
to reset all settings, you had to visit every page and reset it
individually.
With this commit, there is now a reset-all button that can be used
instead.
----
Screenshot (the new button is at the bottom left):

FEAT(client, ui): Add button to reset all settings

---

Dockerfile

As requested in #4549 this commit adds the ca-certificates package to
the Dockerfile in order to use Certified Authorities with Mumble.
Fixes #4549

MAINT(docker): Add ca-certificates package

---

src/mumble/Plugins.cpp

As this variable will always be set by the cmake build system the debug
code should also respect its setting.

FIX(client): Also respect MUMBLE_PLUGIN_PATH in debug mode

---

docs/dev/build-instructions/README.md
docs/dev/build-instructions/build_static.md
docs/dev/build-instructions/build_windows.md
docs/dev/build-instructions/setup_visual_studio.md

It seems like this part was overlooked at the time the docs were
written.

DOCS: Added instructions to install Visual Studio

---

docs/dev/build-instructions/build_static.md

Includes a script that implementers can *basically* copy and paste and run in order to use the same process for setting environment and path variables that the developer command prompt uses.

DOCS: Added info for building with powershell.

---

plugins/HostLinux.cpp
plugins/HostLinux.h
plugins/HostWindows.cpp
plugins/HostWindows.h
plugins/Process.cpp
plugins/Process.h
plugins/ProcessLinux.cpp
plugins/ProcessWindows.cpp

[Toolhelp32ReadProcessMemory()](https://docs.microsoft.com/en-us/windows/win32/api/tlhelp32/nf-tlhelp32-toolhelp32readprocessmemory) takes the process ID, as opposed to [ReadProcessMemory()](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-readprocessmemory).
This allows us to read memory without the need for an handle ([OpenProcess()](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocess)).
This PR also moves `m_ok` to `Process`.

REFAC(plugins): Use Toolhelp32ReadProcessMemory() instead of ReadProcessMemory(), move "m_ok" to Process

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/mumble_en.ts

FEAT(client): Adds a new shortcut which hides/shows the main window

---

src/mumble/GlobalShortcut.cpp
src/mumble/GlobalShortcut.h
src/mumble/mumble_en.ts

This improves readability, especially when the keys combination and/or the keys' name is long.
Previously, the tooltip always showed "List of configured shortcuts".

FEAT(client): Show keys in tooltip in shortcuts settings, each one in a new line

---

plugins/HostLinux.cpp
plugins/HostLinux.h
plugins/HostWindows.cpp
plugins/HostWindows.h
plugins/Module.cpp
plugins/Module.h
plugins/Process.h
plugins/ProcessLinux.cpp
plugins/ProcessWindows.cpp
plugins/mumble_plugin_utils.h
plugins/se/CMakeLists.txt
plugins/se/se.cpp

Previously, only `module()` was present: it retrieved the base address of the specified module.
It worked fine, but it iterated through the process' modules every time it was called.
This commit replaces it with `modules()`, which returns an `std::unordered_map` containing all modules.
The map uses the module name as key and Module as value.
Aside from the performance improvement, the new code also provides info for each module region:
- Start address.
- Size.
- Whether it's readable, writable and/or executable.

REFAC(positional-audio): Proper functions/classes for module-related operations

---

plugins/se/client.h

The code was retrieving the wrong offset (`GetLocalClient`).
As a result, `peek()` always returned 0 and the player ID was always 1.
The plugin appeared to be working fine because the player ID is always 1 when playing locally.

FIX(positional-audio): Fix Source Engine plugin using wrong player ID on Linux

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/TalkingUI.cpp

In cases where the TalkingUI was overlaying the MainWindow, it could
happen that a context menu triggered from the TalkingUI would actually
be created using another element (listener, channel, user) as the
context for that menu. This would happen because in these cases there is
an entry below the cursor (behind the TalkingUI) that would
automatically be recognized as the desired target.
The fix works by explicitly disabling the position-dependent target
search and using explicitly defined targets instead.

FIX(talking-ui): Context-menu z-index issues

---

docs/dev/build-instructions/build_macos.md
docs/dev/build-instructions/faq.md

The issue of cmake finding an incompatible OpenSSL version was
encountered on macOS in #4486, which is why the problem is also
explicitly mentioned in the macOS instructions.

DOCS: Note about selecting OpenSSL directory

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

The template includes a link to our commit guidelines as this seems to
be something a lot of people don't know about.

MAINT: Create PR template

---

docs/dev/build-instructions/build_linux.md

On a fresh install of Ubuntu 20.10, this additional dependency needed to be installed in order to build Mumble.

Add g++-multilib to Linux build docs

---

docs/dev/build-instructions/build_linux.md

Add a link to the cmake download page where various options for installing cmake can be found.

DOCS: Add link to cmake download page

---

Dockerfile

The Dockerfile contained instructions at the wrong position causing it
to not work properly (it didn't install the necessary dependencies).
Fixes #4600
Don't install qtcreator via Dockerfile
The Qt Creator IDE should not be needed in the Docker image at all.

MAINT: Fix Dockerfile 

---

.github/actions/install-dependencies/action.yml
.github/actions/install-dependencies/extractWithProgress.sh
.github/actions/install-dependencies/install_ubuntu_shared_64bit.sh
.github/actions/install-dependencies/install_ubuntu_static_64bit.sh
.github/actions/install-dependencies/main.sh
.github/workflows/build.yml
.github/workflows/set_environment_variables.sh

Now that Travis CI decided to stop offering their services for free, we
had to look for an alternative solution. GitHub Actions seems to fit the
picture really well and has the benefit of being tightly integrated into
GitHub (obviously).
For now only shared builds for Ubuntu 18.04 and 20.04 are included. The
scripts and the framework for also including static builds is part of
this commit as well but as it stands the static build always failed and
therefore it was given up upon for now.
Adding support for other OS will require a few tweaks and a couple of
new scripts but in general the framework was built with this kind of
extension in mind.

CI: Introduce GitHub Actions

---

plugins/ut99/ut99.cpp

When building on CentOS 8 with default flags which includes Wall flag, 
build stops because array n[3] is not initialized. Initialize it to have all 
values to be zero.

FIX(plugin): initialize array to prevent warning

---

Dockerfile

Sequence of added code in PR #4588 caused Cmake to break in Docker Build. This rearranges additions to fix. (Sorry.)

FIX: Break in Docker Build from PR #4588

---

src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h

The race condition was that the channel of a user could be modified
and before it gets updated in the TalkingUI as well, the talking state
of that user changes. Then inside the talkingStateChanged function the
code would assume that the TalkingUIUser is in the container representing
the current channel of that user but in fact in the TalkingUI this user
is still in its own channel, causing the user-search to return nullptr
which then yields a SegFault as soon as the returned pointer gets
dereferenced.

FIX(client): Crash due to race-condition in TalkingUI

---

src/murmur/Server.cpp

Before this commit, the code on the server made sure that a
ChannelListener would always receive audio that was being shouted to a
channel. It didn't respect though if the shout was actually restricted
to be received by only a specific group.
This patch now makes sure that listeners are also checked for their
group so that a listener that doesn't belong to the target group (if one
is set) won't receive the audio either.

FIX(server): Prevent listeners from hearing all shouts

---

src/mumble/CustomElements.cpp

When you set the imagemessagelength to 0 on the server and paste an
image into the client chat no error should pop up that the image is too
large.

FIX(client): Respect unlimited imagemessagelength

---

scripts/murmur.service

As things are now, `systemctl start murmur` hangs and eventually times out.
The problem is that in the unit file, both `Type=forking` and `PIDFile=/run/murmur/murmur.pid` are specified. In this scenario systemd will wait for the PID file to appear. However, it will never appear there, as murmur does setuid on its own before writing the pid file, and thus lacks the rights to write to /run, and even if it had the rights, it doesn't try to create a missing directory anyway.
Although the unit file has been broken for a long time, Debian-based distros still use the `/etc/init.d/mumble-server` wrapped with `systemd-sysv-generator,` and haven't noticed the problem.

MAINT/FIX(server): Fix systemd murmur.service

---

overlay_gl/CMakeLists.txt

If a system for instance uses -z,now in their default build flags (as
Arch Linux does), it will overwrite the -z,lazy flag which however is
needed in order for the overlay to work with games that are not directly
linked with OpenGL.
By using the BEFORE keyword in cmake, we can prevent this from
happening.
This commit can be viewed as a follow-up for #3307.
Fixes #3296

BUILD(cmake): Fix overlay link option being overwritten

---

installer/ServerInstaller.cs

Since the ini file would be removed or overwritten by installs,
upgrades, and uninstalls it should be created at app runtime or manually
copied to the install path after install.

FIX(installer) Remove ini file

---

src/mumble/AudioWizard.cpp
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h
src/mumble/main.cpp

This reverts commit 7d0b933a7e9595e0afef854c6f0a2f68a1feea7c.
The issue with theses changes is that they cause
AudioInput::encodeAudioframe from no longer being called if the user is
muted. The functionality packed inside the mentioned function relies on
being continually being called even if there is no audio to send.
Thus no longer calling them affects the following things (maybe more):
- local user's talking state (can get stuck in a certain state)
- Audio cues for begin/end of a transmission
- Idle actions
- Framesize stuffing when using Opus
- Resetting of certain variables (iBitrate)
- Clearing/Handling of whisper targets (for last audio frame)
- Properly updating bPreviousVoice
In order to use the changes originally made by that commit, the audio
system has to be refactored first …

FIX: Revert audio corking (PulseAudio)

---

src/mumble/Settings.cpp

Disable Text-To-Speech by default As requested in #4626

Disable Text-To-Speech by default

---

overlay_gl/CMakeLists.txt

This is a follow-up on #4629 that also adds the BEFORE link option to
the x86 build of the overlay.

BUILD(cmake): Fix overlay link option being overwritten 2.0

---

src/mumble/CMakeLists.txt
src/mumble/TalkingUI.cpp
src/mumble/TalkingUI.h
src/mumble/TalkingUIComponent.h
src/mumble/TalkingUIContainer.cpp
src/mumble/TalkingUIContainer.h
src/mumble/TalkingUIEntry.cpp
src/mumble/TalkingUIEntry.h
src/mumble/widgets/MultiStyleWidgetWrapper.cpp
src/mumble/widgets/MultiStyleWidgetWrapper.h

It turned out that it is absolutely impossible to only overwrite
specific properties via a styleSheet without also overwriting all other
properties that have been set via styleSheet on that object before.
Therefore a myWidget->setStyleSheet("background: red") will not only set
the background color to red but also erase everything that has been
written to the StyleSheet before this point.
As this is very inconvenient and always appending the most recent
property to the existing StyleSheet is not an option (the StyleSheet
will just keep growing in size and also this doesn't work well once one
starts using selectors), this commit introduces a wrapper class that can
be used for fine-tuned control of a widget's style.
This works by storing the desired properties in a separate class and …

REFAC(client, talking-ui): Stylable widget wrapper

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/Log.cpp
src/mumble/Log.h
src/mumble/mumble_en.ts

Currently pasting or dragging and dropping images in the Mumble chat is
difficult because:
1) They are rejected because they exceed the allowed size. As a user I
would not expect it to transmitted losslessly but I would hope that the
client compresses it to a size the server allows.
2) Images are rejected because the server does not allow html. When
inserting an image via drag and drop you aren't notified what went
wrong.

FEAT(client): Easier pasting of images

---

src/mumble/Zeroconf.cpp
src/mumble/Zeroconf.h
src/murmur/Zeroconf.cpp
src/murmur/Zeroconf.h

This change:
- Fixes binaries failing to start on versions of Windows where `dnsapi.dll` doesn't export the symbols we need.
- Allows us to use the native API in x86 builds.
See https://developercommunity.visualstudio.com/content/problem/1191345/some-dns-api-functions-cause-lnk2019-errors-in-32.html for more info.

FIX(client, server): Load native mDNS/DNS-SD symbols at runtime

---

macx/scripts/osxdist.py

In addition to the plugins, the `plugins` folder in the build directory also contains temporary build files.
As the script was copying the entire tree, those files made their way into the bundle.
This commit fixes the issue by explicitly copying only files that end with `.dylib`.

BUILD(macOS): Only include ".dylib" files in bundle's "Plugins" directory

---

COMMIT_GUIDELINES.md

The TRANSLATION type has been used for example in 9e8b9afaadbaff342000deb69a1a228f5f9a4073 and 38215622f48f85e5b7cd9d7dec164fea5edbafee, for updating the translated strings and source strings respectively.

MAINT: Add TRANSLATION type to commit guidelines

---

plugins/amongus/Game.cpp

The reason why the signature has to be stricter now is due to a very similar function being present at an earlier address:
```asm
il2cpp:10E99B02 83 C4 08          add     esp, 8
il2cpp:10E99B05 84 C0             test    al, al
il2cpp:10E99B07 74 39             jz      short loc_10E99B42
il2cpp:10E99B09 A1 AC 7C C5 11    mov     eax, HLBNNHFCNAJ__TypeInfo ; HLBNNHFCNAJ
il2cpp:10E99B0E 8B 40 5C          mov     eax, [eax+5Ch]
il2cpp:10E99B11 8B 38             mov     edi, [eax]
il2cpp:112CC4B8 83 C4 08          add     esp, 8
il2cpp:112CC4BB 84 C0             test    al, al
il2cpp:112CC4BD 74 39             jz      short loc_112CC4F8
il2cpp:112CC4BF A1 54 7F C5 11    mov     eax, FMLLKEACGIO__TypeInfo ; FMLLKEACGIO
il2cpp:112CC4C4 8B 40 5C          mov     eax, [eax+5Ch]
il2cpp:112CC4C7 8B …
```

FIX(positional-audio): Update Among Us plugin to work with v2020.12.09s

---

src/mumble/CustomElements.cpp

Fixed: "This server does not allow sending images" displayed no matter if images are in the pasted content when pasting contents into the chatbar.
Fixed #4660.

FIX(client): Image not supported error message wrongly displayed,

---

src/mumble/DBus.cpp
src/mumble/DBus.h

I initially tried using the toggle() function, but that did not work.
Reading the check state and setting the same value ended up actually
inverting the state.

FEAT(client): Added DBus calls to toggle mute and deaf state.

---

src/CMakeLists.txt
src/QtUtils.cpp
src/QtUtils.h
src/mumble/MainWindow.h
src/mumble/UserLocalNicknameDialog.cpp
src/mumble/UserLocalNicknameDialog.h

When having the dialog open that allows to set a custom nickname to
another client (UserLocalNicknameDialog) pressing Esc would crash
Mumble. This is due to the Esc key triggering the dialog's reject()
function in which the dialog's smart-pointer object is removed from a
global list and therefore goes out of scope.
This results in the dialog getting deleted, but since this is done in a
member function of the dialog, there is still code accessing the now
deleted object (in Qt's internals) and this is causing the segmentation
fault.
The fix is to use a custom deleter function for the dialog pointer that
instead of using delete on it, calls deleteLater() on it. Thus the
deletion of the object is left to Qt which can then do it at a point at
which it is done with it.
As this is something that …

FIX(client,ui): Crash by pressing Esc in nickname dialog

---

.ci/azure-pipelines/assertNoTranslationChanges.sh

Translation test failed on #4676 even if update translation script run on some OS (my macOS 10.15).
This commit aims to provide more information on translation changes when this test failed.

CI(azure): Show translation difference if assert no translation test failed

---

docs/dev/build-instructions/build_installer.md
installer/ClientInstaller.cs
installer/ServerInstaller.cs
src/mumble_exe/CMakeLists.txt
src/murmur/CMakeLists.txt

This pull request:
- Adds null checks and error messages for "--arch" and "--version" to WixSharp projects.
- Sets cabinet file name to "Mumble.cab", for consistency with our previous installers.
- Cleans up ClientInstaller.
- Fixes regex patterns for string input safety and to simplify conditions.

FEAT(installer): Add support for snapshot builds

---

src/OSInfo.cpp
src/Version.cpp
src/Version.h
src/mumble/ConnectDialog.cpp
src/mumble/CrashReporter.cpp
src/mumble/NetworkConfig.cpp
src/mumble/Overlay_macx.mm
src/mumble/Settings.cpp
src/mumble/os_win.cpp

#4669 introduced support for the 4th part (build/tweak) of the version, however:
1. It didn't replace all instances of `MUMBLE_VERSION_STRING` with `MUMBLE_VERSION`.
2. It accidentally replaced `MUMBLE_VERSION_STRING` with `MUMBLE_RELEASE_ID` in `MumbleVersion::get()`'s signature.
3. It didn't update the regex expression in `MumbleVersion::get()` to support 4 digits.
This pull request fixes all issues listed above.
---
Thanks to @Natenom for reporting the issue.

FIX(client, server): Fix protocol version not being set correctly

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat
.ci/azure-pipelines/main.yml

`BUILD_NUMBER_TOKEN` has to be manually exported because it's a secret variable: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
Also, the version sent to our endpoint has to be different for each job, we want the build number to increase a single time for each pipeline.

CI(azure): Fix build number system

---

src/mumble/UserView.cpp

With the introduction of #3929 a channel's description would not be
accessible by clicking on the comment icon next to the channel's name
but rather by clicking to the lock icon to its right (if there was one).
This was due to some implicit assumptions about the comment icon's
position in the code that is responsible for showing the description.
Thus the fix was simply to let that part of the code account for the
possible new icon as well.
Fixes #4685

FIX(client,ui): Channel description via lock icon

---

src/murmur/Messages.cpp

Clients < 1.4.0 don't know about the new ChannelListener feature and
thus there is no indication in the UI for them. In order to make sure
that users know that they could potentially be listened to without
seeing anything in the UI, a warning message was introduced in #4097.
There was an error in the implementation however causing this warning to
not be sent by the server if there are no explicit limits on the amount
of channel listeners via the server configuration.
The bug was that "no limit" was expressed as -1 but the check for
whether these features are enabled checked for > 0. The fix is simply to
check for != 0 instead.
Fixes #4687

FIX(server): Older clients not being warned about ChannelListener

---

docs/dev/build-instructions/ide_integration.md

We used mumble-vcpkg while the get script was still being implemented in a separate repository.
When we integrated it in this repository in 2f45772c9c9ad90e480e50008419c598b19bf01e it was already, and still is, using `vcpkg`.

DOCS: Fix vcpkg paths in build documentation

---

src/mumble/UserModel.cpp
src/mumble/mumble_en.ts

The following icons were added (with a description) to Qt's "What's
this?" help system:
- padlocks (#3929)
- talking state for locally muted users (#4322)
- listener symbol (#4011)
Fixes #4686

FEAT(client): Add new icons to "What's this?"

---

src/mumble/ALSAAudio.cpp
src/mumble/ASIOInput.cpp
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioConfigDialog.h
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioInput.ui
src/mumble/CMakeLists.txt
src/mumble/CoreAudio.h
src/mumble/CoreAudio.mm
src/mumble/JackAudio.cpp
src/mumble/OSS.cpp
src/mumble/PAAudio.cpp
src/mumble/PulseAudio.cpp
src/mumble/WASAPI.cpp
src/mumble/mumble_en.ts

This commit utilized the internal permission check function to examine
if the user has granted mumble the microphone permission when initializing
CoreAudioInput backend. If the user hasn't granted the permission, it will
request it through macOS's interface. If being denied, a warning message
will appear in the chat log.
This commit addressed #4547 and #4580. However, self-compiled unsigned
mumble binary still cannot access microphone because this is denied by
Apple's policy. The workaround is to start mumble binary from a terminal,
which is properly signed (e.g. the Terminal app pre-installed).
Fixes #4547
Fixes #4580

FEAT(client, mac): Prompt user for microphone permission if not granted.

---

scripts/murmur.ini
src/murmur/Meta.cpp

558000 = 510000 (Opus) + 9600 (position) + 38400 (TCP overhead)
Closes https://github.com/mumble-voip/mumble/issues/3895

FIX(server): Make max bandwidth the highest supported

---

src/mumble/Log_unix.cpp

These no longer exist in contemporary icon themes like Adwaita.
Per https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
and https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html

FIX(client): Ancient notification icon names

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat
.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml
.ci/azure-pipelines/steps_linux.yml
.ci/azure-pipelines/steps_macos.yml
.ci/azure-pipelines/steps_windows.yml

Turns out environment variables cannot be exported globally:
"/.ci/azure-pipelines/main.yml (Line: 7, Col: 1): Unexpected value 'env'"
It has to be done for each step that makes use of the variable.
Furthermore if a variable is not defined on Azure, the expansion
$(MY_VARIABLE) does not resolve to an empty String (as is the case e.g.
in Bash) but this expression is then taken literally without any
expansion at all. Therefore we have to make sure that the
BUILD_NUMBER_TOKEN variable is always defined. Thus we define it in
main-pr.yml as for PRs we don't define it on Azure.
In order for these variables to not interfere with each other, the
variable name inside the scripts was prefixed with MUMBLE_

CI(azure): Export BUILD_NUMBER_TOKEN correctly

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

This fixes the last build failure, which was due to the job's display name containing spaces.
`x86_64` is changed to `x64` as the latter appears to be the most common identifier for the architecture, at least for Windows.

CI(azure): Simplify and improve job name for Windows builds

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat

On Windows (Batch) the syntax was correct, but `mumble-version.py` was not being executed due to the path using a slash instead of a backslash.
On UNIX (Bash) the syntax was incorrect: https://unix.stackexchange.com/questions/88452/concatenating-two-variables-with-an-underscore

CI(azure): Fix VERSION variable not being expanded correctly in curl call

---

src/mumble/AudioWizard.cpp
src/mumble/AudioWizard.h
src/mumble/AudioWizard.ui
src/mumble/CMakeLists.txt
src/mumble/Cert.ui
src/mumble/widgets/CompletablePage.cpp
src/mumble/widgets/CompletablePage.h

The class was defined in `AudioWizard.cpp`/`.h`, however `AudioWizard` is not the only user.
In fact, `Cert.ui` had to include `AudioWizard.h` in order to make use of `CompletablePage`.
This pull request moves the class into a dedicated file set and changes the include header in `AudioWizard.ui`and `Cert.ui`.

REFAC(client): Move CompletablePage class into dedicated file set

---

.ci/azure-pipelines/build_windows.bat

I have no idea why but these changes make this work on my Windows 10 VM.
If this really solves the issue then this is a perfect illustration for
why batch is weird.

CI(windows): Fix build number fetching script

---

src/crypto/CryptStateOCB2.cpp
src/crypto/CryptStateOCB2.h
src/tests/TestCrypt/TestCrypt.cpp

The mitigation for vulnerabilities discovered in
OCB2 (https://eprint.iacr.org/2019/311, called XEX* attack, or XEXStarAttack, in code)
introduced in be97594 (#4227) willingly allowed for some packets with specific
characteristics to be dropped during encryption to prevent the vulnerability
from being exploited.
It was assumed that the chance of such packets was sufficiently small (given
we are dealing with compressed audio) that such loss was acceptable.
It was however discovered that digital silence (as produced by e.g. a noise
gate) will cause Opus to emit almost exclusively such packets, leading to strong
artifacts on the receiving end. See #4385.
This commit tries to work around the issue by modifying such packets in a way
which will no longer require them to be dropped, and yet …

FIX(ocb2): Work around packet loss due to OCB2 XEX* mitigation

---

src/mumble/ConnectDialog.cpp
src/mumble/mumble_en.ts

Our public server list registration script doesn't have an URL scheme whitelist for the website field.
Turns out a malicious server can register itself with a dangerous URL in an attempt to attack a user's machine.
User interaction is required, as the URL has to be opened by right-clicking on the server entry and clicking on `Open Webpage`.
This PR introduces a client-side whitelist, which only allows `http` and `https` schemes. We will also implement it in our public list.
In future we should probably add a warning `QMessageBox` informing the user that there's no guarantee the URL is safe (regardless of the scheme).
Thanks a lot to https://positive.security for reporting us the RCE vulnerability privately.

FIX(client): Only allow "http" and "https" schemes in ConnectDialog for web page

---

src/mumble/Log_unix.cpp

These no longer exist in contemporary icon themes like Adwaita.
Per https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
and https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html
This is a backport of #4705

Backport "FIX(client): Ancient notification icon names"

---

src/murmur/main.cpp

For some reason qFatal has been used to log information such as the
version requested by the --version argument.
abdb5004bb92b28271673e33df9cc3e314f5711a made qFatal exit with an
exit status of one leading to successful operations that happened
to contain some print-out to leave an exit status of 1 (#3911).
Note: This is a backport of #3998

Backport "Use qInfo instead of qFatal for normal logging"

---

src/mumble/ConnectDialog.cpp
src/mumble/mumble_en.ts

Our public server list registration script doesn't have an URL scheme
whitelist for the website field.
Turns out a malicious server can register itself with a dangerous URL in
an attempt to attack a user's machine.
User interaction is required, as the URL has to be opened by
right-clicking on the server entry and clicking on "Open Webpage".
This commit introduces a client-side whitelist, which only allows "http"
and "https" schemes. We will also implement it in our public list.
In future we should probably add a warning QMessageBox informing the
user that there's no guarantee the URL is safe (regardless of the
scheme).
Thanks a lot to https://positive.security for reporting the RCE
vulnerability to us privately.
This is a backport of #4733

Backport "FIX(client): Only allow "http"/"https" for URLs in ConnectDialog"

---

src/CryptState.cpp
src/CryptState.h
src/tests/TestCrypt/TestCrypt.cpp

The mitigation for vulnerabilities discovered in
OCB2 (https://eprint.iacr.org/2019/311, called XEX* attack, or XEXStarAttack, in code)
introduced in be97594 (#4227) willingly allowed for some packets with specific
characteristics to be dropped during encryption to prevent the vulnerability
from being exploited.
It was assumed that the chance of such packets was sufficiently small (given
we are dealing with compressed audio) that such loss was acceptable.
It was however discovered that digital silence (as produced by e.g. a noise
gate) will cause Opus to emit almost exclusively such packets, leading to strong
artifacts on the receiving end. See #4385.
This commit tries to work around the issue by modifying such packets in a way
which will no longer require them to be dropped, and yet …

Backport "FIX(ocb2): Work around packet loss due to OCB2 XEX* mitigation"

---

installer/ClientInstaller.cs
installer/ServerInstaller.cs

Now that we reached build number 10 the current expression is not valid anymore.
As a result, the version is not set and the build fails.
This PR rewrites the regex so that it accepts multiple digits and is also shorter.

FIX(installer): Change version regex so that it accepts multiple digits

---

.cirrus.yml

According to https://www.freebsd.org/releases/ 12.1 is no longer
supported.
This also seemed to cause some problems in the most recent runs of the
Cirrus CI tasks.
Thus this commit updates the used version to 12.2

CI: Update to FreeBSD 12.2

---

scripts/updatetranslations.sh
src/mumble/ALSAAudio.cpp
src/mumble/ASIOInput.cpp
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/AudioInput.ui
src/mumble/AudioWizard.cpp
src/mumble/AudioWizard.h
src/mumble/CMakeLists.txt
src/mumble/CoreAudio.h
src/mumble/CoreAudio.mm
src/mumble/EchoCancelOption.h
src/mumble/JackAudio.cpp
src/mumble/OSS.cpp
src/mumble/PAAudio.cpp
src/mumble/PulseAudio.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/WASAPI.cpp
src/mumble/mumble_en.ts

Apple doesn't provide a way to hijack the system audio stream into Mumble
so speex's echo cancellation cannot work for Mac.
It was reported in https://developers.google.com/web/updates/2018/03/macos-native-echo-cancellation
that Mac has a native echo cancellation AU. This commit uses this
native AU to enable echo cancellation for Mac users.
Unfortunately, this function is poorly documented by Apple. The best
reference of this function is from Chromium's code,
https://github.com/chromium/chromium/blob/master/media/audio/mac/audio_low_latency_input_mac.cc
Limited support from Apple made invoking this AU a very unfriendly
task. Also, the subtleness of echo cancellation made it hard to be
tested. I would just submit this PR and see the reactions from other
testers.
Implement #1775.
> Me: I …

Experimental Echo Cancellation for MacOS

---

src/OSInfo.cpp
src/OSInfo.h

Fixes #3554.
As `/etc/os-release` is considered the standard on Linux distributions which make use of `systemd`, we should try to read the version from that file prior to using other methods (currently `lsb_release` and `uname()`).

FEAT: Improve OSInfo so that architecture and OS are properly reported

---

src/mumble/SocketRPC.cpp
src/mumble/main.cpp
src/mumble/mumble_en.ts

FEAT(client): add starttalking and stoptalking to the socket rpc interface
If mumble isn't allowed to listen to all input from an input device, for example when running as wayland client, ptt events can be sent via socket rpc, and, in the case of wayland, the keybinding can be done by the compositor. #3675 implements this for dbus.
To avoid executing the rather large mumble binary to do the rpc, one could also do something like this:
`echo '<self><starttalking>starttalking</starttalking></self>' | socat - UNIX-CONNECT:/tmp/MumbleSocket`
Fixes  #1594

FEAT(client): Add "starttalking" and "stoptalking" to the socket RPC interface

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat

Our script on the server now bumps the build number for every new version.
A version is now associated to a unique build number and vice versa.
The previous system didn't cause collisions, but it was very fragile.
For example, the build number got de-synced between OSes a few days ago.
It probably happened due to at least a build being restarted after the build number bump.
With the new system there should be no problems anymore, as the build number is permanent for a given version.

CI(azure): Use version & commit hash as identifier for build number

---

src/mumble/Settings.cpp

This fixes a few regressions introduced in #4694 affecting the echo cancellation settings.
Fixes #4761

Fix echo cancellation setting not saved

---

src/mumble/Settings.cpp

613a5d5fb0ed4078e3a127b784eada14a809fa50 introuced a compatibility layer
for porting over the old echo cancel settings to the new one. However by
doing so it prevented the default setting (Speex mixed) from being
loaded properly as in this case it is not saved explicitly. This would
lead to the compat block being executed that would disable echo
cancelling if there are no old settings.
This commit fixes this by making sure the compat block is only run when
the old setting is actually present.
Fixes #4761

FIX(client): Default echo cancel setting not loaded correctly

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/azure-pipelines/build_windows.bat
scripts/mumble-version.py

The tag logic is removed from the script.
Its purpose was to set the name of the tag associated to the latest version as version.
It was working as expected, however in some instances we don't want the script to take the tag into account.
For example, we had to rebuild the first 1.4.0 snapshot as the version was accidentally set to `1.4.0-snapshot1`.
As replacement, the `--revision`and `--type` options are implemened.
They allow to explicitly set the release type and its revision, when applicable.
Assuming the revision is set to 1 (default value), the output is currently as follows:
Type set to "snapshot": `1.4.0~2021-02-14~g973cee211~snapshot`
Type set to "beta": `1.4.0-beta1`
Type set to "rc": `1.4.0-rc1`
Type set to "stable": `1.4.0`
The `--format` option replaces `--project` and …

BUILD(versioning): Remove tag logic, implement "--revision", "--format" and "--type" options in mumble-version.py

---

src/mumble/TalkingUI.cpp

If the local user was added to the TalkingUI, renamed after that and
then changes its talking status, the client would crash.
The reason for this is that in TalkingUI::findOrAddUser we first create
the user's channel. Therefore we expect the channel to exist at a later
point in this function. However we also check whether the current name
of the user matches the name we have stored for it. If not (which is the
case after a rename), we remove that user. If the user was the only one
in its channel, the channel gets removed as well. In this case however
the original assumption of the user's channel already existing is not
valid anymore, ultimately leading to the crash.
The fix is to only create the user's channel **after** the name check in
order to make sure the assumption is always …

FIX(talking-ui): Crash after rename

---

CMakeLists.txt
src/mumble/CoreAudio.mm
src/mumble/GlobalShortcut_macx.mm
src/mumble/MainWindow.cpp
src/mumble/mumble.plist.in
src/mumble/os_macx.mm

I've been working on getting Mumble to build natively on ARM Macs (testing on an M1 MacBook Air.)
I've gotten Mumble and murmur to build, and everything except echo cancellation and shortcuts seems to work. (see caveats)
Detailed explanations are also in the commit messages.
- Some fixes to make `-Doverlay=OFF` compile cleanly on macOS:
- FIX(overlay): add missing ifdefs for USE_OVERLAY  …
- FIX(overlay, mac): handle hideEvent without USE_OVERLAY  …
- Fix missing permissions
- FEAT(mumble.plist, mac): add NSMicrophoneUsageDescription  …
- Replace usage of deprecated (and now disabled) APIs
-  FEAT(audio, mac): migrate to Audio Component API  …
- FIX(build): disable overlay on ARM macs  …
- CMake only seems to search for libraries in `/usr/local/opt`.  
Homebrew installs everything into …

Fixes for building on ARM Macs

---

src/mumble/ConnectDialog.cpp
src/mumble/mumble_en.ts

In the server connect dialog the buttons for Cancel and Connect were
accessible through the same keyboard shortcut "C".
Thus this commit changes the shortcut for Connect to "O".
Fixes #4726

FIX(client, accessibility): Duplicate keyboard shortcuts

---

src/mumble/MainWindow.cpp

FIX(client): Don't show URL password in clear text

---

scripts/org.mumble_voip.mumble.appdata.xml

The referenced links on debian.net seem to have died. Thus they were
replaced with links to our own website.

MAINT: Fix broken links in AppStream meatinfo file

---

src/Version.cpp
src/mumble/MainWindow.cpp
src/mumble/mumble_en.ts

This PR contains multiple fixes and refactorings related to the version handling
for versions specified in URLs.
See the individual commits for details
Fixes #4684

Fix url version

---

.cirrus.yml
src/licenses.h
src/mumble/About.cpp

In the About dialog Mumble was claiming that the copyright ended in
2019, which is obviously wrong.
Fixes #4784 (for the 1.3.x branch)

FIX(client): Update copyright notice

---

.ci/azure-pipelines/build_macos.bash

The issue was introduced in #4669 and is only cosmetic.
More specifically, the volume name is set to `Mumble `  (trailing space at the end) because the version string is empty.

CI(macos): Fix release ID not being set for macOS package

---

scripts/commitMessage/CommitMessage.py
scripts/generateChangelog.py

The script automatically parses the new merge commits between two given
tags and tries its best to generate a Changelog out of it.

MAINT: Added script to automatically generate Changelog

---

src/murmur/MurmurIce.cpp

Previously, the un-encoded array length was used to construct a string from the encoded byte array, resulting in truncated base64.

FIX(ice): Use the encoded array size to construct the base64 string

---

.gitignore

VSCode's Remote Container feature allows developers to spin up a container of their choosing to develop in. To facilitate ease of use, VSCode writes files to track the Dockerfile which generates the container, as well as config for how VSCode should handle the created container.
Some projects suggest to include these files, as it helps all developers have a consistent development experience, but I'll leave that topic for a future debate and instead only suggest to incorporate the ignoring of this data for now.

MAINT: Added VSCode's .devcontainer directory to .gitignore for when developing in a remote container

---

.ci/azure-pipelines/install-environment_macos.bash

ba5e7bc352c979b1b90ca1cb8771d180cd6293f0 introduced such a hardening of
the CI scripts for the Windows runs. This commit adds this
functionality to the macOS script as well.
This simply causes the script to retry a download several times before
giving up. This mitigates temporary network errors (saving us a manual
restart of the CI).

CI(macOS): Use mutliple attempts for downloads

---

.github/workflows/check_commit_style.py
.github/workflows/check_commit_style.yml
.gitignore

This PR adds a CI check (on GitHub Actions) that checks every commit
in a PR for accordance to our commit guidelines.

CI: Added commit-style check

---

src/murmur/Server.cpp

When changing the welcome text via Ice, Murmur would broadcast the new text to all connected clients. It is a matter of opinion if this is proper behavior or not, but it seems too proactive of an action. Let the clients see the new welcometext when they next connect, or let the Murmur administrator explicitly perfor a sendMessage() to all connected clients after changing the welcometext.
Closes: #4788

FEAT(server): Remove broadcast of new welcometext when changing via Ice

---

cmake/pkg-utils.cmake

If a package is searched for with multiple casings (as is currently the
case for libsndfile), it will be very hard to use the resulting cmake variables
(e.g. <name>_FOUND) as one does not know which casing was 
eventually found.
This issue actually broke the build on macOS when installing libsndfile
via homebrew.
The solution is to always also set the all-lowercase version of the package
name variables (if the all-lowercase package name is contained in the
package's aliases) so that this can then be used further down to reference
the result.
Fixes #4790

BUILD(cmake): Fix pkg search on case-insensitive filesystems

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

The timeout has been increased for the Windows CI builds. The new
timeouts are:
- x64: 90 minutes
- x86: 120 minutes
x86 has the higher timeout because it always takes quite a bit longer
than the x64 build.
The timeout was increased as we frequently see the CI job being
cancelled because it did not finish within the default 60 minutes
timeout.

CI(windows): Increase timeout

---

src/mumble/CoreAudio.mm
src/mumble/Settings.cpp

Some USB audio interfaces have both input and output stream,
but they are accidentally ignored in #4694.
Independent from that this PR changes the macro names for saving
and loading values to and from the settings in order to make that part
of the code less confusing.

FIX(mac, audio): Identify output device

---

src/murmur/Messages.cpp
src/murmur/Server.cpp

This commit fixes both issues discussed in #4277 which were related to
the fact that any socket connection was allocated an ID and marked as
a user. This bug allowed for a malicious user to lock out all users of
a server regardless of server password usage. This change simply moves ID
allocation to after a connection is marked as Authenticated.
FIXES: #4277
This is a modification and reopening of #4812 because I accidentally killed it.

FIX(Server): Unauthenticated connections no longer add to user count

---

.ci/azure-pipelines/install-environment_windows.ps1

The powershell download is incredibly slow, so we use aria2 instead that
promises to be fast.

CI(windows): Use aria2 for downloading

---

README.md

The Weblate free libre hosting requires us to mention them in the README.
See also migration process in #4727

MAINT: Add Weblate and translation notice to README.md

---

src/mumble/mumble_de.ts
src/mumble/mumble_no.ts

These changes were lost in the migration process as the project was removed by Weblate within it.

TRANSLATION: Recover lost translations from Weblate

---

cmake/qt-utils.cmake

If the *_plugin_import.cpp files already exist before the latest cmake
changes for unity builds are pulled, the necessary property does not get
set on these files, which can cause build failure.

BUILD(cmake): Fix unity build failure

---

src/mumble/mumble_si.ts

This was requested on Weblate a week ago.
Sinhala is one of the three official languages used in Sri Lanka.

TRANSLATION: Add new translation for Sinhala (si)

---

.ci/azure-pipelines/steps_macos.yml

The variable holding the directory to change into to run the tests in,
had a typo in its name, causing the cd to fail. Therefore no tests were
found and run.

CI(macOS): Fix test cases not being found

---

src/murmur_grpcwrapper_protoc_plugin/main.cpp

While working with gRPC I ran up against an issue where using the bidirectional streams results in the server freezing after some time. I believe this is the result of the 100ms timeout on the call to processEvents. I changed out the method to one recommended by the Qt docs when using a local loop, but I believe the core of the issue to be with the timeout. With this change applied, my server has been running for 5+ days without running into the issue (normal use) where previously the longest it ever lasted was 2 days.

FIX(grpc): Replace call to processEvents to circumvent exceeding 100ms timeout freezing murmur.

---

src/mumble/CMakeLists.txt

On Unix there are the X11 headers that define incredibly many macros of
which basically none are prefixed in any way. Thus these can easily lead
to name clashes in other files if unity builds are active.
Thus the files known to make problems, are excluded from unity builds in
order to avoid that.

BUILD(cmake): Fix unity build issue

---

src/mumble/AudioInput.cpp

This fixes a heap corruption that was originally discovered by @PaulDana on `#mumble-dev`.
In addition to that, all upstream changes are integrated.

FIX(client): Update rnnoise-src submodule

---

overlay_gl/overlay_gl.pro

BUILD: Bumped overlay version to 1.3.4 as well

---

src/mumble/Translations.cpp
src/mumble/Translations.h
src/mumble/main.cpp

Commit 0dcc1f614b2ab4f0d4bbac5fd29676595072a133 introduced a regression
that caused translations to no longer work (the UI would always remain
in English).
The reason for this is that the translator objects installed into the
application have to remain alive in order to function. By moving them
into a dedicated function they went out of scope very quickly after
their creation and thus none of them actually performed any work.
This commit fixes this by creating the translator objects on the heap
and using a smart-pointer-like structure for making sure they are only
deleted once they are really not needed anymore.
Fixes #4856

FIX(client): Make translations work again

---

src/mumble/Translations.cpp

Commit 0dcc1f614b2ab4f0d4bbac5fd29676595072a133 changed the used
function for loading translation files. The new overload requires an
extra parameter when specifying the directory in which to search for
translation files. This was not provided though and thus the provided
directory path was mis-interpreted as something else.
Fixes #4856

FIX(client): Qt translations not found

---

src/SelfSignedCertificate.cpp

Otherwise names using non-ASCII characters won't be handled properly.
Fixes #4871

FIX(client): Use Utf8 for name field in certificat

---

plugins/cod2/CMakeLists.txt
plugins/cod2/cod2.cpp

It was not working because the camera position values were all set to 0.
This commit fixes the issue while also revamping the code.

FIX(positional-audio): Fix and revamp Call of Duty 2 plugin

---

src/User.cpp

If two persons are reading out the users in a channel in the order they
are rendered, chances are that they will read the names in a different
order. This is because the ordering of users takes the currently used
locale into account that can differ from machine to machine.
This is an inconsistency that one probably does not expect.
Therefore this commit changes back to using a lexicographical comparison
that should be the same on all machines, regardless of the locale.
Fixes #4873

FIX(client, ui): Ordering of Users inconsistent

---

scripts/generateChangelog.py

This PR concentrates on improvements of the generateChangelog.py script.

MAINT: Changelog script improvements

---

src/mumble/TalkingUI.cpp

993f640e0d16d01e2de34c9dfd1edea181414e16 fixed a crash caused by being
renamed. However it did mess up a conditional check that now prevents
any users from being added to the TalkingUI.
This is fixed by this commit.

FIX(client, talking-ui): No users being added

---

src/murmur/Server.cpp

fixes bug introduced in eabfbab4
When an unauthenticated connection is terminated, the session ID still got enqueued into `qqIds`.
The session ID of unauthenticated clients is always 0 when it's not assigned. This means that
whenever an unauthenticated connection is terminated, 0 will be enqueued into `qqIds`. If this
happens multiple times, multiple clients will later be assigned session ID 0. All connections
with the same session ID are displayed as the same user for all clients. As a result of that
users might be listening to what you are saying in your channel without you noticing. If one
connection with session ID 0 gets terminated, all other connections with the same ID will
be terminated as well. This potentially enables denial of service.
Thanks to the Zom.bi community for fixing …

FIX(Server): Prevent multiple Sessions with ID 0

---

src/murmur/Server.cpp

u_char is an old nonstandard BSD alias and should not be used in portable code.
For example the musl libc doesn't provide this alias.

REFAC(server): Replace non-standard u_char with uint8_t

---

src/mumble/Log.cpp

This commit adds support for the Gemini protocol in chat messages.

FEAT(client): Allow gemini:// in chat messages

---

src/mumble/MainWindow.cpp
src/mumble/Markdown.cpp

The Markdown code was using \</br> instead of the correct \<br/>.
This error was introduced in 2da3f0d39e37e6bf10318d174744bb7e7924794b.
Fixes #4899

FIX(client, markdown): Wrong line break HTML code

---

src/crypto/CryptStateOCB2.cpp
src/crypto/CryptographicRandom.cpp
src/murmur/PBKDF2.cpp

https://www.openssl.org/docs/man1.1.1/man3/RAND_bytes.html:
If the entropy source fails or is not available, the CSPRNG will enter an error state and refuse to generate random bytes. For that reason, it is important to always check the error return value of RAND_bytes() and RAND_priv_bytes() and not take randomness for granted.
Also remove unnecessary cast.

FIX: Replace RAND_bytes with CryptographicRandom::fillBuffer

---

COMMIT_GUIDELINES.md
scripts/commitMessage/CommitMessage.py
scripts/generateChangelog.py

This commit type is supposed to be used when e.g. a setting is changed.

MAINT: Add `CHANGE` commit type

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

On our self-hosted macOS runner we were seeing issues due to the
workspace not being cleaned up after each run, causing the next one to
fail.
This commit makes sure that Azure will clean the entire workspace of any
remaining files, before starting a new job.
Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace

CI(azure): Clean entire workspace before starting

---

src/mumble/ALSAAudio.cpp

The functions snd_card_get_name and snd_card_get_longname allocate a
String for the caller that needs to be freed once it is no longer needed.
This was not done in the current implementation and thus this was causing
a memory leak.
This commit fixes this by explicitly `free`ing the resources after usage.
Fixes #4910
Ref: https://www.alsa-project.org/alsa-doc/alsa-lib/group___control.html#ga547dcead4a72f24db4a0f9f530f75228

FIX(client): Memory leak in ALSA implementation

---

src/murmur/UnixMurmur.cpp

The fields of the rlimit struct were assumed to be of type long int when
printing via the qWarning function. This seems to be correct on e.g.
Ubuntu but at least on Alpine Linux this is not true.
In that case the wrong format specifiers are being used for printing
these values, which causes undefined behavior.
The fix is to always copy the values into variables of type long long
unsigned int and then printing these. The code also adds an assertion
making sure that within this copy operation the values won't overflow
the variable's size.
Fixes #4897

FIX(server): Fix undefined behvior on Linux hosts

---

src/murmur/Messages.cpp
src/murmur/Meta.cpp
src/murmur/Server.cpp

The first commits in this PR deal with making sure that usernames
will only be used in a trimmed version, so that the allowance of spaces
in usernames will not allow for "empty" (pure whitespace) names.
Fixes #1202

CHANGE(server): Allow spaces in username by default

---

.github/workflows/check_commit_style.py
.github/workflows/pr-checks.yml

This is to make sure that new patches will actually follow the code
formatting rules that we set up. The used check will make the CI fail if
that was not the case.

CI: Add check for source-code formatting

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

Previously handling the change of transmission mode was done in many
different places causing code duplication.
This commit factors the common functionality out into its own function
and creates a new event for when the transmission mode is changed.

REFAC(client): Transmission mode change events

---

.appveyor.yml

The previous token contained a quote, causing the batch script to break.

CI(appveyor): Replace token with one that doesn't contain special characters

---

COMMIT_GUIDELINES.md
docs/dev/build-instructions/build_static.md

Scope of changes is restricted to docs only.

DOCS: Fixed typos

---

src/mumble/Plugin.cpp
src/mumble/ServerHandler.cpp

In the latest Qt version, specifying a recrsion mode when creating a
mutex was deprecated in favor of QRecursiveMutex being used for the
cases where recursion is needed.
Given that we only ever needed non-recursive mutexes, all we had to do
was to remove the argument to the ctor.
Ref.: Upstream commit deprecating that ctor:
https://github.com/qt/qtbase/commit/d4b206b246caf9b49110526585693ab629609d99
Fixes #4973

REFAC(client): Don't use deprecated mutex ctor

---

scripts/vcpkg/get_mumble_dependencies.ps1

Removes invalid characters (UTF-16 BOM) at the start of line 6.
The profiledir variable is set properly again. Fixing the vcpkg directory being created in the root of the system directory.
Anyone that built the vcpkg using get_mumble_dependecies.ps1 should move their vcpkg folder to the userprofile directory before re-running it. If vcpkg doesn't exist under the userprofile directory it will be recreated by the script.
Original error message below:
```
ï»¿$profiledir` : The term 'ï»¿$profiledir' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Dev\Git\mumble\scripts\vcpkg\get_mumble_dependencies.ps1:6 char:1
+ ï»¿$profiledir = …
```

MAINT(vcpkg): Restore profiledir variable in get_mumble_dependencies.ps1

---

src/mumble/ALSAAudio.cpp
src/mumble/ASIOInput.cpp
src/mumble/AudioConfigDialog.cpp
src/mumble/AudioInput.h
src/mumble/AudioOutput.h
src/mumble/CoreAudio.h
src/mumble/CoreAudio.mm
src/mumble/JackAudio.cpp
src/mumble/OSS.cpp
src/mumble/PAAudio.cpp
src/mumble/PAAudio.h
src/mumble/PulseAudio.cpp
src/mumble/WASAPI.cpp
src/mumble/WASAPI.h

Every audio backend implementation was moving the current device at the top.
This commit replaces that logic by selecting the current device in the combobox.
---

FIX(client): Properly show currently selected audio device in settings dialog

---

src/mumble/GlobalShortcut_win.cpp
src/mumble/GlobalShortcut_win.h
src/mumble/PluginManager.cpp
src/mumble/Settings.cpp

This pull request fixes the following issues:
The revamped raw inputs are not saving / loading shortcuts for the Windows client.
Keyboard shortcuts that are outside of the normal range show up as "Unknown"
Fix the shortcuts events not firing for input buttons when the structs were compared using the default memcmp.
I don't believe InputGKey is compatible with my mouse under Logitech GHub.
1. Is the Xinput Xbox controller's A.
2. Is the InputHid Xbox controller's A.
3. M3 is for Mouse3.
4. K118 is "F24" on the keyboard which is mapped from mouse using Logitech GHub.
This could be considered a breaking change since the shortcut save format might not be backwards compatible. Though that format change had already been made, this fixes it so the change persists to disk.
It is also difficult to …

FIX(client): Windows loading/saving shortcuts

---

src/mumble/widgets/MultiStyleWidgetWrapper.cpp
src/mumble/widgets/MultiStyleWidgetWrapper.h

When scaling the font size system-wide (e.g. set to 150%), the TalkingUI
might not adapt to this properly.
This started happening with the introduction of the
MultiStyleWidgetWrapper class (commit
ff040fb23c407ee34e6d8796a3f058a455f40cb1). As it turns out the
conversion from pixel to point size performed in its setFontSize did not
work properly, causing an incorrect font size to be used. And as the
font size also determines the icons size, these were not scaled properly
either.
The fix is to simply skip on the pixel to point conversion entirely and
instead use the appropriate unit when setting the respective StyleSheet
property. That way Qt can figure the conversion out as needed.

FIX(client, ui): TalkingUI font not scaling properly

---

cmake/os.cmake
src/mumble/AudioConfigDialog.cpp
src/mumble/CMakeLists.txt
src/mumble/EchoCancelOption.cpp
src/mumble/EchoCancelOption.h

These Strings were not translated because as global static variables
they were created before the necessary translators are installed.
This commit fixes this by making sure the containing EchoCancelOption
objects are created lazily (at the time they are needed for the first
time), thus causing a delaying instantiation.
Fixes #4993

FIX(client): Echo cancellation options not translated

---

COMMIT_GUIDELINES.md
macx/scripts/osxdist.py
scripts/commitMessage/CommitMessage.py
scripts/generateChangelog.py

We were seeing errors like
```
could not access /Volumes/Mumble 1.4.0~2021-05-16~g789f2d79e~snapshot/Mumble.app/Contents/MacOS/Mumble - No space left on device
hdiutil: create failed - No space left on device
```
every now and then when attempting to package the DMG package for macOS.
Following the trick described at
www.apple.stackexchange.com/a/177071/417917, we now add the
-megabytes option to the call which seems to fix the issue somehow.
This PR also reverts 0b75cd6f8a25f015857525392e746949b680c99c which failed to solve the issue.

BUILD(macos): Fix package script failing 

---

3rdparty/celt-0.7.0-build/CMakeLists.txt
plugins/PluginComponents_v_1_0_x.h
src/CMakeLists.txt
src/mumble/GlobalShortcut_unix.h

While working on the Ubuntu ppa build I ran into a few build issues on my local 20.04 VM.
To finish up prepping for the mumble-ubuntu-ppa PR it would help if these were merged.
The fix for PRIVATE keyword in target_sources could apply to the macOS mach 3rd party build's CMakeLists.txt it appears to have a comment about the unity build not working.

BUILD: Fixes for Ubuntu 20.04 ppa build

---

.github/workflows/check_commit_style.py
.github/workflows/pr-checks.yml

The commit style checker had a hard-coded assumption that the changes
were made against the master branch. For backports that is not the case
though and that's why the script fails for backports as soon as the
master and the backport branch have diverged.

CI: Fix PR checks for backports

---

docs/dev/build-instructions/build_installer.md

I assume we want to support and use the most recent version of WixSharp. The description does not mention a specific version.
This change changes the link to WixSharp from the v1.15.0.0 release to the releases page, which shows the most recent release first.

DOCS: Link WixSharp to latest releases page

---

src/mumble/AudioWizard.cpp

The `bPosTest` variable indicates whether we're in the middle of a test.
It causes the user's direction vector to freeze so that it always "looks" straight ahead.
When completing the wizard, `accept()` is called and thus the variable is set to false again.
However, when the wizard is closed prematurely, `reject()` is called instead.

FIX(client): Positional audio not working properly after canceling audio wizard

---

src/mumble/AudioInput.cpp

Push-to-mute requires a constant button press (not togglable), so reminding them that they are muted is not really useful in that case.
The use case that targets is using push-to-mute to talk to another VOIP client (a game for example) with the same people as in the mumble channel. Without this change the user will get the muted cue each time they use push-to-mute.

FEAT(client): Do not play the mute cue when push-to-muted

---

src/mumble/Log.cpp

The commit message describes it:
```
For most images, this results in far better legibility, especially if they contain text, such as memes or web comics - you currently need to squint at the screen often, because it's always sized down to 480x270.
People with windows smaller than that will get a horizontal scroll. Scrolling is still better than having an image that's illegible because it's too small, and small images will never be scaled up this way.
800x600 should be okay since 1920x1080 is a very common desktop resolution by now.
This is a stopgap measure until images can be sized per client.
```
As mentioned, I don't know if this is an acceptable change, but I thought I'd propose it anyway as a stopgap. For our user group, this already significantly improves the use of images to the …

Make posted images slightly larger to improve legibility

---

src/mumble/GlobalShortcut_win.cpp

Backport "BUILD(windows): Fix missing include"

---

src/mumble/GlobalShortcut_win.cpp

GlobalShortcut_win was using stringstream objects but did not include
the sstream header for it.

BUILD(windows): Fix missing include

---

src/mumble/AudioWizard.cpp

Backport "FIX(client): Positional audio not working properly after canceling audio wizard"

---

src/mumble/AudioInput.cpp

Backport "FEAT(client): Do not play the mute cue when push-to-muted"

---

src/mumble/Log.cpp

Backport "CHANGE(client): Resize posted images to 800x600 instead of 420x270"

---

plugins/MumblePlugin_v_1_0_x.h

Instead of passing the type name directly we pass the alias instead in
order to make code more easily portable between API versions.

REFAC(plugin): Rename plugin ID parameter

---

.backportrc.json

In order to use https://github.com/sqren/backport we need a bit of
configuration in our project but in the end this has the potential to
save use a lot of time when backporting commits to a stable release
series.

MAINT: Add config for backport CLI

---

docs/dev/build-instructions/build_installer.md

The requirement to set the BUILD_NUMBER variable was not mentioned in
the docs for how to build an installer.
Fixes #5060

DOCS: Mention BUILD_NUMBER for building installer

---

docs/dev/build-instructions/build_static.md

DOCS(build): Add a missing dependency to static build instructions.

---

installer/ServerInstaller.cs
src/murmur/CMakeLists.txt

The produced binary as well as the used cmake target was renamed from
"murmurd" and "murmur" respectively to "mumble-server".
The installer code was adapted accordingly.

BUILD(cmake): Rename server to mumble-server

---

installer/ServerInstaller.cs
src/murmur/CMakeLists.txt

- BUILD(cmake): Rename server to mumble-server (#5062)

Backport "BUILD(cmake): Rename server to mumble-server (#5062)" to 1.4.x

---

src/mumble/Settings.cpp

FIX(pipewire): Do not initialize stream with 0 channels

---

src/mumble/AudioWizard.cpp

See #5081 
The PR is separated in two commits, the first one is the actual fix (should probably be cherry-picked to 1.4.x), the second one is just a minor code refactor, as we are doing `aosSource = nullptr;` in `restartAudio()` already.

Fix deadlock when cancelling AudioWizard

---

src/mumble/AudioWizard.cpp

- FIX(audiowizard): Reset AudioOutput ownership before restartAudio() (#5082)

Backport "FIX(audiowizard): Reset AudioOutput ownership before restartAudio() (#5082)" to 1.4.x

---

src/mumble/Themes.cpp

2cd4635e85ba8629e98a956d1f73d99f2a166728 has integrated the theme
submodule into the main repository and by doing so renamed the default
theme from "Mumble" to "Default".
When using no theme (The "None" theme) for the application's style, it
would fail to find the necessary icons though.
This is because the fallback theme that is used in this case was still
referring to the old "Mumble" theme that no longer exists.
This commit fixes the issue by changing the name referenced in the
fallback theme to "Default" again.
Fixes #5086

FIX(client, ui): Use proper name for fallback theme

---

plugins/amongus/amongus.cpp
plugins/cod2/cod2.cpp
plugins/se/se.cpp

- BUILD(windows): Fix missing include (#5077)

Backport "BUILD(windows): Fix missing include (#5077)" to 1.4.x

---

installer/ClientInstaller.cs
src/mumble_exe/CMakeLists.txt

The overlay binaries were expected to be present in any case when the
installer was built. Same goes for the g15-helper binary.
This commit makes sure these binaries are only included if the
respective feature was actually built before.
Fixes #5058

BUILD(installer): Include binaries only if built 

---

installer/ClientInstaller.cs
src/mumble_exe/CMakeLists.txt

Backport "BUILD(installer): Include binaries only if built " to 1.4.x

---

plugins/mumble_positional_audio_utils.h

The windows header was included for the definition of M_PI. However
given that we define _USE_MATH_DEFINES globally for all source files and
cmath is included already, this symbol is defined by cmath, making the
windows-specific header superfluous.

REFAC(client): Remove unnecessary include

---

plugins/HostWindows.cpp
plugins/HostWindows.h

I was wrong in #4566.
Turns out `Toolhelp32ReadProcessMemory()` is simply a wrapper for `ReadProcessMemory()` that takes care of opening an handle to the process and closing it.
For reference: MicrosoftDocs/sdk-api#793

FIX(client): Use ReadProcessMemory() instead of Toolhelp32ReadProcessMemory()

---

plugins/HostWindows.cpp
plugins/HostWindows.h

- FIX(client): Use ReadProcessMemory() instead of Toolhelp32ReadProcessMemory() (#5087)

Backport "FIX(client): Use ReadProcessMemory() instead of Toolhelp32ReadProcessMemory() (#5087)" to 1.4.x

---

scripts/backportTranslations.py

Up to now when a stable release series was split off from the master
branch, there was essentially no (good) way of backporting new
translations for source strings in the stable series.
This is because usually the master branch contains new or changed source
strings and thus simply merging the respective commits into the stable
series can cause all sorts of trouble.
The script added by this commit takes care of that by comparing
translation files translation by translation and only updates the
translation if there is a newer translation for the exact same source
string in the target (master) branch.
This takes care of cases in which translations are added or altered
after the stable series has been split off.
It does not however work as soon as the source string for that
translation has …

MAINT: Translations backport script

---

src/mumble/mumble.entitlements.plist

The file is used by `codesign`.
The following entitlements are enabled:
- `com.apple.security.device.audio-input`: To capture audio.
- `com.apple.security.cs.disable-library-validation`: To load plugins.
- `com.apple.security.network.client`: To start TCP connection and to send UDP packets.
- `com.apple.security.network.server`: To receive UDP packets.

MAINT(macOS): Add client entitlements plist, for hardened runtime to work

---

docs/dev/plugins/PositionalAudioPlugin.md

- DOCS(plugins): Fix missing pointer star in example (#5105)

Backport "DOCS(plugins): Fix missing pointer star in example (#5105)" to 1.4.x

---

src/mumble/PluginInstaller.cpp

On Windows the PluginInstaller was unable to extract certain zip files.
As it turns out the issue was that the filestreams were not opened
in binary mode which threw Poco off in certain situations.
Therefore the fix simply is to use binary mode when working with
these file streams. Note that the used Poco filestream class operates
in binary mode by default.

FIX(client): PluginInstaller unable to extract zips

---

src/mumble/PluginInstaller.cpp

- FIX(client): PluginInstaller unable to extract zips (#5106)

Backport "FIX(client): PluginInstaller unable to extract zips (#5106)" to 1.4.x

---

src/mumble/PluginManager.cpp

The channel count and sample rate parameters for this function were
passed in reverse order (compared to the API spec). This would cause
plugins using this callback to calculate buffer sizes (sampleCount *
channelCount) to be vastly too high and therefore they most likely tried
accessing the output buffer at indices outside its actual range.

FIX(client, plugin-api): onAudioOutputAboutToPlay

---

src/mumble/PluginManager.cpp

- FIX(client, plugin-api): onAudioOutputAboutToPlay (#5114)

Backport "FIX(client, plugin-api): onAudioOutputAboutToPlay (#5114)" to 1.4.x

---

src/mumble/Audio.h
src/mumble/AudioOutput.cpp
src/mumble/AudioOutputSample.cpp
src/mumble/AudioOutputSpeech.cpp
src/mumble/AudioOutputUser.h

Adds a slight 0.6 millisecond delay between ears depending on where the sound source is coming from.
There is a small time delay (interaural time delay or ITD) between your
ears depending on the sound source position on the horizontal plane and
the distance between your ears. This commit will add this delay by using
the extra sound data in the audio buffer.
Fixes #2324

FEAT(client): Positional interaural delay

---

src/murmur/ServerDB.cpp

Inside ServerDB there was one SQL statement that reads values off from
one table and writes them into another one. However while doing so, it
(in contrast to the other statements doing the same for other DB
versions) also queries the `last_disconnect` value. This values is
unused in the INSERT statement though and therefore reading it in the
first place seems to be pointless.

FIX(server): Value queried but not used in DB insertion

---

src/murmur/ServerDB.cpp

- FIX(server): Value queried but not used in DB insertion (#5131)

Backport "FIX(server): Value queried but not used in DB insertion (#5131)" to 1.4.x

---

src/murmur/ServerDB.cpp

13b85a3 introduced a new feature for
which it is required to remember when the last user disconnected from a
channel. However in the upgrade path that variable was part of the query
but not of the insert statement.
Note this reverts the changes of #5131 as it seems the approach taken there was wrong.

FIX(server): Also INSERT queried value 

---

src/Mumble.proto

The datatype used for permissions in proto messages is inconsistent. In
2 of 3 message types it is uint32 but in erverSync it is uint64.
We can't change that anymore but this commit adds a note about it into
the proto file.
Ref: #5139

DOCS: Add note to Mumble.proto

---

src/mumble/Log.ui

The UI file was using a name that was alredy in use. This has been
introduced with 6a10b4627fab7352601e4bde8d0a440c132bf7b3. However as of
now this did not cause any trouble except a warning during building.
Nonetheless this commit fixes the duplicate name. In fact the fix is
performed by changing how the "problematic" component is laid out in
the first place (entirely removing the need for a GridLayout).
Fixes #5148

FIX(client): Duplicate name in Log.ui

---

src/mumble/JackAudio.cpp
src/mumble/JackAudio.h
src/mumble/PAAudio.cpp
src/mumble/PAAudio.h
src/mumble/PipeWire.cpp
src/mumble/PipeWire.h
src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h

It looks like some Backends were unnecessarily waiting for another thread, that didn't exist.
I tested all affected backends, they all still work for me (though obviously this should be tested by at least someone else).
Mumble starts up instantly now.
Fixes #5157
Fixes #5022

FIX(client): Remove unnecessary wait for mutex

---

src/mumble/JackAudio.cpp
src/mumble/JackAudio.h
src/mumble/PAAudio.cpp
src/mumble/PAAudio.h
src/mumble/PipeWire.cpp
src/mumble/PipeWire.h
src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h

- FIX(client): Remove unnecessary wait for mutex (#5159)

Backport "FIX(client): Remove unnecessary wait for mutex (#5159)" to 1.4.x

---

src/murmur/CMakeLists.txt

The code that was used to create the tray icon was perfectly fine. The
issue was that the icon that was set was invalid because Qt did not find
the respective resource (which for some reason leads to the tray entry
not being shown at all).
The issue was that auto-RCC was not enabled for the server. This is
probably because usually the server doesn't need it, except on Windows
where we have that tray icon. While the respective resource files were
present and added as needed, the lack of this property caused Qt to
never process the resource file and thus thew icon was always missing.
Fixes #4930

FIX(server): Tray icon not shown on Windows

---

src/murmur/CMakeLists.txt

- FIX(server): Tray icon not shown on Windows (#5172)

Backport "FIX(server): Tray icon not shown on Windows (#5172)" to 1.4.x

---

Dockerfile

The Dockerfile was still referencing the old name (Murmur)
for the server executable but this has changed to mumble-server
by now causing the Dockerfile to error.
Fixes #5171

MAINT(docker): Update server executable name

---

src/mumble/PluginUpdater.cpp

PR #5152 overhauled the code for the plugin installer such that it
can completely unload a plugin before attempting to overwrite it.
However when the installer is called from the updater, that doesn't work
since the installer itself was still holding a handle to that plugin,
preventing it from unloading. Therefore this commit makes sure that the
installer releases its handle before calling the installer.
Fixes #4946

FIX(client): Plugin updater keeping plugin locked

---

Dockerfile

- MAINT(docker): added frequently used sql drivers (#5175)

Backport "MAINT(docker): added frequently used sql drivers (#5175)" to 1.4.x

---

src/mumble/PluginUpdater.cpp

- FIX(client): Plugin updater keeping plugin locked (#5176)

Backport "FIX(client): Plugin updater keeping plugin locked (#5176)" to 1.4.x

---

src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h

PR #5159 removed a few seemingly unneeded waits on audio system
initialization which drastically sped up Mumble's startup. However as it
turns out for PulseAudio some waiting is actually required as the system
initializes asynchronously but we require the knowledge about the init
result.
Instead of adding an arbitrary wait time again though, this commit adds
a mechanism that waits exactly as long as necessary for the init to be
completed and then continues. That still cuts down the waiting time
tremendously when comparing with the previous (arbitrary) wait time of 1
second.
Fixes #5181

FIX(client, audio): PulseAudio not initializing

---

src/mumble/PulseAudio.cpp
src/mumble/PulseAudio.h

- FIX(client, audio): PulseAudio not initializing (#5183)

Backport "FIX(client, audio): PulseAudio not initializing (#5183)" to 1.4.x

---

plugins/amongus/structs.h

- FIX(positional-audio): Update Among Us plugin to work with v2021.6.30s (#5185)

Backport "FIX(positional-audio): Update Among Us plugin to work with v2021.6.30s (#5185)" to 1.4.x

---

plugins/se/client.h

- FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.2.0 (#5186)

Backport "FIX(positional-audio): Update Source Engine plugin to work with L4D2 2.2.2.0 (#5186)" to 1.4.x

---

.ci/azure-pipelines/steps_linux.yml

The packaging of the AppImage did not yield usable binaries for a long
time now but it does take up a significant amount of time in the Linux
CI and (more importantly) tends to fail every now and then causing the
entire build to fail with it.
For this reason, we will no longer bundle an AppImage at least until we
properly fixed the underlying issues and are able to produce working
AppImages again.

CI(azure): Don't package AppImage

---

installer/ClientInstaller.cs

This allows to install .mumble_plugin bundles simply by double-
clicking on them in the explorer.

BUILD(installer): Add file assoc. for plugin-files

---

installer/ClientInstaller.cs

- BUILD(installer): Add file assoc. for plugin-files (#5169)

Backport "BUILD(installer): Add file assoc. for plugin-files (#5169)" to 1.4.x

---

src/mumble/API.h
src/mumble/API_v_1_0_x.cpp

PR #5161 introduced a new facet to the synchronization of plugin API
calls in order to avoid the possibility of running into a deadlock.
However the mechanism of using timeouts had the flaw that the dispatched
execution of the API call would access the promise object which lives on
the Stack of the calling wrapper function. In case of a timeout though
that wrapper function may exit, before the actual API implementation
has run. Thus as soon as that function will end up running, it will
access memory that no longer exists as the referenced promise object has
gone out of scope already.
This commit fixes this by creating the promise on the Heap instead and
using a shared pointer on it such that whichever function is the last to
exit, it the one that frees the resource. This guarantees that …

FIX(client): Potential access of invalid object

---

.ci/azure-pipelines/steps_linux.yml

- CI(azure): Don't package AppImage (#5191)

Backport "CI(azure): Don't package AppImage (#5191)" to 1.4.x

---

src/mumble/API.h
src/mumble/API_v_1_0_x.cpp

- FIX(client): Potential access of invalid object (#5188)

Backport "FIX(client): Potential access of invalid object (#5188)" to 1.4.x

---

scripts/org.mumble_voip.mumble.desktop

This adds the StartupWMClass to the .desktop file which allows pinning Mumble to the dash/dock/whatever in all major desktop environments. Since most package maintainers ship their own .desktop file where this is fixed this fixes it for everyone who compiles Mumble from source.

MAINT(desktop-file): Add StartupWMClass

---

scripts/generateChangelog.py

Merge commits of backports follow a little different pattern than
regular merge commits. This has to be accounted for in the script
generating the changelog.

MAINT: Make changelog script work with backports

---

scripts/generateChangelog.py

- MAINT: Make changelog script work with backports (#5199)

Backport "MAINT: Make changelog script work with backports (#5199)" to 1.4.x

---

.appveyor.yml

Previously we were using the test certificate but since we now have a
release cert, we should use that instead.

MAINT: Use release cert on SignPath

---

src/murmur/Meta.cpp
src/murmur/Server.cpp
src/murmur/Server.h

The check for configured network interfaces at startup has a problem that if IPv4 is not configured for some reason, Mumble will bind to IPv6-only socket, and will not be available over IPv4 until manually restarted.
There's no harm binding to the "any" IPv6 address with `IPV6_V6ONLY` set to 0 even if there're no assigned addresses of either address family. The bind will succeed either way, and will accept connections on any new address configured in the system regardless of the address family.
`QHostAddress::Any` tries to setup an `AF_INET6` socket with `IPV6_V6ONLY` set to 0, and falls back to `AF_INET` in case it's unavailable. However, it will only happen if IPv6 is completely disabled on the system, which is a rare configuration, but nevertheless it will fall back gracefully.
Fixes …

FIX(server): Always bind to both IPv6 and IPv4 by default

---

src/murmur/Meta.cpp
src/murmur/Server.cpp
src/murmur/Server.h

- FIX(server): Always bind to both IPv6 and IPv4 by default (#5209)

Backport "FIX(server): Always bind to both IPv6 and IPv4 by default (#5209)" to 1.4.x

---

Dockerfile

Docker builds was failing on my local due to #5120.
Just adding CA certs and git to perform `git submodule update --init`.
Fixes build if not done. If not needed (already done), build just continues.
-------

MAINT(Dockerfile): Make 'git submodule update' to be recursive.

---

Dockerfile

* Dump CMake logs on failure.
* Set `DEBIAN_FRONTEND=noninteractive` for `apt-get` on final image.
* Use `ARG` instead of `ENV` to prevent variable persisting after build (it can't be assumed that `apt-get` won't be invoked interactively from a running container).
* Add verbosity to `chown`. Might come handy in diagnosing failures.
* A bit of cleanup after package install (`apt-get clean`).
* Remove reference to 'disco' distribution (no longer true) from comments.
I've tested log dumping on failure by just commenting out the `git submodule update` line on a fresh checkout.
Also, using `:latest` as base image is against Dockerfile best practices. Ideally, it should be pinned to a specific distro. I would suggest using latest LTS (Focal, as of now). I can send a PR, if it's OK.

MAINT(Dockerfile): Dockerfile improvements.

---

src/mumble/qttranslations/qt_nl.ts

Some dialog button texts, such as "Cancel" weren't translated in Dutch as they are part of Qt's internal translations. This fixes that.
See also the discussion starting from https://github.com/mumble-voip/mumble/issues/4359#issuecomment-839983019.

TRANSLATION: Add missing Dutch translations for dialog buttons

---

.gitmodules
src/mumble/CMakeLists.txt

Upon switching to CMake, we kept using our own fork for the repository because a few fixes for the build were needed.
Now that the upstream repository works correctly as submodule, we can fetch from it directly.
Please note that tests provided in the Opus repository are not built anymore.

BUILD(opus): Fetch submodule from upstream repository

---

.gitmodules
src/mumble/CMakeLists.txt

- BUILD(opus): Fetch submodule from upstream repository (#5229)

Backport "BUILD(opus): Fetch submodule from upstream repository (#5229)" to 1.4.x

---

src/mumble/qttranslations/qt_nl.ts

- TRANSLATION: Add missing Dutch translations for dialog buttons (#5226)

Backport "TRANSLATION: Add missing Dutch translations for dialog buttons (#5226)" to 1.4.x

---

docs/dev/maintenance/BackportTranslations.md

DOCS: Backporting translations

---

Dockerfile

The Dockerfile was still referencing the old name (Murmur)
for the server executable but this has changed to mumble-server
by now causing the Dockerfile to error.
Fixes #5171

MAINT(docker): Update server executable name (backported)

---

src/mumble/CoreAudio.h
src/mumble/CoreAudio.mm

Previously, when switching input/output devices at the system level, Mumble would ignore the switch and continue to use the previous device. This patch adds support for proper device switching, allowing Mumble to correctly follow the system input/output device.
Fixes #1013

FIX(client,mac): Add support for input/output device switching on macOS

---

src/mumble/CoreAudio.h
src/mumble/CoreAudio.mm

- FIX(client,mac): Add support for input/output device switching on macOS (#5273)

Backport "FIX(client,mac): Add support for input/output device switching on macOS (#5273)" to 1.4.x

---

src/User.cpp

In #4875 we changed the comparing between users to be locale-unaware.
During this change, the sorting was made case-sensitive, whereas before
it (potentially) was not.
However, intuitively a user will expect a case-insensitive ordering of
users in the UI. The only problem with that is that a case-insensitive
comparison will not yield a strong ordering between users that use
usernames that only differ in casing (e.g. "tom" and "Tom").
In order to avoid this problem, we now first perform a case-insensitive
comparison and fall back to a case-sensitive one, should the first
comparison yield "equal".
Fixes #5293

FIX(client): Sort users case-insensitively

---

src/User.cpp

- FIX(client): Sort users case-insensitively (#5294)

Backport "FIX(client): Sort users case-insensitively (#5294)" to 1.4.x

---

src/mumble/LookConfig.ui

Previously the maximum allowed value for the "silent user lifetime"
setting (affecting the TalkingUI) was 99 (apparently Qt's default for
spin boxes). However, this prevented users from keeping recent speakers
visible for a couple of minutes, which might be desirable (especially in
a situation in which Mumble is only running in the background while one
is doing other stuff).

CHANGE(client): Max. value for silent user setting

---

plugins/CMakeLists.txt
plugins/deadLockPlugin/CMakeLists.txt
plugins/deadLockPlugin/deadLockPlugin.cpp

This plugin tests the built-in deadlock prevention of the Mumble plugin
API.

TEST(client): Add plugin to test deadlock prevention

---

src/mumble/PluginConfig.cpp
src/mumble/PluginManager.cpp
src/mumble/ServerHandler.cpp

This fixes the compile errors encountered when building without the
manual plugin (`-Dmanual-plugin=OFF`).
Fixes #5304

BUILD(client): Fix compile errors without manual plugin

---

src/Connection.cpp
src/Connection.h
src/mumble/ServerHandler.cpp
src/murmur/Server.cpp

The commit in this PR is an exceed from #5119 and part of the ssl overhault; for an in deep discussion, see there. For more information about this commit itself, see the commit's message.
Quick additional note: According to the TLS standard, the CA's certificate may be ommitted. If there are now no intermediates, the only remaning (and therefor the first and simultaneously last) certificate is the users certificate. Since most likely no mumble user ever sended multiple certificates with intermediates (and the ssl system even ignores some errors), this bug was not noticed before.

FIX(server,client): Validate/use the correct certifiacte from a chain

---

src/mumble/GlobalShortcut_win.cpp

0e17c5394c5597b746c6076d16c732e2a4a04e7f introduced a migration system
from migrating from the old shortcut format to the newer one (on
Windows) but it seems in this new function it was forgotten to check
whether support for GKey and/or XBox-Input was actually included or not.
This could lead to compile errors when e.g. using -Dgkey=OFF when
invoking cmake.
This PR fixes that by adding the mentioned include-guards.
Fixes #5322

BUILD(client): Add missing ifdef guards

---

src/mumble/GlobalShortcut_win.cpp

- BUILD(client): Add missing ifdef guards (#5323)

Backport "BUILD(client): Add missing ifdef guards (#5323)" to 1.4.x

---

src/mumble/Messages.cpp
src/murmur/Messages.cpp

When joining a server, a client is placed in the root channel by
default. However, this placement was implicit as the server would
explicitly exclude this information to be broadcast with the sent
UserState message.
In order to facilitate external applications to get this all right, this
commit now makes sure that this information is shared explicitly (just
as if the user would be placed in a different channel because the server
remembered their last channel).
Note: This commit also adapts the client code to only move the user if
the specified channel is not its current channel already, but even
without this change, the client code will handle the additional
information gracefully.
Fixes #5270

CHANGE: Make joining root channel explicit

---

src/Connection.cpp
src/Connection.h
src/mumble/ServerHandler.cpp
src/murmur/Server.cpp

- FIX(server,client): Validate/use the correct certifiacte from a peers chain (#5280)

Backport "FIX(server,client): Validate/use the correct certifiacte from a peers chain (#5280)" to 1.4.x

---

src/mumble/PluginManager.cpp

ff8be8b80eae32311345f90ee5d184076c023017 introduced a fix that prevented
duplicate entries from showing up in the plugin search path by ensuring
that only canonical, absolute paths are used.
However, the function to canonicalize a path will return an empty
string, if the given path doesn't exist. Thus by adding a non-existing
path to the search path, an empty string was added instead, which means
that the current working directory is considered part of the plugin
search path. This could lead to misleading errors about "non-plugins"
being found in a "plugin directory".
This commit fixes this by first checking whether the specified directory
actually exists and only then adding it to the search path (in
canonicalized form).

FIX(client): Wrong entry in plugin search path

---

src/mumble/PluginManager.cpp

- FIX(client): Wrong entry in plugin search path (#5339)

Backport "FIX(client): Wrong entry in plugin search path (#5339)" to 1.4.x

---

src/mumble/PluginUpdater.h

BUILD: Fix potential use of uninitialized var

---

src/mumble/PluginManager.cpp
src/mumble/PluginManager.h

This PR fixes a crash that could occur on logging plugin-related info such as
linking/unlinking a positional data plugin and also fixes a deadlock that could
occur in the linking process.
Fixes #5319

FIX(client): Fix crash & deadlock on plugin link/unlink

---

src/mumble/MainWindow.cpp
src/mumble/Markdown.cpp

The markdown "parser" would get hung up on links followed by a quote due
to the way links were recognized. This commit makes sure links will only
contain allowed characters. In order to do so, the HTML escaping must
not be done before the "parsing" though.
Furthermore these changes seemed to cause too many newlines to be
inserted in the HTML, so as an additional post-processing we now only
replace double-newlines with `</br>` and remove the single linebreaks.
Fixes #5347
---

FIX: Markdown parsing messing up links

---

src/mumble/MainWindow.cpp
src/mumble/Markdown.cpp

- FIX: Markdown parsing messing up links (#5351)

Backport "FIX: Markdown parsing messing up links (#5351)" to 1.4.x

---

src/mumble/AudioInput.cpp

When the input signal is very loud and clipping, the output of RNNoise
is very distorted, way more than the input signal.
This is because RNNoise outputs a signal that is unbounded and sometimes
goes over the limits of the signed 16-bit signal that Mumble uses
internally. When Mumble converts RNNoise output signal to 16-bit,
integer overflow occurs and creates a very loud distortion.
Mumble now clamps the output of RNNoise which results in a signal that
is not more distorted than the input signal.
Fixes #4391

FIX(client): very distorted RNNoise output

---

src/mumble/Log.cpp

While beta testing 1.4.x the patrons of my server at first adored the new larger images but soon grew to dislike them as they were always larger than what they wanted to keep their Mumble windows. Having to scroll around their chat windows to see the entire image soon turned the larger images into an anti-feature.
A compromize between the 1.3 size of 480x270 and the currently in beta 1.4 size of 800x600 is what this commit suggests.
It should be noted that the aspect ratio of the original image is kept in the transform. This means that for the original 1.3 max sizes the much smaller vertical limit of 270px was most often the limiting factor among the two in 1.3.
480/270=1.78
600/400=1.5
800/600=1.33
These new limits of 600x400 also strikes a balance between the original Mumble 1.3 aspect …

CHANGE(client): Rezise chat images to 600x400 instead of 800x600

---

src/mumble/AudioInput.cpp

- FIX(client): very distorted RNNoise output (#5363)

Backport "FIX(client): very distorted RNNoise output (#5363)" to 1.4.x

---

src/crypto/CryptStateOCB2.cpp
src/crypto/CryptStateOCB2.h

Functions ocb_encrypt and ocb_decrypt share the same set of encrypt and decrypt contexts. However, they are invoked
in different threads (audio input thread and server handler thread).
This may lead to conflicts that would crash Mumble. This patch separates contexts used in these two functions to avoid such conflicts.
Fixes #5361

FIX(crypto): Sharing EVP context between threads crashes Mumble

---

src/mumble/Log.cpp

- CHANGE(client): Rezise chat images to 600x400 instead of 800x600 (#5359)

Backport "CHANGE(client): Rezise chat images to 600x400 instead of 800x600 (#5359)" to 1.4.x

---

plugins/amongus/structs.h

- FIX(positional-audio): Update Among Us plugin to work with v2021.12.15s (1421) (#5376)

Backport "FIX(positional-audio): Update Among Us plugin to work with v2021.12.15s (1421) (#5376)" to 1.4.x

---

docs/DockerCompose.md
scripts/docker-compose.yml

This commit adds an example docker-compose.yml file. This makes it much easier to create a docker image of mumble and gives examples about how the mounts and ports etc should work.

DOCS(docker): Docker compose

---

.github/workflows/pr-checks.yml

The old version was using Ubuntu Groovy as a base, which went EOL in
July, 2020 and apparently now the package repositories (required to run
this action) have been shut down.
The newer release uses Ubuntu focal (20.04) which is an LTS and will
remain supported for a while.

CI: Update clang-format action

---

src/mumble/CMakeLists.txt

It seems like defining this macro isn't necessary after all but could be
causing warnings during the build process due to redefinition of the
macro.
Fixes #5375

BUILD(client): Remove HAVE_STDINT_H definition

---

.github/workflows/pr-checks.yml

- CI: Update clang-format action (#5384)

Backport "CI: Update clang-format action (#5384)" to 1.4.x

---

plugins/ProcessBase.cpp
plugins/ProcessBase.h
plugins/ProcessLinux.cpp
plugins/ProcessLinux.h
plugins/ProcessWindows.cpp
plugins/ProcessWindows.h
plugins/amongus/CMakeLists.txt
plugins/cod2/CMakeLists.txt
plugins/cod2/cod2.cpp
plugins/gtav/CMakeLists.txt
plugins/se/CMakeLists.txt
plugins/se/se.cpp

When performing a debug build, the "deadlock plugin" will be included
in the build, which uses the thread functionality of the std. However,
during compiling there would be an error about a symbol in thread.hpp
not being found (_beginthreadex). As it turns out, this was due to us
having a header file called Process.h, which would shadow the windows-
specific header file defining the mentioned symbol.
Therefore, in this commit we rename the Process base class to
AbstractProcess and rename the files accordingly, fixing that error.
See also: https://stackoverflow.com/q/27230258

BUILD(windows): Fix debug build

---

src/mumble/CMakeLists.txt

- BUILD(client): Remove HAVE_STDINT_H definition (#5383)

Backport "BUILD(client): Remove HAVE_STDINT_H definition (#5383)" to 1.4.x

---

.cirrus.yml
CMakeLists.txt
docs/dev/build-instructions/cmake_options.md
src/CMakeLists.txt
src/crypto/CryptographicHash.cpp
src/mumble/CMakeLists.txt
src/murmur/CMakeLists.txt

In theory LTO could give us a bit more performance than what we are
currently seeing. Client-side this will probably not be very noticeably
but on the server-side a few drops of extra performance can't hurt.
LTO will be enabled by default in all non-Debug builds. It remains
disabled for Debug builds as this is expected to be the kind of build
that a developer will use when they perform their work and there it is
useful to be able to go through multiple iterations of the program,
without waiting long times on the linker each time.

BUILD: Enable LTO, if supported 

---

src/mumble/mumble.plist.in
src/murmur/murmur.plist.in

The previously used sourceforge-related IDs were really outdated and
were therefore changed.
And while we were touching these already, the description was also
adapted to remove the "intended for gamers" touch from it.

MAINT: Change app ID in plist files

---

src/crypto/CryptographicHash.cpp

FIX(crypto): no such function empty for QByteArray

---

scripts/docker-compose.yml

This adds support for UDP to the docker compose file. Without it will only allow TCP traffic.

MAINT(docker): Docker Compose UDP Support

---

.gitmodules
docs/dev/Profiling.md
docs/dev/build-instructions/cmake_options.md
src/CMakeLists.txt
src/murmur/Messages.cpp
src/murmur/Server.cpp
src/murmur/TracyConstants.h

Tracy (https://github.com/wolfpld/tracy) is a profiler that is aimed at
having a very low impact on the runtime performance and is thus suitable
to be used in production systems to figure out what is going on and how
the code is performing.
For the time being, this commit instruments only the server code.
Furthermore, the instrumentation is performed in a rather minimalistic
way that should suffice to start profiling audio and control message
processing but is definitely far from being complete. Further
instrumentation will be added on-demand.

FEAT(server): Add support for the tracy profiler

---

src/ChannelListenerManager.cpp
src/ChannelListenerManager.h
src/mumble/Database.cpp
src/mumble/Database.h
src/mumble/MainWindow.cpp
src/mumble/Messages.cpp

This is done, since the underlying framework for how channel listeners
are handled (more specifically: where they are stored) will be changed
in an upcoming PR. This upcoming change will cause listener persistence
to only apply to registered users. Thus, if the current persistence
feature was to be retained, that would mean that when introducing this
change, we'd remove a feature from Mumble.
As that is not a great thing to do, we'll remove the feature now that it
is still unreleased and then the upcoming change will _introduce_
persistence for some users instead of taking it away from others.
Furthermore, this PR fixes a little bug that made it possible for channel listeners
to be shown multiple times in the UI.

CHANGE(client): Remove channel listener persistence

---

COMMIT_GUIDELINES.md

The used example was a bit misleading

DOCS: Clarify MAINT type in commit guidelines

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash

ef045be7fe04657e27141922000d84a144b75c26 changed how the
mumble-version.py script works, but these two scripts have not been
adapted to it yet. This commit fixes that.

BUILD: Fix build error

---

src/mumble/BanEditor.cpp

When using the BanEditor to manually create a new Ban entry, it was
really easy to get the "mask" property wrong, which had the effect of
apparently not performing any action at all, when clicking on the "Add"
button.
The underlying problem was most likely that the "mask" field defaults to
128, which is only valid for IPv6 addresses. When entering an IPv4
address, the mask would be considered invalid (through some internal
wizardry) and thus the Ban would not be added.
However, the user was not presented with any kind of error message that
would have hinted at the problem.
This commit tackles this issue by first of all validating that the
entered IP address is valid. If it is not, then the respective input
field will be colored red. If it is, the mask spin box's maximum value
will …

FEAT(client): Improve handling of IP masks in BanEditor

---

README.md

OpenBSD has provided binary packages for years,
both `mumble` and `murmurd` work.
(I happen to currently maintain the audio/mumble port.)

DOCS(client): Mention OpenBSD support

---

scripts/mumble-build-number.py

There were a few typos in the program's logic regarding the handling of
a provided password which rendered its use invalid.

MAINT: Fix password use in build-number script

---

.appveyor.yml

- MAINT: Change build-number token for AppVeyor (#5418)

Backport "MAINT: Change build-number token for AppVeyor (#5418)" to 1.4.x

---

src/mumble/AudioWizard.cpp

Move the declaration/definition of `iMessage` to where it is used,
otherwise the build fails with
```
src/mumble/AudioWizard.cpp:95:10: error: variable 'iMessage' set but not used [-Werror,-Wunused-but-set-variable]
quint32 iMessage = Settings::LogNone;
^
1 error generated.
```
Build-tested on OpenBSD 7.0-CURRENT using
```
$ cc --version
OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.0
Thread model: posix
InstalledDir: /usr/bin
```

BUILD(audiowizard): Fix build with -Dspeechd=OFF -Dwarnings-as-errors=ON

---

docs/dev/build-instructions/cmake_options.md
src/mumble/CMakeLists.txt

OS packages (at least on Linux and BSDs) prefer prepackaged libraries to
bundled/statically linked versions where possible.
Introduce `rnnoise` (default `ON`) and make `bundled-rnnoise` default to
it's value;  this retains current behaviour.
This way, `rnnoise=OFF` disables use of RNNoise completely and a simple
`bundled-rnnoise=OFF` requires the system's library.
Tested on OpenBSD 7.0-CURRENT.

BUILD(client): RNNoise: Support linking against the system library

---

.github/workflows/pr-checks.yml

- CI: Update clang-format action (#5431)

Backport "CI: Update clang-format action (#5431)" to 1.4.x

---

scripts/docker-compose.yml

As discussed on #5435. It will restart container on daemon restart or container crashing, but will keep it off if stopped manually.
See [docs](https://docs.docker.com/config/containers/start-containers-automatically/) for reference.

MAINT(docker): Set Docker Compose restart policy to 'unless-stopped'.

---

src/murmur/main.cpp

FIX(server): Add missing line breaks to --help output

---

docs/dev/build-instructions/build_linux.md

The concept of RELEASE_ID was dropped with PR #5401 in commit 6caa808e6.
Thus, drop its leftovers from the documentation.

DOCS(build): Clean up leftovers from RELEASE_ID concept

---

docs/dev/build-instructions/README.md

DOCS: Updated build instructions to remove duplicated step
There's a duplicated step in the build instructions, which is already covered on line 8.  This change removes the unneeded duplicate step.

DOCS: Updated build instructions to remove duplicated step

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/support.yml

MAINT(github): List OpenBSD as supported OS

---

plugins/HostLinux.cpp
plugins/mumble_positional_audio_linux.h

As per POSIX, basename(3) is defined in libgen.h. Without including this header file the code presently does not compile (on musl) due to `-Werror` and a `-Wimplicit-function-declaration` warning.

BUILD: include libgen.h for files which use basename(3)

---

src/mumble/ALSAAudio.cpp

As per POSIX.1-2008, the correct header to include for poll(3) is
poll.h. Including sys/poll.h instead of poll.h causes the following
warning message on Alpine Linux:
/usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
Due to `-Werror`, this ultimately causes the build to fail.

BUILD: include poll.h for poll(3) (instead of sys/poll.h)

---

src/mumble/AudioInput.cpp

The clampFloatSample function is only used when rnnoise support is enabled, when it isn't this the presence of the function (since it is static) causes a `-Wunused-function` warning which ultimately ends up causing a build error due to `-Werror`.

BUILD: Fix -Wunused-function when compiling without rnnoise

---

docs/dev/build-instructions/cmake_options.md
src/mumble/CMakeLists.txt

The library is readily available in OpenBSD's version of X[0].
Follow suit with Linux in enabling.
Noticed by the warning upon startup:
```
-<W>2022-01-21 02:30:40.548 GlobalShortcutX: No XInput support, falling back to polled input. This wastes a lot of CPU resources, so please enable one of the other methods.
+<W>2022-01-21 02:34:00.159 GlobalShortcutX: Using XI2 2.4
```
0: https://xenocara.org/

BUILD(client): Enable XInput2 support on OpenBSD by default

---

CMakeLists.txt
docs/dev/build-instructions/cmake_options.md

Encourage OS package maintainers to run tests by `packaging=ON` implying
`tests=ON`.
Keep `online-tests=OFF` by default since it is common practise for
packages to be built in unprivileged environments, e.g. without network.

BUILD: Build tests in package builds by default

---

src/mumble/CMakeLists.txt

The bundled version is 0.7.0 and versions >0.7.x are NOT supported.
At least on OpenBSD (only packaging 0.11.x), the built would fail.
Yield and error at configure time with this fix.
CMake's `find_package()` function accepts an optional `version` argument
but Mumble's `find_pkg()` wrapper does not (treating it as package), so
roll our own check/error:
```
-- celt found | Version: 0.11.1
CMake Error at src/mumble/CMakeLists.txt:677 (message):
CELT 0.7.x is required, found 0.11.1!
```
Relates to #4476.

BUILD(client): CELT: Require version 0.7.x when using the system library

---

LICENSE

Varioues files were bumped but not this one.  Spotted by following the
https://www.mumble.info/LICENSE link in another file.

MAINT: Update copyright notice to 2022

---

src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/Settings.cpp

As request in #2453, this commit implements the industry standard
for microphone hold time for voice activation detection. The calculation
that yields hold time (s) from the iVoiceHold setting is described and
comments are added to describe the function of related fields.
Implements #2453.

FEAT(client): Industry standard for hold time

---

installer/ClientInstaller.cs

In the installer refactor (88e17868493b7e08fe3339069c11cbc5c39e62e5) these registry keys were removed, so new installs did not register a URL protocol and users weren't able to use `mumble://` links.
This is a direct translation of `Files.wxs` to equivalent WixSharp code.
Closes #5473

FIX(installer): Re-add URL protocol registration registry keys on install

---

src/mumble/main.cpp

In a Plasma Wayland session the Mumble icon was not used in the task bar,
instead the generic Wayland icon shows up.
Setting the desktop file name resolves this.
Fixes #4851

FIX(client): Icon not used on Plasma Wayland session

---

src/Timer.cpp

Including sys/time.h instead of time.h was causing compile errors in
certain environments.
Related: f6a546b7f673540c261a07b6e6a1047eabe8022c
Fixes #5546

BUILD(client,server): Include time.h instead of sys/time.h

---

src/mumble/PipeWire.cpp

PipeWire is correctly built and enabled in a Flatpak runtime, but does not properly intialize because the .so filename of the library is named slightly differently there.
See also https://github.com/flathub/info.mumble.Mumble/issues/19#issuecomment-1023001248
After this, I can select PipeWire as back end [in the Flatpak build](https://github.com/flathub/info.mumble.Mumble). As mentioned in the above issue, it doesn't actually _work_ yet after selecting it (no input or output is generated), but it's a first step. I'll do some digging to see if I can fix the second issue as well in a separate PR.

FIX(client): Fix PipeWire not being usable in Flatpaks

---

installer/ClientInstaller.cs

- FIX(installer): Re-add URL protocol registration registry keys on install (#5521)

Backport "FIX(installer): Re-add URL protocol registration registry keys on install (#5521)" to 1.4.x

---

scripts/runClangFormat.sh

Current problems:
- bash(1) is not always installed (by default), /bin/sh is
- (Open)BSD find(1) requires at least one path argument, i.e. `.` which GNU
find(1) implies
- (Open)BSD find(1) does not support `-ipath`
git-ls-files(1) benefits:
- gitignore(5) files are honored
- simpler/more powerful patterns (see gitglossary(7) wrt. `pathspec`)
- `runClangFormat.sh` can be run from git subdirectories to only format
selected files (explicitl passing files could be easil implemented)
- works on every system with git(1), no portability issues (see above)
The one "drawback" with git-ls-files(1) is requiring git(1) working tree
rather than a release tarball, but active development requries git
anyway, so that does not seem like a blocker.
Only run xargs(1) if files were listed (`-r`), since we …

CI: scripts/runClangFormat.sh: Use git-ls-files(1)

---

docs/dev/build-instructions/common_build_errors.md

TYPE(Scope): DOCS
Found this extremely helpful and I had difficulty finding this error.
https://githubmemory.com/repo/mumble-voip/mumble/issues/5120
Adds a line to FAQ for updating submodules

DOCS: Add FindPythonInterpreter error to common build errors

---

src/mumble/mumble.entitlements.plist

- MAINT(macOS): Add client entitlements plist, for hardened runtime to work (#5093)

Backport "MAINT(macOS): Add client entitlements plist, for hardened runtime to work (#5093)" to 1.4.x

---

src/murmur/main.cpp

- FIX(server): Add missing line breaks to --help output (#5443)

Backport "FIX(server): Add missing line breaks to --help output (#5443)" to 1.4.x

---

themes/Default/lock_locked.svg
themes/Default/lock_unlocked.svg

The current channel lock icons introduced for 1.4.x use a line-art
style. This stands out against the other icons that show in the
channel tree (user mute status, comments, friend hearts, etc.) because
they are all filled in.
The included changes to the icons are:
- Switch to a filled-in style
- Set opacity to 75% to match other icons
- Slightly shrink them, as they look somewhat large compared to the
channel comment icon.

CHANGE(ui): Make lock icons fit with other icons

---

src/mumble/Audio.cpp
src/mumble/AudioInput.cpp
src/mumble/AudioOutputSpeech.cpp
src/mumble/CMakeLists.txt
src/mumble/Global.cpp
src/mumble/MainWindow.cpp
src/mumble/Messages.cpp
src/mumble/ServerHandler.cpp

CELT support will be removed, so Opus will not be optional any longer.
Remove all code outside of `USE_OPUS` scope with
```
$ git grep -w -l USE_OPUS -- '**/*'.{h,hpp,cpp} |
xargs unifdef -B -D USE_OPUS -M ''
```
This is a no-op since it has already been defined unconditionally.
Supersedes #5505.

BUILD(client): Remove USE_OPUS define, make Opus a hard requirement

---

CMakeLists.txt
overlay_gl/CMakeLists.txt

Get sane default configuration and prepare the build for future fixes.
- BUILD(client): overlay_gl: Do not build overlay-xcompile on OpenBSD
- BUILD(client): overlay_gl: Require libGL includes on OpenBSD
- BUILD(client): overlay_gl: Do not build by default on OpenBSD (for now)

BUILD(client): overlay_gl: Detect OpenBSD

---

src/mumble/Markdown.cpp

If a link contains any percent encoded characters (e.g. umlauts),
the markdown parser sets a wrong offset, thus resulting in a cut off
link in the log.
This is fixed by adjusting the url parsing regex to include a percent
symbol.

FIX(client): Percent encoded links not clickable

---

plugins/gtav/gtav.cpp

Without the change the build fails on upcoming gcc-12 as:
/build/mumble/plugins/gtav/gtav.cpp:13:13:
error: 'unique_ptr' in namespace 'std' does not name a template type
13 | static std::unique_ptr< Game > game;
|             ^~~~~~~~~~
/build/mumble/plugins/gtav/gtav.cpp:12:1:
note: 'std::unique_ptr' is defined in header '<memory>';
did you forget to '#include <memory>'?
11 | #include <cstring>
+++ |+#include <memory>
12 |

BUILD(positional-audio): Fix missing <memory> include

---

docs/dev/build-instructions/cmake_options.md
src/mumble/CMakeLists.txt

This commit introduces an option that toggles between using a bundled
version of nlohmann_json (default) and looking for a version installed
on the system instead.
Fixes #5584

BUILD(client): Add option to use system JSON lib

---

src/mumble/Database.cpp
src/mumble/Global.cpp
src/mumble/Global.h
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/main.cpp

This PR contains fixes related to the migration of the data directory as performed
in #5531.
The following issues are fixed
1. The database wouldn't be found on Windows, after the migration has been performed (after having restarted Mumble once)
2. Plugin settings were lost due their explicit dependence on the plugin's path

FIX(client): Data dir migration issues

---

src/mumble/main.cpp

The switch to a new settings format messed up the setting for whether or
not the audio wizard has been shown already or not. For new
installations, the wizard would be shown, but the fact that it has been
shown is not reflected in the settings causing the wizard to be re-shown
upon a restart.
This commit fixes this by making sure that the respective setting is set
after the wizard has been shown for the first time.

FIX(client): Audio wizard being shown repeatedly

---

plugins/gtav/Game.cpp
plugins/gtav/Game.h
plugins/gtav/gtav.cpp

- [Merge PR #5532: Update GTAV positional audio plugin to v1.58.2545](https://github.com/mumble-voip/mumble/pull/5532)

Backport "Merge PR #5532: Update GTAV positional audio plugin to v1.58.2545" to 1.4.x

---

scripts/sign_macOS.py

Right now we are using `osxdist.py` to generate a DMG package from scratch.
The script also takes care of signing the content.
However, our `mumble-releng` repository has had a dedicated script called `sign-dmg.py` since 2013.
In fact, that's what we have always been using to sign the app bundle.
As we're planning to eventually ditch `osxdist.py` in favor of CPack's generator, we decided to complete `sign-dmg.py`.
The script now:
- Takes care of signing all binaries in the bundle in addition to it, effectively replacing `osxdist.py`.
- Supports single binaries, replacing `sign-mach-o.py` (which only called `codesign()` from `sign-dmg.py`).
- Supports PKG packages.
- Provides a `--config` option to specify the path to the configuration file. Default: `$HOME/.sign_macOS.cfg`.
- Provides a …

MAINT: Add script to sign macOS binaries and packages

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

The automatic upgrade from VS2019 to VS2022 broke our build and in order
to prevent that in the future, we now pin the used VS version to 2022.
Later upgrades will have to be performed explicitly.

CI(azure): Pin to VS2022

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

- [CI(azure): Pin to VS2022](https://github.com/mumble-voip/mumble/pull/5610)

Backport "CI(azure): Pin to VS2022" to 1.4.x

---

src/mumble/CMakeLists.txt

Without this, building against the latest poco snapshot results in errors like:
/usr/bin/ld: /builddir/build/BUILD/mumble-1.4.230.src/src/mumble/PluginManifest.cpp:72: undefined reference to `typeinfo for Poco::XML::Element'

BUILD(cmake): Find and link Poco::XML 

---

src/mumble/Log.cpp

As reported in #4491, #4986 and #5430, since the changes to the chat in
the 1.4.x release, some tags would "pollute" the rest of the log, i.e.
cause future log entries to be contained within them.
The source of the issue seems to be that the `insertBlock` method of
`QTextCursor` appears to correspond to the `<p>` HTML tag. The `<p>` tag
may only contain inline elements, but `QTextEdit` will not fail outright
when inserting block-level elements and will instead attempt to correct
the invalid input which results in the behaviour reported in the above
issues (as far as I can tell).
My proposed solution is to use the `insertFrame` method for all
messages.
Fixes #4491

FIX(client): resolve list tags, etc. polluting log

---

src/mumble/CMakeLists.txt

- [BUILD(cmake): Find and link Poco::XML](https://github.com/mumble-voip/mumble/pull/5616)

Backport "BUILD(cmake): Find and link Poco::XML" to 1.4.x

---

src/mumble/Markdown.cpp

Having plain http as the default means that a site, even though able to support https, will be able to fall back to using the insecure and outdated protocol.
Furthermore, major browsers already support https by default, falling back to legacy http in the cases where a website does not support https connections, e.g. [Chromium](https://blog.chromium.org/2021/03/a-safer-default-for-navigation-https.html), [Firefox](https://blog.mozilla.org/security/2021/08/10/firefox-91-introduces-https-by-default-in-private-browsing/).
Therefore, this commit makes it so that a link without a protocol specification will have `https://` prefixed to be clickable instead of `http://`.

CHANGE(client): Make https default link protocol

---

src/mumble/Log.cpp

- [FIX(client): resolve list tags, etc. polluting log](https://github.com/mumble-voip/mumble/pull/5619)

Backport "FIX(client): resolve list tags, etc. polluting log" to 1.4.x

---

src/MumbleProtocol.cpp

Received compiler warning of an assert that is always true.
The assert checked if variable is negative but it is an unsigned variable.
unsigned at: 
https://github.com/mumble-voip/mumble/blob/74faaba32ea94f9654d461e5e544cf0d7ad36dd8/src/MumbleProtocol.h#L64
https://github.com/mumble-voip/mumble/blob/74faaba32ea94f9654d461e5e544cf0d7ad36dd8/src/MumbleProtocol.h#L96
https://github.com/mumble-voip/mumble/blob/74faaba32ea94f9654d461e5e544cf0d7ad36dd8/src/MumbleProtocol.h#L105
fixes: 
gcc (GCC) 11.2.0
manjaro
```
Building CXX object src/CMakeFiles/shared.dir/MumbleProtocol.cpp.o
/home/pat/Desktop/eclipse/mumble/src/MumbleProtocol.cpp: In member function ‘void Mumble::Protocol::UDPAudioEncoder<role>::preparePreEncodedSnippets()’:
/home/pat/Desktop/eclipse/mumble/src/MumbleProtocol.cpp:338:49: …
```

BUILD(client,server): Fix warning for always true assert

---

Dockerfile

By using the list form, no shell is spawned and the TERM signal is forwarded to the mumble-server process

BUILD(server): Fix TERM signal not forwarded in docker container

---

src/murmur/AudioReceiverBuffer.h
src/tests/TestAudioReceiverBuffer/TestAudioReceiverBuffer.cpp

1d45d991aa4d53b6c1bd7d7cae0126a21f3991e1 refactored the audio processing
on the server and introduced the new AudioReceiverBuffer class. In the
function that is responsible for obtaining the current range of
receivers that shall obtain the identical audio packet, the passed begin
iterator was always dereferenced. However, in the case in which the
receiver list is actually empty begin == end and therefore dereferencing
the begin iterator is undefined behavior.
This could lead to the entire server crashing (or could work just fine -
UB is great at this) but in any case, this is a severe problem.
The fix consists of a simple check for this specific situation and an
early return in that case.

FIX(server): Crash due to dereferencing invalid iterator

---

Dockerfile
README.md

the the docker image that is built by default uses murmur user to run
the server. When users use bind mount volumes the host system is
expected to match the permissions (UID/GID) of the created murmur user
or else they will get permission errors
this change allows users who build the docker image to specify which
user id and group id to be used in the docker image
Closes #5634

BUILD(server): allow users to specify the UID/GID for the murmur user

---

src/mumble/GlobalShortcut_macx.mm

When building on a Mac -Doverlay=OFF, the compiler would produce a
warning about an unused variable in the macOS shortcut implementation.
This commit silences the warning, by explicitly marking the variable in
question as unused.
Fixes #5636

BUILD(client): Fix warning about unused variable

---

plugins/ql/ql.cpp

From my commit on the issue:
> The "spectator" property address was slightly off, which prevented the plugin from working at all. Additionally, the previous "map" address only worked for listen servers.
> 
> I've corrected the first, and found a new, properly-working address for the second.
Thanks to members of the Mumble Matrix room for pointing me in the right direction to help debug this issue!

FIX(positional-audio): Fix Quake Live plugin

---

.github/workflows/build.sh
.github/workflows/build.yml
.github/workflows/pr-checks.yml
.github/workflows/set_environment_variables.sh

GitHub Actions previously did not use the build number token. This is
changed by this commit. In order to to so, the build process has been
outsourced into its own script.

CI: Also fetch build number token on GA

---

.github/workflows/build.sh
.github/workflows/build.yml
.github/workflows/pr-checks.yml
.github/workflows/set_environment_variables.sh
scripts/mumble-build-number.py

Backport "CI: Also fetch build number token on GA"

---

src/mumble/PipeWire.cpp

Since version 0.3.51, PipeWire has support for buffers with a size of 0 being passed in the process callback. More specifically, this feature was added in commit [`96286fb8b11658a0fdaa61194504a3f9541b25e6`](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/96286fb8b11658a0fdaa61194504a3f9541b25e7) ("resample: use a -1 buffer size to drain") in PipeWire.
Unfortunately, this causes an endless loop, because we try to destroy the PipeWire stream, but it keeps waiting for the node to be completely drained, which now never happens because it keeps calling `processCallback()` where we feed buffers with a size of 0 to it.
To fix this problem, we do not longer pass 0-size buffers to PipeWire.
Instead we now push silence, if we don't have any data available. This is what PipeWire prefers …

FIX(client): Prevent endless loop when disconnecting PipeWire stream

---

.github/workflows/release_dispatch.yml

This will trigger a workflow in mumble-voip/mumble-docker every time
we release a new version here.

CI: Add dispatch for new releases

---

src/mumble/PipeWire.cpp

- [Merge PR #5648: FIX(client): Prevent endless loop when disconnecting PipeWire stream](https://github.com/mumble-voip/mumble/pull/5648)

Backport "Merge PR #5648: FIX(client): Prevent endless loop when disconnecting PipeWire stream" to 1.4.x

---

src/murmur/ServerDB.cpp
src/murmur/ServerDB.h
src/murmur/main.cpp

- [Merge PR #5646: FIX(server): Improve rememberchannelduration compare logic](https://github.com/mumble-voip/mumble/pull/5646)

Backport "Merge PR #5646: FIX(server): Improve rememberchannelduration compare logic" to 1.4.x

---

plugins/ql/ql.cpp

- [Merge PR #5640: FIX(positional-audio): Fix Quake Live plugin](https://github.com/mumble-voip/mumble/pull/5640)

Backport "Merge PR #5640: FIX(positional-audio): Fix Quake Live plugin" to 1.4.x

---

plugins/amongus/structs.h

- [Merge PR #5612: FIX(positional-audio): Update Among Us plugin to work with v2022.3.29s (1864)](https://github.com/mumble-voip/mumble/pull/5612)

Backport "Merge PR #5612: FIX(positional-audio): Update Among Us plugin to work with v2022.3.29s (1864)" to 1.4.x

---

plugins/gtav/gtav.cpp

- [Merge PR #5587: BUILD(positional-audio): Fix missing <memory> include](https://github.com/mumble-voip/mumble/pull/5587)

Backport "Merge PR #5587: BUILD(positional-audio): Fix missing <memory> include" to 1.4.x

---

src/mumble/Markdown.cpp

- [Merge PR #5564: FIX(client): Percent encoded links not clickable](https://github.com/mumble-voip/mumble/pull/5564)

Backport "Merge PR #5564: FIX(client): Percent encoded links not clickable" to 1.4.x

---

src/mumble/PluginManager.cpp

- [Merge PR #5554: FIX(client): Context and identity not getting cleared](https://github.com/mumble-voip/mumble/pull/5554)

Backport "Merge PR #5554: FIX(client): Context and identity not getting cleared" to 1.4.x

---

src/Timer.cpp

- [Merge PR #5550: BUILD(client,server): Include time.h instead of sys/time.h](https://github.com/mumble-voip/mumble/pull/5550)

Backport "Merge PR #5550: BUILD(client,server): Include time.h instead of sys/time.h" to 1.4.x

---

src/mumble/main.cpp

- [Merge PR #5536: FIX(client): Icon not used on Plasma Wayland session](https://github.com/mumble-voip/mumble/pull/5536)

Backport "Merge PR #5536: FIX(client): Icon not used on Plasma Wayland session" to 1.4.x

---

src/mumble/PipeWire.cpp

- [Merge PR #5530: FIX(client): Fix PipeWire not being usable in Flatpaks](https://github.com/mumble-voip/mumble/pull/5530)

Backport "Merge PR #5530: FIX(client): Fix PipeWire not being usable in Flatpaks" to 1.4.x

---

src/mumble/CMakeLists.txt

- [Merge PR #5503: BUILD(client): CELT: Require version 0.7.x when using the system library](https://github.com/mumble-voip/mumble/pull/5503)

Backport "Merge PR #5503: BUILD(client): CELT: Require version 0.7.x when using the system library" to 1.4.x

---

scripts/sign_macOS.py

- [Merge PR #5428: MAINT: Add script to sign macOS binaries and packages](https://github.com/mumble-voip/mumble/pull/5428)

Backport "Merge PR #5428: MAINT: Add script to sign macOS binaries and packages" to 1.4.x

---

macx/scripts/osxdist.py

If the osxdist script was not executed within the build directory, it
would not bundle the built plugins (most notably the Link plugin) as it
was using a relative path and was ignoring the binary dir command-line
option.
This is remedied by this PR.
Fixes https://github.com/mumble-voip/mumble/issues/5571

BUILD(macos): Fix plugins not getting bundled 

---

src/mumble/Markdown.cpp
src/mumble/PluginManifest.cpp
src/mumble/QtWidgetUtils.cpp
src/mumble/QtWidgetUtils.h
src/mumble/SearchDialog.cpp

- [Merge PR #5609: BUILD(client): Fix various issues](https://github.com/mumble-voip/mumble/pull/5609)

Backport "Merge PR #5609: BUILD(client): Fix various issues" to 1.4.x

---

macx/scripts/osxdist.py

- [Merge PR #5667: BUILD(macos): Fix plugins not getting bundled](https://github.com/mumble-voip/mumble/pull/5667)

Backport "Merge PR #5667: BUILD(macos): Fix plugins not getting bundled" to 1.4.x

---

docs/dev/build-instructions/build_linux.md

DOCS(build_linux): Added build instructions for Debian, w/ related Ubuntu issues
Added build instructions for Debian, with notes on changes affecting Ubuntu, and a *workaround* for an Opus bug causing a crash (in the docs, not in code).
https://github.com/mumble-voip/mumble/issues/5302

DOCS(build_linux): Added build instructions for Debian, w/ related Ubuntu issues

---

.ci/azure-pipelines/assertNoTranslationChanges.sh
.ci/azure-pipelines/release_macos.bash

CI(azure): Switch to using python3 instead of python

---

scripts/vcpkg/get_mumble_dependencies.ps1
scripts/vcpkg/get_mumble_dependencies.sh

It probably used to be a dependency of at least another package we install.

MAINT(vcpkg): Install protobuf

---

.appveyor.yml
.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

f999081ab82d0a70843036bd2ebb2629921facde enabled the MySQL plugin for Qt.
Turns out its master dependency (libmysql) cannot be built for x86:
microsoft/vcpkg#11214
This issue leaves us with two choices:
1. Get rid of x86 builds altogether.
2. x64 builds with MySQL plugin, x86 ones without. Potential confusion.
We asked on our Matrix channel whether anyone used official x86 releases.
Nobody did, which is a very good thing considering x86 (32 bit) CPUs are no more.
In addition to that, Microsoft dropped the platform with Windows 10 2004.

CI: Remove x86 Windows build(s), update build environment(s)

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

We used to use a self-hosted macOS CI runner but since we were only
using that for Nightly builds, we frequently ran into situations where
some issue was only appearing there which meant that while for the PR
the CI succeeded, it would fail after the change had been merged in.
As this is not a desirable situation, this commit makes sure that we are
using the same macOS runner for all CI runs. For simplicity we are using
the Azure hosted ones for that purpose.

CI(macos): Use azure-hosted runner

---

scripts/vcpkg/get_mumble_dependencies.ps1
scripts/vcpkg/get_mumble_dependencies.sh

- [Merge PR #5676: MAINT(vcpkg): Install protobuf](https://github.com/mumble-voip/mumble/pull/5676)

Backport "MAINT(vcpkg): Install protobuf" to 1.4.x

---

src/mumble/Settings.cpp
src/tests/TestSettingsJSONSerialization/generate_test_case.py

In the 1.4.230 release, we enabled RNNoise by default as there have been
lots of reports of how well it works. However, after the release we saw
numerous reports complaining about bad audio quality, which was traced
back to having RNNoise enabled.
For some reason the outcome of having RNNoise enabled is very different
in different scenarios. Sometimes it works miraculously well and other
times it worsens the audio quality to an unbearable level.
There seems to be a higher chance of RNNoise messing up, when using
Windows, but the same effect has also been observed on Linux. It might
also depend on the quality of the used microphone (better quality = less
noise -> RNNoise starts doing weird stuff), but we don't have any
definitive clues yet.
Because of this, we will change the default noise …

CHANGE(client): Disable RNNoise by default

---

.ci/azure-pipelines/main.yml

CI(macos): Use correct build env on macOS nightly builds

---

scripts/info.mumble.Mumble.appdata.xml.in

Fixed FreeDesktop AppStream metadata showcasing Windows screenshots

---

src/mumble/Settings.cpp

- [Merge PR #5677: CHANGE(client): Disable RNNoise by default](https://github.com/mumble-voip/mumble/pull/5677)

Backport "Merge PR #5677: CHANGE(client): Disable RNNoise by default" to 1.4.x

---

overlay_gl/init_mac.c

The cgl symbol was resolved but never used, which triggered a warning
in our macOS CI.

REFAC(macos,overlay): Remove unused symbol

---

plugins/Module.h

Without the change mumble build fails on this week's gcc-13 snapshot as:
plugins/Module.h:13:9: error: 'uint64_t' does not name a type
13 | typedef uint64_t procptr_t;
|         ^~~~~~~~
plugins/Module.h:12:1: note: 'uint64_t' is defined in header '<cstdint>';
did you forget to '#include <cstdint>'?
11 | #include <unordered_map>
+++ |+#include <cstdint>
12 |

BUILD: Fix missing <cstdint> include

---

plugins/Module.h

- [BUILD: Fix missing <cstdint> include](https://github.com/mumble-voip/mumble/pull/5703)

Backport "BUILD: Fix missing <cstdint> include" to 1.4.x

---

plugins/HostLinux.h
plugins/HostWindows.h
plugins/ProcessBase.cpp
plugins/ProcessBase.h
plugins/amongus/Game.cpp
plugins/amongus/Game.h
plugins/gtav/Game.cpp
plugins/gtav/Game.h
plugins/gtav/gtav.cpp
plugins/gtav/structs.h
plugins/mumble_legacy_plugin.h

It should now work flawlessly with all variants (Rockstar, Steam, Epic Games).

FEAT/REFAC(positional-audio): Rewrite GTAV plugin, define "procid_t" to "uint64_t"

---

.github/workflows/code-ql.yml

CodeQL Action v2 was released 2022-03-30.
Deprecation of v1 is scheduled for December 2022. [1]
Fixes a CI warning.
[1] https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

CI(codeql): Upgrade CodeQL action version v1 -> v2

---

docs/dev/build-instructions/build_static.md

Although installing MFC is mentioned in setup_visual_studio.md,
identifying where the header file is expected from is not obvious.
A C++ environment may already be installed without MFC, where the VS setup docs may not be followed/opened before-hand.

DOCS(winbuild): Add troubleshooting for missing MFC dependency

---

src/mumble/GlobalShortcut_win.cpp

Prior to the implementaiton of raw mouse input, a low-level mouse hook was used for capturing mouse events. Windows would emit a single WM_* event per button state change. With the move to capturing raw mouse input events, it was expected that this behavior remained, despite now needing to listen for WM_INPUT events.
However, unlike when using the low-level hook, WM_INPUT events can contain data for multiple simultaneous mouse state changes. If this occurred, Mumble would register none of the state changes.
Changing the logic to account for multiple state changes in a single event correctly allows for all states changes to be registered.
Fixes mumble-voip#5706

FIX(client): Register simultaneous mouse button presses separately

---

src/ServerResolver.cpp
src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h

Previously, Mumble would always use the original hostname when verifying a server certificate. When the actual server hostname (resolved through an SRV record) differs from the original hostname, it should be used instead.
Fixes #3563

FIX(client): properly verify certificates when SRV records are used

---

src/murmur/Meta.cpp

In theory these changes should cause the server to no longer silently
ignore encountered INI syntax errors.
In practice however, it seems that it is pretty much impossible to
create an INI file that Qt actually considers erroneous and thus this
code essentially doesn't work. But in case Qt ever fixes this weird
behavior, at least in theory Mumble users should immediately profit from
it.
Fixes #5749

FIX(server): Don't silently ignore errors in INI

---

overlay_gl/CMakeLists.txt

We use the CHECK_INCLUDE_FILE macro without previously including the
corresponding CMake module. This usually still works as the Opus CMake
files include the same module and apparently are loaded before
processing the overlay CMakeLists.txt. Thus, thee Opus code fixes this
issue for us by accident.
However, when building without the bundled Opus version, this leads to a
build error as in this case the Opus CMake scripts are not processed by
us.
Fixes #5742

BUILD(cmake, overlay): Include missing CMake module

---

scripts/murmur.ini

The example murmur.ini file was missing a few options which were added
by this commit.
Fixes #5732

DOCS: Document missing option in murmur.ini

---

overlay_gl/CMakeLists.txt

- [BUILD(cmake, overlay): Include missing CMake module](https://github.com/mumble-voip/mumble/pull/5752)

Backport "BUILD(cmake, overlay): Include missing CMake module" to 1.4.x

---

src/mumble/Overlay_macx.mm

The removed code was part of some logic introduced in
f6d9c4f7b57bc8163f392bdf50bda520f107b72f but the functional parts have
been removed when getting rid of all Qt4-specific code parts.
This left a few now unused variables in the code which in more recent
compiler versions would cause a warning (and thus in the default
settings a build error).
Since the code doesn't do anything anymore, this commit fully removes
the remaining parts of this code snippet.
Fixes #5724

BUILD(overlay): Remove dead code

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

Add the ability to press Ctrl+Enter to send a plain text message while
preserving line breaks. This adds an easy way of preserving messages
with line breaks without having to resort to using Markdown.
Implements #5707

FEAT(client): Add shortcut to send plain text messages

---

scripts/murmur.ini

- [DOCS: Document missing option in murmur.ini](https://github.com/mumble-voip/mumble/pull/5753)

Backport "DOCS: Document missing option in murmur.ini" to 1.4.x

---

src/mumble/ACLEditor.cpp

If a recent client (1.4 or newer) was to connect to a pre-1.4 server and
decide to edit a channel's ACL, the user would be presented with the
option to configure the Listen ACL. However, since the server is too old
to know about this particular ACL, setting it will have no effect. Thus,
to the end user this creates the impression that something is broken.
This commit ensures that the Listen ACL is only shown, if the server one
is currently connected to, is recent enough to know about this ACL.
Fixes #5692

FIX(client, ui): Don't display unsupported ACL

---

src/murmur/Server.cpp
src/murmur/Server.h

7439bc4fe6b423ff0d36d3b1d529e474c14e9b01 introduced the ability for
clients to query for their permissions in any given channel. Since that
commit also added an automatic permissions broadcast for channels that a
client enters (and also its parent channel), it also introduced a
system to keep track of whether a given permission set has already been
broadcast to a given client. Supposedly this was meant as to not flood
the client with PermissionQuery messages if it just keeps switching
between the same channels (and thus already knows about the respective
permissions after having joined a channel for the first time).
Oddly enough though, when a client explicitly requests to be informed
about a channel's permissions, the cache would also be consolidated and
if the server was under the …

FIX(server): Don't ignore explicit PermissionQuery

---

src/murmur/Server.cpp

The suppress state of a user represents whether the user is currently in
a channel in which they don't have the Speak ACL. As of now this state
is only updated whenever the user switches channel.
However, the suppress state should also change, if the ACL for a given
channel change. This is what the current commit does. If this is not
done, a user will be able to continue speaking in a channel where they
should not be able to and only if they leave and re-join the channel
will the new ACL take effect.
To avoid such a situation, the current code updates the suppress state
every time the ACL change.
Fixes #5264

FIX(server): Update suppress state on ACL change

---

src/mumble/UserView.cpp
src/mumble/UserView.h

Fixes #5632 (duplicates: #3773 #3412)
Similar to [``TalkingUI``](https://github.com/mumble-voip/mumble/blob/master/src/mumble/TalkingUIEntry.cpp#L127), this commit changes the way the size of the user status icons is determined.
|scaling|before|after|
|----|----|----|
|100%|![13100](https://user-images.githubusercontent.com/1348773/182947678-e43b3233-a66e-4529-b26d-78109851fd7a.png)|![15100](https://user-images.githubusercontent.com/1348773/182947705-6049ea00-a110-4c06-b4d3-4eca18ab88a3.png)|
|200%|![13200](https://user-images.githubusercontent.com/1348773/182947762-9ada8e46-ff63-4337-936e-d48fbe1c8fdf.png)|![15200](https://user-images.githubusercontent.com/1348773/182947794-0eac3aef-6c2b-4115-9dbd-50161447ff22.png)|
Should probably be tested on other fractional scaling (I can only do …

FIX(ui): User and channel status icons take display scaling into account

---

src/mumble/MainWindow.ui
themes/Default/Dark.qss
themes/Default/Lite.qss
themes/Default/source/Imports/Base Theme.scss

Fixes #5462 
This merge request contains **two** commits:
1) The padding for QMenu items is adjusted according to the Qt behavior change described [here](https://bugreports.qt.io/browse/QTBUG-78238?focusedCommentId=488799&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-488799). It has the side effect that menus without either icon or check-mark are now not reserving space on the left (see new help menu).
| before | after |
| --------  | -------- |
|![screen1](https://user-images.githubusercontent.com/1348773/182615026-b87de977-47f5-473b-8aea-ced73e514b90.png)|![screen1b](https://user-images.githubusercontent.com/1348773/182615091-2292e765-43c6-46a8-a0f4-4db4fb6260cf.png)|
|![screen2](https://user-images.githubusercontent.com/1348773/182615118-5b32d0d6-5905-4 …

FIX(theme): Adapt Qt behavior change regarding padding in QMenu

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

Fixes #3090
Thise merge request contains 2 commits:
1) The shared/copied code for user, listener and channel context menu target selection is unified
2) Adds a ``nullptr`` check to make sure the selected user/channel is used in context menus rather than the most recently used context item. This was an oversight in 4f5089fe30a

FIX(client): Prefer selected tree item for context menu creation

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

- [Merge PR #5773: FIX(client): Prefer selected tree item for context menu creation](https://github.com/mumble-voip/mumble/pull/5773)

Backport "Merge PR #5773: FIX(client): Prefer selected tree item for context menu creation" to 1.4.x

---

src/mumble/UserView.cpp
src/mumble/UserView.h

- [Merge PR #5772: FIX(ui): User and channel status icons take display scaling into account](https://github.com/mumble-voip/mumble/pull/5772)

Backport "Merge PR #5772: FIX(ui): User and channel status icons take display scaling into account" to 1.4.x

---

src/mumble/ACLEditor.cpp

- [Merge PR #5768: FIX(client, ui): Don't display unsupported ACL](https://github.com/mumble-voip/mumble/pull/5768)

Backport "Merge PR #5768: FIX(client, ui): Don't display unsupported ACL" to 1.4.x

---

src/ServerResolver.cpp
src/mumble/ServerHandler.cpp
src/mumble/ServerHandler.h

- [Merge PR #5750: FIX(client): properly verify certificates when SRV records are used](https://github.com/mumble-voip/mumble/pull/5750)

Backport "Merge PR #5750: FIX(client): properly verify certificates when SRV records are used" to 1.4.x

---

src/mumble/GlobalShortcut_win.cpp

- [Merge PR #5739: FIX(client): Register simultaneous mouse button presses separately](https://github.com/mumble-voip/mumble/pull/5739)

Backport "Merge PR #5739: FIX(client): Register simultaneous mouse button presses separately" to 1.4.x

---

src/mumble/MainWindow.cpp

- [FIX(client, ui): Minimal view not always working](https://github.com/mumble-voip/mumble/pull/5777)

Backport "FIX(client, ui): Minimal view not always working" to 1.4.x

---

src/mumble/UserModel.cpp

Removed the duplicate entry for "Talking while being muted on your end"
from the "What's this?" text for users in the TreeView.
Fixes #5793

FIX(ui): Remove duplicate entry for "What's this?" in UserModel

---

src/mumble/UserModel.cpp

- [Merge PR #5794: FIX(ui): Remove duplicate entry for "What's this?" in UserModel](https://github.com/mumble-voip/mumble/pull/5794)

Backport "Merge PR #5794: FIX(ui): Remove duplicate entry for "What's this?" in UserModel" to 1.4.x

---

.ci/azure-pipelines/build_linux.bash
.ci/azure-pipelines/build_macos.bash
.ci/build_windows.bat

- [CI: Use new build-number script](https://github.com/mumble-voip/mumble/pull/5410)

Backport "CI: Use new build-number script" to 1.4.x

---

CMakeLists.txt
docs/dev/build-instructions/cmake_options.md

As the 1.4.x series is in feature-frozen mode, having this enabled by
default does no good (no active development happening on it anymore,
anyway)

BUILD: Disable warnings-as-errors

---

scripts/mumble-build-number.py

Previously the script would assemble the query URL by taking the
individual parameters literally. However, for certain inputs this could
lead to an invalid URL, resulting in an error 400 (Bad Request) when
attempting to make this query to the server.
In order to avoid these situations, the parameters are now properly
encoded (quoted) before being inserted into the query URL. Thus, we
ensure to always produce valid URLs.

MAINT: Fix mumble-build-number.py script

---

scripts/mumble-build-number.py

Backport "MAINT: Fix mumble-build-number.py script"

---

scripts/generateChangelog.py

Sometimes backport commits still have a "Merged PR xxx" part in them,
which we have to strip before processing the message. This is exactly
what this commit adds to the existing changelog script.

MAINT: Extend changelog script

---

src/mumble/Markdown.cpp

When sending a link that contains a percent followed by a digit, where
the digit is <= 2 (e.g. %1), the link's target would be messed up as the
respective %x would be treated as an argument replacement specifier by
Qt (and would thus be replaced by some replacement text).
The reason for this lies in the use of two consecutive calls to
QString::arg, where the second call will gladly try to replace any new
replacement specifications introduced with the first replacement.
The solution is to use an overload of QString::arg, that takes both
replacement texts at the same time and applies them in one go. This
specifically allows to ignore any newly introduced replacement
specifications.
The bug has been introduced with the introduction of Markdown support in …

FIX(client): Broken link targets with percent signs

---

src/mumble/Themes.cpp

Change the skin fallback path from `themes/Mumble` to `themes/Default`
to reflect the change during the integration of the theme submodule.

FIX(theme): update fallback path for skins

---

src/mumble/MainWindow.cpp

Due to a regression introduced in
6aa88691e16c807b998301f2cbecfda599ef4592 when hiding individual UI
components (e.g. the icon toolbar) - possible when using a custom
layout - these elements would re-appear after restarting Mumble (or
after applying the settings or after exiting minimal view).
The reason is that the state of whether or not a given UI component is
shown or not is saved as the window's geometry. In the above commit we
added code that explicitly shows or hides these elements after the
geometry has been restored, thus overwriting the visibility changes of
this geometry restoration.
The fix for this problem is to only explicitly hide the elements when
entering minimal view but let the showing be handled by restoring the
window's geometry. Thus, only those elements are shown …

FIX(client, ui): Make hiding UI elements persistent again

---

src/mumble/UserView.cpp
src/mumble/UserView.h

This merge requests fixes an oversight in #5772 on my part
Fixes one of the issues mentioned in #5817 
I misunderstood the code at hand a little. Especially, I introduced [this line](https://github.com/mumble-voip/mumble/blob/master/src/mumble/UserView.cpp#L114). It was supposed to use the font used by the TreeView to determine the icon size. However, I now realize ``p`` refers to the MainWindow and not the TreeView (UserView INHERITS TreeView), so it was using the wrong font metric.
**Why was this not caught?**
This is coincidentally related to the log text issues #5820. As far as I can tell, the log text uses the exact same font object I was basing my calculations of.
For SOME platforms/Qt the Log text size was decreased for *reasons* that are out of scope of the problem hat hand. All …

FIX(client): Use correct font size for scaling status icons

---

src/mumble/MainWindow.cpp

In 39047d2a57a9288262c5f303d96798a1b1692b8d a new note was added for
when a user enters minimal view but is not connected to a server.
Incidentally, this caused the new note to appear in the popup menu
appearing as a context menu when using a custom layout, which in theory
would allow a manual toggling of that note's visibility. However, this
is not what we want and thus this commit makes sure that this popup menu
only contains entries for UI elements that we really want to be manually
toggelable.

FIX(client, ui): Don't allow manual toggling of minimal view note

---

CMakeLists.txt
scripts/info.mumble.Mumble.appdata.xml.in

Flathub requires this now.
This is done in the same way as the build number.

BUILD(appstream): Include release date

---

src/mumble/Log.cpp

Fixed chat log scaling issue introduced by PR #5619 (my fault, whoops)
The bug fixed by that commit is still fixed after this PR, but the
regression introduced has been resolved.
Added minimum icon size for channel status icons which now scale since PR #5772
Initially, icons were too small at 100% scale.

FIX(ui): resolve text/icon scaling issues

---

cmake/compiler.cmake

Fix a typo in the `COMPILER_HAS_MBIG_OBJ` test which fixes this failure:
```
c++: warning: Wa,-mbig-obj: linker input file unused because linking not done
c++: error: Wa,-mbig-obj: linker input file not found: No such file or directory
```

BUILD(build): Fix -mbig-obj test

---

src/CMakeLists.txt

This has the advantage of not creating a dependency on the respective
.so/.dll which will be present, even if Tracy support is actually
disabled for the binary. This in turn can cause some issues for
packagers.

BUILD: Always build Tracy as static library

---

plugins/gtav/structs.h

https://en.cppreference.com/w/cpp/language/alignas
This fixes compilation when the implicit alignment is not 8 bytes.
It can be the case with 32 bit targets.
---
Fixes #5849.

FIX(positional-audio): Force 8 bytes alignment for CCameraAngles in GTAV plugin

---

CMakeLists.txt
scripts/info.mumble.Mumble.appdata.xml.in

- [Merge PR #5835: BUILD(appstream): Include release date](https://github.com/mumble-voip/mumble/pull/5835)

Backport "Merge PR #5835: BUILD(appstream): Include release date" to 1.4.x

---

src/mumble/MainWindow.cpp

- [Merge PR #5834: FIX(client, ui): Don't allow manual toggling of minimal view note](https://github.com/mumble-voip/mumble/pull/5834)

Backport "Merge PR #5834: FIX(client, ui): Don't allow manual toggling of minimal view note" to 1.4.x

---

src/mumble/MainWindow.cpp

- [Merge PR #5833: FIX(client, ui): Make hiding UI elements persistent again](https://github.com/mumble-voip/mumble/pull/5833)

Backport "Merge PR #5833: FIX(client, ui): Make hiding UI elements persistent again" to 1.4.x

---

src/mumble/Themes.cpp

- [Merge PR #5823: FIX(theme): update fallback path for skins](https://github.com/mumble-voip/mumble/pull/5823)

Backport "Merge PR #5823: FIX(theme): update fallback path for skins" to 1.4.x

---

src/mumble/UserView.cpp
src/mumble/UserView.h

- [Merge PR #5822: FIX(ui): Use correct font size for scaling status icons](https://github.com/mumble-voip/mumble/pull/5822)

Backport "Merge PR #5822: FIX(ui): Use correct font size for scaling status icons" to 1.4.x

---

src/mumble/Markdown.cpp

- [Merge PR #5821: FIX(client): Broken link targets with percent signs](https://github.com/mumble-voip/mumble/pull/5821)

Backport "Merge PR #5821: FIX(client): Broken link targets with percent signs" to 1.4.x

---

scripts/generateChangelog.py

- [Merge PR #5814: MAINT: Extend changelog script](https://github.com/mumble-voip/mumble/pull/5814)

Backport "Merge PR #5814: MAINT: Extend changelog script" to 1.4.x

---

.github/workflows/release_dispatch.yml

- [CI: Add dispatch for new releases](https://github.com/mumble-voip/mumble/pull/5649)

Backport "CI: Add dispatch for new releases" to 1.4.x

---

.github/workflows/winget.yml

This commit introduces an automatic approach that will publish the
Windows installers to the WinGet repository every time a release is
created on GitHub.
Fixes https://github.com/mumble-voip/mumble/issues/5870

CI(github-actions): Automatically publish to WinGet

---

.github/workflows/winget.yml

- [Merge PR #5874: CI(github-actions): Automatically publish to WinGet](https://github.com/mumble-voip/mumble/pull/5874)

Backport "Merge PR #5874: CI(github-actions): Automatically publish to WinGet" to 1.4.x

---

cmake/pkg-utils.cmake

If the systemd module was not installed (or could not be located by pkg-config for other reasons), a big chunk of text would be emitted to stdout stating that no such module could be found and how one might resolve this issue. However, we don't want to throw this at our users as we have backup code paths implemented for the case in which pkg-config can't query the necessary information.
This commit makes sure that these warnings are not emitted anymore.

BUILD(cmake): Silence pkg-config warnings

---

.github/workflows/release_dispatch.yml

- [Merge PR #5884: CI(github-actions): Fix workflow file syntax](https://github.com/mumble-voip/mumble/pull/5884)

Backport "Merge PR #5884: CI(github-actions): Fix workflow file syntax" to 1.4.x

---

src/murmur/RPC.cpp

As it was, the sent UserState message would have only contained the user's session ID, which in and of itself is absolutely useless. Thus, it is better to not send a UserState message in this case.

FIX(server, rpc): Don't send useless UserState message

---

src/mumble/Log.cpp
src/mumble/MainWindow.cpp

The commit 902fe5841ca03f59b introduced links in the log for users and channels. This either never worked correctly, or regressed due to an undocumented behavior change in Qt. The 'channelid' stored in the host part of a QUrl is automatically converted to an IP address (e.g. '1' -> '0.0.0.1') which lets the channel lookup fail. A different code path for clients was present, so the issue was not observed often (or at all) there.
This commit changes the host part composition to contain a string (e.g. '1' > 'id.1') and makes sure this new string is parsed correctly.
Fixes #2961

FIX(client): Fixes link context menu creation for channels

---

src/murmur/ServerDB.cpp

Remember when [I asked why the code was using ``setTimeSpec``](https://github.com/mumble-voip/mumble/pull/5646#discussion_r863694635)? This is actually needed, because the database itself contains UTC and we tell Qt that we do NOT have to cast again. The issue is only really noticeable on certain server local times.
This MR simply adds the ``setTimeSpec`` calls back. It should fix rememerchannelduration, if and only if all database backends use UTC by default (which is assumed in the rest of mumble's code I suppose). If other database backends may use the server's local time, there is a much larger issue here which needs to be addressed.
I noticed this while testing #5907 
Commit message:
In ccbf4072c the rememberchannelduration logic was improved. An explicit call to …

FIX(server): Explicitly set parsed timestamps to UTC for rememberchannelduration

---

.github/actions/install-dependencies/install_ubuntu_shared_64bit.sh
.github/workflows/build.yml

We were still using a runner on Ubuntu 18.04, which is getting deprecated by GitHub in the near future. In order to avoid having failing CI jobs due to that and also in order to keep up with changes in Ubuntu, we now build on 20.04 and 22.04 instead.

CI(github-actions): Update Ubuntu runners

---

auxiliary_files/config_files/info.mumble.Mumble.appdata.xml.in

See [AppStream format documentation](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url). Took donation URL from `.github/FUNDING.yml`.

Add donation link to AppStream Metadata

---

cmake/compiler.cmake

typo.
Also fast-math is not compatiple with opus and rnnoise, so the build fails as is.

BUILD(cmake): the "optimize" option

---

cmake/compiler.cmake

because they block compilation (fast-math)
or are part of -O3 (tree-vectorize)

BUILD(cmake): remove -ffast-math and -ftree-vectorize

---

cmake/qt-utils.cmake

See also https://github.com/mumble-voip/mumble/discussions/5956 for how this manifested itself, if encountered.

BUILD(cmake): Fix syntax error

---

overlay_gl/init_unix.c

glibc 2.34 moved all functionality of various libraries into the main one.
As a result, `dlsym()` is now exported by `libc` instead of `libdl`.
This commit also makes the related code more robust.
We now iterate through a common library name/path list, regardless of the OS.

FIX(overlay): Implement library search list for dlsym(), add "libc.so.6" to it

---

src/Mumble.proto
src/murmur/ClientType.h
src/murmur/Messages.cpp
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

Extended Authenticate message by int ```client_type``` in ```Mumble.proto``` so server knows what type of connection it is(for now it's just 0 for ```REGULAR``` and 1 for ```BOT```). Next I created header file called ```ClientType.h``` where I define enum class for types of connections. This enum is easily extendable for any special connection types in future.
In ```Server.h``` I extended Server class by ```m_botCount``` attribute.
In ```Messages.cpp``` I extended ```msgAuthenticate``` function by a check at the end before authentication log that checks whether connection type is regular or bot and if it's a bot then it increments ```m_botCount``` by one. It also sets ```client_type``` for ```ServerUser```.
Before disconnect in ```Server.cpp``` I check if ```ServerUser``` is ```BOT``` and …

FEAT(server): Flag bot connections, so user count does not get inflated by them

---

src/murmur/Messages.cpp
src/murmur/Server.cpp

This MR contains two changes:
1) Clear the priority speaker flag on channel switch (#5334)
2) Change how the temporary channel mute/deaf permission check is performed. Also: Allow priority speaker in temporary channels. (#1877)
Fixes #5334
Fixes #1877
See also: #5296 #3584

Priority speakers and temporary channels

---

cmake/install-paths.cmake

When packaging is not enabled, do not assert that the install paths are relative. This fixes issues with live ebuilds in Gentoo.
This partially reverts 703af920d8c296cdd0e0567f66d8c3e6b58521ad

BUILD(cmake): only assert install paths are relative when packaging

---

.gitmodules
docs/dev/build-instructions/cmake_options.md
src/mumble/CMakeLists.txt

Since newer Opus versions appear to cause crashes under some
circumstances, we downgrade our Opus submodule to point to the latest
stable release, which is v1.3.1 from 2019.
We will only be able to upgrade again, once the underlying issue causing
the crashes has been identified and fixed.
Fixes https://github.com/mumble-voip/mumble/issues/5302
-----
Old PR description (outdated)
Since our last update, there have been several fixes contributed to the
upstream repo. Thus, we should update our submodule to include these
fixes. In particular
- https://github.com/xiph/opus/commit/ec64b3c5b7abd621dfddee6b4cc115298e5d6803
- https://github.com/xiph/opus/commit/12a356e431d1b2d3531d3d73de330bf9ee9be48b
- https://github.com/xiph/opus/commit/ccb42e05cc6eb98a15874b9695361025b3ee17ab

MAINT: Downgrade Opus submodule 

---

src/mumble/OpusCodec.cpp

This commit ensures that we first try all names for the different base paths in turn, before we fall back for a generic search for that lib based only on the given name.
Otherwise, e.g. the system Opus library could be used instead of the bundled version compiled together with Mumble.

FIX(client): Prevent loading unwanted Opus version

---

.gitmodules
src/mumble/CMakeLists.txt
src/mumble/GlobalShortcut_win.cpp
src/mumble/GlobalShortcut_win.h

We've been receiving quite a few reports about the program seemingly freezing, such as
https://forums.mumble.info/topic/14467-14-conflict-with-flight-control-rudder-pedals.
Turns out there are HID devices, namely advanced controllers, that constantly send packets.
The reason behind the behavior is probably to prevent games from losing track of the physical state.
Qt's event dispatcher blows up and consumes all resources, leading to:
```
QEventDispatcherWin32::registerTimer: Failed to create a timer (The current process has used all of its system allowance of handles for Window Manager objects.)
```
As a result, the UI completely freezes due to events not being processed anymore.
This commit fixes the issue by using an SPSC (Single Producer Single Consumer) queue.
The event loop and 20 ms …

FIX(client): Use SPSC queue for global shortcuts on Windows

---

CMakeLists.txt

The overlay doesn't work on ARM Macs, so we disable it on these machines. However, the CMAKE_SYSTEM_PROCESSOR variable doesn't always hold the target architecture and as it turned out it contained the host arch on our M1 macOS builder, causing the overlay to be disabled for our x86 macOS binaries that were cross-compiled from our M1 machine.
Therefore, we now leverage the system we also use to detect the target architecture for passing it as a macro to our code.

BUILD(cmake): Cross-compile overlay on M1 macs

---

CMakeLists.txt

Now that the 1.5.x branch has been split off, everything on the master branch has to be considered to belong to 1.6.x

MAINT: Bump version number to 1.6

---

CMakeLists.txt
docs/dev/build-instructions/cmake_options.md

BUILD(cmake): Disable warnings as errors by default

---

.appveyor.yml

- [Merge PR #6011: CI(appveyor): Update to latest image version](https://github.com/mumble-voip/mumble/pull/6011)

Backport "Merge PR #6011: CI(appveyor): Update to latest image version" to 1.5.x

---

.appveyor.yml

- [Merge PR #6019: CI(appveyor): Fix vcvars path](https://github.com/mumble-voip/mumble/pull/6019)

Backport "Merge PR #6019: CI(appveyor): Fix vcvars path" to 1.5.x

---

scripts/create_source_archive.py

The advantage of this script is that contrary to git archive it is capable of including submodules into the archive.
All files tracked via git are included in the archive (at the given revision) except for hidden files (files and folders starting with a dot)

MAINT: Added script for creating source archives

---

scripts/create_source_archive.py

- [Merge PR #6016: MAINT: Added script for creating source archives](https://github.com/mumble-voip/mumble/pull/6016)

Backport "Merge PR #6016: MAINT: Added script for creating source archives" to 1.5.x

---

.appveyor.yml
.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml
.ci/build_windows.bat
.ci/install-environment_windows.ps1

This way, we won't have to update the path every time we update the used Visual Studio version (and find the correct one via trial & error).
This solution makes use of Microsoft's vswhere script (see https://github.com/microsoft/vswhere) to locate the VS installation directory. Based on that, we assemble the required path.

CI(windows): Auto-determine path to vcvars script

---

.appveyor.yml
.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml
.ci/build_windows.bat
.ci/install-environment_windows.ps1

- [Merge PR #6022: CI(windows): Auto-determine path to vcvars script](https://github.com/mumble-voip/mumble/pull/6022)

Backport "Merge PR #6022: CI(windows): Auto-determine path to vcvars script" to 1.5.x

---

.appveyor.yml

Apparently we have been using our test certificate for signing our released binaries so far.
This is obviously not what we want, so this commit changes this so now the actual (proper) certificate will be used.

CI(appveyor): Use release signing

---

.appveyor.yml

- [Merge PR #6025: CI(appveyor): Use release signing](https://github.com/mumble-voip/mumble/pull/6025)

Backport "Merge PR #6025: CI(appveyor): Use release signing" to 1.5.x

---

.github/workflows/build.yml
.github/workflows/code-ql.yml

- [Merge PR #6027: CI(github-actions): Avoid duplicate runs](https://github.com/mumble-voip/mumble/pull/6027)

Backport "Merge PR #6027: CI(github-actions): Avoid duplicate runs" to 1.5.x

---

src/murmur/CMakeLists.txt

In #6002 the dbus option was removed and on Linux systems DBus was unconditionally enabled. However, in the server's cmake file a copy&paste error was introduced that would produce an error if the client was not built alongside the server.
This commit fixes this error and therefore makes server-only builds possible again.

BUILD(cmake): Fix server-only builds

---

.github/workflows/build.sh
.github/workflows/build.yml

If the actual build is skipped due to a duplicate workflow run, the build  number script won't run. This can be problematic if this would have been the only place where the script runs for the given commit as that'll mean that for this commit no build number will be tagged on our central server.
Therefore, we now fetch the build number in a separate step that will not be skipped, if the build itself is skipped.

CI(github-actions): Ensure build number tagging

---

.github/workflows/build.sh
.github/workflows/build.yml

- [Merge PR #6033: CI(github-actions): Ensure build number tagging](https://github.com/mumble-voip/mumble/pull/6033)

Backport "Merge PR #6033: CI(github-actions): Ensure build number tagging" to 1.5.x

---

.gitmodules

One of the tools (Gentoo Portage) I occasionally use to build mumble from git  breaks with a submodule without a path. Finishes the removal started in commit d11fd05 by removing the second 3rdparty/opus section and url (without path) added in commit 60d0a86.

MAINT: Finish removing bundled opus git module

---

.gitmodules

- [Merge PR #6059: MAINT: Finish removing bundled opus git module](https://github.com/mumble-voip/mumble/pull/6059)

Backport "Merge PR #6059: MAINT: Finish removing bundled opus git module" to 1.5.x

---

src/murmur/Messages.cpp

- [Merge PR #6057: FIX(server): Multiple channel enter restriction broadcast issues](https://github.com/mumble-voip/mumble/pull/6057)

Backport "Merge PR #6057: FIX(server): Multiple channel enter restriction broadcast issues" to 1.5.x

---

auxiliary_files/CMakeLists.txt

Trying the 1.5.x RC on OpenBSD suddenly installed unit files and wrappers
which are of no use;  I am not aware of other UNIX systems running systemd,
ignore them outside of Linux.

BUILD(cmake): Install systemd related files on Linux only

---

auxiliary_files/CMakeLists.txt

- [Merge PR #6081: BUILD(cmake): Install systemd related files on Linux only](https://github.com/mumble-voip/mumble/pull/6081)

Backport "Merge PR #6081: BUILD(cmake): Install systemd related files on Linux only" to 1.5.x

---

src/mumble/PipeWire.cpp

When destroying the PipeWire object we first destroyed the thread loop and then the stream, but this has to be done in reverse order in order to avoid crashes.
Fixes #6101

FIX(client): PipeWire crash

---

src/mumble/PipeWire.cpp

- [Merge PR #6103: FIX(client): PipeWire crash](https://github.com/mumble-voip/mumble/pull/6103)

Backport "Merge PR #6103: FIX(client): PipeWire crash" to 1.5.x

---

CMakeLists.txt
docs/dev/build-instructions/cmake_options.md
src/CMakeLists.txt
src/mumble/CMakeLists.txt
src/murmur/CMakeLists.txt

Instead of having a fixed setting that affects all build modes, we now set LTO only for release builds (but then for all targets). This has the advantage that a dev doesn't have to switch LTO on and off when switching between Release and Debug builds.

BUILD(cmake): Improve LTO handling

---

CMakeLists.txt
docs/dev/build-instructions/cmake_options.md
src/CMakeLists.txt
src/mumble/CMakeLists.txt
src/murmur/CMakeLists.txt

- [Merge PR #6110: BUILD(cmake): Improve LTO handling](https://github.com/mumble-voip/mumble/pull/6110)

Backport "Merge PR #6110: BUILD(cmake): Improve LTO handling" to 1.5.x

---

src/murmur/AudioReceiverBuffer.cpp
src/murmur/AudioReceiverBuffer.h
src/murmur/Messages.cpp
src/murmur/Server.cpp

- [Merge PR #6107: MAINT: Update Tracy to v0.9.1](https://github.com/mumble-voip/mumble/pull/6107)

Backport "Merge PR #6107: MAINT: Update Tracy to v0.9.1" to 1.5.x

---

src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

- [Merge PR #6117: FIX(server): Actually use the settings provided pluginmessagelimit and -burst](https://github.com/mumble-voip/mumble/pull/6117)

Backport "Merge PR #6117: FIX(server): Actually use the settings provided pluginmessagelimit and -burst" to 1.5.x

---

plugins/link/LinkedMem.h
plugins/link/SharedMemory.cpp
plugins/link/SharedMemory.h
plugins/link/link.cpp
plugins/link/link_tester.cpp

The Link plugin uses an inherently racy protocol to communicate with applications: shared memory with no means of synchronization. This commit makes no changes to this protocol and shouldn't break anything that was working before. That means it doesn't eliminate race conditions, but it does allow the plugin to work without the risk of *data races* specifically, which are undefined behavior.
This is done by using 32-bit atomic operations to copy the LinkedMem struct out of shared memory before reading from it. This should work well, since every field of LinkedMem has a size that's a multiple of 32 bits, and 32-bit atomics are widely supported.
With this change, applications can avoid data races with the Link plugin by also accessing shared memory exclusively with 32-bit atomic operations. …

FIX(plugins): Use atomic operations in Link plugin

---

plugins/link/LinkedMem.h
plugins/link/SharedMemory.cpp
plugins/link/SharedMemory.h
plugins/link/link.cpp
plugins/link/link_tester.cpp

- [Merge PR #6075: FIX(plugins): Use atomic operations in Link plugin](https://github.com/mumble-voip/mumble/pull/6075)

Backport "Merge PR #6075: FIX(plugins): Use atomic operations in Link plugin" to 1.5.x

---

scripts/generate_flag_qrc.py

Sort input file list, so that `mumble_flags.qrc` builds in a reproducible way in spite of non-deterministic filesystem readdir order.
See https://reproducible-builds.org/ for why this is good.
Without this patch, I got
```diff
--- /home/abuild/rpmbuild/BUILD/mumble-1.5.517/build/mumble_flags.qrc      2023-06-09 05:38:13.972000000 +0000
+++ /home/abuild/rpmbuild/BUILD/mumble-1.5.517/build/mumble_flags.qrc     2039-07-11 18:54:57.716000000 +0000
@@ -1,262 +1,262 @@
<!DOCTYPE RCC>
<RCC version="1.0">
<qresource>
-<file alias="flags/ru.svg">../icons/flags/ru.svg</file>
-<file alias="flags/ic.svg">../icons/flags/ic.svg</file>
-<file alias="flags/lk.svg">../icons/flags/lk.svg</file>
...
+<file alias="flags/et.svg">../icons/flags/et.svg</file>
+<file …
```

MAINT: Sort input file list

---

docs/dev/build-instructions/build_static.md
scripts/vcpkg/get_mumble_dependencies.ps1
scripts/vcpkg/get_mumble_dependencies.sh

The different dependency lists have become out-of-sync and/or out-of-date.
This should remedy problems as encountered in #6163.

DOCS/MAINT: Update vcpkg dependency list

---

src/CMakeLists.txt

Microsoft.GSL exports the Microsoft.GSL::GSL target. If the namespace isn't specified, the detection moves on the else() block, and while it still gets detected by FindMSGSL.cmake, a false warning is emitted saying that the version is less than 3.0.

BUILD(cmake): Fix detection of unbundled GSL

---

.gitmodules

~Revert speex library to previous commit, as the current commit was more of a workaround than an actual fix to the problem.~
As our speex fork contained a fix which was more of a workaround than actually fixing the underlying problem we move back to the upstream xiph/speexdsp repository, as we do not need our modified fork anymore.
The actual problem was fixed through https://github.com/mumble-voip/mumble/pull/6154/files but the combination of both fixes manifested a problem ~in Windows~, where the cache was cleared at a point were it should not be cleared yet.
Edit: Mistake found through discussion in https://github.com/mumble-voip/mumble/issues/6177

FIX(client): Fix speex bug, introduced through double fix

---

src/CMakeLists.txt

- [Merge PR #6191: BUILD(cmake): Fix detection of unbundled GSL](https://github.com/mumble-voip/mumble/pull/6191)

Backport "Merge PR #6191: BUILD(cmake): Fix detection of unbundled GSL" to 1.5.x

---

.gitmodules

- [Merge PR #6179: FIX(client): Fix speex bug, introduced through double fix](https://github.com/mumble-voip/mumble/pull/6179)

Backport "Merge PR #6179: FIX(client): Fix speex bug, introduced through double fix" to 1.5.x

---

src/mumble/PulseAudio.cpp

```c++
src/mumble/PulseAudio.cpp:581:24: error: variable-sized object may not be initialized
unsigned char buffer[bytes] = {};
^~~~~
```

FIX(client): Use memset() to initialize VLA

---

scripts/vcpkg/get_mumble_dependencies.ps1
scripts/vcpkg/get_mumble_dependencies.sh

Fixes broken vcpkg dependency installation due to missing comma in the install scripts.

BUILD(vcpkg): Add missing comma in get_mumble_dependencies

---

src/mumble/PulseAudio.cpp

- [Merge PR #6209: FIX(client): Use memset() to initialize VLA](https://github.com/mumble-voip/mumble/pull/6209)

Backport "Merge PR #6209: FIX(client): Use memset() to initialize VLA" to 1.5.x

---

.appveyor.yml
.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

- [Merge PR #6226: MAINT: Update Windows build env to latest version](https://github.com/mumble-voip/mumble/pull/6226)

Backport "Merge PR #6226: MAINT: Update Windows build env to latest version" to 1.5.x

---

docs/dev/build-instructions/build_static.md

- [Merge PR #6230: DOCS(build): fix custom ice link](https://github.com/mumble-voip/mumble/pull/6230)

Backport "Merge PR #6230: DOCS(build): fix custom ice link" to 1.5.x

---

docs/dev/build-instructions/build_static.md

- [Merge PR #6235: DOCS: Change encoding to UTF-8 & clean up error msg in FAQ](https://github.com/mumble-voip/mumble/pull/6235)

Backport "Merge PR #6235: DOCS: Change encoding to UTF-8 & clean up error msg in FAQ" to 1.5.x

---

src/murmur/Meta.cpp

Apparently, QSettings does not care if the specified settings file exists or not. Therefore, no keys will be loaded into the settings as if the file was empty. We specifically check for the missing file to not reference a ghost file in the logs.
Fixes #6077

FIX(server,settings,log): announce if settings file is not present

---

plugins/se/se.cpp

The bug was introduced in #4536.
It was only reported last year and because of a side effect: consistent lag for the entire application.
That's something that should be dealt with independently.

FIX(positional-audio): Fix Source Engine plugin not working on Windows

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioOutput.cpp
src/mumble/ManualPlugin.cpp

This MR contains 3 commits, each related to problems in the current implementation of positional audio.
The problems that are fixed are:
1) The manual position plugin listener indicator was facing the wrong direction
2) The sliders for minimum and maximum positional distance did not properly load values
3) The use case for minimum volume = 0 is broken
Fixes #6149

FIX(client): Positional audio fixes

---

plugins/se/se.cpp

- [Merge PR #6245: FIX(positional-audio): Fix Source Engine plugin not working on Windows](https://github.com/mumble-voip/mumble/pull/6245)

Backport "Merge PR #6245: FIX(positional-audio): Fix Source Engine plugin not working on Windows" to 1.5.x

---

src/murmur/Meta.cpp

- [Merge PR #6231: FIX(server,settings,log): announce if settings file is not present](https://github.com/mumble-voip/mumble/pull/6231)

Backport "Merge PR #6231: FIX(server,settings,log): announce if settings file is not present" to 1.5.x

---

overlay_gl/CMakeLists.txt

Despite the 32-bit library building on FreeBSD-amd64 when the overlay-xcompile option is enabled, it never gets installed.

BUILD(cmake, overlay): Install 32-bit lib on FreeBSD

---

overlay_gl/CMakeLists.txt

- [Merge PR #6192: BUILD(cmake, overlay): Install 32-bit lib on FreeBSD](https://github.com/mumble-voip/mumble/pull/6192)

Backport "Merge PR #6192: BUILD(cmake, overlay): Install 32-bit lib on FreeBSD" to 1.5.x

---

src/mumble/AudioConfigDialog.cpp
src/mumble/Settings.h

- [Merge PR #6134: FEAT(client): Positional audio improvements](https://github.com/mumble-voip/mumble/pull/6134)

Backport "Merge PR #6134: FEAT(client): Positional audio improvements" to 1.5.x

---

src/mumble/Themes.cpp

Previously, all "notice" labels had no font color assigned. That means they would use the selected themes default font color. This is fine, if the user would select any theme in Mumble.
However, if the user would select the 'None' theme, the font color would default to the systems default font color. And, if the user had a dark system theme, that would usually mean a very bright font color.
That very bright font color clashes with the hard-coded faint yellow and is therefore hard to read.
This commit hard-codes a dark font color for the notices. This will of course still be overwritten by the Mumble themes, if selected.
Fixes #6160

FIX(client,theme): Use fixed dark font color for themeless notice labels

---

src/mumble/AudioConfigDialog.cpp
src/mumble/AudioOutput.cpp
src/mumble/ManualPlugin.cpp

- [Merge PR #6234: FIX(client): Positional audio fixes](https://github.com/mumble-voip/mumble/pull/6234)

Backport "Merge PR #6234: FIX(client): Positional audio fixes" to 1.5.x

---

src/mumble/Themes.cpp

- [Merge PR #6256: FIX(client,theme): Use fixed dark font color for themeless notice labels](https://github.com/mumble-voip/mumble/pull/6256)

Backport "Merge PR #6256: FIX(client,theme): Use fixed dark font color for themeless notice labels" to 1.5.x

---

plugins/MumblePlugin.h
plugins/deadLockPlugin/deadLockPlugin.cpp
plugins/testPlugin/testPlugin.cpp

- [Merge PR #6268: FIX(plugins): Compilation with new unified header](https://github.com/mumble-voip/mumble/pull/6268)

Backport "Merge PR #6268: FIX(plugins): Compilation with new unified header" to 1.5.x

---

scripts/generateIceWrapper.py

- [Merge PR #6286: MAINT: Fix invalid escape sequences in generateIceWrapper.py](https://github.com/mumble-voip/mumble/pull/6286)

Backport "Merge PR #6286: MAINT: Fix invalid escape sequences in generateIceWrapper.py" to 1.5.x

---

src/mumble/Markdown.cpp

- [Merge PR #6261: FIX(client,markdown): Don't end code-blocks on first backtick](https://github.com/mumble-voip/mumble/pull/6261)

Backport "Merge PR #6261: FIX(client,markdown): Don't end code-blocks on first backtick" to 1.5.x

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h

When the chat log is detected to be scrolled all the way to the bottom, it is set to the bottom again when new entries are added to the chat log.
The detection works properly, but sometimes (especially when an image is pasted into the chat box) the scroll bar ends up in an incorrect position.
When the chat log ends up in this incorrect state, subsequent calls to `scrollLogToBottom` still work correctly, i.e. resizing the window (which triggers this function) will correctly set the chat log scroll bar to the bottom.
Therefore, the issue seems to be caused by the scrollbar sometimes being in an inconsistent state *immediately* after a message is sent, but not any longer.
My workaround is to add a call to `QApplication::processEvents` before setting the scrollbar to its maximum position to …

FIX(client, ui): Fix log incorrectly scrolling up

---

themes/Default/Dark.qss
themes/Default/Lite.qss
themes/Default/source/Imports/Dark Definitions.scss
themes/Default/source/Imports/Lite Definitions.scss

This commit adds some font families to the default themes that improve the displaying of Chinese characters.
Added Windows(Microsoft YaHei), Linux(Noto Sans SC), Mac(PingFang SC) default Chinese fonts in the default theme's font-family, which can avoid the system calling fonts such as Simsun by default and bring bad display effect. I put it in front of Arial and sans-serif, and behind other fonts, so as to avoid affecting the display of non-CJK fonts on the operating system.
I modified the scss code as requested, and I'm sorry to restart a pull request again because I'm not familiar with using git yet.

FIX(client, theme): Chinese characters not displayed properly (scss modified)

---

docs/dev/build-instructions/cmake_options.md
installer/ClientInstaller.cs
src/mumble/CMakeLists.txt
src/tests/TestSettingsJSONSerialization/generate_test_case.py

Due to RNNoise being unmaintained and the library's code being in very poor shape, this commit excludes the RNNoise feature from Mumble by default and discourages its use.
The library contains Opus and CELT symbols (probably due to copy&paste of code) that can end up being called from Opus instead of its own versions of these functions. This can lead to completely unforeseen behavior, including crashes.
An example of this is as of writing this, enabling RNNoise on macOS leads to a crash of Mumble pretty much as soon as it starts up with an "invalid instruction" error. The reason being that part of RNNoise's implementation of one of Opus's symbols contains a code path that produces an invalid instruction in optimized builds (and a segfault in debug builds) and this code path is taken when …

CHANGE(client): Exclude and discourage RNNoise

---

src/mumble/CMakeLists.txt
src/mumble/ListenerVolumeSlider.cpp
src/mumble/ListenerVolumeSlider.h
src/mumble/UserLocalVolumeSlider.cpp
src/mumble/UserLocalVolumeSlider.h
src/mumble/VolumeSliderWidgetAction.cpp
src/mumble/VolumeSliderWidgetAction.h
src/mumble/widgets/EventFilters.cpp
src/mumble/widgets/EventFilters.h

Previously, when using keyboard arrows, the new slider widget action applied the new local volume but did not save it. That was because it used the sliderReleased event to save the value, which is not triggered by keyboard updates.
We could simply save the local volume on every sliderChange instead of on sliderRelease, but that would cause many writes to the disk in a short period of time and possibly lag the client.
This commit introduces an event filter in addition to the sliderChanged event, which is observing key releases. If the slider has focus and left/right is released, it is then calling the save slot of the slider.
Fixes #6211

FIX(client): Fix using the keyboad to change local volume adjustment

---

src/mumble/Markdown.cpp

Turns out that the regex introduced in #6261 was using syntax that Qt doesn't support.
Therefore, the regex has been replaced with a valid one that should be functionally identical.

FIX(client): Invalid code-block regex

---

src/mumble/Log.cpp

In v1.4, the logic surrounding when entries in the chat log are put in their own text frame was changed, introducing a bug where elements such as lists would not be terminated correctly (#4491).
The fix for this issue was to put every chat log entry into its own text frame, but Qt inserts a blank line between adjacent frames resulting in too much space between subsequent chat entries.
There is no convenient Qt API (as far as I know) to disable this behaviour, so my second attempt to resolve this (PR #5820) set the font size to near zero for the blank lines between entries.
This worked on Linux, but broke on (at least) Windows (#5886).
PR #5927 fixed the issue by calling `setVisible(false)` on the blank lines instead of changing the font size, but this introduced a regression to text …

FIX(client, ui): fix text selection in chat log

---

3rdparty/mach-override-build/CMakeLists.txt

BUILD(mach-override): Make use of standard C headers

---

.cirrus.yml
CMakeLists.txt

The protobuf version on the FreeBSD CI image that we are using requires
C++17.

CI(freebsd): Build with C++17 

---

src/mumble/ConnectDialog.cpp

When selecting new public servers, we randomize their order. The random number used for that is an unsigned integer from which we compute the modulus with the list size in order to get a random index into the list.
This involved an implicit conversion from an unsigned integer (the random number) to a signed integer (the list index - as Qt uses signed integers for that). Thus, b5a67c05fb54e030ddadf6219e350fb2ac9eb7f6 added an explicit cast to a signed integer. However, it did this to the random number before the modulus operation, meaning that if a large enough random number is drawn, the cast would actually create a negative integer, yielding a negative list index after the modulus. This caused a crash of the application.
The fix consists in switching to using the bounded() function that …

FIX(client): Crash when opening connect dialog

---

cmake/TargetArch.cmake

Not important as far as i can tell but makes cmake's configuration output pretty
(and changes some paths in PluginInstaller.cpp via MUMBLE_TARGET_ARCH)

BUILD: Detect arm64 / aarch64 architecture

---

src/mumble/PulseAudio.cpp

In b5a67c05f a buffer in the PulseAudio backend was made static, but at the same time the memset(0) was removed.
In combination, that lead to a bug where the last few frames of any given audio played back was repeated until something else filled the buffer.
This commit adds a simple fill to the buffer where the memset(0) previously was fixing the bug.
Exact bug location: https://github.com/mumble-voip/mumble/commit/b5a67c05fb54e030ddadf6219e350fb2ac9eb7f6#diff-3468a698a1554e9292714294b8c8766bff543c8b4949c3fa02ad833084bf2867L648-R665

FIX(client): Fix PulseAudio regression by nulling buffer

---

src/HostAddress.cpp

FIX(shared): Crash in HostAddress::toIPv4()

---

auxiliary_files/CMakeLists.txt

To make the build reproducible, it's needed to set the timezone as otherwise the date could vary based on the timezone of the build server.
Link: https://bugs.debian.org/1060254

BUILD: Set timezone on release date for reproducibility

---

src/mumble/API.h
src/mumble/API_v_1_x_x.cpp

QT invoke functions use the size_t type from std:: and some of the API functions that calls these invoke functions using the size_t type from the global namespace.This commit fixes the size_t type as std::size_t for these QT invoke functions.

FIX(client): Fix the size_t type for QT invoke functions in API.

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h

The function was called "toggle*" and yet it didn't toggle anything but instead only acted as a setter for the respective property. Therefore, the naming has been adjusted accordingly.

REFAC(client): Streamline function naming

---

src/murmur/Messages.cpp

In 635d71960f cache invalidation for access tokens was added. A check for ``uSource->iId >= 0`` was added which was intended to only parse access tokens, if the ``authenticate`` method was not returning an error code.
As it turns out though, ``uSource->iId`` will be -1 for unREGISTERED users instead of unAUTHENTICATED users which lead to a bug where unregistered users would not have the correct channel access when connecting to the server. A subsequent update of their tokens would fix that.
This commit moves the respective code block down and changes the condition to ``ok``, which should now behave as originally intended.
Fixes #6334

FIX(server): Allow unregistered users to transmit access tokens

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/Log.cpp
src/mumble/Log.h

In my previous PR (https://github.com/mumble-voip/mumble/pull/6290) addressing this bug, I wrote:
> The issue seems to be caused by the scrollbar sometimes being in an
> inconsistent state immediately after a message is sent, but not any
> longer.
>
> My workaround is to add a call to QApplication::processEvents before
> setting the scrollbar to its maximum position to avoid the inconsistent
> state.
I have found that this change only reduces the likelihood of the incorrect scroll behaviour from happening: it is still reproducible after the log grows past a certain size.
In my testing since then, the cause of the "inconsistent state" described previously seems to be the following: When images (whose contents are stored in a base64-encoded data URL) are inserted into the log, they are
not …

FIX(client, ui): Fix log scroll position after loading resources

---

src/mumble/Log.cpp

In the 'Messages' settings, when disabling a single notification method for a single message type, all check-boxes will disappear in that column if 'All messages' was checked to begin with. This is because the automatic unchecking of the 'All messages' check-box is treated as if the user actually clicked it. Using a `QSignalBlocker` before unchecking the 'All messages' fixes the issue
Fixes #6302

FIX(ui): Preserve other check-box states if All messages was checked

---

src/HostAddress.cpp

In 6c565689 the HostAddress was refactored. A check for ``isV6`` when creating a QHostAddress was removed. However, the QHostAddress determines the (IPv4 vs IPv6) distinction at construction time. This resulted in some regressions both visual and functional.
This commit reintroduces the distinction.
Fixes #6349

FIX(client): Use IPv4 HostAddress representation where applicable

---

src/mumble/PulseAudio.cpp

The second call to `pa_context_subscribe()` was overriding the first, as a result we were only receiving sink events.
This caused hotplugging to fail with devices that don't have any output ports (e.g. USB microphones).

FIX(client): Correctly subscribe to both sink and source events in PulseAudioSystem

---

src/mumble/WASAPI.cpp

In b5a67c05fb54e030ddadf6219e350fb2ac9eb7f6 a refactor took place which removed some compiler warnings.
In WASAPI.cpp a STACKVAR was swapped for a static std::vector,
which led to some unforeseen consequences and total audio input
failure on some systems.
This commit removes the static modifier as it is not needed there
anyway.
Fixes #6356

FIX(client): Fix incorrect WASAPI sound device handling

---

src/mumble/PulseAudio.cpp

- [Merge PR #6371: FIX(client): Correctly subscribe to both sink and source events in PulseAudioSystem](https://github.com/mumble-voip/mumble/pull/6371)

Backport "Merge PR #6371: FIX(client): Correctly subscribe to both sink and source events in PulseAudioSystem" to 1.5.x

---

src/mumble/WASAPI.cpp

- [Merge pull request #6370 from Hartmnt/fix_wasapi_hopefully_haha](https://github.com/mumble-voip/mumble/pull/6370)

Backport "Merge pull request #6370 from Hartmnt/fix_wasapi_hopefully_haha" to 1.5.x

---

src/murmur/Messages.cpp
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/ServerUser.h

Since the whisper cache entry was computed while holding the read-lock,
it was possible for a user in that cache to get deleted while the voice
thread drops the read lock in order to upgrade it to a write lock. In
such a case, the cache entry would contain an invalid (stale) user
pointer, which can lead to crashes when using the cache later on.
By moving the cache entry computation into the block in which we already
hold a read lock, we turn computing the cache and adding it to the cache
store into an atomic operation. As soon as the cache entry is in the
store, deleting a user is no longer an issue as that will implicitly
clear all whisper caches (thereby preventing stale cache entries).
Additionally, the cache creation has been factored out into its own function (for improved …

FIX(server): Stale user pointers in whisper cache 

---

.github/workflows/build.yml

The v3 actions are based on Node 16 and are therefore deprecated.

CI(github-actions): Upgrade to Node 20 actions

---

src/murmur/MumbleServer.ice

The Mumble Client UI offers the temporary checkbox only in the Add Channel dialog, not in the Edit Channel dialog.
For Ice consumers it is not obvious that the temporary flag is read-only, and setting it may work but has no effect.
In https://github.com/mumble-voip/mumo/issues/26 it was reported as having no effect.
I did not verify but it is consistent to the Mumble Client UI, hence I am suggesting extending the slice documentation to make this limitation more obvious.

DOCS(ice): Add Channel.temporary read-only notice

---

.github/ISSUE_TEMPLATE/config.yml

Drop obsolete, archived forums web-link from issue templates

MAINT(github): Drop forums web-link from issue templates

---

COMMIT_GUIDELINES.md

We had two level-one headlines.
Add a document-level headline and intro text (without an intro text it would be quite empty).
Indent every over headline by one level to have correct, consistent levels.
The intro text provides general context even without specific technical knowledge about the document context. Although it does not introduce the connection between Git and commit.

DOCS(commit-guidelines): Fix headlines, Add general intro

---

src/mumble/AudioInput.cpp
src/mumble/AudioInput.h
src/mumble/Messages.cpp
src/mumble/PipeWire.cpp
src/mumble/PipeWire.h

When the user is muted and/or suppressed in Mumble, there is no reason to keep the audio stream running (unless the mute cue is enabled).
Disabling/suspending the pipewire stream has the advantage of allowing upstream nodes to suspend themselves as well. When using resource-heavy system-wide audio filters (e.g. via pipewire filter-chain) such as DeepFilterNet, this can save significant amounts of CPU time.
The actual implementation for this in `PipeWire.h/cpp` is dead simple with just 3 function calls, but letting the `AudioInput` know the mute state was a bit more complex. Please let me know in case there is a better approach - I would be happy to change it.
The onUserMutedChanged can potentially be used by other audio backends in the future to implement similar functionality.

FEAT(client): disable pipewire input stream while muted

---

src/murmur/Messages.cpp
src/murmur/Server.cpp
src/murmur/Server.h
src/murmur/ServerUser.h

- [Merge PR #6372: FIX(server): Stale user pointers in whisper cache ](https://github.com/mumble-voip/mumble/pull/6372)

Backport "Merge PR #6372: FIX(server): Stale user pointers in whisper cache " to 1.5.x

---

src/crypto/CryptStateOCB2.cpp

The inventor dedicated the design to the public domain, all patents lapsed intentionally. Comments only, no code change.
Fixes #6403

MAINT: The OCB design is in the public domain

---

src/crypto/CryptStateOCB2.cpp

This will backport the following commits from master to 1.5.x:
* [Merge PR 6404: MAINT: The OCB design is in the public domain](https://github.com/mumble-voip/mumble/pull/6404)
Rationale for back-porting: openSUSE source license checker bot triggers on the patent comment.
Fixes #6403

 Backport "Merge PR #6404: MAINT: The OCB design is in the public domain " to 1.5.x

---

src/murmur/Server.cpp

FEAT(server): Add error code when UDP socket binding fails

---

scripts/create_source_archive.py

Previously, tarballs created from our script would contain user/group info from the host system.
This could be verified by running:
``tar -tvf <file>``
This commit adds an explicit tarinfo filter
to drop username and groupname automatically.
---
Note: I renamed the folder inside the tarball for 1.5.629 from ``mumble-1.5.x`` to ``mumble-1.5.629`` causing this fix to not apply to that release without realizing, lol...

MAINT: Drop user and group info from tarball

---

src/mumble/ConfigDialog.cpp

The settings page could not be opened after the user clicked on the settings button in the main window.
The problem is due to tab button ordering function. This function is called before buttons are created. That's why application throws an assertion error.
Fixes #6421

FIX(client): Crash when loading settings

---

src/mumble/GlobalShortcut.cpp
src/mumble/ListenerVolumeSlider.cpp
src/mumble/VolumeSliderWidgetAction.cpp

```cpp
src/mumble/GlobalShortcut.cpp:96:74: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
96 |         connect(eventFilter, &KeyEventObserver::keyEventObserved, this, [=]() { m_comboBox->showPopup(); });
|                                                                                 ^
src/mumble/GlobalShortcut.cpp:388:74: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
388 |         connect(eventFilter, &KeyEventObserver::keyEventObserved, this, [=]() { qtbEdit->click(); });
|                                                                                 ^
src/mumble/GlobalShortcut.cpp:405:12: error: implicit capture of 'this' with a capture default of …
```

FIX(client): Capture "this" explicitly in lambdas

---

src/mumble/ConfigDialog.cpp

- [Merge PR #6426: FIX(client): Crash when loading settings](https://github.com/mumble-voip/mumble/pull/6426)

Backport "Merge PR #6426: FIX(client): Crash when loading settings" to 1.5.x

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/Settings.h
src/mumble/SettingsKeys.h
src/mumble/SettingsMacros.h

Previously, only the "mute" and "deaf" states were saved to the settings file. However, when a user deafens themselves without muting first, Mumble will automatically unmute the user as soon as they undeafen. The "autoUnmute" state was not saved in the settings though, leading to the state "deafened (muted implied)" being reduced to "deafened and muted".
This commit moves the autoUnmute state from being a local member of MainWindow to the settings file allowing to preserve the "deafened (muted implied)" state.
Fixes #6393

FIX(client): Correctly remember muted state across restarts

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/Settings.h
src/mumble/SettingsKeys.h
src/mumble/SettingsMacros.h

- [Merge PR #6440: FIX(client): Correctly remember muted state across restarts](https://github.com/mumble-voip/mumble/pull/6440)

Backport "Merge PR #6440: FIX(client): Correctly remember muted state across restarts" to 1.5.x

---

src/mumble/GlobalShortcut.cpp
src/mumble/ListenerVolumeSlider.cpp
src/mumble/VolumeSliderWidgetAction.cpp

- [Merge PR #6444: FIX(client): Capture "this" explicitly in lambdas](https://github.com/mumble-voip/mumble/pull/6444)

Backport "Merge PR #6444: FIX(client): Capture "this" explicitly in lambdas" to 1.5.x

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/QtWidgetUtils.cpp

We simulate placeholder text by setting the actual value of the text edit to "qsDefaultText". This allows us to use html in the placeholder text.
However, the entire text is being displayed no matter the window size. That can lead to annoying automatic resizing while typing and sending messages.
This commit changes the behavior of the ChatBar to switch the wrap mode and elide the text depending on whether we are currently displaying placeholder text.
Fixes #1823

FIX(client): Remove placeholder wrapping in ChatBar

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/QtWidgetUtils.cpp

- [Merge PR #6442: FIX(client): Remove placeholder wrapping in ChatBar](https://github.com/mumble-voip/mumble/pull/6442)

Backport "Merge PR #6442: FIX(client): Remove placeholder wrapping in ChatBar" to 1.5.x

---

src/murmur/Messages.cpp

- [Merge PR #6454: FIX(server): Allow to move temporary channels provided sufficient per…](https://github.com/mumble-voip/mumble/pull/6454)

Backport "Merge PR #6454: FIX(server): Allow to move temporary channels provided sufficient per…" to 1.5.x

---

src/mumble/ACLEditor.cpp
src/mumble/ACLEditor.h
src/mumble/widgets/EventFilters.cpp
src/mumble/widgets/EventFilters.h

This contains 3 commits.
The first makes the QComboBoxes in the ACLEditor commit changes when they lose focus, even if the entry was not autocompleted.
The second automatically pops up the QComboBox menu when the user hits space in an empty QComboBox for accessibility reasons
The third removes the redundant entries from the group combo box
Fixes #2359

Fix the QComboBoxes in ACLEditor

---

src/SSLLocks.cpp

The CRYPTO_num_locks function of OpenSSL returns an int, but we assigned the value to an unsigned int, leading to a compiler warning about a potential sign change.
This is no issue on newer systems as apparently OpenSSL has removed these functions at some point and replaced them with a macro that evaluates to a numeric constant (1). However, on older systems such as CentOS 7, this function still seems to exist and there it actually matters that we are using a wrong type.
Fixes #6467

BUILD: Use correct type for num locks

---

src/SSLLocks.cpp

- [Merge PR #6474: BUILD: Use correct type for num locks](https://github.com/mumble-voip/mumble/pull/6474)

Backport "Merge PR #6474: BUILD: Use correct type for num locks" to 1.5.x

---

src/mumble/AudioInput.ui

In #6364 RNNoise was replaced with ReNameNoise. I missed the tab-order in AudioInput.ui and it sill contained the old name for the UI element leading to compile-time warnings.
This commit fixes the tab-order.

FIX(client): Update tab order in AudioInput.ui

---

src/mumble/AudioInput.ui

- [Merge PR #6478: FIX(client): Update tab order in AudioInput.ui](https://github.com/mumble-voip/mumble/pull/6478)

Backport "Merge PR #6478: FIX(client): Update tab order in AudioInput.ui" to 1.5.x

---

src/mumble/Database.cpp
src/mumble/Database.h
src/mumble/main.cpp

Previously, local muted users would be muted persistently basically forever. This meant that local muting a client could end up being confusing down the line (e.g days later) when the user forgot that they muted someone.
As a means of self-moderation though, local mutes should also not expire when the muted client reconnects or something similar.
This commit clears the all local mutes in the client when Mumble starts.
Fixes #5983

FEAT(client): Clear local mutes on Mumble restart

---

.ci/azure-pipelines/main.yml

The macOS 11 image has been deprecated and is likely to (or already has been?) be removed entirely.

MAINT(ci): Upgrade to macOS 12 on Azure Pipelines

---

src/mumble/UserLocalVolumeSlider.cpp
src/mumble/UserLocalVolumeSlider.h

In #5776 the local volume adjustment sliders were moved into the user context menu. A log warning message appears, if you adjust the volume of a client without certificate.
Due to a combination of Qt's buggy MouseWheel events and the oversight that volume changes to the DB happen much more frequently with that change, the log warning messages are spammed way to often now in that case.
This commit moves the log warning message explicitly into a separate slot on slider release. Note: We "lose" the warning message for other input methods that are not "releasing the slider", but given the fact that certificates are pretty prevalent now and dragging the slider is likely the most often used input method, this will likely affect a very little amount of users.
Fixes #6462

FIX(client): Do not spam log when adjusting volume of clients without certificate

---

.ci/azure-pipelines/install-environment_linux.bash
.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml
.github/workflows/backport.yml
.github/workflows/build.yml
.github/workflows/code-ql.yml
.github/workflows/pr-checks.yml
.github/workflows/release_dispatch.yml
.github/workflows/stale_issues.yml

- [Merge PR #6494: MAINT(ci): Various maintenance work related to CI configs](https://github.com/mumble-voip/mumble/pull/6494)

Backport "MAINT(ci): Various maintenance work related to CI configs" to 1.5.x

---

.github/workflows/backport.yml

MAINT: Only run backport action when PR is merged

---

.github/workflows/backport.yml

- [Merge PR #6496: MAINT: Only run backport action when PR is merged](https://github.com/mumble-voip/mumble/pull/6496)

Backport "MAINT: Only run backport action when PR is merged" to 1.5.x

---

src/mumble/AudioInput.cpp

In the mumble_onAudioInput callback that plugins can use, the sampleCount parameter was actually wrong for all cases in which the input had more than a single channel. Instead of the sample count per channel, the total sample count (across all channels) was passed along.
Fixes #6464

FIX(client, plugins): Wrong sample count in plugin callback

---

.backportrc.json

- [Merge PR #6498: MAINT: Update backport config](https://github.com/mumble-voip/mumble/pull/6498)

Backport "Merge PR #6498: MAINT: Update backport config" to 1.5.x

---

.github/workflows/backport.yml

- [Merge PR #6502: MAINT(ci): Don&#x27;t run backport action on backport PRs](https://github.com/mumble-voip/mumble/pull/6502)

Backport "Merge PR #6502: MAINT(ci): Don't run backport action on backport PRs" to 1.5.x

---

src/mumble/UserLocalVolumeSlider.cpp
src/mumble/UserLocalVolumeSlider.h

- [Merge PR #6486: FIX(client): Do not spam log when adjusting volume of clients without certificate](https://github.com/mumble-voip/mumble/pull/6486)

Backport "Merge PR #6486: FIX(client): Do not spam log when adjusting volume of clients without certificate" to 1.5.x

---

.cirrus.yml
.gitmodules
CMakeLists.txt
plugins/CMakeLists.txt
plugins/HostWindows.cpp
plugins/HostWindows.h
plugins/ProcessBase.cpp
plugins/ProcessBase.h
plugins/amongus/CMakeLists.txt
plugins/amongus/Game.cpp
plugins/cod2/cod2.cpp
plugins/link/CMakeLists.txt
plugins/link/link.cpp
plugins/mumble_positional_audio_utils.h
plugins/se/se.cpp
plugins/ut99/CMakeLists.txt
plugins/ut99/ut99.cpp
src/mumble/CMakeLists.txt
src/mumble/GlobalShortcut_win.cpp
src/mumble/GlobalShortcut_win.h
src/mumble/LegacyPlugin.cpp

Deprecated in C++17 and slated for removal in C++26.
Unfortunately no standard replacement is available yet.

REFAC(client): Replace <codecvt> usage

---

src/mumble/AudioOutput.cpp
src/mumble/Log.cpp

Merge request #5247 introduced a warning that is triggered when Mumble is configured to use positional audio and only a single channel output is configured.
However, this warning is emitted from the audio thread and therefore causes a crash. This is because Qt does not want to add child QObjects from any other thread than main.
This commit makes sure the static version of ``logOrDefer`` is called and also adds a check to ``Log::log`` to forward the call to the main thread, if necessary.
The ``invokeMethod`` construct is the same idea as
https://github.com/mumble-voip/mumble/blob/b75fe546ab6e5f32204e20df7ee3ceb8ce70262c/src/mumble/API_v_1_x_x.cpp#L1587-L1593
Fixes #6507

FIX(client): Fix crash on mono pos. audio warning from audio thread

---

src/MumbleProtocol.cpp
src/mumble/Audio.cpp
src/mumble/AudioOutput.cpp
src/murmur/Server.cpp

BUILD: Fix compiler warnings on 32bit architectures

---

src/mumble/AudioOutput.cpp
src/mumble/Log.cpp

- [Merge PR #6510: FIX(client): Fix crash on mono pos. audio warning from audio thread](https://github.com/mumble-voip/mumble/pull/6510)

Backport "Merge PR #6510: FIX(client): Fix crash on mono pos. audio warning from audio thread" to 1.5.x

---

src/MumbleProtocol.cpp
src/mumble/Audio.cpp
src/mumble/AudioOutput.cpp
src/murmur/Server.cpp

- [Merge PR #6536: BUILD: Fix compiler warnings on 32bit architectures](https://github.com/mumble-voip/mumble/pull/6536)

Backport "Merge PR #6536: BUILD: Fix compiler warnings on 32bit architectures" to 1.5.x

---

cmake/compiler.cmake

Let's disable the Qt < 5.15.17 specific warning until #6516 is merged

BUILD: Disable MSVC 17.8 warning for stdext::checked_array_iterator

---

src/SSL.cpp

`CRYPTO_get_locking_callback()` has been defined to NULL since OpenSSL 1.1.0.  This check therefore doesn't do anything in any supported version of OpenSSL.
This fixes the following compiler error that I saw with GCC 14:
```
/build/source/src/SSL.cpp: In static member function ‘static void MumbleSSL::initialize()’: /build/source/src/SSL.cpp:36:14: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]
36 |         if (!CRYPTO_get_locking_callback()) {
|              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

FIX(client, server): Remove redundant OpenSSL locking callback check

---

src/SSL.cpp

- [Merge PR #6553: FIX(client, server): Remove redundant OpenSSL locking callback check](https://github.com/mumble-voip/mumble/pull/6553)

Backport "Merge PR #6553: FIX(client, server): Remove redundant OpenSSL locking callback check" to 1.5.x

---

src/murmur/Server.cpp

FIX(server): Change server thread name to "mumble-server" instead of "Main"

---

src/murmur/Server.cpp

- [Merge PR #6559: FIX(server): Change server thread name to &quot;mumble-server&quot; instead of &quot;Main&quot;](https://github.com/mumble-voip/mumble/pull/6559)

Backport "Merge PR #6559: FIX(server): Change server thread name to "mumble-server" instead of "Main"" to 1.5.x

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/GlobalShortcut_unix.h

**FIX(client): Prevent sending plain text on fast CTRL+V + ENTER**
In e658c4a0e094d2af82d5f425e90d4c73d5cfc9ef plain text sending was added. Due to the
way Qt handles events, a regression was introduced where
very fast inputs would wrongly trigger the plain text send code
branch - removing e.g. links from chat messages.
This commit introduces a member to keep track when a paste event
happend, and prevents subsequent plain text sends until the CTRL
key was released at least once. This also means that pasting
and then purposefully sending plain text now requires the user to
lift the CTRL key once before hitting ENTER.
Fixes #6568

FIX(client): Prevent sending plain text on fast CTRL+V + ENTER

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/GlobalShortcut_unix.h

- [Merge PR #6570: FIX(client): Prevent sending plain text on fast CTRL+V + ENTER](https://github.com/mumble-voip/mumble/pull/6570)

Backport "Merge PR #6570: FIX(client): Prevent sending plain text on fast CTRL+V + ENTER" to 1.5.x

---

src/mumble/VolumeSliderWidgetAction.cpp

Since ed988e646af57eeeb2e47a0d077549999c23957f, clicking the slider bar of the local volume adjustment slider would correctly update the label and (temporarily) also update the user volume.
However, since clicking on the slider bar does not fire a "sliderReleased" event, the value was not saved to the local volume adjustment database leading to it "randomly" resetting.
This commit adds an additional signal/slot connection to save the value when the slider bar is clicked.

FIX(client): Save local volume adjustment when clicking slider bar

---

src/mumble/VolumeSliderWidgetAction.cpp

- [Merge PR #6574: FIX(client): Save local volume adjustment when clicking slider bar](https://github.com/mumble-voip/mumble/pull/6574)

Backport "Merge PR #6574: FIX(client): Save local volume adjustment when clicking slider bar" to 1.5.x

---

src/mumble/AudioOutput.cpp

- [ x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)
FIX(client): Registered the AudioOutputBuffer as qRegisterMetaType
Just a QT registration missing for the AudioOutputBuffer. Being only a single required registration I didn't make a separate function for it -- it's just in the constructor.
Fixes: https://github.com/mumble-voip/mumble/issues/6569

FIX(client): Registered AudioOutputBuffer as qRegisterMetaType

---

.github/workflows/backport.yml

With these changes, the backport action should only run on PRs that have an explicit auto-backport-xxx label

CI(backport): Prevent CI failure for non-backported PRs

---

src/mumble/CustomElements.cpp

Previously, the chat bar QTextEdit was unlimited in screen space size and would start stretching the main window and chat log, if messages were too large.
This resulted in the window becoming unusable unless you would manually resize the window down again.
This commit adds a sensible limit to how much of the chat bar can be visible at once. Currently, this limit is set to 10 times the font height. After that the chat bar will stop growing in screen space and instead start showing a scrollbar.
Fixes #6528
Fixes #1320

FIX(client): Limit size of the chat bar

---

src/mumble/CustomElements.cpp

- [Merge PR #6578: FIX(client): Limit size of the chat bar](https://github.com/mumble-voip/mumble/pull/6578)

Backport "Merge PR #6578: FIX(client): Limit size of the chat bar" to 1.5.x

---

plugins/HostWindows.cpp

This `VirtualQueryEx()` loop is called for each module in a process. It reads pages starting at the module address but seems to continue past into other modules and into dynamic allocations also.
This check stops enumerating pages once it encounters one that no longer belongs to the module for which pages are being collected.
(Also this function opens two handles, this adds a clean up for the first handle if opening the second fails.)
Fixes #6558

FIX(plugins): Load correct pages for modules

---

plugins/HostWindows.cpp

- [Merge PR #6598: FIX(plugins): Load correct pages for modules](https://github.com/mumble-voip/mumble/pull/6598)

Backport "Merge PR #6598: FIX(plugins): Load correct pages for modules" to 1.5.x

---

src/mumble/Settings.h

The off audio cue was incorrectly using on in a new configuration.
This commit sets the off audio cue to the correct one.
Fixes #6614

FIX(client): Use correct off audio cue

---

src/mumble/Settings.h

- [Merge PR #6615: FIX(client): Use correct off audio cue](https://github.com/mumble-voip/mumble/pull/6615)

Backport "Merge PR #6615: FIX(client): Use correct off audio cue" to 1.5.x

---

src/mumble/AudioWizard.cpp
src/mumble/AudioWizard.h

The echo cancellation checkbox had two separate, but similar problems:
1) It would never load in a checked state when you open up the AudioWizard
2) It would also never load the correct checked state representing the user settings when switching AudioInput or AudioOutput systems.
The first problem can be traced back to commit 010437556dc81b4ed2e16baba65447c32fda61cd where the state of qcbEcho depends on the selected element of the AudioOutput dropdown menu, before it has been filled.
The second problem probably goes back to 2991d2093a0fa0d9060afbe0004af9d3383f48e0 where the enabled state of the qcbEcho checkbox was updated on changing audio systems, but the checked state was not reloaded.
This commit refactors the code (swaps initializing input and output) and adds a shared method to …

FIX(client): Fix AudioWizard echo cancellation checkbox

---

src/mumble/AudioWizard.cpp
src/mumble/AudioWizard.h

- [Merge PR #6611: FIX(client): Fix AudioWizard echo cancellation checkbox](https://github.com/mumble-voip/mumble/pull/6611)

Backport "Merge PR #6611: FIX(client): Fix AudioWizard echo cancellation checkbox" to 1.5.x

---

cmake/project-utils.cmake
src/mumble/CMakeLists.txt
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/OverlayClient.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/SettingsMacros.h

This fixes a crash caused by the state being incompatible between Qt 5 and 6.
Please note that the default argument value for `restoreState()` is 0: https://doc.qt.io/qt-6/qmainwindow.html#restoreState

FIX(client): Specify version when loading/saving MainWindow state

---

CMakeLists.txt
helpers/g15helper/CMakeLists.txt
overlay/CMakeLists.txt
plugins/CMakeLists.txt
src/mumble/CMakeLists.txt

This is a workaround for a bug that appeared in a recent version of CMake.
`WORKING_DIRECTORY` prepends the specified path to a list instead of using it directly, resulting in:
`cd /D D:\a\1\b\overlay\overlay_xcompile-prefix;D:\a\1\b\overlay\overlay_xcompile-prefix\src\overlay_xcompile-build`
For reference, this causes the build to fail on Windows with the following error:
"The filename, directory name, or volume label syntax is incorrect."
This commit simply removes the parameter from the `ExternalProject_Add()` call, since the default working directory is perfectly fine.

FIX(cmake): Don't set WORKING_DIRECTORY for ExternalProject_Add()

---

auxiliary_files/config_files/mumble-server.service.in

Make it easy to view the man page by documenting it in its service unit file. Then it can be viewed via `systemctl help mumble-server.service`.

DOCS(server): Add Documentation key to mumble-server unit

---

docs/dev/build-instructions/build_linux.md

Since Debian Bookworm the pkg-config package is a transitional package to pkgconf, so update the build dependency install instructions to point to its target.

DOCS(build_linux): Update Debian B-D: pkg-config -> pkgconf

---

src/QtUtils.cpp
src/QtUtils.h
src/mumble/PluginInstaller.cpp
src/mumble/Settings.cpp

2 commits:
1) Use ``boost::filesystem::path`` and abstract the ``QString`` -> path conversion.
2) Replace ``boost::filesystem::path`` with ``std::filesystem::path`` (for 1.6.x and C++17)

FIX(client): Fix Windows Unicode paths when using raw file streams

---

src/QtUtils.cpp
src/QtUtils.h
src/mumble/PluginInstaller.cpp
src/mumble/Settings.cpp

Backport "FIX(client): Fix Windows Unicode paths when using raw file streams #6635" to 1.5.x

---

.appveyor.yml

This adds a fix for the appveyor CI pipeline to the 1.5.x branch.
from @davidebeatrici:
The Effect-Compiler Tool ("fxc.exe") seems to have only two direct dependencies:
- kernel32.dll
- D3DCompiler_47.dll
Both libraries are shipped with Windows, but the SDK provides a variant of the latter along with the executable. Turns out that variant is causing FXC to fail to launch with the following error:
"The procedure entry point __CxxFrameHandler4 could not be located in the dynamic link library C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\D3DCOMPILER_47.dll."
It's unclear when exactly the issue started happening and why. We just know it was never encountered until this week, when triggering a new official release (last one was in May).
The workaround is simple: we delete any …

CI(appveyor): Workaround for FXC failing to run with error C0000139

---

docs/dev/build-instructions/build_linux.md

This MR consists of the following 3 commits:
- DOCS(build_linux): Sort Debian Build Dependencies
- DOCS(build_linux): Actually update Debian B-D: pkg-config -> pkgconf
- DOCS(build_linux): Add missing B-Ds to Debian instructions
Feel free to (ask me to) squash those into 1 (or 2) commit(s).

DOCS: Update Debian Build-Dependencies

---

cmake/project-utils.cmake
src/mumble/CMakeLists.txt
src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/OverlayClient.cpp
src/mumble/Settings.cpp
src/mumble/Settings.h
src/mumble/SettingsMacros.h

- [Merge PR #6584: FIX(client): Specify version when loading/saving MainWindow state](https://github.com/mumble-voip/mumble/pull/6584)

Backport "Merge PR #6584: FIX(client): Specify version when loading/saving MainWindow state" to 1.5.x

---

README.md
docs/dev/build-instructions/README.md

We should specify that the build documentation will change over time and the correct branch needs to be selected for any given version.
Fixes #6658
Ping @roughnecks

DOCS: Mention differences in documentation across branches

---

src/ACL.cpp
src/mumble/ACLEditor.cpp
src/mumble/MainWindow.cpp
src/murmur/Messages.cpp

**FIX(server): Make sure context is applied to traverse and write ACL**
Previously, both the traverse and write ACL would be evaluatedwithout taking the "in this channel" and "in sub-channels" context options into account.
This would lead to denying traverse for channels that were actually supposed to be traversable.
This commit refactors the ACL calculation for readability and makes sure the write and traverse checks are actually taking the context into account.
Fixes #3579 
**FIX(server, client): Remove "Write" ACL parent channel inheritance**
Since 2a9dcfde4e423c4414f975a4b0b77cb08d08e782 and 62b1536fe0e91c03bf803075dff031a1f4dba9f4 the Mumble server would overwrite the current channel Write ACL, if the user had Write ACL permission in the parent channel.
Supposedly, this was done …

FIX(server, client): Fix ACL write and traverse permissions

---

src/PacketDataStream.h

Instead of providing explicit overloads for some integer types, we now use a template to cover all integer types. Using a manually selected subset has repeatedly led to issues where integer definitions vary between platforms (and library versions?).

REFAC: Use template to support arbitrary integer types

---

src/mumble/PluginManager.cpp
src/mumble/PluginManager.h

If a plugin is providing positional audio data and it becomes unloaded, such as by disabling the plugin in the settings GUI, the plugin manager may still interact with the plugin through m_activePositionalDataPlugin.
This looks unintentional and, in debug mode, this fails an assertion in the plugin fairly quickly: `assertPluginLoaded(this)`.
Additionally, in case Mumble shuts down while there exists an active
positional data plugin, Mumble will (now) try to log that the plugin has
lost link by calling the respective function on the global Log instance.
However, at the point where the plugin manager object is destroyed, the
log has already been deleted, making this produce a segmentation fault.
To prevent this from happening, an explicit check for whether the Log
instance still exists has …

FIX(plugins): Unset active positional plugin on unloading it

---

src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

Fixes https://github.com/mumble-voip/mumble/issues/6377 (hopefully for real, this time)

REFAC(server): Add explicit casts to avoid conversion warnings

---

src/mumble/PluginManager.cpp
src/mumble/PluginManager.h

- [Merge PR #6602: FIX(plugins): Unset active positional plugin on unloading it](https://github.com/mumble-voip/mumble/pull/6602)

Backport "Merge PR #6602: FIX(plugins): Unset active positional plugin on unloading it" to 1.5.x

---

src/mumble/Cert.cpp
src/murmur/Cert.cpp

BIO_set_close with BIO_NOCLOSE argument leads to OpenSSL not (fully)
deleting the allocated BIO struct under the assumption that the user
code has taken ownership of it. However, in our case, this is not the
case and therefore OpenSSL should do the deletion as usual.
The flag was probably introduced under the assumption that the component
that either is or isn't deleted by OpenSSL was the externally provided
buffer that is wrapped into a BIO object via BIO_new_mem_buf. However,
this is not the case. OpenSSL doesn't take ownership of the provided
buffer and therefore also doesn't delete it.
Closes https://github.com/mumble-voip/mumble/issues/6603

FIX(client): Fix memory leaks due to BIO_NOCLOSE flag

---

src/mumble/Cert.cpp
src/murmur/Cert.cpp

Backport "Merge PR #6604: FIX(client): Fix memory leaks due to BIO_NOCLOSE flag"

---

src/murmur/ServerUser.cpp
src/murmur/ServerUser.h

- [Merge PR #6694: REFAC(server): Add explicit casts to avoid conversion warnings](https://github.com/mumble-voip/mumble/pull/6694)

Backport "Merge PR #6694: REFAC(server): Add explicit casts to avoid conversion warnings" to 1.5.x

---

src/murmur/Messages.cpp

Previously, the Register ACL was required to get extended user statistics (which includes used Mumble version, IP address etc.). However, the Register ACL was deemed to be a rather arbitrary choice for this. Instead, the Ban ACL was chosen as access to information such as packet loss, IP address and used Mumble version and OS seem much more relevant in the case of banning clients than it is for registering them.
Also, Ban permission is likely to be a better proxy for whether or not someone is a moderator/admin on a given server than Register privilege.
Fixes #6697

CHANGE(server): Extended user stats now requires Ban ACL

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

The macOS 12 image has been removed.
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
We skip version 13 since we always run the latest macOS on our own builder anyway.

MAINT(ci): Update to macOS 14 on Azure Pipelines

---

.ci/azure-pipelines/main-pr.yml
.ci/azure-pipelines/main.yml

- [Merge PR #6703: MAINT(ci): Update to macOS 14 on Azure Pipelines](https://github.com/mumble-voip/mumble/pull/6703)

Backport "Merge PR #6703: MAINT(ci): Update to macOS 14 on Azure Pipelines" to 1.5.x

---

src/mumble/ALSAAudio.cpp

A user reported that sometimes the client log gets spammed with repeated messages such as:
`<W>2025-01-10 10:24:10.638 ALSAAudioInput: No such device: No such device`
The error corresponds to `ENODEV` (19), which we treat like any other.
Since it's unrecoverable, the code gets stuck in a full speed loop until the audio engine is stopped.
This commit:
1. Switches from `snd_pcm_prepare()` to `snd_pcm_recover()`, which is specifically designed to recover streams.
2. Breaks the loop if the error is not one of the only three recoverable (`EINTR`, `EPIPE`, `ESTRPIPE`). Example log:
`<W>2025-01-14 06:16:44.494 ALSAAudioInput encountered unrecoverable error: File descriptor in bad state -> exiting...`
Please note that also `ALSAAudioOutput` doesn't explicitly handle fatal errors in its loop, but …

FIX(client): Infinite loop and log spam on ALSA input device disconnection

---

src/mumble/ALSAAudio.cpp

- [Merge PR #6702: FIX(client): Infinite loop and log spam on ALSA input device disconnection](https://github.com/mumble-voip/mumble/pull/6702)

Backport "Merge PR #6702: FIX(client): Infinite loop and log spam on ALSA input device disconnection" to 1.5.x

---

src/murmur/Messages.cpp

- [Merge PR #6700: CHANGE(server): Extended user stats now requires Ban ACL](https://github.com/mumble-voip/mumble/pull/6700)

Backport "Merge PR #6700: CHANGE(server): Extended user stats now requires Ban ACL" to 1.5.x

---

docs/dev/network-protocol/establishing_connection.rst
docs/dev/network-protocol/voice_data.rst

* Replace non-breaking space ("nbsp") characters with normal space characters
* Fix rst cross-document reference that worked on readthedocs but does not work on GitHub rendering
These changes can be considered a follow-up or fixup to PR #6623, which integrated the network protocol docs into this repository.

DOCS(dev): Clean up network protocol docs

---

docs/dev/network-protocol/README.md
docs/dev/network-protocol/establishing_connection.md
docs/dev/network-protocol/protocol_stack_tcp.md

We migrated our network protocol documentation into this repository, but the documentation is outdated, documenting the state of 1.2.0.
Add a few notes/disclaimers and pointers to up-to-date information.

DOCS(dev): Add network protocol outdated and up-to-date information

---

docs/dev/network-protocol/overview.md
docs/dev/network-protocol/protocol_stack_tcp.md

Drop the 'unreliable' label from UDP. Delivery is not guaranteed, but delivery reliability largely depends on network context. Unreliable makes it sound more negative and error-prone than it is. We use UDP because and with the understanding that in most cases it is quite reliable, or reliable enough, rather than simply being unreliable. The point is that we use it for low-latency. Everything else is technical reasoning.
Prefer short statement sentences over long comma sentences.
'an TLSv1 encrypted connection' -> 'a TLSv1 encrypted connection'
Format message type name as inline code to indicate it being a "type" name.

DOCS(dev): Improve wording and formatting of network protocol docs

---

.cirrus.yml

- [Merge PR #6723: CI(cirrus): Update to FreeBSD 14.2](https://github.com/mumble-voip/mumble/pull/6723)

Backport "Merge PR #6723: CI(cirrus): Update to FreeBSD 14.2" to 1.5.x

---

src/mumble/AudioPreprocessor.h

FIX(client): Build error with make -j$(nproc) **note: ‘size_t’ is defined in header ‘<cstddef>’;**

fix for error: ‘size_t’ does not name a type

---

src/mumble/LookConfig.cpp

- [Merge PR #6728: FIX(Client): bug with talking UI options](https://github.com/mumble-voip/mumble/pull/6728)

Backport "Merge PR #6728: FIX(Client): bug with talking UI options" to 1.5.x

---

src/mumble/AudioOutput.cpp

Added metatype registration of const void * 
previously audio output wasn't working correctly due to forgotten registration in ca87877
Closes #6735

FIX(Client): register const void *

---

macx/scripts/osxdist.py

This fixes #6741
The CFBundleVersion is used as a technical identifier by the system, while the CFBundleShortVersionString is used as a user visible value throughout the system. Most notably in the Finder where it defines the user visible version.
See:
- Apples Documentation about CFBundleVersion https://developer.apple.com/documentation/bundleresources/information-property-list/cfbundleversion
- Apples Documentation about CFBundleShortVersionString https://developer.apple.com/documentation/bundleresources/information-property-list/cfbundleshortversionstring

FIX(mac): Set CFBundleShortVersionString

---

macx/scripts/osxdist.py

- [Merge PR #6742: FIX(mac): Set CFBundleShortVersionString](https://github.com/mumble-voip/mumble/pull/6742)

Backport "Merge PR #6742: FIX(mac): Set CFBundleShortVersionString" to 1.5.x

---

src/murmur/Meta.cpp

- [FIX(server): Prevent server startup when providing empty certificate files (#6750)](https://github.com/mumble-voip/mumble/pull/6750)

Backport "FIX(server): Prevent server startup when providing empty certificate files (#6750)" to 1.5.x

---

docs/dev/network-protocol/protocol_stack_tcp.md

Quick fix for docs image of a TCP packet

Fix image link in docs

---

src/mumble/MainWindow.cpp
src/mumble/MainWindow.h
src/mumble/Messages.cpp

**FIX(client): Update chat bar if selected channel target state is modified**
Previously, the chat bar would not update its text when a selected target
channel was modified.
This commit adds a signal slot to the channel state modified message
and updates the chat bar accordingly.
Fixes #1884
**REFAC(client): Move forced visual update from Messages.cpp to channelState slot**

FIX(client): Update chat bar if selected channel target state is modified

---

docs/dev/build-instructions/build_linux.md
docs/dev/build-instructions/cmake_options.md
src/database/CMakeLists.txt

* Changes db backend CMake vars to default to ``${server}``
* Updates build documentation for Linux

Do not build database backends by default when compiling the client

---

overlay_gl/overlay.c

- [Merge PR #6775: BUILD(overlay): Fix building with GCC 15](https://github.com/mumble-voip/mumble/pull/6775)

Backport "Merge PR #6775: BUILD(overlay): Fix building with GCC 15" to 1.5.x

---

src/mumble/UserView.cpp
themes/Default/Dark.qss
themes/Default/Lite.qss
themes/Default/source/Imports/Base Theme.scss

Something changed in Qt6 and the QTreeView elements don't look like they used to in Qt5 (Mumble 1.5.x)
Notably:
* The row background somehow extends all the way to the left
* The icons are no longer aligned to the center of the item row
This MR addresses this. Tested in KDE Wayland
Before (broken):
After (fixed):

Fix status icon alignment and TreeView item background (Qt6 regression)

---

src/mumble/AudioOutput.cpp
src/mumble/JackAudio.cpp

Previously, application attenuation and priority speaker attenuation would not consider local muted clients. In both situations local muted clients would still lower other clients or applications volume, despite not being played back.
This commit adds a check to the code where client voice is added to the mix data structure and prevents local muted clients (including priority speakers) to be considered in attenuation logic.
Fixes #6247 
Supersedes #6394

FIX(client): Prevent local muted users from triggering attenuation

---

src/mumble/AudioOutput.cpp

Backport "Merge PR #6747: FIX(client): Prevent local muted users from triggering attenuation"

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/RichTextEditor.cpp

This PR fixes three minor issues with copy and pasting images:
1. When pasting/dragging images to the chat was added in 3d2a196, limiting the size of images pasted in the RichTextEditor was removed.
I was used to send images via the RichTextEditor from old mumble versions (1.3.4 and earlier) and was very confused why sending images via that editor in newer versions would show `Denied: Text message too long.` errors. I guess the limit was removed by accident. This commit re-enables the limit to correctly reduce the size of limit exceeding images again.
2. Previously, images inserted using the GUI-Button in the RichTextEditor were rejected when they exceeded the size limit.
(The button, which opens a file dialog to choose an image.)
With this PR images will be resized and converted to …

FIX(client): Multiple minor Fixes for pasting Images in Chat

---

src/mumble/CustomElements.cpp
src/mumble/CustomElements.h
src/mumble/RichTextEditor.cpp

- [Merge PR #6790: FIX(client): Multiple minor Fixes for pasting Images in Chat](https://github.com/mumble-voip/mumble/pull/6790)

Backport "Merge PR #6790: FIX(client): Multiple minor Fixes for pasting Images in Chat" to 1.5.x

---

src/mumble/ACLEditor.cpp
src/mumble/ACLEditor.h

Qt6 removed the deprecated activate(const QString) in favor of textActivate(const QString). This lead to certain comboboxes in the channel edit dialog to misbehave.
This commit replaces the old with the new signals.
Fixes #6812

FIX(client): Fix regression of QComboBox activation in Qt6

---

src/mumble/Log.cpp

- [Merge PR #6825: CHANGE(client): Changed client-side max image width and height](https://github.com/mumble-voip/mumble/pull/6825)

Backport "Merge PR #6825: CHANGE(client): Changed client-side max image width and height" to 1.5.x

---

src/mumble/Settings.h

The issue was due to the `QDataStream` operator functions only being visible in `Settings.cpp`.

FIX(client): Shortcut data not being saved

---

src/mumble/Settings.h

- [Merge PR #6832: FIX(client): Shortcut data not being saved](https://github.com/mumble-voip/mumble/pull/6832)

Backport "Merge PR #6832: FIX(client): Shortcut data not being saved" to 1.5.x

---

auxiliary_files/mumble-server.ini
docs/dev/build-instructions/README.md
docs/dev/build-instructions/build_macos.md
scripts/updatetranslations.py

* ``qt5`` -> ``qt6`` in build_macos (Thanks @maxer137 )
* Mention and explain ``BUILD_NUMBER`` in build_linux
* Remove specific Qt version in updatetranslations.py documentation
* Bump qt5 -> qt6 in updatetranslations.py code
* ``rememberchannel`` only applies to registered users

Documentation Updates

---

src/mumble/VolumeSliderWidgetAction.cpp

- [Merge PR #6841: FIX(client): Add more key events to local volume adjustment slider](https://github.com/mumble-voip/mumble/pull/6841)

Backport "Merge PR #6841: FIX(client): Add more key events to local volume adjustment slider" to 1.5.x

---

.ci/azure-pipelines/release_windows.bat
CMakeLists.txt
installer/ClientInstaller.cs
installer/MumbleInstall.cs
installer/ServerInstaller.cs
installer/Theme.xml
src/mumble/CMakeLists.txt
src/murmur/CMakeLists.txt

After building each server and client msi, the installer script creates an exe bundle that includes a step to download and install the visual c++ redistributables.
re #5549 
This commit needs the redistrituables installer downloaded to `installer/VC_redist.x64.exe`. It includes a change in cmake to copy the file from there to the build directory. The wixsharp installer building stuff needs `VC_redist.x64.exe` when building the bundle, even though the file isn't embedded in the resulting exe.
I presume you would rather configure cmake download `VC_redist.x64.exe` or something instead of adding it to version control, so I didn't commit it.
I left some comments in the C# code to try to explain what is going on with the installer and how the Wix stuff works. Let me know if you have any other …

FEAT(installer): Bundle C++ redistributables

---

src/mumble/PipeWire.cpp

- [Merge PR #6852: FIX(client): Crash in PipeWire when the main thread is null](https://github.com/mumble-voip/mumble/pull/6852)

Backport "Merge PR #6852: FIX(client): Crash in PipeWire when the main thread is null" to 1.5.x

---

src/ACL.cpp

* Traverse: not sure how I missed that we needed ``applyTraverse`` for ``allow``, too (instead of ``apply``)
* Write: The "simplified" boolean expression was not equivalent to the way it was written before

Fix Write and Traverse ACL permission regressions

---

src/ACL.cpp

- [Merge PR #6859: Fix Write and Traverse ACL permission regressions](https://github.com/mumble-voip/mumble/pull/6859)

Backport "Merge PR #6859: Fix Write and Traverse ACL permission regressions" to 1.5.x

---

.github/workflows/pr-checks.yml

- [Merge PR #6879: MAINT: Update Check-CRLF action](https://github.com/mumble-voip/mumble/pull/6879)

Backport "Merge PR #6879: MAINT: Update Check-CRLF action" to 1.5.x

---

src/mumble/Log.cpp

- [Merge PR #6875: FIX(client): Bypassing of message size limit](https://github.com/mumble-voip/mumble/pull/6875)

Backport "Merge PR #6875: FIX(client): Bypassing of message size limit" to 1.5.x

---

src/tests/TestSSLLocks/TestSSLLocks.cpp

Without this patch, calling `RAND_seed` depleted the entropy pool and made the test block until sufficient entropy was added back into the pool. On network-less VMs there is little entropy, so this made it exceed the default Qt test timeout of 300s.
On my system, this changed runtime of `TestSSLLocks` from 495s to 32s (62s with 128 rounds).
This patch was done while working on reproducible builds for openSUSE.
Fixes #6818

FIX(tests): Reduce the amount of rounds in TestSSLLocks

---

src/murmur/CMakeLists.txt

BUILD: Backport BZip2 link failure workaround

---

src/mumble/CMakeLists.txt
src/mumble/ThemeSwitch_macx.mm
src/mumble/Themes.cpp

This commit allows the MacOS `NSApplication` Appearance to be set depending on the theme. This sets the application bar to the right color depending on if the Light or Dark appearance is chosen.
This fixes the issue described in [a comment under PR #6877](https://github.com/mumble-voip/mumble/pull/6877#issuecomment-3146561982)
When the themes are opposite, System has "Light" appearance and mumble has "Dark" appearance and vice versa, the application header and other parts of Mumble will display the incorrect colors inherinted from the system appearance.
When the appearance is set to "Light" or "Dark", Mumble will set it's NSApplication NSAppearance to the correct style to ensure the colors of the theme are correct.
---
Since I do not have access to Linux or Windows build systems, testing …

FEAT(client, MacOS): Set application appearance based on Theme

---

src/murmur/Messages.cpp

The QueryUsers protocol is used to fill the ACLEditor with usernames. It relates registered user ids with registered user names, even if the target user is offline.
Since its inception, msgQueryUsers did not check for any permissions when replying to user requests. So in theory, any fully unpriviledged user could get the entire registered user list if they knew what they were doing.
This commit adds a check so that the server only responds to msgQueryUsers if the requesting user has the Write ACL in any channel on the server.
Note: Being able to create and then creating a temporary channel is enough to satisfy this condition.
Fixes #3394

FIX(server): Make msgQueryUsers perform a permission check

---

src/database/CMakeLists.txt

When multiple database backends are enabled, our `find_pkg()` macro cannot be used because SOCI's package internally creates the `soci_interface` library each time it is called which causes a conflict for each enabled backend:
```
-- Found SOCI: /usr/lib64/cmake/soci-4.1.2/soci-config.cmake (found version "4.1.2") found components: Core, PostgreSQL, SQLite3
-- Soci component found: SQLite3 | Version: 4.1.2
CMake Error at /usr/lib64/cmake/soci-4.1.2/soci-config.cmake:179 (add_library):
add_library cannot create target "soci_interface" because another target
with the same name already exists.  The existing target is an interface
library created in source directory
"/var/tmp/portage/net-voip/murmur-9999/work/murmur-9999/src/database".  See
documentation for policy CMP0002 for more details. …
```

FIX(build): fix build with unbundled SOCI

---

themes/Default/OSX Dark.qss
themes/Default/OSX Lite.qss

- [Merge PR #6925: FIX(client, macos): Add missing theme changes](https://github.com/mumble-voip/mumble/pull/6925)

Backport "Merge PR #6925: FIX(client, macos): Add missing theme changes" to 1.5.x
